/** Arabic strings for the stock screens. Keys are those of en-US.ts. */
export const shared: Readonly<Record<string, string>> = {
  "shared.cancel": "إلغاء",
  "shared.close": "إغلاق",
  "shared.continuePosting": "متابعة الترحيل",
  "shared.dismiss": "تجاهل",
  "shared.failed.title": "تعذّر تحميل هذا",
  "shared.loading": "جارٍ التحميل",
  "shared.next": "التالي",
  "shared.pageN": "صفحة {n}",
  "shared.previous": "السابق",
  "shared.progress": "{done} من {all} من السطور",
  "shared.refused.body": "اطلبه من مسؤول المخزون إن احتجت إليه.",
  "shared.refused.title": "ليست لديك صلاحية لفتح هذا",
  "shared.retry": "إعادة المحاولة",
  "shared.scan.addNew": "أضفه كصنف جديد",
  "shared.scan.asking": "جارٍ البحث عنه",
  "shared.scan.failed": "تعذّر البحث عن هذا",
  "shared.scan.label": "ابحث أو امسح",
  "shared.scan.placeholder": "امسح باركود، أو اكتب اسمًا أو كودًا",
  "shared.scan.unknown": "لا يوجد صنف بهذا الكود · {code}"
};

export const refusal: Readonly<Record<string, string>> = {
  "refusal.conflict": "غيّر شخص آخر هذا في الوقت نفسه. حاول مرة أخرى.",
  "refusal.expired": "هذه التشغيلة منتهية الصلاحية بالفعل",
  "refusal.forbidden": "ليست لديك صلاحية لفعل هذا.",
  "refusal.full": "أمر الشراء يتسع لـ 50 سطرًا. ابدأ أمرًا آخر للباقي.",
  "refusal.move.children": "أضف سطرًا أولًا.",
  "refusal.move.linked": "هذا المستند لم يعد مفتوحًا لذلك.",
  "refusal.move.other": "لا يمكن فعل هذا الآن.",
  "refusal.move.where": "بعض السطور لم تدخل المخزون بعد.",
  "refusal.needsBatch": "أدخل رقم التشغيلة",
  "refusal.notAllowed": "هذا غير مسموح به هنا.",
  "refusal.oneAtATime": "تُحفظ هذه السطور واحدًا تلو الآخر.",
  "refusal.other": "تعذّر حفظ هذا. حاول مرة أخرى.",
  "refusal.outOfStock": "المتبقي لا يكفي للتراجع عن هذا السطر",
  "refusal.outOfStockLeft": "لم يتبقَّ سوى {left} {unit} من {item} في التشغيلة {batch}: لا يمكن التراجع عن هذا السطر",
  "refusal.receiptOpen": "{rows, plural, zero {لا صفوف تحجز} one {صف واحد يحجز} two {صفان يحجزان} few {# صفوف تحجز} many {# صفًا تحجز} other {# صف تحجز}} مخزونًا: أعدها أولًا",
  "refusal.stock": "تعذّر تحديث المخزون. لم يتغير شيء في هذا السطر. حاول مرة أخرى، وإن تكرر الفشل فأخبر المسؤول عن Adminium.",
  "refusal.tooLarge": "هذا السطر أكبر من أن يُرحَّل مرة واحدة. قسّمه إلى سطور أصغر."
};

export const receive: Readonly<Record<string, string>> = {
  "receive.another": "استلام توريد آخر",
  "receive.anotherBatch": "تشغيلة أخرى",
  "receive.bar": "إذن الاستلام هذا",
  "receive.batch": "التشغيلة",
  "receive.batchHint": "كما هي مطبوعة على العلبة",
  "receive.batchKnown": "التشغيلة {code} معروفة بالفعل",
  "receive.choose": "اختر موقعًا",
  "receive.choosePlace": "اختر الموقع الذي يدخله هذا التوريد",
  "receive.closedMeanwhile": "أُغلق {order} أثناء الاستلام. دخل المخزون، ولم يتغير الأمر.",
  "receive.col.cost": "تكلفة الوحدة",
  "receive.col.item": "الصنف",
  "receive.col.now": "يُستلم الآن",
  "receive.col.ordered": "المطلوب",
  "receive.col.received": "المستلم حتى الآن",
  "receive.col.total": "الإجمالي",
  "receive.costOrdered": "في أمر الشراء {cost}",
  "receive.costToCheck": "رُحِّل سطر بمتوسط التكلفة لأن تكلفته غير معروفة. راجع تكلفته.",
  "receive.costUsed": "استخدم Adminium {cost}",
  "receive.countPacks": "العدّ حسب {pack} من {size}",
  "receive.countUnits": "العدّ حسب {unit}",
  "receive.delivery": "التوريد",
  "receive.discard.body": "السطور التي كتبتها غير محفوظة. تغيير الأمر يبدأ من جديد.",
  "receive.discard.title": "هل تتجاهل ما أدخلته؟",
  "receive.discard.yes": "تجاهل وغيّر",
  "receive.draftSaved": "حُفظت المسودة. تجدها ضمن أذون الاستلام.",
  "receive.empty.body": "امسح علبة أو اكتب اسم صنف في الأعلى. كل صنف تضيفه يصبح سطرًا.",
  "receive.empty.title": "لم يُضف شيء بعد",
  "receive.err.expires": "أدخل تاريخ انتهاء الصلاحية",
  "receive.err.qty": "أدخل الكمية التي تستلمها",
  "receive.err.whole": "أدخل عددًا صحيحًا",
  "receive.expires": "تنتهي الصلاحية",
  "receive.fixFirst": "{count, plural, zero {لا حقول تحتاج} one {حقل واحد يحتاج} two {حقلان يحتاجان} few {# حقول تحتاج} many {# حقلًا تحتاج} other {# حقل تحتاج}} إلى تصحيح قبل الترحيل",
  "receive.into": "إلى",
  "receive.itemAdded": "أُضيف الصنف: {item}",
  "receive.lineCount": "{count, plural, zero {لا سطور} one {سطر واحد} two {سطران} few {# سطور} many {# سطرًا} other {# سطر}}",
  "receive.lineIn": "دخل المخزون",
  "receive.lineRefused": "{item}: {reason}",
  "receive.lines": "السطور",
  "receive.missing.body": "ربما أُزيل، أو ربما لا تستطيع رؤيته.",
  "receive.missing.title": "إذن الاستلام هذا غير موجود",
  "receive.newItem.add": "أضف الصنف واستلمه",
  "receive.newItem.barcode": "الباركود",
  "receive.newItem.name": "الاسم",
  "receive.newItem.nameHint": "كما تحب أن يظهر في الجرد",
  "receive.newItem.nameMissing": "اكتب اسمًا للصنف",
  "receive.newItem.pack": "عدد الوحدات في العلبة (اختياري)",
  "receive.newItem.subtitle": "يُضاف إلى الأصناف وإلى هذا التوريد.",
  "receive.newItem.title": "صنف جديد",
  "receive.newItem.tracks": "يتتبع التشغيلات — يطلب تشغيلة وتاريخ انتهاء الصلاحية عند كل استلام",
  "receive.newItem.unit": "وحدة العدّ",
  "receive.noOrder": "بدون أمر شراء",
  "receive.noSupplier": "بدون مورّد",
  "receive.notAllIn": "بعض السطور لم تدخل المخزون بعد",
  "receive.notOnOrder": "ليس في هذا الأمر",
  "receive.nothing": "أضف شيئًا لتستلمه أولًا",
  "receive.order": "أمر شراء",
  "receive.orderLabel": "{number} · {supplier}",
  "receive.orderedPacks": "{packs} {pack} من {size}",
  "receive.overview": "نظرة عامة على المخزون",
  "receive.pack": "عبوة",
  "receive.packs": "عبوات",
  "receive.per": "لكل {unit}",
  "receive.post": "ترحيل إذن الاستلام",
  "receive.posted": "تم ترحيل إذن الاستلام",
  "receive.posted.batch": "التشغيلة {code}",
  "receive.posted.batchExpires": "التشغيلة {code} · تنتهي في {date}",
  "receive.posted.full": "تم استلام {order} بالكامل.",
  "receive.posted.noOrder": "تم استلام المخزون من مورّده.",
  "receive.posted.onHand": "المتاح الآن {qty} {unit}",
  "receive.posted.part": "تم استلام {order} جزئيًا.",
  "receive.posted.plain": "تم استلام المخزون.",
  "receive.posted.title": "تم ترحيل إذن الاستلام",
  "receive.posted.toCome": "تم استلام {order} جزئيًا. ما زال متبقيًا {qty} {unit} من {item}.",
  "receive.posted.totalsMoney": "تم استلام {units} وحدة · {total}",
  "receive.posted.totalsUnits": "تم استلام {units} وحدة",
  "receive.posted.where": "إلى {place} · {when} · {by}",
  "receive.postedFor": "تم ترحيل إذن الاستلام لـ {order}",
  "receive.posting.body": "دخل {done} من {all} من السطور. تابع عندما تكون جاهزًا، والسطر الذي لم يدخل بعد يمكن تصحيحه.",
  "receive.posting.title": "إذن الاستلام هذا دخل جزئيًا",
  "receive.remove": "إزالة {item}",
  "receive.removed": "تمت إزالة {item}",
  "receive.reopenFirst": "أعد فتح الأمر أولًا",
  "receive.reversed.body": "أُخرج كل سطر من المخزون مرة أخرى. يبقى إذن الاستلام مسجَّلًا.",
  "receive.reversed.title": "تم التراجع عن إذن الاستلام",
  "receive.reversing.title": "تم التراجع عن إذن الاستلام هذا جزئيًا",
  "receive.saveDraft": "حفظ كمسودة",
  "receive.scan.added": "أُضيف {item} · 1 {unit}",
  "receive.scan.hintPack": "الماسح الضوئي يكتب في هذا الحقل. كل مسح يضيف عبوة واحدة.",
  "receive.scan.hintUnit": "الماسح الضوئي يكتب في هذا الحقل. كل مسح يضيف واحدًا.",
  "receive.scan.raised": "{item} · الآن {qty} {unit}",
  "receive.seeMovements": "عرض الحركات",
  "receive.sendBack": "إرجاع إلى المورّد",
  "receive.sendBack.body": "يخرج السطر كله من المخزون بتكلفته ويُحسب ضمن المطلوب من جديد. لشطب جزء من سطر، استخدم «استخدام المخزون» في الصنف بدلًا من ذلك.",
  "receive.sendBack.title": "هل تُرجع هذا السطر إلى مورّده؟",
  "receive.sentBack": "تم إرجاع {item}",
  "receive.status.reversed": "تم التراجع عنه",
  "receive.status.sentBack": "تم إرجاعه",
  "receive.stopped": "دخل {done} من {all} من السطور. تابع عندما تكون جاهزًا.",
  "receive.stoppedAt": "دخل {done} من {all} من السطور. {item}: {reason}",
  "receive.supplier": "المورّد (اختياري)",
  "receive.supplierOf": "المورّد",
  "receive.title": "استلام المخزون",
  "receive.totalsMoney": "جارٍ استلام {units} وحدة · {total}",
  "receive.totalsTyped": "{count, plural, zero {لا سطور للاستلام} one {سطر واحد للاستلام} two {سطران للاستلام} few {# سطور للاستلام} many {# سطرًا للاستلام} other {# سطر للاستلام}}",
  "receive.totalsUnits": "جارٍ استلام {units} وحدة",
  "receive.undo": "التراجع عن إذن الاستلام هذا",
  "receive.undo.body": "يُسحب كل سطر من المخزون من جديد، واحدًا تلو الآخر. السطر الذي استُخدم مخزونه بالفعل لا يمكن التراجع عنه، ويُذكر اسمه.",
  "receive.undo.title": "هل تتراجع عن إذن الاستلام هذا؟",
  "receive.undoContinue": "متابعة التراجع",
  "receive.undoStopped": "لم يتم التراجع عن كل السطور بعد. تابع عندما تكون جاهزًا.",
  "receive.undone": "تم التراجع عن إذن الاستلام"
};

export const transfer: Readonly<Record<string, string>> = {
  "transfer.bar": "هذا التحويل",
  "transfer.batch.any": "الأقرب انتهاءً أولًا",
  "transfer.batch.kept": "التشغيلة المختارة من قبل",
  "transfer.batch.option": "{code} · {qty} {unit}",
  "transfer.choose": "اختر موقعًا",
  "transfer.choosePlaces": "اختر الموقع الذي يخرج منه المخزون والموقع الذي يذهب إليه",
  "transfer.col.batch": "التشغيلة",
  "transfer.col.item": "الصنف",
  "transfer.col.qty": "الكمية",
  "transfer.done": "تم التحويل",
  "transfer.draftSaved": "حُفظت المسودة. تجدها ضمن التحويلات.",
  "transfer.empty.body": "امسح صنفًا أو اكتب اسمه في الأعلى. كل صنف تضيفه يصبح سطرًا.",
  "transfer.empty.title": "لم يُضف شيء بعد",
  "transfer.err.qty": "أدخل الكمية التي تنقلها",
  "transfer.finish": "تم",
  "transfer.fixFirst": "يوجد سطر يحتاج إلى تصحيح أولًا",
  "transfer.from": "من",
  "transfer.lineCount": "{count, plural, zero {لا سطور} one {سطر واحد} two {سطران} few {# سطور} many {# سطرًا} other {# سطر}}",
  "transfer.lineDone": "تم نقله",
  "transfer.lineRefused": "{item}: {reason}",
  "transfer.lineUndone": "تم التراجع عنه",
  "transfer.lines": "السطور",
  "transfer.missing.body": "ربما أُزيل، أو ربما لا تستطيع رؤيته.",
  "transfer.missing.title": "هذا التحويل غير موجود",
  "transfer.nothing": "أضف شيئًا لتنقله أولًا",
  "transfer.places": "من وإلى",
  "transfer.posting": "هذا التحويل تم جزئيًا. تابع عندما تكون جاهزًا.",
  "transfer.remove": "إزالة {item}",
  "transfer.reversed": "تم التراجع عن هذا التحويل.",
  "transfer.reversing": "تم التراجع عن هذا التحويل جزئيًا. تابع عندما تكون جاهزًا.",
  "transfer.samePlace": "اختر موقعًا مختلفًا",
  "transfer.saveDraft": "حفظ كمسودة",
  "transfer.scan.added": "أُضيف {item} · 1 {unit}",
  "transfer.scan.hint": "الماسح الضوئي يكتب في هذا الحقل. كل مسح يضيف واحدًا.",
  "transfer.scan.raised": "{item} · الآن {qty} {unit}",
  "transfer.short": "أكثر مما كان في الدفاتر",
  "transfer.shortToast": "نُقل أكثر مما كان في الدفاتر: {items}",
  "transfer.stopped": "تم {done} من {all} من السطور. تابع عندما تكون جاهزًا.",
  "transfer.title": "تحويل المخزون",
  "transfer.to": "إلى",
  "transfer.totals": "{count, plural, zero {لا سطور للنقل} one {جارٍ نقل سطر واحد} two {جارٍ نقل سطرين} few {جارٍ نقل # سطور} many {جارٍ نقل # سطرًا} other {جارٍ نقل # سطر}}",
  "transfer.totalsDone": "تم تحويل {count, plural, zero {لا سطور} one {سطر واحد} two {سطرين} few {# سطور} many {# سطرًا} other {# سطر}}",
  "transfer.totalsTyped": "{count, plural, zero {لا سطور للنقل} one {سطر واحد للنقل} two {سطران للنقل} few {# سطور للنقل} many {# سطرًا للنقل} other {# سطر للنقل}}",
  "transfer.totalsUndone": "تم التراجع · {count, plural, zero {لا سطور} one {سطر واحد} two {سطران} few {# سطور} many {# سطرًا} other {# سطر}}",
  "transfer.undo": "التراجع عن هذا التحويل",
  "transfer.undo.body": "يُعاد كل سطر إلى موقعه، واحدًا تلو الآخر. السطر الذي استُخدم مخزونه بالفعل لا يمكن التراجع عنه، ويُذكر اسمه.",
  "transfer.undo.title": "هل تتراجع عن هذا التحويل؟",
  "transfer.undoContinue": "متابعة التراجع",
  "transfer.undone": "تم التراجع عن التحويل"
};

export const opening: Readonly<Record<string, string>> = {
  "opening.another": "تحميل ملف آخر",
  "opening.bar": "مخزون أول المدة",
  "opening.choose": "اختر موقعًا",
  "opening.choosePlace": "اختر الموقع الذي يوجد فيه هذا المخزون",
  "opening.col.batch": "التشغيلة",
  "opening.col.cost": "تكلفة الوحدة",
  "opening.col.expires": "تنتهي الصلاحية",
  "opening.col.item": "الصنف",
  "opening.col.qty": "الكمية",
  "opening.draftSaved": "حُفظت المسودة. تجدها ضمن أذون الاستلام.",
  "opening.empty": "اختر ملفًا لتبدأ",
  "opening.err.cost": "أدخل تكلفة مثل 1.10",
  "opening.err.expires": "اكتب التاريخ هكذا: 2027-04-30",
  "opening.err.qty": "أدخل كمية أكبر من صفر، واستخدم النقطة للكسور العشرية",
  "opening.file.body": "صف واحد لكل صنف، أو لكل تشغيلة من الصنف. تُكتب التواريخ هكذا: 2027-04-30، وتُكتب الكسور العشرية بالنقطة.",
  "opening.file.choose": "اختر ملف CSV",
  "opening.file.empty": "هذا الملف لا يحتوي على صفوف.",
  "opening.file.header": "يجب أن يسمّي الصف الأول الأعمدة: quantity، وواحدًا من sku أو barcode أو name. نزّل الملف النموذجي لتراها.",
  "opening.file.title": "الملف",
  "opening.file.tooMany": "هذا الملف فيه {count} صف. الملف يتسع حتى {max}: قسّمه وحمّل كل جزء.",
  "opening.fixFirst": "{count, plural, zero {لا صفوف تحتاج} one {صف واحد يحتاج} two {صفان يحتاجان} few {# صفوف تحتاج} many {# صفًا تحتاج} other {# صف تحتاج}} إلى تصحيح في الملف أولًا",
  "opening.itemsMade": "{count, plural, zero {لم يُنشأ أي صنف} one {أُنشئ صنف واحد} two {أُنشئ صنفان} few {أُنشئت # أصناف} many {أُنشئ # صنفًا} other {أُنشئ # صنف}}",
  "opening.load": "تحميل مخزون أول المدة",
  "opening.loaded": "تم تحميل مخزون أول المدة",
  "opening.nothing": "لا يوجد شيء لتحميله",
  "opening.onePart": "مخزون أول المدة",
  "opening.openPart": "فتح",
  "opening.pages": "صفحات السطور",
  "opening.part": "مخزون أول المدة، الجزء {n} من {m}",
  "opening.partLines": "{count, plural, zero {لا سطور} one {سطر واحد} two {سطران} few {# سطور} many {# سطرًا} other {# سطر}}",
  "opening.parts": "{count} سطر: يُحفظ هذا في {parts} من أذون الاستلام، بترتيب الملف.",
  "opening.place": "الموقع",
  "opening.progress": "الجزء {part}: {done} من {all} من السطور",
  "opening.reading": "جارٍ قراءة الملف · تمت مطابقة {done} صف حتى الآن",
  "opening.review": "مراجعة",
  "opening.reviewCount": "{count, plural, zero {لا سطور للتحميل} one {سطر واحد للتحميل} two {سطران للتحميل} few {# سطور للتحميل} many {# سطرًا للتحميل} other {# سطر للتحميل}}",
  "opening.row": "الصف {at}",
  "opening.sample": "تنزيل ملف نموذجي",
  "opening.saveDraft": "حفظ كمسودة",
  "opening.saved.title": "حُفظ للتحميل",
  "opening.status.draft": "مسودة",
  "opening.status.loaded": "تم تحميله",
  "opening.status.partly": "تم تحميله جزئيًا",
  "opening.stopped": "الجزء {part}: دخل {done} من {all} من السطور. تابع عندما تكون جاهزًا.",
  "opening.stoppedAt": "الجزء {part}: رُفض سطر. {reason} افتح الجزء لتصحيحه.",
  "opening.title": "مخزون أول المدة",
  "opening.totals": "{count, plural, zero {لا سطور للتحميل} one {سطر واحد للتحميل} two {سطران للتحميل} few {# سطور للتحميل} many {# سطرًا للتحميل} other {# سطر للتحميل}}",
  "opening.totalsSaved": "{count, plural, zero {لم يُحفظ أي إذن استلام} one {حُفظ إذن استلام واحد} two {حُفظ إذنا استلام} few {حُفظت # أذون استلام} many {حُفظ # إذن استلام} other {حُفظ # إذن استلام}}",
  "opening.unmatched.body": "{count, plural, zero {الصفوف {rows}{more}. ستُستبعد} one {الصف {rows}. سيُستبعد} two {الصفان {rows}. سيُستبعدان} few {الصفوف {rows}{more}. ستُستبعد} many {الصفوف {rows}{more}. ستُستبعد} other {الصفوف {rows}{more}. ستُستبعد}} ما لم تنشئ الأصناف.",
  "opening.unmatched.leave": "استبعاد",
  "opening.unmatched.make": "إنشاء هذه الأصناف",
  "opening.unmatched.title": "{count, plural, zero {لا يوجد صف لا يطابق} one {صف واحد لا يطابق} two {صفان لا يطابقان} few {# صفوف لا تطابق} many {# صفًا لا تطابق} other {# صف لا تطابق}} أي صنف"
};

export const counts: Readonly<Record<string, string>> = {
  "counts.add.batch": "إضافة التشغيلة {code}",
  "counts.add.plain": "إضافة {item} إلى هذا الجرد",
  "counts.add.title": "{item} موجود في هذا الموقع وليس في هذا الجرد",
  "counts.askManager": "اطلب من مسؤول المخزون ترحيل هذا الجرد",
  "counts.bar": "هذا الجرد",
  "counts.batch": "التشغيلة {code}",
  "counts.cancel": "إلغاء الجرد",
  "counts.cancel.body": "لم يُرحَّل شيء، فلا يتغير شيء في المخزون. الأعداد المكتوبة حتى الآن تبقى محفوظة مع الجرد الملغى.",
  "counts.cancel.title": "هل تلغي هذا الجرد؟",
  "counts.cancelledToast": "أُلغي الجرد. لم يتغير شيء في المخزون.",
  "counts.col.count": "العدد",
  "counts.col.counted": "تم جرده",
  "counts.col.difference": "الفرق",
  "counts.col.differences": "الفروق",
  "counts.col.expected": "المتوقع",
  "counts.col.item": "الصنف",
  "counts.col.place": "الموقع",
  "counts.col.scope": "النطاق",
  "counts.col.sku": "SKU",
  "counts.col.started": "بدأ في",
  "counts.col.status": "الحالة",
  "counts.col.value": "القيمة",
  "counts.countedFor": "العدد، {item}",
  "counts.doneForNow": "يكفي الآن",
  "counts.empty.body": "اجرد موقعًا لتطابق الدفاتر مع الأرفف.",
  "counts.empty.differ": "لا فروق حتى الآن",
  "counts.empty.differBody": "كل سطر جُرد حتى الآن يطابق المتوقع.",
  "counts.empty.lines": "هذا الجرد ليس فيه سطور",
  "counts.empty.open": "تم جرد كل السطور",
  "counts.empty.openBody": "لم يبقَ شيء للجرد هنا.",
  "counts.empty.showAll": "عرض كل السطور",
  "counts.empty.title": "لا توجد عمليات جرد بعد",
  "counts.filter.all": "عرض الكل",
  "counts.filter.differ": "الفروق فقط",
  "counts.filter.item": "عرض {item}",
  "counts.filter.open": "لم يُجرد",
  "counts.linePages": "صفحات السطور",
  "counts.lineRefused": "{item}: {reason}",
  "counts.lines": "السطور",
  "counts.missing.body": "ربما أُزيل، أو ربما لا تستطيع رؤيته.",
  "counts.missing.title": "هذا الجرد غير موجود",
  "counts.noBatch": "بدون تشغيلة",
  "counts.notOpen": "هذا الجرد لم يعد مفتوحًا",
  "counts.notSaved": "لم يُحفظ",
  "counts.onHandNow": "المتاح الآن {qty}",
  "counts.pages": "صفحات عمليات الجرد",
  "counts.post": "ترحيل الجرد",
  "counts.post.body": "{count, plural, zero {لن يُعدَّل أي سطر} one {سيُعدَّل سطر واحد} two {سيُعدَّل سطران} few {ستُعدَّل # سطور} many {سيُعدَّل # سطرًا} other {سيُعدَّل # سطر}}. يستطيع مسؤول المخزون عكس الجرد المرحَّل.",
  "counts.post.more": "و{count} أخرى",
  "counts.post.reason": "السبب",
  "counts.post.title": "هل ترحّل هذا الجرد؟",
  "counts.posted": "تم ترحيل الجرد · {count, plural, zero {لم يُعدَّل أي سطر} one {عُدِّل سطر واحد} two {عُدِّل سطران} few {عُدِّلت # سطور} many {عُدِّل # سطرًا} other {عُدِّل # سطر}}",
  "counts.progress": "تم جرد {done} من {all} من السطور",
  "counts.reverse": "عكس الجرد…",
  "counts.reverse.body": "{count, plural, zero {لن يُعاد أي سطر} one {سيُعاد سطر واحد إلى ما كان عليه} two {سيُعاد سطران إلى ما كانا عليه} few {ستُعاد # سطور إلى ما كانت عليه} many {سيُعاد # سطرًا إلى ما كان عليه} other {سيُعاد # سطر إلى ما كان عليه}}. أي تشغيلة ستنزل تحت الصفر تُرفض، ويُذكر اسمها.",
  "counts.reverse.title": "هل تعكس هذا الجرد؟",
  "counts.reverse.yes": "عكس الجرد",
  "counts.reverseContinue": "متابعة العكس",
  "counts.reverseStopped": "لم تُعكس كل السطور بعد. تابع عندما تكون جاهزًا.",
  "counts.reversedToast": "تم عكس الجرد",
  "counts.saved": "تم الحفظ",
  "counts.saving": "جارٍ الحفظ",
  "counts.scan.hint": "امسح صنفًا أو اكتبه للانتقال إلى سطره.",
  "counts.scan.now": "الآن عند {item}",
  "counts.scan.unknown": "ليس في هذا الجرد · {code}",
  "counts.scope.all": "كل ما في هذا الموقع",
  "counts.scope.category": "فئة واحدة",
  "counts.scope.categoryNamed": "الفئة: {category}",
  "counts.scope.stale": "لم يُجرد مؤخرًا",
  "counts.scope.staleDays": "أصناف لم تُجرد منذ {days} يوم",
  "counts.scope.toCheck": "معلَّم للمراجعة",
  "counts.scope.toCheckItems": "أصناف معلَّمة للمراجعة",
  "counts.sheet.subtitle": "{number} · {scope} · بدأ في {date}",
  "counts.sheet.title": "جرد",
  "counts.sheet.titlePlace": "جرد · {place}",
  "counts.start": "بدء جرد",
  "counts.start.category": "الفئة",
  "counts.start.chooseCategory": "اختر فئة",
  "counts.start.choosePlace": "اختر موقعًا",
  "counts.start.done": "بدأ الجرد في {place}",
  "counts.start.doneParts": "بدأ الجرد في {place} على {parts} من عمليات الجرد",
  "counts.start.go": "ابدأ",
  "counts.start.help": "المبيعات التي تتم أثناء الجرد تبقى محسوبة. كل سطر يُقارن بما كان في الدفاتر لحظة كتابة عدده.",
  "counts.start.nothing": "لا شيء في هذا الموقع يطابق: لا يوجد سطر للجرد.",
  "counts.start.openHere": "عمليات جرد ما زالت مفتوحة لهذا الموقع:",
  "counts.start.place": "الموقع",
  "counts.start.reading": "جارٍ بدء الجرد · قراءة {n} من الأرصدة",
  "counts.start.title": "بدء جرد",
  "counts.start.what": "ما الذي يُجرد",
  "counts.status.cancelled": "ملغى",
  "counts.status.open": "قيد الجرد",
  "counts.status.posted": "مرحَّل",
  "counts.status.posting": "جارٍ الترحيل",
  "counts.status.reversed": "معكوس",
  "counts.status.reversing": "جارٍ العكس",
  "counts.stopped": "تم ترحيل {done} من {all} من السطور. تابع عندما تكون جاهزًا.",
  "counts.title": "الجرد",
  "counts.toCheck.body": "عُدِّلت هذه الأصناف وتبقى معلَّمة للمراجعة: {items}",
  "counts.toCheck.title": "بيع منها بعد جردها",
  "counts.totals": "{count, plural, zero {لا فروق} one {فرق واحد} two {فرقان} few {# فروق} many {# فرقًا} other {# فرق}}",
  "counts.totalsMoney": "{count, plural, zero {لا فروق} one {فرق واحد} two {فرقان} few {# فروق} many {# فرقًا} other {# فرق}} · {value}",
  "counts.uncounted": "{count, plural, zero {لا سطور لم تُجرد بعد} one {سطر واحد لم يُجرد بعد} two {سطران لم يُجردا بعد} few {# سطور لم تُجرد بعد} many {# سطرًا لم يُجرد بعد} other {# سطر لم يُجرد بعد}}"
};

export const rules: Readonly<Record<string, string>> = {
  "rules.add": "إضافة قاعدة",
  "rules.added": "تمت إضافة قاعدة {table}",
  "rules.badge.app": "من {app}",
  "rules.badge.yours": "جدولك",
  "rules.caughtUp": "تم تسجيل {planned}، وما زال {left} في الانتظار",
  "rules.edit": "تعديل",
  "rules.empty.body": "القاعدة تحدد متى يحجز صف في أحد جداولك مخزونًا، أو يسحب منه، أو يعيده.",
  "rules.empty.title": "لا يوجد جدول يسحب من المخزون بعد",
  "rules.fixed": "لا يغيّر هذه القواعد إلا من يحق له تغيير طريقة عمل الجداول.",
  "rules.itemsMade": "أُنشئ {made} من الأصناف، و{skipped} مرتبط بالفعل",
  "rules.makeItems": "إنشاء أصناف مخزون من هذا الجدول",
  "rules.makeItems.go": "إنشاء الأصناف",
  "rules.makeItems.label": "العمود الذي يسمّي كل صف",
  "rules.needsUnit": "اختر وحدة افتراضية في الإعدادات أولًا",
  "rules.off": "متوقفة",
  "rules.point.create": "يُنشأ الصف",
  "rules.point.from": "ينتقل {row} من {fromStates} إلى {states}",
  "rules.point.in": "يصبح {column} {values}",
  "rules.point.parent": "{column} الخاص به",
  "rules.point.row": "الصف",
  "rules.point.set": "تُحدَّد قيمة {column}",
  "rules.point.to": "ينتقل {row} إلى {states}",
  "rules.recordNow": "سجّلها الآن",
  "rules.remove": "إزالة القاعدة",
  "rules.remove.confirm": "هل تزيل هذه القاعدة؟ صفوف هذا الجدول ستتوقف عن السحب من المخزون.",
  "rules.rule.back": "عندما {point}، يُعاد إلى المخزون.",
  "rules.rule.count": "يُحسب {multipliers}.",
  "rules.rule.from": "من {place}.",
  "rules.rule.fromColumn": "من الموقع المذكور في {column}.",
  "rules.rule.give": "عندما {point}، يُعاد {what} إلى الرف.",
  "rules.rule.hold": "عندما {point}، يُحجز المخزون.",
  "rules.rule.take": "عندما {point}، يُسحب {what}.",
  "rules.saved": "تم حفظ قاعدة {table}",
  "rules.setBy": "ضبطها {app}. يمكنك إيقافها، أما خطواتها فلا تتغير إلا بتحديث {app}.",
  "rules.sheet.add": "إضافة قاعدة",
  "rules.sheet.addRule": "إضافة القاعدة",
  "rules.sheet.back": "إعادة",
  "rules.sheet.chooseColumn": "اختر عمودًا",
  "rules.sheet.chooseTable": "اختر جدولًا",
  "rules.sheet.defaultPlace": "الموقع الافتراضي",
  "rules.sheet.edit": "تعديل القاعدة",
  "rules.sheet.err.table": "اختر جدولًا",
  "rules.sheet.err.take": "اختر متى يُحجز المخزون أو يُسحب",
  "rules.sheet.err.until": "الحجز يحتاج إلى العمود الذي يحدد متى ينتهي",
  "rules.sheet.err.when": "أكمل كل «عندما» اخترتها",
  "rules.sheet.guest": "يُحسب لكل ضيف في",
  "rules.sheet.hold": "حجز",
  "rules.sheet.linkColumn": "أي عمود",
  "rules.sheet.night": "يُحسب لكل ليلة في",
  "rules.sheet.notNeeded": "غير مطلوب",
  "rules.sheet.one": "واحد في كل مرة",
  "rules.sheet.place": "من أي موقع",
  "rules.sheet.placeColumn": "الموقع المذكور في {column}",
  "rules.sheet.quantity": "الكمية",
  "rules.sheet.reads": "تُقرأ هكذا",
  "rules.sheet.save": "حفظ القاعدة",
  "rules.sheet.table": "الجدول",
  "rules.sheet.take": "سحب",
  "rules.sheet.until": "حتى متى",
  "rules.sheet.used": "ما الذي يُستخدم",
  "rules.sheet.used.link": "عمود مرتبط",
  "rules.sheet.used.linkHelp": "الصف يشير إلى ما يُستخدم.",
  "rules.sheet.used.row": "هذا الصف",
  "rules.sheet.used.rowHelp": "كل صف في الجدول شيء محفوظ في المخزون.",
  "rules.switchLabel": "قاعدة {table}",
  "rules.switchedOff": "تم إيقاف قاعدة {table}",
  "rules.switchedOn": "تم تشغيل قاعدة {table}",
  "rules.title": "قواعد المخزون",
  "rules.unavailable": "تعذّر على المخزون الرد بخصوص هذا الجدول. عمليات الحفظ الجديدة تنتظر أو تُرفض.",
  "rules.waiting": "{count, plural, zero {لا عمليات حفظ في الانتظار} one {عملية حفظ واحدة في الانتظار} two {عمليتا حفظ في الانتظار} few {# عمليات حفظ في الانتظار} many {# عملية حفظ في الانتظار} other {# عملية حفظ في الانتظار}}",
  "rules.what.column": "{quantity} من {column}",
  "rules.what.recorded": "ما هو مسجَّل فيه",
  "rules.what.row": "صنف هذا الصف",
  "rules.what.rowMany": "{quantity} من صنف هذا الصف",
  "rules.when.becomes": "عندما يصبح عمود",
  "rules.when.column": "{label}: أي عمود",
  "rules.when.create": "عندما يُنشأ الصف",
  "rules.when.moves": "عندما ينتقل الصف إلى",
  "rules.when.never": "أبدًا",
  "rules.when.set": "عندما تُحدَّد قيمة عمود"
};
