/** Czech strings for the stock screens. Keys are those of en-US.ts. */
export const shared: Readonly<Record<string, string>> = {
  "shared.cancel": "Zrušit",
  "shared.close": "Zavřít",
  "shared.continuePosting": "Pokračovat v účtování",
  "shared.dismiss": "Skrýt",
  "shared.failed.title": "Tohle se nepodařilo načíst",
  "shared.loading": "Načítání",
  "shared.next": "Další",
  "shared.overLimit": "Na chvíli příliš mnoho požadavků. Pokračuje se samo za {seconds, plural, one {# sekundu} few {# sekundy} many {# sekundy} other {# sekund}}.",
  "shared.pageN": "Strana {n}",
  "shared.previous": "Předchozí",
  "shared.progress": "{done} z {all} řádků",
  "shared.refused.body": "Pokud to potřebujete, požádejte správce skladu.",
  "shared.refused.title": "K otevření nemáte oprávnění",
  "shared.retry": "Zkusit znovu",
  "shared.scan.addNew": "Přidat jako novou položku",
  "shared.scan.asking": "Vyhledávání",
  "shared.scan.failed": "Tohle se nepodařilo vyhledat",
  "shared.scan.label": "Najít nebo naskenovat",
  "shared.scan.placeholder": "Naskenujte čárový kód nebo napište název či kód",
  "shared.scan.unknown": "Tento kód nemá žádná položka · {code}"
};

export const refusal: Readonly<Record<string, string>> = {
  "refusal.conflict": "Někdo jiný to ve stejnou chvíli změnil. Zkuste to znovu.",
  "refusal.expired": "Tato šarže už je prošlá",
  "refusal.forbidden": "K tomuto kroku nemáte oprávnění.",
  "refusal.full": "Objednávka pojme 50 řádků. Na zbytek založte další objednávku.",
  "refusal.move.children": "Nejdřív přidejte řádek.",
  "refusal.move.linked": "Tento doklad už k tomu není otevřený.",
  "refusal.move.other": "Tohle zatím udělat nelze.",
  "refusal.move.where": "Některé řádky ještě nejsou zaúčtovány.",
  "refusal.needsBatch": "Zadejte číslo šarže",
  "refusal.notAllowed": "Tohle zde není povoleno.",
  "refusal.oneAtATime": "Tyto řádky se ukládají po jednom.",
  "refusal.other": "Tohle se nepodařilo uložit. Zkuste to znovu.",
  "refusal.outOfStock": "Na vrácení tohoto řádku zpět nezbývá dost zásob",
  "refusal.outOfStockLeft": "V šarži {batch} zbývá jen {left} {unit} položky {item}: tento řádek nelze vrátit zpět",
  "refusal.receiptOpen": "{rows, plural, one {# řádek drží} few {# řádky drží} many {# řádku drží} other {# řádků drží}} zásoby: nejdřív je vraťte",
  "refusal.stock": "Zásoby se nepodařilo aktualizovat. U tohoto řádku se nic nezměnilo. Zkuste to znovu; pokud to selhává dál, dejte vědět tomu, kdo se stará o Adminium.",
  "refusal.tooLarge": "Tento řádek je příliš velký na zaúčtování najednou. Rozdělte ho na menší řádky."
};

export const receive: Readonly<Record<string, string>> = {
  "receive.another": "Přijmout další dodávku",
  "receive.anotherBatch": "Další šarže",
  "receive.bar": "Tato příjemka",
  "receive.batch": "Šarže",
  "receive.batchHint": "Jak je vytištěno na krabici",
  "receive.batchKnown": "Šarže {code} je už známá",
  "receive.choose": "Vyberte místo",
  "receive.choosePlace": "Vyberte, kam tato dodávka půjde",
  "receive.closedMeanwhile": "Objednávka {order} byla během příjmu uzavřena. Zásoby jsou přijaty; objednávka se nezměnila.",
  "receive.col.cost": "Cena za jednotku",
  "receive.col.item": "Položka",
  "receive.col.now": "Přijímáte nyní",
  "receive.col.ordered": "Objednáno",
  "receive.col.received": "Dosud přijato",
  "receive.col.total": "Celkem",
  "receive.costOrdered": "Podle objednávky {cost}",
  "receive.costToCheck": "Jeden řádek byl zaúčtován v průměrné ceně, protože žádná cena nebyla známá. Zkontrolujte jeho cenu.",
  "receive.costUsed": "Adminium použilo {cost}",
  "receive.countPacks": "Počítat v {pack} po {size}",
  "receive.countUnits": "Počítat v jednotce {unit}",
  "receive.delivery": "Dodávka",
  "receive.discard.body": "Zadané řádky nejsou uloženy. Změnou objednávky začnete znovu.",
  "receive.discard.title": "Zahodit, co jste zadali?",
  "receive.discard.yes": "Zahodit a změnit",
  "receive.draftSaved": "Koncept uložen. Najdete ho v Příjemkách.",
  "receive.empty.body": "Naskenujte krabici nebo nahoře napište název položky. Každá přidaná položka se stane řádkem.",
  "receive.empty.title": "Zatím není nic přidáno",
  "receive.err.expires": "Zadejte datum expirace",
  "receive.err.qty": "Zadejte, kolik přijímáte",
  "receive.err.whole": "Zadejte celé číslo",
  "receive.expires": "Expirace",
  "receive.fixFirst": "Před zaúčtováním je třeba opravit {count, plural, one {# pole} few {# pole} many {# pole} other {# polí}}",
  "receive.into": "Kam",
  "receive.itemAdded": "Položka přidána: {item}",
  "receive.lineCount": "{count, plural, one {# řádek} few {# řádky} many {# řádku} other {# řádků}}",
  "receive.lineIn": "Zaúčtováno",
  "receive.lineRefused": "{item}: {reason}",
  "receive.lines": "Řádky",
  "receive.missing.body": "Možná byla odstraněna, nebo ji nemůžete vidět.",
  "receive.missing.title": "Tato příjemka tu není",
  "receive.newItem.add": "Přidat položku a přijmout",
  "receive.newItem.barcode": "Čárový kód",
  "receive.newItem.name": "Název",
  "receive.newItem.nameHint": "Tak, jak se má zobrazovat v inventurách",
  "receive.newItem.nameMissing": "Dejte položce název",
  "receive.newItem.pack": "Jednotek v krabici (nepovinné)",
  "receive.newItem.subtitle": "Přidá se do Položek a do této dodávky.",
  "receive.newItem.title": "Nová položka",
  "receive.newItem.tracks": "Sleduje šarže — při každém příjmu se zeptá na šarži a datum expirace",
  "receive.newItem.unit": "Počítá se v",
  "receive.noOrder": "Bez objednávky",
  "receive.noSupplier": "Bez dodavatele",
  "receive.notAllIn": "Některé řádky ještě nejsou zaúčtovány",
  "receive.notOnOrder": "Není na této objednávce",
  "receive.nothing": "Nejdřív přidejte něco k příjmu",
  "receive.order": "Objednávka",
  "receive.orderLabel": "{number} · {supplier}",
  "receive.orderedPacks": "{packs} {pack} po {size}",
  "receive.overOrder": "{qty} {unit} navíc oproti objednávce",
  "receive.overOrderPacks": "{count, plural, one {# balení} few {# balení} many {# balení} other {# balení}} navíc oproti objednávce",
  "receive.overview": "Přehled zásob",
  "receive.pack": "balení",
  "receive.packs": "balení",
  "receive.per": "za {unit}",
  "receive.post": "Zaúčtovat příjemku",
  "receive.posted": "Příjemka zaúčtována",
  "receive.posted.batch": "Šarže {code}",
  "receive.posted.batchExpires": "Šarže {code} · expirace {date}",
  "receive.posted.full": "Objednávka {order} je přijata celá.",
  "receive.posted.noOrder": "Zásoby přijaty od dodavatele.",
  "receive.posted.onHand": "Nyní skladem {qty} {unit}",
  "receive.posted.part": "Objednávka {order} je přijata částečně.",
  "receive.posted.plain": "Zásoby přijaty.",
  "receive.posted.title": "Příjemka zaúčtována",
  "receive.posted.toCome": "Objednávka {order} je přijata částečně. Ještě má dorazit: {item}, {qty} {unit}.",
  "receive.posted.totalsMoney": "Přijato jednotek: {units} · {total}",
  "receive.posted.totalsUnits": "Přijato jednotek: {units}",
  "receive.posted.where": "Místo: {place} · {when} · {by}",
  "receive.postedFor": "Příjemka k objednávce {order} zaúčtována",
  "receive.posting.body": "Zaúčtováno {done} z {all} řádků. Pokračujte, až budete připraveni; řádek, který ještě není zaúčtován, lze stále opravit.",
  "receive.posting.title": "Tato příjemka je zaúčtována částečně",
  "receive.remove": "Odebrat položku {item}",
  "receive.removed": "Položka {item} odebrána",
  "receive.reopenFirst": "Nejdřív objednávku znovu otevřete",
  "receive.reversed.body": "Každý řádek byl ze zásob znovu odebrán. Příjemka zůstává v evidenci.",
  "receive.reversed.title": "Příjemka vrácena zpět",
  "receive.reversing.title": "Tato příjemka je vrácena zpět částečně",
  "receive.saveDraft": "Uložit jako koncept",
  "receive.scan.added": "Přidáno: {item} · 1 {unit}",
  "receive.scan.hintPack": "Čtečka píše do tohoto pole. Každé naskenování přidá jedno balení.",
  "receive.scan.hintUnit": "Čtečka píše do tohoto pole. Každé naskenování přidá jednu jednotku.",
  "receive.scan.raised": "{item} · nyní {qty} {unit}",
  "receive.seeMovements": "Zobrazit pohyby",
  "receive.sendBack": "Odeslat zpět dodavateli",
  "receive.sendBack.body": "Celý řádek opustí sklad ve své ceně a znovu se počítá jako objednaný. Chcete-li odepsat jen část řádku, použijte raději u položky volbu „Použít zásoby“.",
  "receive.sendBack.title": "Odeslat tento řádek zpět dodavateli?",
  "receive.sentBack": "Položka {item} odeslána zpět",
  "receive.status.reversed": "Vráceno zpět",
  "receive.status.sentBack": "Odesláno zpět",
  "receive.stopped": "Zaúčtováno {done} z {all} řádků. Pokračujte, až budete připraveni.",
  "receive.stoppedAt": "Zaúčtováno {done} z {all} řádků. {item}: {reason}",
  "receive.supplier": "Dodavatel (nepovinné)",
  "receive.supplierOf": "Dodavatel",
  "receive.title": "Příjem zásob",
  "receive.toCome": "{qty} {unit} ještě dorazí",
  "receive.toComePacks": "{count, plural, one {# balení} few {# balení} many {# balení} other {# balení}} ještě dorazí",
  "receive.totalsMoney": "Přijímáte jednotek: {units} · {total}",
  "receive.totalsTyped": "{count, plural, one {# řádek} few {# řádky} many {# řádku} other {# řádků}} k příjmu",
  "receive.totalsUnits": "Přijímáte jednotek: {units}",
  "receive.undo": "Vrátit tuto příjemku zpět",
  "receive.undo.body": "Každý řádek se ze skladu zase odebere, jeden po druhém. Řádek, jehož zásoby už byly použity, vrátit zpět nelze a bude uveden jménem.",
  "receive.undo.title": "Vrátit tuto příjemku zpět?",
  "receive.undoContinue": "Pokračovat ve vracení zpět",
  "receive.undoStopped": "Ještě nejsou vráceny zpět všechny řádky. Pokračujte, až budete připraveni.",
  "receive.undone": "Příjemka vrácena zpět"
};

export const transfer: Readonly<Record<string, string>> = {
  "transfer.bar": "Tento přesun",
  "transfer.batch.any": "Nejdřív nejbližší expirace",
  "transfer.batch.kept": "Dříve vybraná šarže",
  "transfer.batch.option": "{code} · {qty} {unit}",
  "transfer.choose": "Vyberte místo",
  "transfer.choosePlaces": "Vyberte, odkud zásoby jdou a kam",
  "transfer.col.batch": "Šarže",
  "transfer.col.item": "Položka",
  "transfer.col.qty": "Množství",
  "transfer.done": "Přesun dokončen",
  "transfer.draftSaved": "Koncept uložen. Najdete ho v Přesunech.",
  "transfer.empty.body": "Naskenujte položku nebo nahoře napište její název. Každá přidaná položka se stane řádkem.",
  "transfer.empty.title": "Zatím není nic přidáno",
  "transfer.err.qty": "Zadejte, kolik přesouváte",
  "transfer.finish": "Hotovo",
  "transfer.fixFirst": "Nejdřív je třeba opravit jeden řádek",
  "transfer.from": "Odkud",
  "transfer.lineCount": "{count, plural, one {# řádek} few {# řádky} many {# řádku} other {# řádků}}",
  "transfer.lineDone": "Přesunuto",
  "transfer.lineRefused": "{item}: {reason}",
  "transfer.lineUndone": "Vráceno zpět",
  "transfer.lines": "Řádky",
  "transfer.missing.body": "Možná byl odstraněn, nebo ho nemůžete vidět.",
  "transfer.missing.title": "Tento přesun tu není",
  "transfer.nothing": "Nejdřív přidejte něco k přesunu",
  "transfer.places": "Odkud a kam",
  "transfer.posting": "Tento přesun je proveden částečně. Pokračujte, až budete připraveni.",
  "transfer.remove": "Odebrat položku {item}",
  "transfer.reversed": "Tento přesun byl vrácen zpět.",
  "transfer.reversing": "Tento přesun je vrácen zpět částečně. Pokračujte, až budete připraveni.",
  "transfer.samePlace": "Vyberte jiné místo",
  "transfer.saveDraft": "Uložit jako koncept",
  "transfer.scan.added": "Přidáno: {item} · 1 {unit}",
  "transfer.scan.hint": "Čtečka píše do tohoto pole. Každé naskenování přidá jednu jednotku.",
  "transfer.scan.raised": "{item} · nyní {qty} {unit}",
  "transfer.short": "Víc, než bylo v evidenci",
  "transfer.shortToast": "Přesunuto bylo víc, než bylo v evidenci: {items}",
  "transfer.stopped": "Hotovo {done} z {all} řádků. Pokračujte, až budete připraveni.",
  "transfer.title": "Přesun zásob",
  "transfer.to": "Kam",
  "transfer.totals": "Přesun: {count, plural, one {# řádek} few {# řádky} many {# řádku} other {# řádků}}",
  "transfer.totalsDone": "Přesunuto: {count, plural, one {# řádek} few {# řádky} many {# řádku} other {# řádků}}",
  "transfer.totalsTyped": "{count, plural, one {# řádek} few {# řádky} many {# řádku} other {# řádků}} k přesunu",
  "transfer.totalsUndone": "Vráceno zpět · {count, plural, one {# řádek} few {# řádky} many {# řádku} other {# řádků}}",
  "transfer.undo": "Vrátit tento přesun zpět",
  "transfer.undo.body": "Každý řádek se přesune zpět, jeden po druhém. Řádek, jehož zásoby už byly použity, vrátit zpět nelze a bude uveden jménem.",
  "transfer.undo.title": "Vrátit tento přesun zpět?",
  "transfer.undoContinue": "Pokračovat ve vracení zpět",
  "transfer.undone": "Přesun vrácen zpět"
};

export const opening: Readonly<Record<string, string>> = {
  "opening.another": "Načíst další soubor",
  "opening.bar": "Počáteční zásoby",
  "opening.choose": "Vyberte místo",
  "opening.choosePlace": "Vyberte místo, kde tyto zásoby jsou",
  "opening.col.batch": "Šarže",
  "opening.col.cost": "Cena za jednotku",
  "opening.col.expires": "Expirace",
  "opening.col.item": "Položka",
  "opening.col.qty": "Množství",
  "opening.draftSaved": "Koncept uložen. Najdete ho v Příjemkách.",
  "opening.empty": "Začněte výběrem souboru",
  "opening.err.cost": "Zadejte cenu ve tvaru 1.10",
  "opening.err.expires": "Datum napište jako 2027-04-30",
  "opening.err.qty": "Zadejte množství větší než nula, s desetinnou tečkou",
  "opening.file.body": "Jeden řádek na každou položku nebo na každou šarži položky. Data se píší jako 2027-04-30; desetinná čísla s tečkou.",
  "opening.file.choose": "Vyberte soubor CSV",
  "opening.file.empty": "Tento soubor nemá žádné řádky.",
  "opening.file.header": "První řádek musí pojmenovat sloupce: quantity a jeden ze sloupců sku, barcode nebo name. Stáhněte si vzorový soubor a uvidíte je.",
  "opening.file.title": "Soubor",
  "opening.file.tooMany": "Tento soubor má řádků: {count}. Soubor jich smí mít nejvýše {max}: rozdělte ho a načtěte každou část zvlášť.",
  "opening.fixFirst": "{count, plural, one {# řádek je} few {# řádky je} many {# řádku je} other {# řádků je}} třeba nejdřív opravit v souboru",
  "opening.itemsMade": "{count, plural, one {Vytvořena # položka} few {Vytvořeny # položky} many {Vytvořeno # položky} other {Vytvořeno # položek}}",
  "opening.load": "Načíst počáteční zásoby",
  "opening.loaded": "Počáteční zásoby načteny",
  "opening.nothing": "Není co načíst",
  "opening.onePart": "Počáteční zásoby",
  "opening.openPart": "Otevřít",
  "opening.pages": "Strany řádků",
  "opening.part": "Počáteční zásoby, část {n} z {m}",
  "opening.partLines": "{count, plural, one {# řádek} few {# řádky} many {# řádku} other {# řádků}}",
  "opening.parts": "Řádků: {count}. Uloží se v pořadí podle souboru, počet příjemek: {parts}.",
  "opening.place": "Místo",
  "opening.progress": "Část {part}: {done} z {all} řádků",
  "opening.reading": "Čtení souboru · zatím spárováno řádků: {done}",
  "opening.review": "Kontrola",
  "opening.reviewCount": "{count, plural, one {# řádek} few {# řádky} many {# řádku} other {# řádků}} k načtení",
  "opening.row": "Řádek {at}",
  "opening.sample": "Stáhnout vzorový soubor",
  "opening.saveDraft": "Uložit jako koncept",
  "opening.saved.title": "Uloženo k načtení",
  "opening.status.draft": "Koncept",
  "opening.status.loaded": "Načteno",
  "opening.status.partly": "Načteno částečně",
  "opening.stopped": "Část {part}: zaúčtováno {done} z {all} řádků. Pokračujte, až budete připraveni.",
  "opening.stoppedAt": "Část {part}: jeden řádek byl odmítnut. {reason} Otevřete část a opravte ho.",
  "opening.title": "Počáteční zásoby",
  "opening.totals": "{count, plural, one {# řádek} few {# řádky} many {# řádku} other {# řádků}} k načtení",
  "opening.totalsSaved": "{count, plural, one {Uložena # příjemka} few {Uloženy # příjemky} many {Uloženo # příjemky} other {Uloženo # příjemek}}",
  "opening.unmatched.body": "{count, plural, one {Řádek {rows}. Bude vynechán} few {Řádky {rows}{more}. Budou vynechány} many {Řádky {rows}{more}. Budou vynechány} other {Řádky {rows}{more}. Budou vynechány}}, dokud položky nevytvoříte.",
  "opening.unmatched.leave": "Vynechat",
  "opening.unmatched.make": "Vytvořit tyto položky",
  "opening.unmatched.title": "{count, plural, one {# řádek neodpovídá} few {# řádky neodpovídají} many {# řádku neodpovídá} other {# řádků neodpovídá}} žádné položce"
};

export const counts: Readonly<Record<string, string>> = {
  "counts.add.batch": "Přidat šarži {code}",
  "counts.add.plain": "Přidat položku {item} do této inventury",
  "counts.add.title": "Položka {item} je na tomto místě, ale v této inventuře není",
  "counts.askManager": "Požádejte správce skladu, aby tuto inventuru zaúčtoval",
  "counts.bar": "Tato inventura",
  "counts.batch": "Šarže {code}",
  "counts.cancel": "Zrušit inventuru",
  "counts.cancel.body": "Nic nebylo zaúčtováno, takže se ve skladu nic nemění. Dosud zadané počty zůstanou u zrušené inventury.",
  "counts.cancel.title": "Zrušit tuto inventuru?",
  "counts.cancelledToast": "Inventura zrušena. Ve skladu se nic nezměnilo.",
  "counts.col.count": "Inventura",
  "counts.col.counted": "Spočítáno",
  "counts.col.difference": "Rozdíl",
  "counts.col.differences": "Rozdíly",
  "counts.col.expected": "Očekáváno",
  "counts.col.item": "Položka",
  "counts.col.place": "Místo",
  "counts.col.scope": "Rozsah",
  "counts.col.sku": "SKU",
  "counts.col.started": "Zahájeno",
  "counts.col.status": "Stav",
  "counts.col.value": "Hodnota",
  "counts.countedFor": "Spočítáno, {item}",
  "counts.doneForNow": "Prozatím hotovo",
  "counts.empty.body": "Spočítejte místo a porovnejte evidenci s regály.",
  "counts.empty.differ": "Zatím žádné rozdíly",
  "counts.empty.differBody": "Každý dosud spočítaný řádek odpovídá očekávanému stavu.",
  "counts.empty.lines": "Tato inventura nemá žádné řádky",
  "counts.empty.open": "Všechny řádky jsou spočítány",
  "counts.empty.openBody": "Tady už nezbývá nic ke spočítání.",
  "counts.empty.showAll": "Zobrazit všechny řádky",
  "counts.empty.title": "Zatím žádné inventury",
  "counts.filter.all": "Zobrazit vše",
  "counts.filter.differ": "Jen rozdíly",
  "counts.filter.item": "Zobrazena položka {item}",
  "counts.filter.open": "Nespočítáno",
  "counts.linePages": "Strany řádků",
  "counts.lineRefused": "{item}: {reason}",
  "counts.lines": "Řádky",
  "counts.missing.body": "Možná byla odstraněna, nebo ji nemůžete vidět.",
  "counts.missing.title": "Tato inventura tu není",
  "counts.noBatch": "Bez šarže",
  "counts.notOpen": "Tato inventura už není otevřená",
  "counts.notSaved": "Neuloženo",
  "counts.onHandNow": "Nyní skladem {qty}",
  "counts.pages": "Strany inventur",
  "counts.post": "Zaúčtovat inventuru",
  "counts.post.body": "{count, plural, one {Upraví se # řádek} few {Upraví se # řádky} many {Upraví se # řádku} other {Upraví se # řádků}}. Zaúčtovanou inventuru může správce skladu stornovat.",
  "counts.post.more": "a {count} dalších",
  "counts.post.reason": "Důvod",
  "counts.post.title": "Zaúčtovat tuto inventuru?",
  "counts.posted": "Inventura zaúčtována · upraveno: {count, plural, one {# řádek} few {# řádky} many {# řádku} other {# řádků}}",
  "counts.progress": "Spočítáno {done} z {all} řádků",
  "counts.reverse": "Stornovat inventuru…",
  "counts.reverse.body": "{count, plural, one {# řádek se vrátí} few {# řádky se vrátí} many {# řádku se vrátí} other {# řádků se vrátí}} do původního stavu. Šarže, která by klesla pod nulu, bude odmítnuta a uvedena jménem.",
  "counts.reverse.title": "Stornovat tuto inventuru?",
  "counts.reverse.yes": "Stornovat inventuru",
  "counts.reverseContinue": "Pokračovat ve stornování",
  "counts.reverseStopped": "Ještě nejsou stornovány všechny řádky. Pokračujte, až budete připraveni.",
  "counts.reversedToast": "Inventura stornována",
  "counts.saved": "Uloženo",
  "counts.saving": "Ukládání",
  "counts.scan.hint": "Naskenujte nebo napište položku a přejdete na její řádek.",
  "counts.scan.now": "Nyní na položce {item}",
  "counts.scan.unknown": "Není v této inventuře · {code}",
  "counts.scope.all": "Vše na tomto místě",
  "counts.scope.category": "Jedna kategorie",
  "counts.scope.categoryNamed": "Kategorie: {category}",
  "counts.scope.stale": "Dlouho nespočítané",
  "counts.scope.staleDays": "Položky nespočítané déle než {days} dní",
  "counts.scope.toCheck": "Označené ke kontrole",
  "counts.scope.toCheckItems": "Položky označené ke kontrole",
  "counts.sheet.subtitle": "{number} · {scope} · zahájeno {date}",
  "counts.sheet.title": "Inventura",
  "counts.sheet.titlePlace": "Inventura · {place}",
  "counts.start": "Zahájit inventuru",
  "counts.start.category": "Kategorie",
  "counts.start.chooseCategory": "Vyberte kategorii",
  "counts.start.choosePlace": "Vyberte místo",
  "counts.start.done": "Inventura zahájena, místo: {place}",
  "counts.start.doneParts": "Inventura zahájena, místo: {place}, počet inventur: {parts}",
  "counts.start.go": "Zahájit",
  "counts.start.help": "Prodeje uskutečněné během počítání zůstávají zachovány. Každý řádek se porovnává s tím, co bylo v evidenci ve chvíli, kdy jste zadali jeho počet.",
  "counts.start.nothing": "Na tomto místě nic neodpovídá: není žádný řádek ke spočítání.",
  "counts.start.openHere": "Stále otevřené inventury tohoto místa:",
  "counts.start.place": "Místo",
  "counts.start.reading": "Zahajuje se inventura · čte se stavů: {n}",
  "counts.start.title": "Zahájit inventuru",
  "counts.start.what": "Co počítat",
  "counts.status.cancelled": "Zrušeno",
  "counts.status.open": "Počítá se",
  "counts.status.posted": "Zaúčtováno",
  "counts.status.posting": "Účtuje se",
  "counts.status.reversed": "Stornováno",
  "counts.status.reversing": "Stornuje se",
  "counts.stopped": "Zaúčtováno {done} z {all} řádků. Pokračujte, až budete připraveni.",
  "counts.title": "Inventury",
  "counts.toCheck.body": "Tyto položky byly upraveny a zůstávají označené ke kontrole: {items}",
  "counts.toCheck.title": "Od spočítání se z nich prodávalo",
  "counts.totals": "{count, plural, one {# rozdíl} few {# rozdíly} many {# rozdílu} other {# rozdílů}}",
  "counts.totalsMoney": "{count, plural, one {# rozdíl} few {# rozdíly} many {# rozdílu} other {# rozdílů}} · {value}",
  "counts.uncounted": "{count, plural, one {# řádek ještě není spočítán} few {# řádky ještě nejsou spočítány} many {# řádku ještě není spočítáno} other {# řádků ještě není spočítáno}}"
};

export const rules: Readonly<Record<string, string>> = {
  "rules.add": "Přidat pravidlo",
  "rules.added": "Pravidlo u tabulky {table} přidáno",
  "rules.badge.app": "Z aplikace {app}",
  "rules.badge.yours": "Vaše tabulka",
  "rules.caughtUp": "Zapsáno: {planned}, stále čeká: {left}",
  "rules.edit": "Upravit",
  "rules.empty.body": "Pravidlo říká, kdy řádek některé z vašich tabulek zásoby rezervuje, odebírá nebo vrací.",
  "rules.empty.title": "Ze skladu zatím neodebírá žádná tabulka",
  "rules.fixed": "Tato pravidla může měnit jen ten, kdo smí měnit fungování tabulek.",
  "rules.itemsMade": "Vytvořené položky: {made}, už propojené: {skipped}",
  "rules.makeItems": "Vytvořit skladové položky z této tabulky",
  "rules.makeItems.go": "Vytvořit položky",
  "rules.makeItems.label": "Sloupec, který pojmenovává každý řádek",
  "rules.needsUnit": "Nejdřív v Nastavení vyberte výchozí jednotku",
  "rules.off": "Vypnuto",
  "rules.on": "Zapnuto",
  "rules.point.create": "řádek vznikne",
  "rules.point.from": "{row} přejde do stavu {states} ze stavu {fromStates}",
  "rules.point.in": "sloupec {column} získá hodnotu {values}",
  "rules.point.parent": "jeho {column}",
  "rules.point.row": "řádek",
  "rules.point.set": "sloupec {column} je vyplněn",
  "rules.point.to": "{row} přejde do stavu {states}",
  "rules.recordNow": "Zapsat je teď",
  "rules.remove": "Odebrat pravidlo",
  "rules.remove.confirm": "Odebrat toto pravidlo? Řádky této tabulky přestanou odebírat ze skladu.",
  "rules.rule.back": "Když {point}, vrátí se zpět.",
  "rules.rule.count": "Počítá se {multipliers}.",
  "rules.rule.from": "Z místa {place}.",
  "rules.rule.fromColumn": "Z místa ve sloupci {column}.",
  "rules.rule.give": "Když {point}, vrátí se do regálu: {what}.",
  "rules.rule.hold": "Když {point}, zásoby se rezervují.",
  "rules.rule.take": "Když {point}, odebere se: {what}.",
  "rules.saved": "Pravidlo u tabulky {table} uloženo",
  "rules.setBy": "Nastavila aplikace {app}. Můžete ho vypnout; jeho kroky se mění jen s aktualizací aplikace {app}.",
  "rules.sheet.add": "Přidat pravidlo",
  "rules.sheet.addRule": "Přidat pravidlo",
  "rules.sheet.back": "Vrátit",
  "rules.sheet.chooseColumn": "Vyberte sloupec",
  "rules.sheet.chooseTable": "Vyberte tabulku",
  "rules.sheet.defaultPlace": "Výchozí místo",
  "rules.sheet.edit": "Upravit pravidlo",
  "rules.sheet.err.table": "Vyberte tabulku",
  "rules.sheet.err.take": "Vyberte, kdy se zásoby rezervují nebo odebírají",
  "rules.sheet.err.until": "Rezervace potřebuje sloupec, který říká, kdy končí",
  "rules.sheet.err.when": "Dokončete každé „kdy“, které jste vybrali",
  "rules.sheet.guest": "Počítat za každého hosta ve sloupci",
  "rules.sheet.hold": "Rezervovat",
  "rules.sheet.linkColumn": "Který sloupec",
  "rules.sheet.night": "Počítat za každou noc ve sloupci",
  "rules.sheet.notNeeded": "Není potřeba",
  "rules.sheet.one": "Pokaždé po jednom",
  "rules.sheet.place": "Ze kterého místa",
  "rules.sheet.placeColumn": "Místo ve sloupci {column}",
  "rules.sheet.quantity": "Kolik",
  "rules.sheet.reads": "Čte se jako",
  "rules.sheet.save": "Uložit pravidlo",
  "rules.sheet.table": "Tabulka",
  "rules.sheet.take": "Odebrat",
  "rules.sheet.until": "Do kdy",
  "rules.sheet.used": "Co se používá",
  "rules.sheet.used.link": "Propojený sloupec",
  "rules.sheet.used.linkHelp": "Řádek ukazuje na to, co se používá.",
  "rules.sheet.used.row": "Tento řádek",
  "rules.sheet.used.rowHelp": "Každý řádek tabulky je něco, co se drží skladem.",
  "rules.switchLabel": "Pravidlo tabulky {table}",
  "rules.switchedOff": "Pravidlo tabulky {table} vypnuto",
  "rules.switchedOn": "Pravidlo tabulky {table} zapnuto",
  "rules.title": "Pravidla zásob",
  "rules.unavailable": "Sklad u této tabulky neodpověděl. Nová uložení čekají nebo jsou odmítnuta.",
  "rules.waiting": "{count, plural, one {# uložení čeká} few {# uložení čekají} many {# uložení čeká} other {# uložení čeká}}",
  "rules.what.column": "{quantity} × {column}",
  "rules.what.recorded": "to, co je na něm zapsáno",
  "rules.what.row": "položka tohoto řádku",
  "rules.what.rowMany": "{quantity} × položka tohoto řádku",
  "rules.when.becomes": "Když sloupec získá hodnotu",
  "rules.when.column": "{label}: který sloupec",
  "rules.when.create": "Když řádek vznikne",
  "rules.when.moves": "Když řádek přejde do stavu",
  "rules.when.never": "Nikdy",
  "rules.when.set": "Když je sloupec vyplněn"
};
