/** Danish strings for the stock screens. Keys are those of en-US.ts. */
export const shared: Readonly<Record<string, string>> = {
  "shared.cancel": "Annuller",
  "shared.close": "Luk",
  "shared.continuePosting": "Fortsæt bogføringen",
  "shared.dismiss": "Afvis",
  "shared.failed.title": "Dette kunne ikke indlæses",
  "shared.loading": "Indlæser",
  "shared.next": "Næste",
  "shared.overLimit": "For mange forespørgsler lige nu. Fortsætter af sig selv om {seconds, plural, one {# sekund} other {# sekunder}}.",
  "shared.pageN": "Side {n}",
  "shared.previous": "Forrige",
  "shared.progress": "{done} af {all} linjer",
  "shared.refused.body": "Spørg en lageransvarlig, hvis du har brug for det.",
  "shared.refused.title": "Du har ikke tilladelse til at åbne dette",
  "shared.retry": "Prøv igen",
  "shared.scan.addNew": "Tilføj den som en ny vare",
  "shared.scan.asking": "Slår den op",
  "shared.scan.failed": "Dette kunne ikke slås op",
  "shared.scan.label": "Find eller scan",
  "shared.scan.placeholder": "Scan en stregkode, eller skriv et navn eller en kode",
  "shared.scan.unknown": "Ingen vare har denne kode · {code}"
};

export const refusal: Readonly<Record<string, string>> = {
  "refusal.conflict": "En anden ændrede dette på samme tid. Prøv igen.",
  "refusal.expired": "Denne batch er allerede udløbet",
  "refusal.forbidden": "Du har ikke tilladelse til at gøre dette.",
  "refusal.full": "En indkøbsordre kan have 50 linjer. Start en ny ordre til resten.",
  "refusal.move.children": "Tilføj en linje først.",
  "refusal.move.linked": "Dette ark er ikke længere åbent for det.",
  "refusal.move.other": "Dette kan ikke gøres endnu.",
  "refusal.move.where": "Nogle linjer er ikke inde endnu.",
  "refusal.needsBatch": "Angiv batchnummeret",
  "refusal.notAllowed": "Det er ikke tilladt her.",
  "refusal.oneAtATime": "Disse linjer gemmes én ad gangen.",
  "refusal.other": "Dette kunne ikke gemmes. Prøv igen.",
  "refusal.outOfStock": "Der er ikke nok tilbage til at fortryde denne linje",
  "refusal.outOfStockLeft": "Der er kun {left} {unit} af {item} tilbage i batch {batch}: denne linje kan ikke fortrydes",
  "refusal.receiptOpen": "{rows, plural, one {# række holder} other {# rækker holder}} på lager: læg dem tilbage først",
  "refusal.stock": "Lageret kunne ikke opdateres. Intet blev ændret for denne linje. Prøv igen; bliver det ved med at fejle, så sig det til den, der passer Adminium.",
  "refusal.tooLarge": "Denne linje er for stor til at bogføre på én gang. Del den op i mindre linjer."
};

export const receive: Readonly<Record<string, string>> = {
  "receive.another": "Modtag en levering mere",
  "receive.anotherBatch": "En batch mere",
  "receive.bar": "Denne varemodtagelse",
  "receive.batch": "Batch",
  "receive.batchHint": "Som der står på kassen",
  "receive.batchKnown": "Batch {code} er allerede kendt",
  "receive.choose": "Vælg et sted",
  "receive.choosePlace": "Vælg, hvor denne levering skal hen",
  "receive.closedMeanwhile": "{order} blev lukket, mens du modtog. Varerne er på lager; ordren blev ikke ændret.",
  "receive.col.cost": "Kostpris pr. enhed",
  "receive.col.item": "Vare",
  "receive.col.now": "Modtages nu",
  "receive.col.ordered": "Bestilt",
  "receive.col.received": "Modtaget indtil nu",
  "receive.col.total": "I alt",
  "receive.costOrdered": "Ifølge bestillingen {cost}",
  "receive.costToCheck": "En linje blev bogført til gennemsnitlig kostpris, fordi ingen var kendt. Tjek dens kostpris.",
  "receive.costUsed": "Adminium brugte {cost}",
  "receive.countPacks": "Tæl i {pack} med {size}",
  "receive.countUnits": "Tæl i {unit}",
  "receive.delivery": "Levering",
  "receive.discard.body": "De linjer, du har skrevet, er ikke gemt. Skifter du ordre, starter du forfra.",
  "receive.discard.title": "Vil du kassere det, du har indtastet?",
  "receive.discard.yes": "Kassér og skift",
  "receive.draftSaved": "Kladde gemt. Find den under Varemodtagelser.",
  "receive.empty.body": "Scan en kasse, eller skriv en vares navn ovenfor. Hver vare, du tilføjer, bliver til en linje.",
  "receive.empty.title": "Intet tilføjet endnu",
  "receive.err.expires": "Angiv udløbsdatoen",
  "receive.err.qty": "Angiv, hvor mange du modtager",
  "receive.err.whole": "Angiv et helt tal",
  "receive.expires": "Udløber",
  "receive.fixFirst": "{count, plural, one {# felt skal} other {# felter skal}} rettes, før du bogfører",
  "receive.into": "Til",
  "receive.itemAdded": "Vare tilføjet: {item}",
  "receive.lineCount": "{count, plural, one {# linje} other {# linjer}}",
  "receive.lineIn": "Inde",
  "receive.lineRefused": "{item}: {reason}",
  "receive.lines": "Linjer",
  "receive.missing.body": "Den er måske blevet fjernet, eller du kan måske ikke se den.",
  "receive.missing.title": "Denne varemodtagelse findes ikke her",
  "receive.newItem.add": "Tilføj vare og modtag",
  "receive.newItem.barcode": "Stregkode",
  "receive.newItem.name": "Navn",
  "receive.newItem.nameHint": "Sådan som du vil se det på optællinger",
  "receive.newItem.nameMissing": "Giv varen et navn",
  "receive.newItem.pack": "Enheder i en kasse (valgfrit)",
  "receive.newItem.subtitle": "Den tilføjes til Varer og til denne levering.",
  "receive.newItem.title": "Ny vare",
  "receive.newItem.tracks": "Følger batches — beder om batch og udløbsdato, hver gang den modtages",
  "receive.newItem.unit": "Tælles i",
  "receive.noOrder": "Ingen indkøbsordre",
  "receive.noSupplier": "Ingen leverandør",
  "receive.notAllIn": "Nogle linjer er ikke inde endnu",
  "receive.notOnOrder": "Ikke på denne ordre",
  "receive.nothing": "Tilføj først noget at modtage",
  "receive.order": "Indkøbsordre",
  "receive.orderLabel": "{number} · {supplier}",
  "receive.orderedPacks": "{packs} {pack} med {size}",
  "receive.overOrder": "{qty} {unit} mere end bestilt",
  "receive.overOrderPacks": "{count, plural, one {# pakke} other {# pakker}} mere end bestilt",
  "receive.overview": "Lageroversigt",
  "receive.pack": "pakke",
  "receive.packs": "pakker",
  "receive.per": "pr. {unit}",
  "receive.post": "Bogfør varemodtagelse",
  "receive.posted": "Varemodtagelse bogført",
  "receive.posted.batch": "Batch {code}",
  "receive.posted.batchExpires": "Batch {code} · udløber {date}",
  "receive.posted.full": "{order} er modtaget helt.",
  "receive.posted.noOrder": "Varer modtaget fra leverandøren.",
  "receive.posted.onHand": "På lager nu {qty} {unit}",
  "receive.posted.part": "{order} er delvist modtaget.",
  "receive.posted.plain": "Varer modtaget.",
  "receive.posted.title": "Varemodtagelse bogført",
  "receive.posted.toCome": "{order} er delvist modtaget. {qty} {unit} af {item} mangler stadig.",
  "receive.posted.totalsMoney": "Modtaget {units} enheder · {total}",
  "receive.posted.totalsUnits": "Modtaget {units} enheder",
  "receive.posted.where": "Til {place} · {when} · {by}",
  "receive.postedFor": "Varemodtagelse bogført for {order}",
  "receive.posting.body": "{done} af {all} linjer er inde. Fortsæt, når du er klar; en linje, der ikke er inde endnu, kan stadig rettes.",
  "receive.posting.title": "Denne varemodtagelse er delvist inde",
  "receive.remove": "Fjern {item}",
  "receive.removed": "Fjernede {item}",
  "receive.reopenFirst": "Genåbn ordren først",
  "receive.reversed.body": "Hver linje er taget ud af lageret igen. Modtagelsen bliver stående.",
  "receive.reversed.title": "Varemodtagelse fortrudt",
  "receive.reversing.title": "Denne varemodtagelse er delvist fortrudt",
  "receive.saveDraft": "Gem som kladde",
  "receive.scan.added": "{item} tilføjet · 1 {unit}",
  "receive.scan.hintPack": "En scanner skriver i dette felt. Hvert scan tilføjer én pakke.",
  "receive.scan.hintUnit": "En scanner skriver i dette felt. Hvert scan tilføjer én.",
  "receive.scan.raised": "{item} · nu {qty} {unit}",
  "receive.seeMovements": "Se bevægelser",
  "receive.sendBack": "Send tilbage til leverandøren",
  "receive.sendBack.body": "Hele linjen går ud af lageret til sin kostpris og tæller som bestilt igen. Vil du afskrive en del af en linje, så brug \"Brug lager\" på varen i stedet.",
  "receive.sendBack.title": "Vil du sende denne linje tilbage til leverandøren?",
  "receive.sentBack": "{item} sendt tilbage",
  "receive.status.reversed": "Fortrudt",
  "receive.status.sentBack": "Sendt tilbage",
  "receive.stopped": "{done} af {all} linjer er inde. Fortsæt, når du er klar.",
  "receive.stoppedAt": "{done} af {all} linjer er inde. {item}: {reason}",
  "receive.supplier": "Leverandør (valgfrit)",
  "receive.supplierOf": "Leverandør",
  "receive.title": "Modtag varer",
  "receive.toCome": "{qty} {unit} mangler stadig",
  "receive.toComePacks": "{count, plural, one {# pakke} other {# pakker}} mangler stadig",
  "receive.totalsMoney": "Modtager {units} enheder · {total}",
  "receive.totalsTyped": "{count, plural, one {# linje} other {# linjer}} at modtage",
  "receive.totalsUnits": "Modtager {units} enheder",
  "receive.undo": "Fortryd denne varemodtagelse",
  "receive.undo.body": "Hver linje tages ud af lageret igen, én ad gangen. En linje, hvis varer allerede er brugt, kan ikke fortrydes og bliver nævnt.",
  "receive.undo.title": "Vil du fortryde denne varemodtagelse?",
  "receive.undoContinue": "Fortsæt med at fortryde",
  "receive.undoStopped": "Ikke alle linjer er fortrudt endnu. Fortsæt, når du er klar.",
  "receive.undone": "Varemodtagelse fortrudt"
};

export const transfer: Readonly<Record<string, string>> = {
  "transfer.bar": "Denne overførsel",
  "transfer.batch.any": "Tidligste udløb først",
  "transfer.batch.kept": "Den batch, der blev valgt før",
  "transfer.batch.option": "{code} · {qty} {unit}",
  "transfer.choose": "Vælg et sted",
  "transfer.choosePlaces": "Vælg, hvor varerne kommer fra, og hvor de skal hen",
  "transfer.col.batch": "Batch",
  "transfer.col.item": "Vare",
  "transfer.col.qty": "Antal",
  "transfer.done": "Overførsel gennemført",
  "transfer.draftSaved": "Kladde gemt. Find den under Overførsler.",
  "transfer.empty.body": "Scan en vare, eller skriv dens navn ovenfor. Hver vare, du tilføjer, bliver til en linje.",
  "transfer.empty.title": "Intet tilføjet endnu",
  "transfer.err.qty": "Angiv, hvor mange du flytter",
  "transfer.finish": "Færdig",
  "transfer.fixFirst": "En linje skal rettes først",
  "transfer.from": "Fra",
  "transfer.lineCount": "{count, plural, one {# linje} other {# linjer}}",
  "transfer.lineDone": "Flyttet",
  "transfer.lineRefused": "{item}: {reason}",
  "transfer.lineUndone": "Fortrudt",
  "transfer.lines": "Linjer",
  "transfer.missing.body": "Den er måske blevet fjernet, eller du kan måske ikke se den.",
  "transfer.missing.title": "Denne overførsel findes ikke her",
  "transfer.nothing": "Tilføj først noget at flytte",
  "transfer.places": "Fra og til",
  "transfer.posting": "Denne overførsel er delvist gennemført. Fortsæt, når du er klar.",
  "transfer.remove": "Fjern {item}",
  "transfer.reversed": "Denne overførsel blev fortrudt.",
  "transfer.reversing": "Denne overførsel er delvist fortrudt. Fortsæt, når du er klar.",
  "transfer.samePlace": "Vælg et andet sted",
  "transfer.saveDraft": "Gem som kladde",
  "transfer.scan.added": "{item} tilføjet · 1 {unit}",
  "transfer.scan.hint": "En scanner skriver i dette felt. Hvert scan tilføjer én.",
  "transfer.scan.raised": "{item} · nu {qty} {unit}",
  "transfer.short": "Mere end bøgerne viste",
  "transfer.shortToast": "Der blev flyttet mere, end bøgerne viste: {items}",
  "transfer.stopped": "{done} af {all} linjer er gennemført. Fortsæt, når du er klar.",
  "transfer.title": "Overfør lager",
  "transfer.to": "Til",
  "transfer.totals": "Flytter {count, plural, one {# linje} other {# linjer}}",
  "transfer.totalsDone": "{count, plural, one {# linje} other {# linjer}} flyttet",
  "transfer.totalsTyped": "{count, plural, one {# linje} other {# linjer}} at flytte",
  "transfer.totalsUndone": "Fortrudt · {count, plural, one {# linje} other {# linjer}}",
  "transfer.undo": "Fortryd denne overførsel",
  "transfer.undo.body": "Hver linje flyttes tilbage, én ad gangen. En linje, hvis varer allerede er brugt, kan ikke fortrydes og bliver nævnt.",
  "transfer.undo.title": "Vil du fortryde denne overførsel?",
  "transfer.undoContinue": "Fortsæt med at fortryde",
  "transfer.undone": "Overførsel fortrudt"
};

export const opening: Readonly<Record<string, string>> = {
  "opening.another": "Indlæs en fil mere",
  "opening.bar": "Startbeholdning",
  "opening.choose": "Vælg et sted",
  "opening.choosePlace": "Vælg det sted, hvor denne beholdning ligger",
  "opening.col.batch": "Batch",
  "opening.col.cost": "Kostpris pr. enhed",
  "opening.col.expires": "Udløber",
  "opening.col.item": "Vare",
  "opening.col.qty": "Antal",
  "opening.draftSaved": "Kladde gemt. Find den under Varemodtagelser.",
  "opening.empty": "Vælg en fil for at begynde",
  "opening.err.cost": "Angiv en kostpris som 1.10",
  "opening.err.expires": "Skriv datoen som 2027-04-30",
  "opening.err.qty": "Angiv et antal over nul, med punktum som decimaltegn",
  "opening.file.body": "Én række for hver vare eller for hver batch af en vare. Datoer skrives 2027-04-30; decimaler skrives med punktum.",
  "opening.file.choose": "Vælg en CSV-fil",
  "opening.file.empty": "Denne fil har ingen rækker.",
  "opening.file.header": "Den første række skal navngive kolonnerne: quantity og én af sku, barcode eller name. Hent eksempelfilen for at se dem.",
  "opening.file.title": "Filen",
  "opening.file.tooMany": "Denne fil har {count} rækker. En fil må have op til {max}: del den op, og indlæs hver del.",
  "opening.fixFirst": "{count, plural, one {# række skal} other {# rækker skal}} først rettes i filen",
  "opening.itemsMade": "{count, plural, one {# vare} other {# varer}} oprettet",
  "opening.load": "Indlæs startbeholdning",
  "opening.loaded": "Startbeholdning indlæst",
  "opening.nothing": "Der er intet at indlæse",
  "opening.onePart": "Startbeholdning",
  "opening.openPart": "Åbn",
  "opening.pages": "Sider med linjer",
  "opening.part": "Startbeholdning, del {n} af {m}",
  "opening.partLines": "{count, plural, one {# linje} other {# linjer}}",
  "opening.parts": "{count} linjer: dette gemmes som {parts} varemodtagelser, i filens rækkefølge.",
  "opening.place": "Sted",
  "opening.progress": "Del {part}: {done} af {all} linjer",
  "opening.reading": "Læser filen · {done} rækker matchet indtil nu",
  "opening.review": "Gennemse",
  "opening.reviewCount": "{count, plural, one {# linje} other {# linjer}} at indlæse",
  "opening.row": "Række {at}",
  "opening.sample": "Hent en eksempelfil",
  "opening.saveDraft": "Gem som kladde",
  "opening.saved.title": "Gemt til indlæsning",
  "opening.status.draft": "Kladde",
  "opening.status.loaded": "Indlæst",
  "opening.status.partly": "Delvist indlæst",
  "opening.stopped": "Del {part}: {done} af {all} linjer er inde. Fortsæt, når du er klar.",
  "opening.stoppedAt": "Del {part}: en linje blev afvist. {reason} Åbn delen for at rette den.",
  "opening.title": "Startbeholdning",
  "opening.totals": "{count, plural, one {# linje} other {# linjer}} at indlæse",
  "opening.totalsSaved": "{count, plural, one {# varemodtagelse} other {# varemodtagelser}} gemt",
  "opening.unmatched.body": "{count, plural, one {Række {rows}. Den udelades} other {Rækker {rows}{more}. De udelades}}, medmindre du opretter varerne.",
  "opening.unmatched.leave": "Udelad",
  "opening.unmatched.make": "Opret disse varer",
  "opening.unmatched.title": "{count, plural, one {# række matcher} other {# rækker matcher}} ingen vare"
};

export const counts: Readonly<Record<string, string>> = {
  "counts.add.batch": "Tilføj batch {code}",
  "counts.add.plain": "Tilføj {item} til denne optælling",
  "counts.add.title": "{item} er på dette sted og ikke med i denne optælling",
  "counts.askManager": "Bed en lageransvarlig om at bogføre denne optælling",
  "counts.bar": "Denne optælling",
  "counts.batch": "Batch {code}",
  "counts.cancel": "Annuller optælling",
  "counts.cancel.body": "Intet blev bogført, så intet ændres på lageret. De tal, der er indtastet indtil nu, gemmes sammen med den annullerede optælling.",
  "counts.cancel.title": "Vil du annullere denne optælling?",
  "counts.cancelledToast": "Optælling annulleret. Intet blev ændret på lageret.",
  "counts.col.count": "Optælling",
  "counts.col.counted": "Optalt",
  "counts.col.difference": "Forskel",
  "counts.col.differences": "Forskelle",
  "counts.col.expected": "Forventet",
  "counts.col.item": "Vare",
  "counts.col.place": "Sted",
  "counts.col.scope": "Omfang",
  "counts.col.sku": "SKU",
  "counts.col.started": "Startet",
  "counts.col.status": "Status",
  "counts.col.value": "Værdi",
  "counts.countedFor": "Optalt, {item}",
  "counts.doneForNow": "Færdig for nu",
  "counts.empty.body": "Tæl et sted op for at tjekke bøgerne mod hylderne.",
  "counts.empty.differ": "Ingen forskelle indtil nu",
  "counts.empty.differBody": "Alle linjer, der er talt indtil nu, stemmer med det forventede.",
  "counts.empty.lines": "Denne optælling har ingen linjer",
  "counts.empty.open": "Alle linjer er optalt",
  "counts.empty.openBody": "Der er ikke mere at tælle her.",
  "counts.empty.showAll": "Vis alle linjer",
  "counts.empty.title": "Ingen optællinger endnu",
  "counts.filter.all": "Vis alle",
  "counts.filter.differ": "Kun forskelle",
  "counts.filter.item": "Viser {item}",
  "counts.filter.open": "Ikke optalt",
  "counts.linePages": "Sider med linjer",
  "counts.lineRefused": "{item}: {reason}",
  "counts.lines": "Linjer",
  "counts.missing.body": "Den er måske blevet fjernet, eller du kan måske ikke se den.",
  "counts.missing.title": "Denne optælling findes ikke her",
  "counts.noBatch": "Ingen batch",
  "counts.notOpen": "Denne optælling er ikke længere åben",
  "counts.notSaved": "Ikke gemt",
  "counts.onHandNow": "På lager nu {qty}",
  "counts.pages": "Sider med optællinger",
  "counts.post": "Bogfør optælling",
  "counts.post.body": "{count, plural, one {# linje} other {# linjer}} bliver justeret. En lageransvarlig kan tilbageføre en bogført optælling.",
  "counts.post.more": "og {count} mere",
  "counts.post.reason": "Årsag",
  "counts.post.title": "Vil du bogføre denne optælling?",
  "counts.posted": "Optælling bogført · {count, plural, one {# linje} other {# linjer}} justeret",
  "counts.progress": "{done} af {all} linjer optalt",
  "counts.reverse": "Tilbagefør optælling…",
  "counts.reverse.body": "{count, plural, one {# linje} other {# linjer}} bliver sat tilbage, som de var. En batch, der ville komme under nul, afvises og bliver nævnt.",
  "counts.reverse.title": "Vil du tilbageføre denne optælling?",
  "counts.reverse.yes": "Tilbagefør optælling",
  "counts.reverseContinue": "Fortsæt tilbageførslen",
  "counts.reverseStopped": "Ikke alle linjer er tilbageført endnu. Fortsæt, når du er klar.",
  "counts.reversedToast": "Optælling tilbageført",
  "counts.saved": "Gemt",
  "counts.saving": "Gemmer",
  "counts.scan.hint": "Scan eller skriv en vare for at hoppe til dens linje.",
  "counts.scan.now": "Nu på {item}",
  "counts.scan.unknown": "Ikke med i denne optælling · {code}",
  "counts.scope.all": "Alt på dette sted",
  "counts.scope.category": "Én kategori",
  "counts.scope.categoryNamed": "Kategori: {category}",
  "counts.scope.stale": "Ikke optalt for nylig",
  "counts.scope.staleDays": "Varer, der ikke er optalt i {days} dage",
  "counts.scope.toCheck": "Markeret til tjek",
  "counts.scope.toCheckItems": "Varer markeret til tjek",
  "counts.sheet.subtitle": "{number} · {scope} · startet {date}",
  "counts.sheet.title": "Optælling",
  "counts.sheet.titlePlace": "Optælling · {place}",
  "counts.start": "Start en optælling",
  "counts.start.category": "Kategori",
  "counts.start.chooseCategory": "Vælg en kategori",
  "counts.start.choosePlace": "Vælg et sted",
  "counts.start.done": "Optælling startet for {place}",
  "counts.start.doneParts": "Optælling startet for {place} som {parts} optællinger",
  "counts.start.go": "Start",
  "counts.start.help": "Salg, der sker, mens du tæller, bliver bevaret. Hver linje sammenlignes med det, bøgerne viste, i det øjeblik du skrev dens tal.",
  "counts.start.nothing": "Intet på dette sted passer: der er ingen linje at tælle.",
  "counts.start.openHere": "Optællinger, der stadig er åbne for dette sted:",
  "counts.start.place": "Sted",
  "counts.start.reading": "Starter optællingen · læser {n} beholdninger",
  "counts.start.title": "Start en optælling",
  "counts.start.what": "Hvad der skal tælles",
  "counts.status.cancelled": "Annulleret",
  "counts.status.open": "Tælles",
  "counts.status.posted": "Bogført",
  "counts.status.posting": "Bogfører",
  "counts.status.reversed": "Tilbageført",
  "counts.status.reversing": "Tilbagefører",
  "counts.stopped": "{done} af {all} linjer er bogført. Fortsæt, når du er klar.",
  "counts.title": "Optællinger",
  "counts.toCheck.body": "Disse blev justeret og er stadig markeret til tjek: {items}",
  "counts.toCheck.title": "Solgt fra, siden de blev optalt",
  "counts.totals": "{count, plural, one {# forskel} other {# forskelle}}",
  "counts.totalsMoney": "{count, plural, one {# forskel} other {# forskelle}} · {value}",
  "counts.uncounted": "{count, plural, one {# linje} other {# linjer}} er ikke optalt endnu"
};

export const rules: Readonly<Record<string, string>> = {
  "rules.add": "Tilføj en regel",
  "rules.added": "Regel for {table} tilføjet",
  "rules.badge.app": "Fra {app}",
  "rules.badge.yours": "Din tabel",
  "rules.caughtUp": "{planned} registreret, {left} venter stadig",
  "rules.edit": "Rediger",
  "rules.empty.body": "En regel siger, hvornår en række i en af dine tabeller reserverer, tager eller lægger varer tilbage på lager.",
  "rules.empty.title": "Ingen tabel tager fra lageret endnu",
  "rules.fixed": "Kun en, der må ændre, hvordan tabeller virker, kan ændre disse regler.",
  "rules.itemsMade": "{made} varer oprettet, {skipped} var allerede tilknyttet",
  "rules.makeItems": "Opret lagervarer ud fra denne tabel",
  "rules.makeItems.go": "Opret varerne",
  "rules.makeItems.label": "Den kolonne, der navngiver hver række",
  "rules.needsUnit": "Vælg først en standardenhed i Indstillinger",
  "rules.off": "Fra",
  "rules.on": "Til",
  "rules.point.create": "rækken oprettes",
  "rules.point.from": "{row} skifter til {states} fra {fromStates}",
  "rules.point.in": "{column} bliver {values}",
  "rules.point.parent": "dens {column}",
  "rules.point.row": "rækken",
  "rules.point.set": "{column} bliver udfyldt",
  "rules.point.to": "{row} skifter til {states}",
  "rules.recordNow": "Registrer dem nu",
  "rules.remove": "Fjern regel",
  "rules.remove.confirm": "Vil du fjerne denne regel? Rækker i denne tabel holder op med at tage fra lageret.",
  "rules.rule.back": "Når {point}, læg det tilbage.",
  "rules.rule.count": "Tæller {multipliers}.",
  "rules.rule.from": "Fra {place}.",
  "rules.rule.fromColumn": "Fra stedet i {column}.",
  "rules.rule.give": "Når {point}, læg {what} tilbage på hylden.",
  "rules.rule.hold": "Når {point}, reservér varerne.",
  "rules.rule.take": "Når {point}, tag {what}.",
  "rules.saved": "Regel for {table} gemt",
  "rules.setBy": "Sat af {app}. Du kan slå den fra; dens trin ændres kun med en opdatering af {app}.",
  "rules.sheet.add": "Tilføj en regel",
  "rules.sheet.addRule": "Tilføj regel",
  "rules.sheet.back": "Læg tilbage",
  "rules.sheet.chooseColumn": "Vælg en kolonne",
  "rules.sheet.chooseTable": "Vælg en tabel",
  "rules.sheet.defaultPlace": "Standardstedet",
  "rules.sheet.edit": "Rediger regel",
  "rules.sheet.err.table": "Vælg en tabel",
  "rules.sheet.err.take": "Vælg, hvornår varer reserveres eller tages",
  "rules.sheet.err.until": "En reservation skal have den kolonne, der siger, hvornår den slutter",
  "rules.sheet.err.when": "Gør hvert \"hvornår\", du valgte, færdigt",
  "rules.sheet.guest": "Tælles for hver gæst i",
  "rules.sheet.hold": "Reservér",
  "rules.sheet.linkColumn": "Hvilken kolonne",
  "rules.sheet.night": "Tælles for hver nat i",
  "rules.sheet.notNeeded": "Ikke nødvendig",
  "rules.sheet.one": "Én hver gang",
  "rules.sheet.place": "Fra hvilket sted",
  "rules.sheet.placeColumn": "Stedet i {column}",
  "rules.sheet.quantity": "Hvor mange",
  "rules.sheet.reads": "Læses som",
  "rules.sheet.save": "Gem regel",
  "rules.sheet.table": "Tabel",
  "rules.sheet.take": "Tag",
  "rules.sheet.until": "Indtil hvornår",
  "rules.sheet.used": "Hvad der bruges",
  "rules.sheet.used.link": "En tilknyttet kolonne",
  "rules.sheet.used.linkHelp": "Rækken peger på det, der bruges.",
  "rules.sheet.used.row": "Denne række",
  "rules.sheet.used.rowHelp": "Hver række i tabellen er noget, der ligger på lager.",
  "rules.switchLabel": "Regel for {table}",
  "rules.switchedOff": "Regel for {table} slået fra",
  "rules.switchedOn": "Regel for {table} slået til",
  "rules.title": "Lagerregler",
  "rules.unavailable": "Inventory kunne ikke svare for denne tabel. Nye gemninger venter eller bliver afvist.",
  "rules.waiting": "{count, plural, one {# gemning venter} other {# gemninger venter}}",
  "rules.what.column": "{quantity} af {column}",
  "rules.what.recorded": "det, der er registreret på den",
  "rules.what.row": "denne rækkes vare",
  "rules.what.rowMany": "{quantity} af denne rækkes vare",
  "rules.when.becomes": "Når en kolonne bliver",
  "rules.when.column": "{label}: hvilken kolonne",
  "rules.when.create": "Når rækken oprettes",
  "rules.when.moves": "Når rækken skifter til",
  "rules.when.never": "Aldrig",
  "rules.when.set": "Når en kolonne bliver udfyldt"
};
