/** German strings for the stock screens. Keys are those of en-US.ts. */
export const shared: Readonly<Record<string, string>> = {
  "shared.cancel": "Abbrechen",
  "shared.close": "Schließen",
  "shared.continuePosting": "Weiter buchen",
  "shared.dismiss": "Ausblenden",
  "shared.failed.title": "Das konnte nicht geladen werden",
  "shared.loading": "Wird geladen",
  "shared.next": "Weiter",
  "shared.pageN": "Seite {n}",
  "shared.previous": "Zurück",
  "shared.progress": "{done} von {all} Zeilen",
  "shared.refused.body": "Fragen Sie die Lagerleitung, wenn Sie es brauchen.",
  "shared.refused.title": "Sie dürfen das nicht öffnen",
  "shared.retry": "Erneut versuchen",
  "shared.scan.addNew": "Als neuen Artikel anlegen",
  "shared.scan.asking": "Wird gesucht",
  "shared.scan.failed": "Das konnte nicht gesucht werden",
  "shared.scan.label": "Suchen oder scannen",
  "shared.scan.placeholder": "Barcode scannen oder Namen oder Code eingeben",
  "shared.scan.unknown": "Kein Artikel hat diesen Code · {code}"
};

export const refusal: Readonly<Record<string, string>> = {
  "refusal.conflict": "Jemand anderes hat das gleichzeitig geändert. Versuchen Sie es erneut.",
  "refusal.expired": "Diese Charge ist bereits abgelaufen",
  "refusal.forbidden": "Sie dürfen das nicht tun.",
  "refusal.full": "Eine Bestellung fasst 50 Zeilen. Legen Sie für den Rest eine weitere Bestellung an.",
  "refusal.move.children": "Fügen Sie zuerst eine Zeile hinzu.",
  "refusal.move.linked": "Dieses Blatt ist dafür nicht mehr offen.",
  "refusal.move.other": "Das geht noch nicht.",
  "refusal.move.where": "Einige Zeilen sind noch nicht eingebucht.",
  "refusal.needsBatch": "Geben Sie die Chargennummer ein",
  "refusal.notAllowed": "Das ist hier nicht erlaubt.",
  "refusal.oneAtATime": "Diese Zeilen werden einzeln gespeichert.",
  "refusal.other": "Das konnte nicht gespeichert werden. Versuchen Sie es erneut.",
  "refusal.outOfStock": "Nicht genug übrig, um diese Zeile rückgängig zu machen",
  "refusal.outOfStockLeft": "In Charge {batch} sind nur noch {left} {unit} von {item} übrig: Diese Zeile kann nicht rückgängig gemacht werden",
  "refusal.receiptOpen": "{rows, plural, one {# Zeile hält} other {# Zeilen halten}} Bestand: Legen Sie ihn zuerst zurück",
  "refusal.stock": "Der Bestand konnte nicht aktualisiert werden. Für diese Zeile wurde nichts geändert. Versuchen Sie es erneut; wenn es weiter fehlschlägt, sagen Sie der Person Bescheid, die Adminium betreut.",
  "refusal.tooLarge": "Diese Zeile ist zu groß, um sie auf einmal zu buchen. Teilen Sie sie in kleinere Zeilen auf."
};

export const receive: Readonly<Record<string, string>> = {
  "receive.another": "Weitere Lieferung annehmen",
  "receive.anotherBatch": "Weitere Charge",
  "receive.bar": "Dieser Wareneingang",
  "receive.batch": "Charge",
  "receive.batchHint": "Wie auf dem Karton aufgedruckt",
  "receive.batchKnown": "Charge {code} ist bereits bekannt",
  "receive.choose": "Lagerort wählen",
  "receive.choosePlace": "Wählen Sie, wohin diese Lieferung kommt",
  "receive.closedMeanwhile": "{order} wurde geschlossen, während Sie die Ware angenommen haben. Der Bestand ist eingebucht; die Bestellung hat sich nicht geändert.",
  "receive.col.cost": "Stückkosten",
  "receive.col.item": "Artikel",
  "receive.col.now": "Jetzt angenommen",
  "receive.col.ordered": "Bestellt",
  "receive.col.received": "Bisher erhalten",
  "receive.col.total": "Summe",
  "receive.costOrdered": "Laut Bestellung {cost}",
  "receive.costToCheck": "Eine Zeile wurde zu den Durchschnittskosten gebucht, weil keine Kosten bekannt waren. Prüfen Sie ihre Kosten.",
  "receive.costUsed": "Adminium hat {cost} verwendet",
  "receive.countPacks": "In {pack} zu {size} zählen",
  "receive.countUnits": "In {unit} zählen",
  "receive.delivery": "Lieferung",
  "receive.discard.body": "Die eingegebenen Zeilen sind nicht gespeichert. Wenn Sie die Bestellung ändern, beginnen Sie von vorn.",
  "receive.discard.title": "Eingaben verwerfen?",
  "receive.discard.yes": "Verwerfen und ändern",
  "receive.draftSaved": "Entwurf gespeichert. Sie finden ihn unter Wareneingänge.",
  "receive.empty.body": "Scannen Sie oben einen Karton oder geben Sie den Namen eines Artikels ein. Jeder hinzugefügte Artikel wird zu einer Zeile.",
  "receive.empty.title": "Noch nichts hinzugefügt",
  "receive.err.expires": "Geben Sie das Verfallsdatum ein",
  "receive.err.qty": "Geben Sie ein, wie viel Sie annehmen",
  "receive.err.whole": "Geben Sie eine ganze Zahl ein",
  "receive.expires": "Läuft ab",
  "receive.fixFirst": "{count, plural, one {# Feld muss} other {# Felder müssen}} vor dem Buchen korrigiert werden",
  "receive.into": "Nach",
  "receive.itemAdded": "Artikel hinzugefügt: {item}",
  "receive.lineCount": "{count, plural, one {# Zeile} other {# Zeilen}}",
  "receive.lineIn": "Eingebucht",
  "receive.lineRefused": "{item}: {reason}",
  "receive.lines": "Zeilen",
  "receive.missing.body": "Er wurde vielleicht entfernt, oder Sie dürfen ihn nicht sehen.",
  "receive.missing.title": "Dieser Wareneingang ist nicht vorhanden",
  "receive.newItem.add": "Artikel anlegen und annehmen",
  "receive.newItem.barcode": "Barcode",
  "receive.newItem.name": "Name",
  "receive.newItem.nameHint": "So, wie er bei Zählungen erscheinen soll",
  "receive.newItem.nameMissing": "Geben Sie dem Artikel einen Namen",
  "receive.newItem.pack": "Einheiten je Karton (optional)",
  "receive.newItem.subtitle": "Er wird zu den Artikeln und zu dieser Lieferung hinzugefügt.",
  "receive.newItem.title": "Neuer Artikel",
  "receive.newItem.tracks": "Führt Chargen — fragt bei jedem Wareneingang nach Charge und Verfallsdatum",
  "receive.newItem.unit": "Gezählt in",
  "receive.noOrder": "Keine Bestellung",
  "receive.noSupplier": "Kein Lieferant",
  "receive.notAllIn": "Einige Zeilen sind noch nicht eingebucht",
  "receive.notOnOrder": "Nicht in dieser Bestellung",
  "receive.nothing": "Fügen Sie zuerst etwas zum Annehmen hinzu",
  "receive.order": "Bestellung",
  "receive.orderLabel": "{number} · {supplier}",
  "receive.orderedPacks": "{packs} {pack} zu {size}",
  "receive.overOrder": "{qty} {unit} mehr als bestellt",
  "receive.overview": "Bestandsübersicht",
  "receive.pack": "Packung",
  "receive.packs": "Packungen",
  "receive.per": "je {unit}",
  "receive.post": "Wareneingang buchen",
  "receive.posted": "Wareneingang gebucht",
  "receive.posted.batch": "Charge {code}",
  "receive.posted.batchExpires": "Charge {code} · läuft ab {date}",
  "receive.posted.full": "{order} ist vollständig erhalten.",
  "receive.posted.noOrder": "Bestand vom Lieferanten erhalten.",
  "receive.posted.onHand": "Jetzt vorrätig {qty} {unit}",
  "receive.posted.part": "{order} ist teilweise erhalten.",
  "receive.posted.plain": "Bestand erhalten.",
  "receive.posted.title": "Wareneingang gebucht",
  "receive.posted.toCome": "{order} ist teilweise erhalten. {qty} {unit} von {item} stehen noch aus.",
  "receive.posted.totalsMoney": "{units} Einheiten erhalten · {total}",
  "receive.posted.totalsUnits": "{units} Einheiten erhalten",
  "receive.posted.where": "Nach {place} · {when} · {by}",
  "receive.postedFor": "Wareneingang für {order} gebucht",
  "receive.posting.body": "{done} von {all} Zeilen sind eingebucht. Machen Sie weiter, wenn Sie so weit sind; eine noch nicht eingebuchte Zeile lässt sich noch korrigieren.",
  "receive.posting.title": "Dieser Wareneingang ist teilweise eingebucht",
  "receive.remove": "{item} entfernen",
  "receive.removed": "{item} entfernt",
  "receive.reopenFirst": "Öffnen Sie zuerst die Bestellung wieder",
  "receive.reversed.body": "Jede Zeile wurde wieder aus dem Bestand genommen. Der Wareneingang bleibt erhalten.",
  "receive.reversed.title": "Wareneingang rückgängig gemacht",
  "receive.reversing.title": "Dieser Wareneingang ist teilweise rückgängig gemacht",
  "receive.saveDraft": "Als Entwurf speichern",
  "receive.scan.added": "{item} hinzugefügt · 1 {unit}",
  "receive.scan.hintPack": "Ein Scanner schreibt in dieses Feld. Jeder Scan fügt eine Packung hinzu.",
  "receive.scan.hintUnit": "Ein Scanner schreibt in dieses Feld. Jeder Scan fügt eine Einheit hinzu.",
  "receive.scan.raised": "{item} · jetzt {qty} {unit}",
  "receive.seeMovements": "Bewegungen ansehen",
  "receive.sendBack": "An Lieferanten zurücksenden",
  "receive.sendBack.body": "Die ganze Zeile verlässt den Bestand zu ihren Kosten und gilt wieder als bestellt. Um nur einen Teil einer Zeile auszubuchen, nutzen Sie stattdessen „Bestand verwenden“ beim Artikel.",
  "receive.sendBack.title": "Diese Zeile an den Lieferanten zurücksenden?",
  "receive.sentBack": "{item} zurückgesendet",
  "receive.status.reversed": "Rückgängig gemacht",
  "receive.status.sentBack": "Zurückgesendet",
  "receive.stopped": "{done} von {all} Zeilen sind eingebucht. Machen Sie weiter, wenn Sie so weit sind.",
  "receive.stoppedAt": "{done} von {all} Zeilen sind eingebucht. {item}: {reason}",
  "receive.supplier": "Lieferant (optional)",
  "receive.supplierOf": "Lieferant",
  "receive.title": "Ware annehmen",
  "receive.toCome": "{qty} {unit} stehen noch aus",
  "receive.totalsMoney": "{units} Einheiten werden angenommen · {total}",
  "receive.totalsTyped": "{count, plural, one {# Zeile} other {# Zeilen}} anzunehmen",
  "receive.totalsUnits": "{units} Einheiten werden angenommen",
  "receive.undo": "Diesen Wareneingang rückgängig machen",
  "receive.undo.body": "Jede Zeile wird einzeln wieder aus dem Bestand genommen. Eine Zeile, deren Bestand schon verbraucht wurde, kann nicht rückgängig gemacht werden und wird genannt.",
  "receive.undo.title": "Diesen Wareneingang rückgängig machen?",
  "receive.undoContinue": "Weiter rückgängig machen",
  "receive.undoStopped": "Noch sind nicht alle Zeilen rückgängig gemacht. Machen Sie weiter, wenn Sie so weit sind.",
  "receive.undone": "Wareneingang rückgängig gemacht"
};

export const transfer: Readonly<Record<string, string>> = {
  "transfer.bar": "Diese Umlagerung",
  "transfer.batch.any": "Frühestes Verfallsdatum zuerst",
  "transfer.batch.kept": "Die zuvor gewählte Charge",
  "transfer.batch.option": "{code} · {qty} {unit}",
  "transfer.choose": "Lagerort wählen",
  "transfer.choosePlaces": "Wählen Sie, woher der Bestand kommt und wohin er geht",
  "transfer.col.batch": "Charge",
  "transfer.col.item": "Artikel",
  "transfer.col.qty": "Menge",
  "transfer.done": "Umlagerung abgeschlossen",
  "transfer.draftSaved": "Entwurf gespeichert. Sie finden ihn unter Umlagerungen.",
  "transfer.empty.body": "Scannen Sie oben einen Artikel oder geben Sie seinen Namen ein. Jeder hinzugefügte Artikel wird zu einer Zeile.",
  "transfer.empty.title": "Noch nichts hinzugefügt",
  "transfer.err.qty": "Geben Sie ein, wie viel Sie umlagern",
  "transfer.finish": "Fertig",
  "transfer.fixFirst": "Eine Zeile muss zuerst korrigiert werden",
  "transfer.from": "Von",
  "transfer.lineCount": "{count, plural, one {# Zeile} other {# Zeilen}}",
  "transfer.lineDone": "Umgelagert",
  "transfer.lineRefused": "{item}: {reason}",
  "transfer.lineUndone": "Rückgängig gemacht",
  "transfer.lines": "Zeilen",
  "transfer.missing.body": "Sie wurde vielleicht entfernt, oder Sie dürfen sie nicht sehen.",
  "transfer.missing.title": "Diese Umlagerung ist nicht vorhanden",
  "transfer.nothing": "Fügen Sie zuerst etwas zum Umlagern hinzu",
  "transfer.places": "Von und nach",
  "transfer.posting": "Diese Umlagerung ist teilweise erledigt. Machen Sie weiter, wenn Sie so weit sind.",
  "transfer.remove": "{item} entfernen",
  "transfer.reversed": "Diese Umlagerung wurde rückgängig gemacht.",
  "transfer.reversing": "Diese Umlagerung ist teilweise rückgängig gemacht. Machen Sie weiter, wenn Sie so weit sind.",
  "transfer.samePlace": "Wählen Sie einen anderen Lagerort",
  "transfer.saveDraft": "Als Entwurf speichern",
  "transfer.scan.added": "{item} hinzugefügt · 1 {unit}",
  "transfer.scan.hint": "Ein Scanner schreibt in dieses Feld. Jeder Scan fügt eine Einheit hinzu.",
  "transfer.scan.raised": "{item} · jetzt {qty} {unit}",
  "transfer.short": "Mehr, als laut Büchern da war",
  "transfer.shortToast": "Es wurde mehr umgelagert, als laut Büchern da war: {items}",
  "transfer.stopped": "{done} von {all} Zeilen sind erledigt. Machen Sie weiter, wenn Sie so weit sind.",
  "transfer.title": "Bestand umlagern",
  "transfer.to": "Nach",
  "transfer.totals": "{count, plural, one {# Zeile wird} other {# Zeilen werden}} umgelagert",
  "transfer.totalsDone": "{count, plural, one {# Zeile} other {# Zeilen}} umgelagert",
  "transfer.totalsTyped": "{count, plural, one {# Zeile} other {# Zeilen}} umzulagern",
  "transfer.totalsUndone": "Rückgängig gemacht · {count, plural, one {# Zeile} other {# Zeilen}}",
  "transfer.undo": "Diese Umlagerung rückgängig machen",
  "transfer.undo.body": "Jede Zeile wird einzeln zurückgelagert. Eine Zeile, deren Bestand schon verbraucht wurde, kann nicht rückgängig gemacht werden und wird genannt.",
  "transfer.undo.title": "Diese Umlagerung rückgängig machen?",
  "transfer.undoContinue": "Weiter rückgängig machen",
  "transfer.undone": "Umlagerung rückgängig gemacht"
};

export const opening: Readonly<Record<string, string>> = {
  "opening.another": "Weitere Datei laden",
  "opening.bar": "Anfangsbestand",
  "opening.choose": "Lagerort wählen",
  "opening.choosePlace": "Wählen Sie den Lagerort, an dem dieser Bestand liegt",
  "opening.col.batch": "Charge",
  "opening.col.cost": "Stückkosten",
  "opening.col.expires": "Läuft ab",
  "opening.col.item": "Artikel",
  "opening.col.qty": "Menge",
  "opening.draftSaved": "Entwurf gespeichert. Sie finden ihn unter Wareneingänge.",
  "opening.empty": "Wählen Sie eine Datei, um zu beginnen",
  "opening.err.cost": "Geben Sie Kosten wie 1.10 ein",
  "opening.err.expires": "Schreiben Sie das Datum als 2027-04-30",
  "opening.err.qty": "Geben Sie eine Menge über null ein, mit Punkt als Dezimalzeichen",
  "opening.file.body": "Eine Zeile je Artikel oder je Charge eines Artikels. Datumsangaben werden als 2027-04-30 geschrieben; Dezimalzahlen mit Punkt.",
  "opening.file.choose": "CSV-Datei wählen",
  "opening.file.empty": "Diese Datei hat keine Zeilen.",
  "opening.file.header": "Die erste Zeile muss die Spalten benennen: quantity und eine von sku, barcode oder name. Laden Sie die Beispieldatei herunter, um sie zu sehen.",
  "opening.file.title": "Die Datei",
  "opening.file.tooMany": "Diese Datei hat {count} Zeilen. Eine Datei darf bis zu {max} enthalten: Teilen Sie sie auf und laden Sie jeden Teil einzeln.",
  "opening.fixFirst": "{count, plural, one {# Zeile muss} other {# Zeilen müssen}} zuerst in der Datei korrigiert werden",
  "opening.itemsMade": "{count, plural, one {# Artikel} other {# Artikel}} angelegt",
  "opening.load": "Anfangsbestand laden",
  "opening.loaded": "Anfangsbestand geladen",
  "opening.nothing": "Es gibt nichts zu laden",
  "opening.onePart": "Anfangsbestand",
  "opening.openPart": "Öffnen",
  "opening.pages": "Seiten mit Zeilen",
  "opening.part": "Anfangsbestand, Teil {n} von {m}",
  "opening.partLines": "{count, plural, one {# Zeile} other {# Zeilen}}",
  "opening.parts": "{count} Zeilen: Das wird als {parts} Wareneingänge gespeichert, in der Reihenfolge der Datei.",
  "opening.place": "Lagerort",
  "opening.progress": "Teil {part}: {done} von {all} Zeilen",
  "opening.reading": "Datei wird gelesen · bisher {done} Zeilen zugeordnet",
  "opening.review": "Prüfen",
  "opening.reviewCount": "{count, plural, one {# Zeile} other {# Zeilen}} zu laden",
  "opening.row": "Zeile {at}",
  "opening.sample": "Beispieldatei herunterladen",
  "opening.saveDraft": "Als Entwurf speichern",
  "opening.saved.title": "Zum Laden gespeichert",
  "opening.status.draft": "Entwurf",
  "opening.status.loaded": "Geladen",
  "opening.status.partly": "Teilweise geladen",
  "opening.stopped": "Teil {part}: {done} von {all} Zeilen sind eingebucht. Machen Sie weiter, wenn Sie so weit sind.",
  "opening.stoppedAt": "Teil {part}: Eine Zeile wurde abgelehnt. {reason} Öffnen Sie den Teil, um sie zu korrigieren.",
  "opening.title": "Anfangsbestand",
  "opening.totals": "{count, plural, one {# Zeile} other {# Zeilen}} zu laden",
  "opening.totalsSaved": "{count, plural, one {# Wareneingang} other {# Wareneingänge}} gespeichert",
  "opening.unmatched.body": "{count, plural, one {Zeile {rows}. Sie wird} other {Zeilen {rows}{more}. Sie werden}} ausgelassen, wenn Sie die Artikel nicht anlegen.",
  "opening.unmatched.leave": "Auslassen",
  "opening.unmatched.make": "Diese Artikel anlegen",
  "opening.unmatched.title": "{count, plural, one {# Zeile passt} other {# Zeilen passen}} zu keinem Artikel"
};

export const counts: Readonly<Record<string, string>> = {
  "counts.add.batch": "Charge {code} hinzufügen",
  "counts.add.plain": "{item} zu dieser Zählung hinzufügen",
  "counts.add.title": "{item} liegt an diesem Lagerort und steht nicht in dieser Zählung",
  "counts.askManager": "Bitten Sie die Lagerleitung, diese Zählung zu buchen",
  "counts.bar": "Diese Zählung",
  "counts.batch": "Charge {code}",
  "counts.cancel": "Zählung abbrechen",
  "counts.cancel.body": "Es wurde nichts gebucht, also ändert sich nichts am Bestand. Die bisher eingegebenen Zählwerte bleiben bei der abgebrochenen Zählung erhalten.",
  "counts.cancel.title": "Diese Zählung abbrechen?",
  "counts.cancelledToast": "Zählung abgebrochen. Am Bestand wurde nichts geändert.",
  "counts.col.count": "Zählung",
  "counts.col.counted": "Gezählt",
  "counts.col.difference": "Differenz",
  "counts.col.differences": "Differenzen",
  "counts.col.expected": "Erwartet",
  "counts.col.item": "Artikel",
  "counts.col.place": "Lagerort",
  "counts.col.scope": "Umfang",
  "counts.col.sku": "SKU",
  "counts.col.started": "Begonnen",
  "counts.col.status": "Status",
  "counts.col.value": "Wert",
  "counts.countedFor": "Gezählt, {item}",
  "counts.doneForNow": "Fürs Erste fertig",
  "counts.empty.body": "Zählen Sie einen Lagerort, um die Bücher mit den Regalen abzugleichen.",
  "counts.empty.differ": "Bisher keine Differenzen",
  "counts.empty.differBody": "Jede bisher gezählte Zeile stimmt mit dem erwarteten Bestand überein.",
  "counts.empty.lines": "Diese Zählung hat keine Zeilen",
  "counts.empty.open": "Jede Zeile ist gezählt",
  "counts.empty.openBody": "Hier ist nichts mehr zu zählen.",
  "counts.empty.showAll": "Alle Zeilen anzeigen",
  "counts.empty.title": "Noch keine Zählungen",
  "counts.filter.all": "Alle anzeigen",
  "counts.filter.differ": "Nur Differenzen",
  "counts.filter.item": "Angezeigt wird {item}",
  "counts.filter.open": "Nicht gezählt",
  "counts.linePages": "Seiten mit Zeilen",
  "counts.lineRefused": "{item}: {reason}",
  "counts.lines": "Zeilen",
  "counts.missing.body": "Sie wurde vielleicht entfernt, oder Sie dürfen sie nicht sehen.",
  "counts.missing.title": "Diese Zählung ist nicht vorhanden",
  "counts.noBatch": "Keine Charge",
  "counts.notOpen": "Diese Zählung ist nicht mehr offen",
  "counts.notSaved": "Nicht gespeichert",
  "counts.onHandNow": "Jetzt vorrätig {qty}",
  "counts.pages": "Seiten mit Zählungen",
  "counts.post": "Zählung buchen",
  "counts.post.body": "{count, plural, one {# Zeile wird} other {# Zeilen werden}} angepasst. Die Lagerleitung kann eine gebuchte Zählung stornieren.",
  "counts.post.more": "und {count} weitere",
  "counts.post.reason": "Grund",
  "counts.post.title": "Diese Zählung buchen?",
  "counts.posted": "Zählung gebucht · {count, plural, one {# Zeile} other {# Zeilen}} angepasst",
  "counts.progress": "{done} von {all} Zeilen gezählt",
  "counts.reverse": "Zählung stornieren…",
  "counts.reverse.body": "{count, plural, one {# Zeile wird} other {# Zeilen werden}} wieder auf den alten Stand gesetzt. Eine Charge, die unter null fallen würde, wird abgelehnt und genannt.",
  "counts.reverse.title": "Diese Zählung stornieren?",
  "counts.reverse.yes": "Zählung stornieren",
  "counts.reverseContinue": "Weiter stornieren",
  "counts.reverseStopped": "Noch sind nicht alle Zeilen storniert. Machen Sie weiter, wenn Sie so weit sind.",
  "counts.reversedToast": "Zählung storniert",
  "counts.saved": "Gespeichert",
  "counts.saving": "Wird gespeichert",
  "counts.scan.hint": "Scannen Sie einen Artikel oder geben Sie ihn ein, um zu seiner Zeile zu springen.",
  "counts.scan.now": "Jetzt bei {item}",
  "counts.scan.unknown": "Nicht in dieser Zählung · {code}",
  "counts.scope.all": "Alles an diesem Lagerort",
  "counts.scope.category": "Eine Kategorie",
  "counts.scope.categoryNamed": "Kategorie: {category}",
  "counts.scope.stale": "Länger nicht gezählt",
  "counts.scope.staleDays": "Artikel, die seit {days} Tagen nicht gezählt wurden",
  "counts.scope.toCheck": "Zum Prüfen markiert",
  "counts.scope.toCheckItems": "Zum Prüfen markierte Artikel",
  "counts.sheet.subtitle": "{number} · {scope} · begonnen {date}",
  "counts.sheet.title": "Zählung",
  "counts.sheet.titlePlace": "Zählung · {place}",
  "counts.start": "Zählung starten",
  "counts.start.category": "Kategorie",
  "counts.start.chooseCategory": "Kategorie wählen",
  "counts.start.choosePlace": "Lagerort wählen",
  "counts.start.done": "Zählung für {place} gestartet",
  "counts.start.doneParts": "Zählung für {place} als {parts} Zählungen gestartet",
  "counts.start.go": "Starten",
  "counts.start.help": "Verkäufe während der Zählung bleiben erhalten. Jede Zeile wird mit dem verglichen, was die Bücher in dem Moment führten, als Sie den Zählwert eingegeben haben.",
  "counts.start.nothing": "An diesem Lagerort passt nichts: Es gibt keine Zeile zu zählen.",
  "counts.start.openHere": "Noch offene Zählungen für diesen Lagerort:",
  "counts.start.place": "Lagerort",
  "counts.start.reading": "Zählung wird gestartet · {n} Bestände werden gelesen",
  "counts.start.title": "Zählung starten",
  "counts.start.what": "Was gezählt wird",
  "counts.status.cancelled": "Abgebrochen",
  "counts.status.open": "Wird gezählt",
  "counts.status.posted": "Gebucht",
  "counts.status.posting": "Wird gebucht",
  "counts.status.reversed": "Storniert",
  "counts.status.reversing": "Wird storniert",
  "counts.stopped": "{done} von {all} Zeilen sind gebucht. Machen Sie weiter, wenn Sie so weit sind.",
  "counts.title": "Zählungen",
  "counts.toCheck.body": "Diese wurden angepasst und bleiben zum Prüfen markiert: {items}",
  "counts.toCheck.title": "Seit der Zählung wurde davon verkauft",
  "counts.totals": "{count, plural, one {# Differenz} other {# Differenzen}}",
  "counts.totalsMoney": "{count, plural, one {# Differenz} other {# Differenzen}} · {value}",
  "counts.uncounted": "{count, plural, one {# Zeile} other {# Zeilen}} noch nicht gezählt"
};

export const rules: Readonly<Record<string, string>> = {
  "rules.add": "Regel hinzufügen",
  "rules.added": "Regel für {table} hinzugefügt",
  "rules.badge.app": "Von {app}",
  "rules.badge.yours": "Ihre Tabelle",
  "rules.caughtUp": "{planned} erfasst, {left} warten noch",
  "rules.edit": "Bearbeiten",
  "rules.empty.body": "Eine Regel legt fest, wann eine Zeile einer Ihrer Tabellen Bestand reserviert, entnimmt oder zurücklegt.",
  "rules.empty.title": "Noch entnimmt keine Tabelle aus dem Bestand",
  "rules.fixed": "Nur wer ändern darf, wie Tabellen arbeiten, kann diese Regeln ändern.",
  "rules.itemsMade": "{made} Artikel angelegt, {skipped} bereits verknüpft",
  "rules.makeItems": "Lagerartikel aus dieser Tabelle anlegen",
  "rules.makeItems.go": "Artikel anlegen",
  "rules.makeItems.label": "Die Spalte, die jede Zeile benennt",
  "rules.needsUnit": "Wählen Sie zuerst in den Einstellungen eine Standardeinheit",
  "rules.off": "Aus",
  "rules.point.create": "die Zeile angelegt wird",
  "rules.point.from": "{row} von {fromStates} zu {states} wechselt",
  "rules.point.in": "{column} zu {values} wird",
  "rules.point.parent": "der Eintrag in {column}",
  "rules.point.row": "die Zeile",
  "rules.point.set": "{column} gesetzt ist",
  "rules.point.to": "{row} zu {states} wechselt",
  "rules.recordNow": "Jetzt erfassen",
  "rules.remove": "Regel entfernen",
  "rules.remove.confirm": "Diese Regel entfernen? Zeilen dieser Tabelle entnehmen dann nichts mehr aus dem Bestand.",
  "rules.rule.back": "Wenn {point}, wieder zurücklegen.",
  "rules.rule.count": "Gezählt nach {multipliers}.",
  "rules.rule.from": "Aus {place}.",
  "rules.rule.fromColumn": "Aus dem Lagerort in {column}.",
  "rules.rule.give": "Wenn {point}, {what} zurück ins Regal legen.",
  "rules.rule.hold": "Wenn {point}, den Bestand reservieren.",
  "rules.rule.take": "Wenn {point}, {what} entnehmen.",
  "rules.saved": "Regel für {table} gespeichert",
  "rules.setBy": "Von {app} festgelegt. Sie können die Regel ausschalten; ihre Schritte ändern sich nur mit einer Aktualisierung von {app}.",
  "rules.sheet.add": "Regel hinzufügen",
  "rules.sheet.addRule": "Regel hinzufügen",
  "rules.sheet.back": "Zurücklegen",
  "rules.sheet.chooseColumn": "Spalte wählen",
  "rules.sheet.chooseTable": "Tabelle wählen",
  "rules.sheet.defaultPlace": "Der Standardlagerort",
  "rules.sheet.edit": "Regel bearbeiten",
  "rules.sheet.err.table": "Wählen Sie eine Tabelle",
  "rules.sheet.err.take": "Wählen Sie, wann Bestand reserviert oder entnommen wird",
  "rules.sheet.err.until": "Eine Reservierung braucht die Spalte, die sagt, wann sie endet",
  "rules.sheet.err.when": "Vervollständigen Sie jedes gewählte „Wann“",
  "rules.sheet.guest": "Je Gast gezählt in",
  "rules.sheet.hold": "Reservieren",
  "rules.sheet.linkColumn": "Welche Spalte",
  "rules.sheet.night": "Je Nacht gezählt in",
  "rules.sheet.notNeeded": "Nicht nötig",
  "rules.sheet.one": "Jedes Mal eins",
  "rules.sheet.place": "Aus welchem Lagerort",
  "rules.sheet.placeColumn": "Der Lagerort in {column}",
  "rules.sheet.quantity": "Wie viel",
  "rules.sheet.reads": "Liest sich als",
  "rules.sheet.save": "Regel speichern",
  "rules.sheet.table": "Tabelle",
  "rules.sheet.take": "Entnehmen",
  "rules.sheet.until": "Bis wann",
  "rules.sheet.used": "Was verbraucht wird",
  "rules.sheet.used.link": "Eine verknüpfte Spalte",
  "rules.sheet.used.linkHelp": "Die Zeile verweist auf das, was verbraucht wird.",
  "rules.sheet.used.row": "Diese Zeile",
  "rules.sheet.used.rowHelp": "Jede Zeile der Tabelle ist etwas, das im Bestand geführt wird.",
  "rules.switchLabel": "Regel für {table}",
  "rules.switchedOff": "Regel für {table} ausgeschaltet",
  "rules.switchedOn": "Regel für {table} eingeschaltet",
  "rules.title": "Bestandsregeln",
  "rules.unavailable": "Inventory konnte für diese Tabelle nicht antworten. Neue Speicherungen warten oder werden abgelehnt.",
  "rules.waiting": "{count, plural, one {# Speicherung wartet} other {# Speicherungen warten}}",
  "rules.what.column": "{quantity} von {column}",
  "rules.what.recorded": "was darauf erfasst ist",
  "rules.what.row": "den Artikel dieser Zeile",
  "rules.what.rowMany": "{quantity} vom Artikel dieser Zeile",
  "rules.when.becomes": "Wenn eine Spalte zu einem Wert wird",
  "rules.when.column": "{label}: welche Spalte",
  "rules.when.create": "Wenn die Zeile angelegt wird",
  "rules.when.moves": "Wenn die Zeile wechselt zu",
  "rules.when.never": "Nie",
  "rules.when.set": "Wenn eine Spalte gesetzt ist"
};
