/** French strings for the stock screens. Keys are those of en-US.ts. */
export const shared: Readonly<Record<string, string>> = {
  "shared.cancel": "Annuler",
  "shared.close": "Fermer",
  "shared.continuePosting": "Continuer la validation",
  "shared.dismiss": "Ignorer",
  "shared.failed.title": "Le chargement a échoué",
  "shared.loading": "Chargement",
  "shared.next": "Suivant",
  "shared.pageN": "Page {n}",
  "shared.previous": "Précédent",
  "shared.progress": "{done} lignes sur {all}",
  "shared.refused.body": "Demandez à un responsable du stock si vous en avez besoin.",
  "shared.refused.title": "Vous n’avez pas la permission d’ouvrir ceci",
  "shared.retry": "Réessayer",
  "shared.scan.addNew": "L’ajouter comme nouvel article",
  "shared.scan.asking": "Recherche en cours",
  "shared.scan.failed": "La recherche a échoué",
  "shared.scan.label": "Chercher ou scanner",
  "shared.scan.placeholder": "Scannez un code-barres, ou saisissez un nom ou un code",
  "shared.scan.unknown": "Aucun article ne porte ce code · {code}"
};

export const refusal: Readonly<Record<string, string>> = {
  "refusal.conflict": "Quelqu’un d’autre a modifié ceci au même moment. Réessayez.",
  "refusal.expired": "Ce lot est déjà périmé",
  "refusal.forbidden": "Vous n’avez pas la permission de faire cela.",
  "refusal.full": "Un bon de commande contient 50 lignes au maximum. Créez un autre bon pour le reste.",
  "refusal.move.children": "Ajoutez d’abord une ligne.",
  "refusal.move.linked": "Cette fiche n’est plus ouverte pour cela.",
  "refusal.move.other": "Ce n’est pas encore possible.",
  "refusal.move.where": "Certaines lignes ne sont pas encore entrées.",
  "refusal.needsBatch": "Saisissez le numéro de lot",
  "refusal.notAllowed": "Ce n’est pas autorisé ici.",
  "refusal.oneAtATime": "Ces lignes s’enregistrent une par une.",
  "refusal.other": "L’enregistrement a échoué. Réessayez.",
  "refusal.outOfStock": "Il ne reste pas assez de stock pour annuler cette ligne",
  "refusal.outOfStockLeft": "Il ne reste que {left} {unit} de {item} dans le lot {batch} : cette ligne ne peut pas être annulée",
  "refusal.receiptOpen": "{rows, plural, one {# ligne réserve} other {# lignes réservent}} du stock : remettez-le d’abord",
  "refusal.stock": "Le stock n’a pas pu être mis à jour. Rien n’a changé pour cette ligne. Réessayez ; si le problème persiste, prévenez la personne qui s’occupe d’Adminium.",
  "refusal.tooLarge": "Cette ligne est trop grande pour être validée en une fois. Divisez-la en lignes plus petites."
};

export const receive: Readonly<Record<string, string>> = {
  "receive.another": "Recevoir une autre livraison",
  "receive.anotherBatch": "Autre lot",
  "receive.bar": "Cette réception",
  "receive.batch": "Lot",
  "receive.batchHint": "Tel qu’imprimé sur le carton",
  "receive.batchKnown": "Le lot {code} est déjà connu",
  "receive.choose": "Choisir un emplacement",
  "receive.choosePlace": "Choisissez où va cette livraison",
  "receive.closedMeanwhile": "{order} a été clôturé pendant la réception. Le stock est entré ; le bon de commande n’a pas changé.",
  "receive.col.cost": "Coût unitaire",
  "receive.col.item": "Article",
  "receive.col.now": "Reçu maintenant",
  "receive.col.ordered": "Commandé",
  "receive.col.received": "Déjà reçu",
  "receive.col.total": "Total",
  "receive.costToCheck": "Une ligne a été validée au coût moyen, faute de coût connu. Vérifiez son coût.",
  "receive.costUsed": "Adminium a utilisé {cost}",
  "receive.countPacks": "Compter en {pack} de {size}",
  "receive.countUnits": "Compter en {unit}",
  "receive.delivery": "Livraison",
  "receive.discard.body": "Les lignes saisies ne sont pas enregistrées. Changer de bon de commande fait tout recommencer.",
  "receive.discard.title": "Abandonner votre saisie ?",
  "receive.discard.yes": "Abandonner et changer",
  "receive.draftSaved": "Brouillon enregistré. Retrouvez-le dans Réceptions.",
  "receive.empty.body": "Scannez un carton ou saisissez le nom d’un article ci-dessus. Chaque article ajouté devient une ligne.",
  "receive.empty.title": "Rien d’ajouté pour l’instant",
  "receive.err.expires": "Saisissez la date d’expiration",
  "receive.err.qty": "Saisissez la quantité reçue",
  "receive.err.whole": "Saisissez un nombre entier",
  "receive.expires": "Expiration",
  "receive.fixFirst": "{count, plural, one {# champ est} other {# champs sont}} à corriger avant de valider",
  "receive.into": "Vers",
  "receive.itemAdded": "Article ajouté : {item}",
  "receive.lineCount": "{count, plural, one {# ligne} other {# lignes}}",
  "receive.lineIn": "Entrée",
  "receive.lineRefused": "{item} : {reason}",
  "receive.lines": "Lignes",
  "receive.missing.body": "Elle a peut-être été supprimée, ou vous n’avez peut-être pas le droit de la voir.",
  "receive.missing.title": "Cette réception est introuvable",
  "receive.newItem.add": "Ajouter l’article et recevoir",
  "receive.newItem.barcode": "Code-barres",
  "receive.newItem.name": "Nom",
  "receive.newItem.nameHint": "Tel qu’il doit apparaître dans les inventaires",
  "receive.newItem.nameMissing": "Donnez un nom à l’article",
  "receive.newItem.pack": "Unités par carton (facultatif)",
  "receive.newItem.subtitle": "Il est ajouté aux Articles et à cette livraison.",
  "receive.newItem.title": "Nouvel article",
  "receive.newItem.tracks": "Suivi par lot — demande un lot et une date d’expiration à chaque réception",
  "receive.newItem.unit": "Compté en",
  "receive.noOrder": "Sans bon de commande",
  "receive.noSupplier": "Sans fournisseur",
  "receive.notAllIn": "Certaines lignes ne sont pas encore entrées",
  "receive.notOnOrder": "Absent de ce bon de commande",
  "receive.nothing": "Ajoutez d’abord quelque chose à recevoir",
  "receive.order": "Bon de commande",
  "receive.orderLabel": "{number} · {supplier}",
  "receive.orderedPacks": "{packs} {pack} de {size}",
  "receive.overview": "Vue d’ensemble du stock",
  "receive.pack": "paquet",
  "receive.packs": "paquets",
  "receive.per": "par {unit}",
  "receive.post": "Valider la réception",
  "receive.posted": "Réception validée",
  "receive.posted.batch": "Lot {code}",
  "receive.posted.batchExpires": "Lot {code} · expire le {date}",
  "receive.posted.full": "{order} est entièrement reçu.",
  "receive.posted.noOrder": "Stock reçu de son fournisseur.",
  "receive.posted.onHand": "En stock maintenant {qty} {unit}",
  "receive.posted.part": "{order} est partiellement reçu.",
  "receive.posted.plain": "Stock reçu.",
  "receive.posted.title": "Réception validée",
  "receive.posted.toCome": "{order} est partiellement reçu. Reste à recevoir : {qty} {unit} de {item}.",
  "receive.posted.totalsMoney": "{units} unités reçues · {total}",
  "receive.posted.totalsUnits": "{units} unités reçues",
  "receive.posted.where": "Vers {place} · {when} · {by}",
  "receive.postedFor": "Réception validée pour {order}",
  "receive.posting.body": "{done} lignes sur {all} sont entrées. Continuez quand vous êtes prêt ; une ligne pas encore entrée peut toujours être corrigée.",
  "receive.posting.title": "Cette réception est partiellement entrée",
  "receive.remove": "Retirer {item}",
  "receive.removed": "{item} retiré",
  "receive.reopenFirst": "Rouvrez d’abord le bon de commande",
  "receive.reversed.title": "Réception annulée",
  "receive.reversing.title": "Cette réception est partiellement annulée",
  "receive.saveDraft": "Enregistrer comme brouillon",
  "receive.scan.added": "{item} ajouté · 1 {unit}",
  "receive.scan.hintPack": "Un scanner écrit dans ce champ. Chaque scan ajoute un paquet.",
  "receive.scan.hintUnit": "Un scanner écrit dans ce champ. Chaque scan ajoute une unité.",
  "receive.scan.raised": "{item} · maintenant {qty} {unit}",
  "receive.seeMovements": "Voir les mouvements",
  "receive.sendBack": "Renvoyer au fournisseur",
  "receive.sendBack.body": "Toute la ligne sort du stock à son coût et compte de nouveau comme commandée. Pour sortir une partie seulement d’une ligne, utilisez plutôt « Utiliser du stock » sur l’article.",
  "receive.sendBack.title": "Renvoyer cette ligne à son fournisseur ?",
  "receive.sentBack": "{item} renvoyé",
  "receive.status.reversed": "Annulée",
  "receive.status.sentBack": "Renvoyée",
  "receive.stopped": "{done} lignes sur {all} sont entrées. Continuez quand vous êtes prêt.",
  "receive.stoppedAt": "{done} lignes sur {all} sont entrées. {item} : {reason}",
  "receive.supplier": "Fournisseur (facultatif)",
  "receive.supplierOf": "Fournisseur",
  "receive.title": "Recevoir du stock",
  "receive.totalsMoney": "{units} unités à recevoir · {total}",
  "receive.totalsTyped": "{count, plural, one {# ligne} other {# lignes}} à recevoir",
  "receive.totalsUnits": "{units} unités à recevoir",
  "receive.undo": "Annuler cette réception",
  "receive.undo.body": "Chaque ligne est ressortie du stock, une par une. Une ligne dont le stock a déjà été utilisé ne peut pas être annulée ; elle est signalée.",
  "receive.undo.title": "Annuler cette réception ?",
  "receive.undoContinue": "Continuer l’annulation",
  "receive.undoStopped": "Toutes les lignes ne sont pas encore annulées. Continuez quand vous êtes prêt.",
  "receive.undone": "Réception annulée"
};

export const transfer: Readonly<Record<string, string>> = {
  "transfer.bar": "Ce transfert",
  "transfer.batch.any": "Expiration la plus proche d’abord",
  "transfer.batch.kept": "Le lot choisi précédemment",
  "transfer.batch.option": "{code} · {qty} {unit}",
  "transfer.choose": "Choisir un emplacement",
  "transfer.choosePlaces": "Choisissez d’où vient le stock et où il va",
  "transfer.col.batch": "Lot",
  "transfer.col.item": "Article",
  "transfer.col.qty": "Quantité",
  "transfer.done": "Transfert effectué",
  "transfer.draftSaved": "Brouillon enregistré. Retrouvez-le dans Transferts.",
  "transfer.empty.body": "Scannez un article ou saisissez son nom ci-dessus. Chaque article ajouté devient une ligne.",
  "transfer.empty.title": "Rien d’ajouté pour l’instant",
  "transfer.err.qty": "Saisissez la quantité à déplacer",
  "transfer.finish": "Terminer",
  "transfer.fixFirst": "Une ligne est à corriger d’abord",
  "transfer.from": "De",
  "transfer.lineCount": "{count, plural, one {# ligne} other {# lignes}}",
  "transfer.lineDone": "Déplacée",
  "transfer.lineRefused": "{item} : {reason}",
  "transfer.lineUndone": "Annulée",
  "transfer.lines": "Lignes",
  "transfer.missing.body": "Il a peut-être été supprimé, ou vous n’avez peut-être pas le droit de le voir.",
  "transfer.missing.title": "Ce transfert est introuvable",
  "transfer.nothing": "Ajoutez d’abord quelque chose à déplacer",
  "transfer.places": "Départ et arrivée",
  "transfer.posting": "Ce transfert est partiellement effectué. Continuez quand vous êtes prêt.",
  "transfer.remove": "Retirer {item}",
  "transfer.reversed": "Ce transfert a été annulé.",
  "transfer.reversing": "Ce transfert est partiellement annulé. Continuez quand vous êtes prêt.",
  "transfer.samePlace": "Choisissez un autre emplacement",
  "transfer.saveDraft": "Enregistrer comme brouillon",
  "transfer.scan.added": "{item} ajouté · 1 {unit}",
  "transfer.scan.hint": "Un scanner écrit dans ce champ. Chaque scan ajoute une unité.",
  "transfer.scan.raised": "{item} · maintenant {qty} {unit}",
  "transfer.short": "Plus que le stock enregistré",
  "transfer.shortToast": "La quantité déplacée dépasse le stock enregistré : {items}",
  "transfer.stopped": "{done} lignes sur {all} sont effectuées. Continuez quand vous êtes prêt.",
  "transfer.title": "Transférer du stock",
  "transfer.to": "Vers",
  "transfer.totals": "{count, plural, one {# ligne} other {# lignes}} en cours de déplacement",
  "transfer.totalsTyped": "{count, plural, one {# ligne} other {# lignes}} à déplacer",
  "transfer.undo": "Annuler ce transfert",
  "transfer.undo.body": "Chaque ligne est ramenée à son emplacement de départ, une par une. Une ligne dont le stock a déjà été utilisé ne peut pas être annulée ; elle est signalée.",
  "transfer.undo.title": "Annuler ce transfert ?",
  "transfer.undoContinue": "Continuer l’annulation",
  "transfer.undone": "Transfert annulé"
};

export const opening: Readonly<Record<string, string>> = {
  "opening.another": "Charger un autre fichier",
  "opening.bar": "Stock initial",
  "opening.choose": "Choisir un emplacement",
  "opening.choosePlace": "Choisissez l’emplacement où se trouve ce stock",
  "opening.col.batch": "Lot",
  "opening.col.cost": "Coût unitaire",
  "opening.col.expires": "Expiration",
  "opening.col.item": "Article",
  "opening.col.qty": "Quantité",
  "opening.draftSaved": "Brouillon enregistré. Retrouvez-le dans Réceptions.",
  "opening.empty": "Choisissez un fichier pour commencer",
  "opening.err.cost": "Saisissez un coût, par exemple 1.10",
  "opening.err.expires": "Écrivez la date ainsi : 2027-04-30",
  "opening.err.qty": "Saisissez une quantité supérieure à zéro, avec un point pour les décimales",
  "opening.file.body": "Une ligne par article, ou par lot d’un article. Les dates s’écrivent 2027-04-30 ; les décimales prennent un point.",
  "opening.file.choose": "Choisir un fichier CSV",
  "opening.file.empty": "Ce fichier ne contient aucune ligne.",
  "opening.file.header": "La première ligne doit nommer les colonnes : quantity, et l’une de sku, barcode ou name. Téléchargez le fichier d’exemple pour les voir.",
  "opening.file.title": "Le fichier",
  "opening.file.tooMany": "Ce fichier contient {count} lignes. Un fichier peut en contenir {max} au maximum : divisez-le et chargez chaque partie.",
  "opening.fixFirst": "{count, plural, one {# ligne est} other {# lignes sont}} à corriger d’abord dans le fichier",
  "opening.itemsMade": "{count, plural, one {# article créé} other {# articles créés}}",
  "opening.load": "Charger le stock initial",
  "opening.loaded": "Stock initial chargé",
  "opening.nothing": "Il n’y a rien à charger",
  "opening.onePart": "Stock initial",
  "opening.openPart": "Ouvrir",
  "opening.pages": "Pages de lignes",
  "opening.part": "Stock initial, partie {n} sur {m}",
  "opening.partLines": "{count, plural, one {# ligne} other {# lignes}}",
  "opening.parts": "{count} lignes : elles sont enregistrées en {parts} réceptions, dans l’ordre du fichier.",
  "opening.place": "Emplacement",
  "opening.progress": "Partie {part} : {done} lignes sur {all}",
  "opening.reading": "Lecture du fichier · {done} lignes reconnues pour l’instant",
  "opening.review": "Vérifier",
  "opening.reviewCount": "{count, plural, one {# ligne} other {# lignes}} à charger",
  "opening.row": "Ligne {at}",
  "opening.sample": "Télécharger un fichier d’exemple",
  "opening.saveDraft": "Enregistrer comme brouillon",
  "opening.saved.title": "Enregistré, prêt à charger",
  "opening.status.draft": "Brouillon",
  "opening.status.loaded": "Chargé",
  "opening.status.partly": "Partiellement chargé",
  "opening.stopped": "Partie {part} : {done} lignes sur {all} sont entrées. Continuez quand vous êtes prêt.",
  "opening.stoppedAt": "Partie {part} : une ligne a été refusée. {reason} Ouvrez la partie pour la corriger.",
  "opening.title": "Stock initial",
  "opening.totals": "{count, plural, one {# ligne} other {# lignes}} à charger",
  "opening.totalsSaved": "{count, plural, one {# réception enregistrée} other {# réceptions enregistrées}}",
  "opening.unmatched.body": "Lignes {rows}{more}. Elles sont ignorées, sauf si vous créez les articles.",
  "opening.unmatched.leave": "Ignorer",
  "opening.unmatched.make": "Créer ces articles",
  "opening.unmatched.title": "{count, plural, one {# ligne ne correspond} other {# lignes ne correspondent}} à aucun article"
};

export const counts: Readonly<Record<string, string>> = {
  "counts.add.batch": "Ajouter le lot {code}",
  "counts.add.plain": "Ajouter {item} à cet inventaire",
  "counts.add.title": "{item} se trouve dans cet emplacement, mais pas dans cet inventaire",
  "counts.askManager": "Demandez à un responsable du stock de valider cet inventaire",
  "counts.bar": "Cet inventaire",
  "counts.batch": "Lot {code}",
  "counts.cancel": "Abandonner l’inventaire",
  "counts.cancel.body": "Rien n’a été validé, donc rien ne change dans le stock. Les quantités déjà saisies sont conservées avec l’inventaire abandonné.",
  "counts.cancel.title": "Abandonner cet inventaire ?",
  "counts.cancelledToast": "Inventaire abandonné. Rien n’a changé dans le stock.",
  "counts.col.count": "Inventaire",
  "counts.col.counted": "Compté",
  "counts.col.difference": "Écart",
  "counts.col.differences": "Écarts",
  "counts.col.expected": "Attendu",
  "counts.col.item": "Article",
  "counts.col.place": "Emplacement",
  "counts.col.scope": "Périmètre",
  "counts.col.sku": "SKU",
  "counts.col.started": "Commencé",
  "counts.col.status": "Statut",
  "counts.col.value": "Valeur",
  "counts.countedFor": "Compté, {item}",
  "counts.doneForNow": "Terminé pour l’instant",
  "counts.empty.body": "Comptez un emplacement pour comparer le stock enregistré à ce qu’il y a en rayon.",
  "counts.empty.differ": "Aucun écart pour l’instant",
  "counts.empty.lines": "Cet inventaire n’a aucune ligne",
  "counts.empty.open": "Toutes les lignes sont comptées",
  "counts.empty.openBody": "Il ne reste rien à compter ici.",
  "counts.empty.title": "Aucun inventaire pour l’instant",
  "counts.filter.all": "Tout afficher",
  "counts.filter.differ": "Écarts seulement",
  "counts.filter.item": "Affichage de {item}",
  "counts.filter.open": "Non comptées",
  "counts.linePages": "Pages de lignes",
  "counts.lineRefused": "{item} : {reason}",
  "counts.lines": "Lignes",
  "counts.missing.body": "Il a peut-être été supprimé, ou vous n’avez peut-être pas le droit de le voir.",
  "counts.missing.title": "Cet inventaire est introuvable",
  "counts.noBatch": "Sans lot",
  "counts.notOpen": "Cet inventaire n’est plus ouvert",
  "counts.notSaved": "Non enregistré",
  "counts.onHandNow": "En stock maintenant {qty}",
  "counts.pages": "Pages d’inventaires",
  "counts.post": "Valider l’inventaire",
  "counts.post.body": "{count, plural, one {# ligne sera ajustée} other {# lignes seront ajustées}}. Un responsable du stock peut annuler un inventaire validé.",
  "counts.post.more": "et {count} de plus",
  "counts.post.reason": "Motif",
  "counts.post.title": "Valider cet inventaire ?",
  "counts.posted": "Inventaire validé · {count, plural, one {# ligne ajustée} other {# lignes ajustées}}",
  "counts.progress": "{done} lignes comptées sur {all}",
  "counts.reverse": "Annuler l’inventaire…",
  "counts.reverse.body": "{count, plural, one {# ligne sera remise} other {# lignes seront remises}} comme avant. Un lot qui passerait sous zéro est refusé et signalé.",
  "counts.reverse.title": "Annuler cet inventaire ?",
  "counts.reverse.yes": "Annuler l’inventaire",
  "counts.reverseContinue": "Continuer l’annulation",
  "counts.reverseStopped": "Toutes les lignes ne sont pas encore annulées. Continuez quand vous êtes prêt.",
  "counts.reversedToast": "Inventaire annulé",
  "counts.saved": "Enregistré",
  "counts.saving": "Enregistrement",
  "counts.scan.hint": "Scannez ou saisissez un article pour aller à sa ligne.",
  "counts.scan.now": "Maintenant sur {item}",
  "counts.scan.unknown": "Absent de cet inventaire · {code}",
  "counts.scope.all": "Tout ce qui est dans cet emplacement",
  "counts.scope.category": "Une catégorie",
  "counts.scope.categoryNamed": "Catégorie : {category}",
  "counts.scope.stale": "Pas comptés récemment",
  "counts.scope.staleDays": "Articles non comptés depuis {days} jours",
  "counts.scope.toCheck": "À vérifier",
  "counts.scope.toCheckItems": "Articles à vérifier",
  "counts.sheet.subtitle": "{number} · {scope} · commencé le {date}",
  "counts.sheet.title": "Inventaire",
  "counts.sheet.titlePlace": "Inventaire · {place}",
  "counts.start": "Commencer un inventaire",
  "counts.start.category": "Catégorie",
  "counts.start.chooseCategory": "Choisir une catégorie",
  "counts.start.choosePlace": "Choisir un emplacement",
  "counts.start.done": "Inventaire commencé pour {place}",
  "counts.start.doneParts": "Inventaire commencé pour {place}, en {parts} inventaires",
  "counts.start.go": "Commencer",
  "counts.start.help": "Les ventes faites pendant que vous comptez sont conservées. Chaque ligne est comparée au stock enregistré au moment où vous saisissez sa quantité.",
  "counts.start.nothing": "Rien ne correspond dans cet emplacement : il n’y a aucune ligne à compter.",
  "counts.start.openHere": "Inventaires encore ouverts pour cet emplacement :",
  "counts.start.place": "Emplacement",
  "counts.start.reading": "Démarrage de l’inventaire · lecture de {n} niveaux de stock",
  "counts.start.title": "Commencer un inventaire",
  "counts.start.what": "Quoi compter",
  "counts.status.cancelled": "Abandonné",
  "counts.status.open": "Comptage en cours",
  "counts.status.posted": "Validé",
  "counts.status.posting": "Validation en cours",
  "counts.status.reversed": "Annulé",
  "counts.status.reversing": "Annulation en cours",
  "counts.stopped": "{done} lignes sur {all} sont validées. Continuez quand vous êtes prêt.",
  "counts.title": "Inventaires",
  "counts.toCheck.body": "Ces articles ont été ajustés et restent à vérifier : {items}",
  "counts.toCheck.title": "Vendus depuis leur comptage",
  "counts.totals": "{count, plural, one {# écart} other {# écarts}}",
  "counts.totalsMoney": "{count, plural, one {# écart} other {# écarts}} · {value}",
  "counts.uncounted": "{count, plural, one {# ligne pas encore comptée} other {# lignes pas encore comptées}}"
};

export const rules: Readonly<Record<string, string>> = {
  "rules.add": "Ajouter une règle",
  "rules.badge.app": "De {app}",
  "rules.badge.yours": "Votre table",
  "rules.caughtUp": "{planned} enregistrés, {left} encore en attente",
  "rules.edit": "Modifier",
  "rules.empty.body": "Une règle dit quand une ligne de l’une de vos tables réserve, prélève ou remet du stock.",
  "rules.empty.title": "Aucune table ne prélève encore dans le stock",
  "rules.fixed": "Seule une personne autorisée à modifier le fonctionnement des tables peut changer ces règles.",
  "rules.itemsMade": "{made} articles créés, {skipped} déjà liés",
  "rules.makeItems": "Créer des articles de stock à partir de cette table",
  "rules.makeItems.go": "Créer les articles",
  "rules.makeItems.label": "La colonne qui nomme chaque ligne",
  "rules.needsUnit": "Choisissez d’abord une unité par défaut dans les Paramètres",
  "rules.off": "Désactivée",
  "rules.point.create": "la ligne est créée",
  "rules.point.from": "{row} passe de {fromStates} à {states}",
  "rules.point.in": "{column} devient {values}",
  "rules.point.parent": "son {column}",
  "rules.point.row": "la ligne",
  "rules.point.set": "{column} reçoit une valeur",
  "rules.point.to": "{row} passe à {states}",
  "rules.recordNow": "Les enregistrer maintenant",
  "rules.remove": "Supprimer la règle",
  "rules.remove.confirm": "Supprimer cette règle ? Les lignes de cette table ne prélèveront plus dans le stock.",
  "rules.rule.back": "Quand {point}, le remettre en stock.",
  "rules.rule.count": "En comptant {multipliers}.",
  "rules.rule.from": "Depuis {place}.",
  "rules.rule.fromColumn": "Depuis l’emplacement indiqué dans {column}.",
  "rules.rule.give": "Quand {point}, remettre {what} en rayon.",
  "rules.rule.hold": "Quand {point}, réserver le stock.",
  "rules.rule.take": "Quand {point}, prélever {what}.",
  "rules.setBy": "Définie par {app}. Vous pouvez la désactiver ; ses étapes ne changent qu’avec une mise à jour de {app}.",
  "rules.sheet.add": "Ajouter une règle",
  "rules.sheet.back": "Remettre",
  "rules.sheet.chooseColumn": "Choisir une colonne",
  "rules.sheet.chooseTable": "Choisir une table",
  "rules.sheet.defaultPlace": "L’emplacement par défaut",
  "rules.sheet.edit": "Modifier la règle",
  "rules.sheet.err.table": "Choisissez une table",
  "rules.sheet.err.take": "Choisissez quand le stock est réservé ou prélevé",
  "rules.sheet.err.until": "Une réservation a besoin de la colonne qui indique quand elle se termine",
  "rules.sheet.err.when": "Complétez chaque « quand » que vous avez choisi",
  "rules.sheet.guest": "Compté pour chaque personne dans",
  "rules.sheet.hold": "Réserver",
  "rules.sheet.linkColumn": "Quelle colonne",
  "rules.sheet.night": "Compté pour chaque nuit dans",
  "rules.sheet.notNeeded": "Pas nécessaire",
  "rules.sheet.one": "Un à chaque fois",
  "rules.sheet.place": "Depuis quel emplacement",
  "rules.sheet.placeColumn": "L’emplacement indiqué dans {column}",
  "rules.sheet.quantity": "Combien",
  "rules.sheet.reads": "Se lit ainsi",
  "rules.sheet.save": "Enregistrer la règle",
  "rules.sheet.table": "Table",
  "rules.sheet.take": "Prélever",
  "rules.sheet.until": "Jusqu’à quand",
  "rules.sheet.used": "Ce qui est utilisé",
  "rules.sheet.used.link": "Une colonne liée",
  "rules.sheet.used.linkHelp": "La ligne désigne ce qui est utilisé.",
  "rules.sheet.used.row": "Cette ligne",
  "rules.sheet.used.rowHelp": "Chaque ligne de la table est quelque chose que l’on garde en stock.",
  "rules.switchLabel": "Règle {table}",
  "rules.switchedOff": "Règle {table} désactivée",
  "rules.switchedOn": "Règle {table} activée",
  "rules.title": "Règles de stock",
  "rules.unavailable": "L’inventaire n’a pas pu répondre pour cette table. Les nouveaux enregistrements attendent ou sont refusés.",
  "rules.waiting": "{count, plural, one {# enregistrement est} other {# enregistrements sont}} en attente",
  "rules.what.column": "{quantity} de {column}",
  "rules.what.recorded": "ce qui y est enregistré",
  "rules.what.row": "l’article de cette ligne",
  "rules.what.rowMany": "{quantity} de l’article de cette ligne",
  "rules.when.becomes": "Quand une colonne devient",
  "rules.when.column": "{label} : quelle colonne",
  "rules.when.create": "Quand la ligne est créée",
  "rules.when.moves": "Quand la ligne passe à",
  "rules.when.never": "Jamais",
  "rules.when.set": "Quand une colonne reçoit une valeur"
};
