/** Simplified Chinese strings for the stock screens. Keys are those of en-US.ts. */
export const shared: Readonly<Record<string, string>> = {
  "shared.cancel": "取消",
  "shared.close": "关闭",
  "shared.continuePosting": "继续过账",
  "shared.dismiss": "知道了",
  "shared.failed.title": "无法加载此内容",
  "shared.loading": "正在加载",
  "shared.next": "下一页",
  "shared.pageN": "第 {n} 页",
  "shared.previous": "上一页",
  "shared.progress": "{done} / {all} 行",
  "shared.refused.body": "如有需要，请联系库存管理员。",
  "shared.refused.title": "你没有权限打开此页面",
  "shared.retry": "重试",
  "shared.scan.addNew": "添加为新物品",
  "shared.scan.asking": "正在查找",
  "shared.scan.failed": "无法查找",
  "shared.scan.label": "查找或扫描",
  "shared.scan.placeholder": "扫描条码，或输入名称或编码",
  "shared.scan.unknown": "没有物品使用此编码 · {code}"
};

export const refusal: Readonly<Record<string, string>> = {
  "refusal.conflict": "有人同时修改了此内容。请重试。",
  "refusal.expired": "此批次已过期",
  "refusal.forbidden": "你没有权限执行此操作。",
  "refusal.full": "一张采购单最多 50 行。其余的请另开一张采购单。",
  "refusal.move.children": "请先添加一行。",
  "refusal.move.linked": "此单据已不能再这样操作。",
  "refusal.move.other": "暂时还不能这样做。",
  "refusal.move.where": "还有一些行未入库。",
  "refusal.needsBatch": "请输入批次号",
  "refusal.notAllowed": "此处不允许这样做。",
  "refusal.oneAtATime": "这些行需要逐行保存。",
  "refusal.other": "无法保存。请重试。",
  "refusal.outOfStock": "剩余数量不足，无法撤销此行",
  "refusal.outOfStockLeft": "批次 {batch} 中的 {item} 只剩 {left} {unit}：此行无法撤销",
  "refusal.receiptOpen": "{rows, plural, other {# 行}}仍占用库存：请先放回",
  "refusal.stock": "无法更新库存。此行未作任何更改。请重试；如果一直失败，请告知负责 Adminium 的人。",
  "refusal.tooLarge": "此行数量太大，无法一次过账。请拆分成几行较小的。"
};

export const receive: Readonly<Record<string, string>> = {
  "receive.another": "再收一批货",
  "receive.anotherBatch": "另一个批次",
  "receive.bar": "此收货单",
  "receive.batch": "批次",
  "receive.batchHint": "按箱子上印的填写",
  "receive.batchKnown": "批次 {code} 已存在",
  "receive.choose": "选择地点",
  "receive.choosePlace": "请选择这批货存放的地点",
  "receive.closedMeanwhile": "{order} 在你收货期间已关闭。库存已入库；采购单未变。",
  "receive.col.cost": "单位成本",
  "receive.col.item": "物品",
  "receive.col.now": "本次收货",
  "receive.col.ordered": "已订购",
  "receive.col.received": "已收数量",
  "receive.col.total": "合计",
  "receive.costOrdered": "订单上为 {cost}",
  "receive.costToCheck": "有一行因没有已知成本，已按平均成本过账。请核对其成本。",
  "receive.costUsed": "Adminium 使用了 {cost}",
  "receive.countPacks": "按{pack}计数（每{pack} {size}）",
  "receive.countUnits": "按 {unit} 计数",
  "receive.delivery": "到货",
  "receive.discard.body": "你输入的行尚未保存。更换采购单后需要重新开始。",
  "receive.discard.title": "放弃已输入的内容？",
  "receive.discard.yes": "放弃并更换",
  "receive.draftSaved": "草稿已保存。可在“收货单”中找到。",
  "receive.empty.body": "扫描箱子，或在上方输入物品名称。每添加一个物品就是一行。",
  "receive.empty.title": "尚未添加任何内容",
  "receive.err.expires": "请输入到期日期",
  "receive.err.qty": "请输入本次收货数量",
  "receive.err.whole": "请输入整数",
  "receive.expires": "到期日期",
  "receive.fixFirst": "过账前有{count, plural, other {# 个字段}}需要修正",
  "receive.into": "收入",
  "receive.itemAdded": "已添加物品：{item}",
  "receive.lineCount": "{count, plural, other {# 行}}",
  "receive.lineIn": "已入库",
  "receive.lineRefused": "{item}：{reason}",
  "receive.lines": "明细行",
  "receive.missing.body": "它可能已被删除，或者你无权查看。",
  "receive.missing.title": "找不到此收货单",
  "receive.newItem.add": "添加物品并收货",
  "receive.newItem.barcode": "条码",
  "receive.newItem.name": "名称",
  "receive.newItem.nameHint": "盘点时显示的名称",
  "receive.newItem.nameMissing": "请给物品起个名称",
  "receive.newItem.pack": "每箱数量（可选）",
  "receive.newItem.subtitle": "它会添加到“物品”和这批到货中。",
  "receive.newItem.title": "新物品",
  "receive.newItem.tracks": "按批次管理——每次收货时都要填写批次和到期日期",
  "receive.newItem.unit": "计量单位",
  "receive.noOrder": "无采购单",
  "receive.noSupplier": "无供应商",
  "receive.notAllIn": "还有一些行未入库",
  "receive.notOnOrder": "不在此采购单上",
  "receive.nothing": "请先添加要收货的物品",
  "receive.order": "采购单",
  "receive.orderLabel": "{number} · {supplier}",
  "receive.orderedPacks": "{packs} {pack}（每{pack} {size}）",
  "receive.overview": "库存概览",
  "receive.pack": "包",
  "receive.packs": "包",
  "receive.per": "每 {unit}",
  "receive.post": "过账收货单",
  "receive.posted": "收货单已过账",
  "receive.posted.batch": "批次 {code}",
  "receive.posted.batchExpires": "批次 {code} · {date} 到期",
  "receive.posted.full": "{order} 已全部收货。",
  "receive.posted.noOrder": "已从供应商收到库存。",
  "receive.posted.onHand": "现有库存 {qty} {unit}",
  "receive.posted.part": "{order} 已部分收货。",
  "receive.posted.plain": "库存已收到。",
  "receive.posted.title": "收货单已过账",
  "receive.posted.toCome": "{order} 已部分收货。{item} 还有 {qty} {unit} 未到。",
  "receive.posted.totalsMoney": "已收 {units} 件 · {total}",
  "receive.posted.totalsUnits": "已收 {units} 件",
  "receive.posted.where": "收入 {place} · {when} · {by}",
  "receive.postedFor": "{order} 的收货单已过账",
  "receive.posting.body": "{done} / {all} 行已入库。准备好后请继续；尚未入库的行仍可更正。",
  "receive.posting.title": "此收货单已部分入库",
  "receive.remove": "移除 {item}",
  "receive.removed": "已移除 {item}",
  "receive.reopenFirst": "请先重新打开采购单",
  "receive.reversed.body": "每一行都已重新从库存中移出。收货单仍保留在记录中。",
  "receive.reversed.title": "收货单已撤销",
  "receive.reversing.title": "此收货单已部分撤销",
  "receive.saveDraft": "保存为草稿",
  "receive.scan.added": "已添加 {item} · 1 {unit}",
  "receive.scan.hintPack": "扫描枪会输入到此栏。每扫一次加一包。",
  "receive.scan.hintUnit": "扫描枪会输入到此栏。每扫一次加一个。",
  "receive.scan.raised": "{item} · 现为 {qty} {unit}",
  "receive.seeMovements": "查看库存变动",
  "receive.sendBack": "退回供应商",
  "receive.sendBack.body": "整行会按其成本从库存中移出，并重新计为在途订购。如只需报损一行中的一部分，请改用该物品的“使用库存”。",
  "receive.sendBack.title": "将此行退回供应商？",
  "receive.sentBack": "{item} 已退回",
  "receive.status.reversed": "已撤销",
  "receive.status.sentBack": "已退回",
  "receive.stopped": "{done} / {all} 行已入库。准备好后请继续。",
  "receive.stoppedAt": "{done} / {all} 行已入库。{item}：{reason}",
  "receive.supplier": "供应商（可选）",
  "receive.supplierOf": "供应商",
  "receive.title": "收货入库",
  "receive.totalsMoney": "本次收货 {units} 件 · {total}",
  "receive.totalsTyped": "待收货 {count, plural, other {# 行}}",
  "receive.totalsUnits": "本次收货 {units} 件",
  "receive.undo": "撤销此收货单",
  "receive.undo.body": "每一行都会逐行从库存中移出。库存已被使用的行无法撤销，并会列出名称。",
  "receive.undo.title": "撤销此收货单？",
  "receive.undoContinue": "继续撤销",
  "receive.undoStopped": "还有一些行未撤销。准备好后请继续。",
  "receive.undone": "收货单已撤销"
};

export const transfer: Readonly<Record<string, string>> = {
  "transfer.bar": "此调拨单",
  "transfer.batch.any": "先到期的先出",
  "transfer.batch.kept": "之前选择的批次",
  "transfer.batch.option": "{code} · {qty} {unit}",
  "transfer.choose": "选择地点",
  "transfer.choosePlaces": "请选择库存的调出地点和调入地点",
  "transfer.col.batch": "批次",
  "transfer.col.item": "物品",
  "transfer.col.qty": "数量",
  "transfer.done": "调拨完成",
  "transfer.draftSaved": "草稿已保存。可在“调拨单”中找到。",
  "transfer.empty.body": "扫描物品，或在上方输入名称。每添加一个物品就是一行。",
  "transfer.empty.title": "尚未添加任何内容",
  "transfer.err.qty": "请输入调拨数量",
  "transfer.finish": "完成",
  "transfer.fixFirst": "有一行需要先修正",
  "transfer.from": "调出",
  "transfer.lineCount": "{count, plural, other {# 行}}",
  "transfer.lineDone": "已调拨",
  "transfer.lineRefused": "{item}：{reason}",
  "transfer.lineUndone": "已撤销",
  "transfer.lines": "明细行",
  "transfer.missing.body": "它可能已被删除，或者你无权查看。",
  "transfer.missing.title": "找不到此调拨单",
  "transfer.nothing": "请先添加要调拨的物品",
  "transfer.places": "调出和调入",
  "transfer.posting": "此调拨单已部分完成。准备好后请继续。",
  "transfer.remove": "移除 {item}",
  "transfer.reversed": "此调拨单已撤销。",
  "transfer.reversing": "此调拨单已部分撤销。准备好后请继续。",
  "transfer.samePlace": "请选择另一个地点",
  "transfer.saveDraft": "保存为草稿",
  "transfer.scan.added": "已添加 {item} · 1 {unit}",
  "transfer.scan.hint": "扫描枪会输入到此栏。每扫一次加一个。",
  "transfer.scan.raised": "{item} · 现为 {qty} {unit}",
  "transfer.short": "超过账面数量",
  "transfer.shortToast": "调拨数量超过了账面数量：{items}",
  "transfer.stopped": "{done} / {all} 行已完成。准备好后请继续。",
  "transfer.title": "调拨库存",
  "transfer.to": "调入",
  "transfer.totals": "正在调拨 {count, plural, other {# 行}}",
  "transfer.totalsDone": "已调拨 {count, plural, other {# 行}}",
  "transfer.totalsTyped": "待调拨 {count, plural, other {# 行}}",
  "transfer.totalsUndone": "已撤销 · {count, plural, other {# 行}}",
  "transfer.undo": "撤销此调拨单",
  "transfer.undo.body": "每一行都会逐行调回。库存已被使用的行无法撤销，并会列出名称。",
  "transfer.undo.title": "撤销此调拨单？",
  "transfer.undoContinue": "继续撤销",
  "transfer.undone": "调拨单已撤销"
};

export const opening: Readonly<Record<string, string>> = {
  "opening.another": "再导入一个文件",
  "opening.bar": "期初库存",
  "opening.choose": "选择地点",
  "opening.choosePlace": "请选择这些库存所在的地点",
  "opening.col.batch": "批次",
  "opening.col.cost": "单位成本",
  "opening.col.expires": "到期日期",
  "opening.col.item": "物品",
  "opening.col.qty": "数量",
  "opening.draftSaved": "草稿已保存。可在“收货单”中找到。",
  "opening.empty": "请选择一个文件开始",
  "opening.err.cost": "请输入成本，例如 1.10",
  "opening.err.expires": "日期请写成 2027-04-30",
  "opening.err.qty": "请输入大于零的数量，小数用小数点",
  "opening.file.body": "每个物品一行，或物品的每个批次一行。日期写成 2027-04-30；小数用小数点。",
  "opening.file.choose": "选择 CSV 文件",
  "opening.file.empty": "此文件没有数据行。",
  "opening.file.header": "第一行必须是列名：quantity，以及 sku、barcode 或 name 中的一个。可下载示例文件查看。",
  "opening.file.title": "文件",
  "opening.file.tooMany": "此文件有 {count} 行。一个文件最多 {max} 行：请拆分后分别导入。",
  "opening.fixFirst": "文件中有{count, plural, other {# 行}}需要先修正",
  "opening.itemsMade": "已创建{count, plural, other {# 个物品}}",
  "opening.load": "导入期初库存",
  "opening.loaded": "期初库存已导入",
  "opening.nothing": "没有可导入的内容",
  "opening.onePart": "期初库存",
  "opening.openPart": "打开",
  "opening.pages": "明细行分页",
  "opening.part": "期初库存，第 {n} 部分，共 {m} 部分",
  "opening.partLines": "{count, plural, other {# 行}}",
  "opening.parts": "共 {count} 行：将按文件中的顺序保存为 {parts} 张收货单。",
  "opening.place": "地点",
  "opening.progress": "第 {part} 部分：{done} / {all} 行",
  "opening.reading": "正在读取文件 · 已匹配 {done} 行",
  "opening.review": "核对",
  "opening.reviewCount": "待导入 {count, plural, other {# 行}}",
  "opening.row": "第 {at} 行",
  "opening.sample": "下载示例文件",
  "opening.saveDraft": "保存为草稿",
  "opening.saved.title": "已保存，待导入",
  "opening.status.draft": "草稿",
  "opening.status.loaded": "已导入",
  "opening.status.partly": "部分导入",
  "opening.stopped": "第 {part} 部分：{done} / {all} 行已入库。准备好后请继续。",
  "opening.stoppedAt": "第 {part} 部分：有一行被拒绝。{reason} 请打开该部分进行更正。",
  "opening.title": "期初库存",
  "opening.totals": "待导入 {count, plural, other {# 行}}",
  "opening.totalsSaved": "已保存{count, plural, other {# 张收货单}}",
  "opening.unmatched.body": "{count, plural, other {第 {rows}{more} 行}}。除非创建这些物品，否则将被略过。",
  "opening.unmatched.leave": "略过",
  "opening.unmatched.make": "创建这些物品",
  "opening.unmatched.title": "{count, plural, other {# 行}}没有匹配的物品"
};

export const counts: Readonly<Record<string, string>> = {
  "counts.add.batch": "添加批次 {code}",
  "counts.add.plain": "将 {item} 加入此盘点",
  "counts.add.title": "{item} 在此地点，但不在此盘点中",
  "counts.askManager": "请让库存管理员过账此盘点",
  "counts.bar": "此盘点",
  "counts.batch": "批次 {code}",
  "counts.cancel": "取消盘点",
  "counts.cancel.body": "尚未过账，因此库存不会有任何变化。已输入的盘点数会随已取消的盘点一并保留。",
  "counts.cancel.title": "取消此盘点？",
  "counts.cancelledToast": "盘点已取消。库存没有任何变化。",
  "counts.col.count": "盘点",
  "counts.col.counted": "实盘数",
  "counts.col.difference": "差异",
  "counts.col.differences": "差异数",
  "counts.col.expected": "账面数",
  "counts.col.item": "物品",
  "counts.col.place": "地点",
  "counts.col.scope": "范围",
  "counts.col.sku": "SKU",
  "counts.col.started": "开始时间",
  "counts.col.status": "状态",
  "counts.col.value": "金额",
  "counts.countedFor": "实盘数，{item}",
  "counts.doneForNow": "先到这里",
  "counts.empty.body": "盘点一个地点，核对账面与货架是否一致。",
  "counts.empty.differ": "目前没有差异",
  "counts.empty.differBody": "目前已盘点的每一行都与预期相符。",
  "counts.empty.lines": "此盘点没有明细行",
  "counts.empty.open": "每一行都已盘点",
  "counts.empty.openBody": "这里没有待盘点的内容了。",
  "counts.empty.showAll": "显示所有行",
  "counts.empty.title": "还没有盘点",
  "counts.filter.all": "显示全部",
  "counts.filter.differ": "只看差异",
  "counts.filter.item": "正在显示 {item}",
  "counts.filter.open": "未盘点",
  "counts.linePages": "明细行分页",
  "counts.lineRefused": "{item}：{reason}",
  "counts.lines": "明细行",
  "counts.missing.body": "它可能已被删除，或者你无权查看。",
  "counts.missing.title": "找不到此盘点",
  "counts.noBatch": "无批次",
  "counts.notOpen": "此盘点已不再开放",
  "counts.notSaved": "未保存",
  "counts.onHandNow": "现有库存 {qty}",
  "counts.pages": "盘点分页",
  "counts.post": "过账盘点",
  "counts.post.body": "将调整{count, plural, other {# 行}}。库存管理员可以冲销已过账的盘点。",
  "counts.post.more": "以及另外 {count} 项",
  "counts.post.reason": "原因",
  "counts.post.title": "过账此盘点？",
  "counts.posted": "盘点已过账 · 已调整{count, plural, other {# 行}}",
  "counts.progress": "已盘点 {done} / {all} 行",
  "counts.reverse": "冲销盘点…",
  "counts.reverse.body": "{count, plural, other {# 行}}将恢复原状。会降到零以下的批次将被拒绝，并会列出名称。",
  "counts.reverse.title": "冲销此盘点？",
  "counts.reverse.yes": "冲销盘点",
  "counts.reverseContinue": "继续冲销",
  "counts.reverseStopped": "还有一些行未冲销。准备好后请继续。",
  "counts.reversedToast": "盘点已冲销",
  "counts.saved": "已保存",
  "counts.saving": "正在保存",
  "counts.scan.hint": "扫描或输入物品，即可跳到对应的行。",
  "counts.scan.now": "当前：{item}",
  "counts.scan.unknown": "不在此盘点中 · {code}",
  "counts.scope.all": "此地点的全部物品",
  "counts.scope.category": "一个类别",
  "counts.scope.categoryNamed": "类别：{category}",
  "counts.scope.stale": "近期未盘点",
  "counts.scope.staleDays": "{days} 天未盘点的物品",
  "counts.scope.toCheck": "标记待核对",
  "counts.scope.toCheckItems": "标记待核对的物品",
  "counts.sheet.subtitle": "{number} · {scope} · {date} 开始",
  "counts.sheet.title": "盘点",
  "counts.sheet.titlePlace": "盘点 · {place}",
  "counts.start": "开始盘点",
  "counts.start.category": "类别",
  "counts.start.chooseCategory": "选择类别",
  "counts.start.choosePlace": "选择地点",
  "counts.start.done": "已开始盘点 {place}",
  "counts.start.doneParts": "已开始盘点 {place}，分为 {parts} 个盘点",
  "counts.start.go": "开始",
  "counts.start.help": "盘点期间的销售会照常保留。每一行都与你输入盘点数那一刻的账面数量比较。",
  "counts.start.nothing": "此地点没有符合条件的内容：没有可盘点的行。",
  "counts.start.openHere": "此地点仍在进行的盘点：",
  "counts.start.place": "地点",
  "counts.start.reading": "正在开始盘点 · 正在读取 {n} 条库存记录",
  "counts.start.title": "开始盘点",
  "counts.start.what": "盘点范围",
  "counts.status.cancelled": "已取消",
  "counts.status.open": "盘点中",
  "counts.status.posted": "已过账",
  "counts.status.posting": "过账中",
  "counts.status.reversed": "已冲销",
  "counts.status.reversing": "冲销中",
  "counts.stopped": "{done} / {all} 行已过账。准备好后请继续。",
  "counts.title": "盘点",
  "counts.toCheck.body": "这些物品已调整，并仍标记为待核对：{items}",
  "counts.toCheck.title": "盘点后又有售出",
  "counts.totals": "{count, plural, other {# 项差异}}",
  "counts.totalsMoney": "{count, plural, other {# 项差异}} · {value}",
  "counts.uncounted": "{count, plural, other {# 行}}尚未盘点"
};

export const rules: Readonly<Record<string, string>> = {
  "rules.add": "添加规则",
  "rules.added": "已添加 {table} 的规则",
  "rules.badge.app": "来自 {app}",
  "rules.badge.yours": "你的表",
  "rules.caughtUp": "已记录 {planned} 条，仍有 {left} 条在等待",
  "rules.edit": "编辑",
  "rules.empty.body": "规则说明你某张表中的一行何时预留、扣减或放回库存。",
  "rules.empty.title": "还没有表从库存中扣减",
  "rules.fixed": "只有可以更改表运作方式的人才能修改这些规则。",
  "rules.itemsMade": "已创建 {made} 个物品，{skipped} 个已关联",
  "rules.makeItems": "根据此表创建库存物品",
  "rules.makeItems.go": "创建物品",
  "rules.makeItems.label": "用来命名每一行的列",
  "rules.needsUnit": "请先在“设置”中选择默认单位",
  "rules.off": "关闭",
  "rules.point.create": "该行被创建",
  "rules.point.from": "{row}从 {fromStates} 转为 {states}",
  "rules.point.in": "{column} 变为 {values}",
  "rules.point.parent": "其 {column}",
  "rules.point.row": "该行",
  "rules.point.set": "{column} 已填写",
  "rules.point.to": "{row}转为 {states}",
  "rules.recordNow": "立即记录",
  "rules.remove": "移除规则",
  "rules.remove.confirm": "移除此规则？此表的行将不再从库存中扣减。",
  "rules.rule.back": "当{point}时，放回库存。",
  "rules.rule.count": "按{multipliers}计数。",
  "rules.rule.from": "从 {place} 扣减。",
  "rules.rule.fromColumn": "从 {column} 中的地点扣减。",
  "rules.rule.give": "当{point}时，将{what}放回货架。",
  "rules.rule.hold": "当{point}时，预留库存。",
  "rules.rule.take": "当{point}时，扣减{what}。",
  "rules.saved": "已保存 {table} 的规则",
  "rules.setBy": "由 {app} 设置。你可以将其关闭；其步骤只会随 {app} 的更新而改变。",
  "rules.sheet.add": "添加规则",
  "rules.sheet.addRule": "添加规则",
  "rules.sheet.back": "放回",
  "rules.sheet.chooseColumn": "选择列",
  "rules.sheet.chooseTable": "选择表",
  "rules.sheet.defaultPlace": "默认地点",
  "rules.sheet.edit": "编辑规则",
  "rules.sheet.err.table": "请选择表",
  "rules.sheet.err.take": "请选择何时预留或扣减库存",
  "rules.sheet.err.until": "预留需要一个说明何时结束的列",
  "rules.sheet.err.when": "请填完你选择的每个“何时”",
  "rules.sheet.guest": "按客人数计算，取自",
  "rules.sheet.hold": "预留",
  "rules.sheet.linkColumn": "哪一列",
  "rules.sheet.night": "按晚数计算，取自",
  "rules.sheet.notNeeded": "不需要",
  "rules.sheet.one": "每次一个",
  "rules.sheet.place": "从哪个地点",
  "rules.sheet.placeColumn": "{column} 中的地点",
  "rules.sheet.quantity": "数量",
  "rules.sheet.reads": "读作",
  "rules.sheet.save": "保存规则",
  "rules.sheet.table": "表",
  "rules.sheet.take": "扣减",
  "rules.sheet.until": "到何时为止",
  "rules.sheet.used": "使用的是什么",
  "rules.sheet.used.link": "关联列",
  "rules.sheet.used.linkHelp": "该行指向所使用的物品。",
  "rules.sheet.used.row": "此行",
  "rules.sheet.used.rowHelp": "表中的每一行都是一种库存物品。",
  "rules.switchLabel": "{table} 规则",
  "rules.switchedOff": "{table} 规则已关闭",
  "rules.switchedOn": "{table} 规则已开启",
  "rules.title": "库存规则",
  "rules.unavailable": "库存模块无法响应此表。新的保存将等待或被拒绝。",
  "rules.waiting": "{count, plural, other {# 次保存}}正在等待",
  "rules.what.column": "{column}，数量 {quantity}",
  "rules.what.recorded": "其上记录的物品",
  "rules.what.row": "此行的物品",
  "rules.what.rowMany": "此行的物品，数量 {quantity}",
  "rules.when.becomes": "当某列变为",
  "rules.when.column": "{label}：哪一列",
  "rules.when.create": "当该行被创建时",
  "rules.when.moves": "当该行转为",
  "rules.when.never": "从不",
  "rules.when.set": "当某列已填写时"
};
