/** Traditional Chinese strings for the stock screens. Keys are those of en-US.ts. */
export const shared: Readonly<Record<string, string>> = {
  "shared.cancel": "取消",
  "shared.close": "關閉",
  "shared.continuePosting": "繼續過帳",
  "shared.dismiss": "關閉提示",
  "shared.failed.title": "無法載入",
  "shared.loading": "載入中",
  "shared.next": "下一頁",
  "shared.overLimit": "暫時請求過多。{seconds, plural, other {# 秒}}後自動繼續。",
  "shared.pageN": "第 {n} 頁",
  "shared.previous": "上一頁",
  "shared.progress": "{done}／{all} 行",
  "shared.refused.body": "如有需要，請洽庫存管理員。",
  "shared.refused.title": "您沒有開啟此頁面的權限",
  "shared.retry": "重試",
  "shared.scan.addNew": "新增為新品項",
  "shared.scan.asking": "查詢中",
  "shared.scan.failed": "無法查詢",
  "shared.scan.label": "尋找或掃描",
  "shared.scan.placeholder": "掃描條碼，或輸入名稱或代碼",
  "shared.scan.unknown": "沒有品項使用此代碼 · {code}"
};

export const refusal: Readonly<Record<string, string>> = {
  "refusal.conflict": "有其他人同時變更了這筆資料。請再試一次。",
  "refusal.expired": "此批次已過期",
  "refusal.forbidden": "您沒有執行此動作的權限。",
  "refusal.full": "一張採購單最多 50 行。其餘的請另開一張採購單。",
  "refusal.move.children": "請先新增一行。",
  "refusal.move.linked": "這張單據已不再開放此動作。",
  "refusal.move.other": "目前還無法執行。",
  "refusal.move.where": "有些行尚未入庫。",
  "refusal.needsBatch": "請輸入批號",
  "refusal.notAllowed": "這裡不允許此動作。",
  "refusal.oneAtATime": "這些行會逐行儲存。",
  "refusal.other": "無法儲存。請再試一次。",
  "refusal.outOfStock": "剩餘數量不足，無法復原此行",
  "refusal.outOfStockLeft": "批次 {batch} 的{item}只剩 {left} {unit}：此行無法復原",
  "refusal.receiptOpen": "{rows, plural, other {有 # 列}}正保留庫存：請先放回",
  "refusal.stock": "無法更新庫存。此行沒有任何變更。請再試一次；如果持續失敗，請通知負責管理 Adminium 的人。",
  "refusal.tooLarge": "此行數量太大，無法一次過帳。請拆成較小的幾行。"
};

export const receive: Readonly<Record<string, string>> = {
  "receive.another": "再收一批貨",
  "receive.anotherBatch": "另一個批次",
  "receive.bar": "這張收貨單",
  "receive.batch": "批次",
  "receive.batchHint": "依箱上印的填寫",
  "receive.batchKnown": "批次 {code} 已存在",
  "receive.choose": "選擇地點",
  "receive.choosePlace": "選擇這批貨要存入的地點",
  "receive.closedMeanwhile": "{order} 在您收貨時已被結案。庫存已入庫；採購單沒有變更。",
  "receive.col.cost": "單位成本",
  "receive.col.item": "品項",
  "receive.col.now": "本次收貨",
  "receive.col.ordered": "訂購量",
  "receive.col.received": "已收數量",
  "receive.col.total": "合計",
  "receive.costOrdered": "採購單上為 {cost}",
  "receive.costToCheck": "有一行因為沒有已知成本，已用平均成本過帳。請檢查其成本。",
  "receive.costUsed": "Adminium 使用了 {cost}",
  "receive.countPacks": "以每{pack} {size} 個計數",
  "receive.countUnits": "以{unit}計數",
  "receive.delivery": "到貨",
  "receive.discard.body": "您輸入的行尚未儲存。變更採購單會重新開始。",
  "receive.discard.title": "要捨棄已輸入的內容嗎？",
  "receive.discard.yes": "捨棄並變更",
  "receive.draftSaved": "草稿已儲存。可在「收貨單」中找到。",
  "receive.empty.body": "掃描箱子，或在上方輸入品項名稱。每加入一個品項就會成為一行。",
  "receive.empty.title": "尚未加入任何內容",
  "receive.err.expires": "請輸入到期日",
  "receive.err.qty": "請輸入本次收貨數量",
  "receive.err.whole": "請輸入整數",
  "receive.expires": "到期日",
  "receive.fixFirst": "{count, plural, other {過帳前有 # 個欄位需要修正}}",
  "receive.into": "存入",
  "receive.itemAdded": "已新增品項：{item}",
  "receive.lineCount": "{count, plural, other {# 行}}",
  "receive.lineIn": "已入庫",
  "receive.lineRefused": "{item}：{reason}",
  "receive.lines": "明細行",
  "receive.missing.body": "它可能已被移除，或您無法檢視。",
  "receive.missing.title": "找不到這張收貨單",
  "receive.newItem.add": "新增品項並收貨",
  "receive.newItem.barcode": "條碼",
  "receive.newItem.name": "名稱",
  "receive.newItem.nameHint": "您希望在盤點時顯示的名稱",
  "receive.newItem.nameMissing": "請為品項取個名稱",
  "receive.newItem.pack": "每箱數量（選填）",
  "receive.newItem.subtitle": "會加入「品項」以及這次到貨。",
  "receive.newItem.title": "新品項",
  "receive.newItem.tracks": "追蹤批次：每次收貨時都會詢問批次與到期日",
  "receive.newItem.unit": "計數單位",
  "receive.noOrder": "無採購單",
  "receive.noSupplier": "無供應商",
  "receive.notAllIn": "有些行尚未入庫",
  "receive.notOnOrder": "不在這張採購單上",
  "receive.nothing": "請先加入要收貨的品項",
  "receive.order": "採購單",
  "receive.orderLabel": "{number} · {supplier}",
  "receive.orderedPacks": "{packs} {pack}，每{pack} {size} 個",
  "receive.overOrder": "比訂購多 {qty} {unit}",
  "receive.overOrderPacks": "比訂購多 {count, plural, other {# 包}}",
  "receive.overview": "庫存總覽",
  "receive.pack": "包",
  "receive.packs": "包",
  "receive.per": "每{unit}",
  "receive.post": "過帳收貨單",
  "receive.posted": "收貨單已過帳",
  "receive.posted.batch": "批次 {code}",
  "receive.posted.batchExpires": "批次 {code} · 到期日 {date}",
  "receive.posted.full": "{order} 已全部收貨。",
  "receive.posted.noOrder": "已從供應商收到庫存。",
  "receive.posted.onHand": "目前現有 {qty} {unit}",
  "receive.posted.part": "{order} 已部分收貨。",
  "receive.posted.plain": "庫存已收到。",
  "receive.posted.title": "收貨單已過帳",
  "receive.posted.toCome": "{order} 已部分收貨。{item}還有 {qty} {unit} 未到。",
  "receive.posted.totalsMoney": "已收 {units} 個單位 · {total}",
  "receive.posted.totalsUnits": "已收 {units} 個單位",
  "receive.posted.where": "存入{place} · {when} · {by}",
  "receive.postedFor": "{order} 的收貨單已過帳",
  "receive.posting.body": "{all} 行中已有 {done} 行入庫。準備好後請繼續；尚未入庫的行仍可修正。",
  "receive.posting.title": "這張收貨單已部分入庫",
  "receive.remove": "移除{item}",
  "receive.removed": "已移除{item}",
  "receive.reopenFirst": "請先重新開啟採購單",
  "receive.reversed.body": "每一列都已重新從庫存中移出。收貨單仍保留在紀錄中。",
  "receive.reversed.title": "收貨單已復原",
  "receive.reversing.title": "這張收貨單已部分復原",
  "receive.saveDraft": "儲存為草稿",
  "receive.scan.added": "已加入{item} · 1 {unit}",
  "receive.scan.hintPack": "掃描器會輸入到這個欄位。每掃一次加一包。",
  "receive.scan.hintUnit": "掃描器會輸入到這個欄位。每掃一次加一個。",
  "receive.scan.raised": "{item} · 目前 {qty} {unit}",
  "receive.seeMovements": "查看異動紀錄",
  "receive.sendBack": "退回給供應商",
  "receive.sendBack.body": "整行會以其成本自庫存移出，並重新計為訂購中。若只要報廢一行中的一部分，請改用該品項的「使用庫存」。",
  "receive.sendBack.title": "要將此行退回給供應商嗎？",
  "receive.sentBack": "{item}已退回",
  "receive.status.reversed": "已復原",
  "receive.status.sentBack": "已退回",
  "receive.stopped": "{all} 行中已有 {done} 行入庫。準備好後請繼續。",
  "receive.stoppedAt": "{all} 行中已有 {done} 行入庫。{item}：{reason}",
  "receive.supplier": "供應商（選填）",
  "receive.supplierOf": "供應商",
  "receive.title": "庫存收貨",
  "receive.toCome": "尚有 {qty} {unit} 未到",
  "receive.toComePacks": "尚有 {count, plural, other {# 包}} 未到",
  "receive.totalsMoney": "本次收貨 {units} 個單位 · {total}",
  "receive.totalsTyped": "{count, plural, other {待收貨 # 行}}",
  "receive.totalsUnits": "本次收貨 {units} 個單位",
  "receive.undo": "復原這張收貨單",
  "receive.undo.body": "每一行都會逐一從庫存中取出。庫存已被使用的行無法復原，並會列出名稱。",
  "receive.undo.title": "要復原這張收貨單嗎？",
  "receive.undoContinue": "繼續復原",
  "receive.undoStopped": "還有行尚未復原。準備好後請繼續。",
  "receive.undone": "收貨單已復原"
};

export const transfer: Readonly<Record<string, string>> = {
  "transfer.bar": "這筆調撥",
  "transfer.batch.any": "最早到期的優先",
  "transfer.batch.kept": "先前選擇的批次",
  "transfer.batch.option": "{code} · {qty} {unit}",
  "transfer.choose": "選擇地點",
  "transfer.choosePlaces": "選擇庫存的來源地點與目的地點",
  "transfer.col.batch": "批次",
  "transfer.col.item": "品項",
  "transfer.col.qty": "數量",
  "transfer.done": "調撥完成",
  "transfer.draftSaved": "草稿已儲存。可在「調撥」中找到。",
  "transfer.empty.body": "掃描品項，或在上方輸入名稱。每加入一個品項就會成為一行。",
  "transfer.empty.title": "尚未加入任何內容",
  "transfer.err.qty": "請輸入要移動的數量",
  "transfer.finish": "完成",
  "transfer.fixFirst": "有一行需要先修正",
  "transfer.from": "從",
  "transfer.lineCount": "{count, plural, other {# 行}}",
  "transfer.lineDone": "已移動",
  "transfer.lineRefused": "{item}：{reason}",
  "transfer.lineUndone": "已復原",
  "transfer.lines": "明細行",
  "transfer.missing.body": "它可能已被移除，或您無法檢視。",
  "transfer.missing.title": "找不到這筆調撥",
  "transfer.nothing": "請先加入要移動的品項",
  "transfer.places": "來源與目的地",
  "transfer.posting": "這筆調撥已部分完成。準備好後請繼續。",
  "transfer.remove": "移除{item}",
  "transfer.reversed": "這筆調撥已復原。",
  "transfer.reversing": "這筆調撥已部分復原。準備好後請繼續。",
  "transfer.samePlace": "請選擇不同的地點",
  "transfer.saveDraft": "儲存為草稿",
  "transfer.scan.added": "已加入{item} · 1 {unit}",
  "transfer.scan.hint": "掃描器會輸入到這個欄位。每掃一次加一個。",
  "transfer.scan.raised": "{item} · 目前 {qty} {unit}",
  "transfer.short": "超過帳面數量",
  "transfer.shortToast": "移動的數量超過帳面數量：{items}",
  "transfer.stopped": "{all} 行中已完成 {done} 行。準備好後請繼續。",
  "transfer.title": "調撥庫存",
  "transfer.to": "到",
  "transfer.totals": "{count, plural, other {正在移動 # 行}}",
  "transfer.totalsDone": "已調撥 {count, plural, other {# 列}}",
  "transfer.totalsTyped": "{count, plural, other {待移動 # 行}}",
  "transfer.totalsUndone": "已復原 · {count, plural, other {# 列}}",
  "transfer.undo": "復原這筆調撥",
  "transfer.undo.body": "每一行都會逐一移回。庫存已被使用的行無法復原，並會列出名稱。",
  "transfer.undo.title": "要復原這筆調撥嗎？",
  "transfer.undoContinue": "繼續復原",
  "transfer.undone": "調撥已復原"
};

export const opening: Readonly<Record<string, string>> = {
  "opening.another": "載入另一個檔案",
  "opening.bar": "期初庫存",
  "opening.choose": "選擇地點",
  "opening.choosePlace": "選擇這些庫存所在的地點",
  "opening.col.batch": "批次",
  "opening.col.cost": "單位成本",
  "opening.col.expires": "到期日",
  "opening.col.item": "品項",
  "opening.col.qty": "數量",
  "opening.draftSaved": "草稿已儲存。可在「收貨單」中找到。",
  "opening.empty": "請選擇檔案以開始",
  "opening.err.cost": "請輸入成本，例如 1.10",
  "opening.err.expires": "日期請寫成 2027-04-30",
  "opening.err.qty": "請輸入大於零的數量，小數請用小數點",
  "opening.file.body": "每個品項一列，或品項的每個批次一列。日期寫成 2027-04-30；小數請用小數點。",
  "opening.file.choose": "選擇 CSV 檔案",
  "opening.file.empty": "這個檔案沒有任何列。",
  "opening.file.header": "第一列必須是欄位名稱：quantity，以及 sku、barcode 或 name 其中之一。請下載範例檔案參考。",
  "opening.file.title": "檔案",
  "opening.file.tooMany": "這個檔案有 {count} 列。一個檔案最多 {max} 列：請分割後逐一載入。",
  "opening.fixFirst": "{count, plural, other {檔案中有 # 列需要先修正}}",
  "opening.itemsMade": "{count, plural, other {已建立 # 個品項}}",
  "opening.load": "載入期初庫存",
  "opening.loaded": "期初庫存已載入",
  "opening.nothing": "沒有可載入的內容",
  "opening.onePart": "期初庫存",
  "opening.openPart": "開啟",
  "opening.pages": "明細行分頁",
  "opening.part": "期初庫存，第 {n} 部分，共 {m} 部分",
  "opening.partLines": "{count, plural, other {# 行}}",
  "opening.parts": "{count} 行：會依檔案順序儲存為 {parts} 張收貨單。",
  "opening.place": "地點",
  "opening.progress": "第 {part} 部分：{done}／{all} 行",
  "opening.reading": "正在讀取檔案 · 目前已比對 {done} 列",
  "opening.review": "檢查",
  "opening.reviewCount": "{count, plural, other {待載入 # 行}}",
  "opening.row": "第 {at} 列",
  "opening.sample": "下載範例檔案",
  "opening.saveDraft": "儲存為草稿",
  "opening.saved.title": "已儲存，待載入",
  "opening.status.draft": "草稿",
  "opening.status.loaded": "已載入",
  "opening.status.partly": "部分載入",
  "opening.stopped": "第 {part} 部分：{all} 行中已有 {done} 行入庫。準備好後請繼續。",
  "opening.stoppedAt": "第 {part} 部分：有一行被拒絕。{reason} 請開啟該部分加以修正。",
  "opening.title": "期初庫存",
  "opening.totals": "{count, plural, other {待載入 # 行}}",
  "opening.totalsSaved": "{count, plural, other {已儲存 # 張收貨單}}",
  "opening.unmatched.body": "{count, plural, other {第 {rows}{more} 列}}。除非建立這些品項，否則將略過。",
  "opening.unmatched.leave": "略過",
  "opening.unmatched.make": "建立這些品項",
  "opening.unmatched.title": "{count, plural, other {有 # 列找不到對應的品項}}"
};

export const counts: Readonly<Record<string, string>> = {
  "counts.add.batch": "加入批次 {code}",
  "counts.add.plain": "將{item}加入這次盤點",
  "counts.add.title": "{item}在這個地點，但不在這次盤點中",
  "counts.askManager": "請庫存管理員過帳這次盤點",
  "counts.bar": "這次盤點",
  "counts.batch": "批次 {code}",
  "counts.cancel": "取消盤點",
  "counts.cancel.body": "尚未過帳，所以庫存不會有任何變更。目前已輸入的盤點數會隨已取消的盤點一併保留。",
  "counts.cancel.title": "要取消這次盤點嗎？",
  "counts.cancelledToast": "盤點已取消。庫存沒有任何變更。",
  "counts.col.count": "盤點數",
  "counts.col.counted": "已盤點",
  "counts.col.difference": "差異",
  "counts.col.differences": "差異數",
  "counts.col.expected": "應有數量",
  "counts.col.item": "品項",
  "counts.col.place": "地點",
  "counts.col.scope": "範圍",
  "counts.col.sku": "SKU",
  "counts.col.started": "開始時間",
  "counts.col.status": "狀態",
  "counts.col.value": "金額",
  "counts.countedFor": "盤點數，{item}",
  "counts.doneForNow": "先到這裡",
  "counts.empty.body": "盤點一個地點，核對帳面與架上的數量。",
  "counts.empty.differ": "目前沒有差異",
  "counts.empty.differBody": "目前已盤點的每一列都與預期相符。",
  "counts.empty.lines": "這次盤點沒有任何行",
  "counts.empty.open": "每一行都已盤點",
  "counts.empty.openBody": "這裡沒有待盤點的項目了。",
  "counts.empty.showAll": "顯示所有列",
  "counts.empty.title": "尚無盤點",
  "counts.filter.all": "顯示全部",
  "counts.filter.differ": "只顯示差異",
  "counts.filter.item": "正在顯示{item}",
  "counts.filter.open": "未盤點",
  "counts.linePages": "明細行分頁",
  "counts.lineRefused": "{item}：{reason}",
  "counts.lines": "明細行",
  "counts.missing.body": "它可能已被移除，或您無法檢視。",
  "counts.missing.title": "找不到這次盤點",
  "counts.noBatch": "無批次",
  "counts.notOpen": "這次盤點已不再開放",
  "counts.notSaved": "未儲存",
  "counts.onHandNow": "目前現有 {qty}",
  "counts.pages": "盤點分頁",
  "counts.post": "過帳盤點",
  "counts.post.body": "{count, plural, other {將調整 # 行}}。庫存管理員可以沖銷已過帳的盤點。",
  "counts.post.more": "以及另外 {count} 個",
  "counts.post.reason": "原因",
  "counts.post.title": "要過帳這次盤點嗎？",
  "counts.posted": "盤點已過帳 · {count, plural, other {已調整 # 行}}",
  "counts.progress": "{all} 行中已盤點 {done} 行",
  "counts.reverse": "沖銷盤點…",
  "counts.reverse.body": "{count, plural, other {# 行}}將恢復原狀。會低於零的批次將被拒絕，並會列出名稱。",
  "counts.reverse.title": "要沖銷這次盤點嗎？",
  "counts.reverse.yes": "沖銷盤點",
  "counts.reverseContinue": "繼續沖銷",
  "counts.reverseStopped": "還有行尚未沖銷。準備好後請繼續。",
  "counts.reversedToast": "盤點已沖銷",
  "counts.saved": "已儲存",
  "counts.saving": "儲存中",
  "counts.scan.hint": "掃描或輸入品項，即可跳到它所在的行。",
  "counts.scan.now": "目前在{item}",
  "counts.scan.unknown": "不在這次盤點中 · {code}",
  "counts.scope.all": "這個地點的所有品項",
  "counts.scope.category": "單一類別",
  "counts.scope.categoryNamed": "類別：{category}",
  "counts.scope.stale": "近期未盤點",
  "counts.scope.staleDays": "已 {days} 天未盤點的品項",
  "counts.scope.toCheck": "標記為待檢查",
  "counts.scope.toCheckItems": "標記為待檢查的品項",
  "counts.sheet.subtitle": "{number} · {scope} · 開始於 {date}",
  "counts.sheet.title": "盤點",
  "counts.sheet.titlePlace": "盤點 · {place}",
  "counts.start": "開始盤點",
  "counts.start.category": "類別",
  "counts.start.chooseCategory": "選擇類別",
  "counts.start.choosePlace": "選擇地點",
  "counts.start.done": "已開始盤點{place}",
  "counts.start.doneParts": "已開始盤點{place}，共分為 {parts} 次盤點",
  "counts.start.go": "開始",
  "counts.start.help": "盤點期間的銷售會保留。每一行都會與您輸入盤點數當下的帳面數量比較。",
  "counts.start.nothing": "這個地點沒有符合的項目：沒有可盤點的行。",
  "counts.start.openHere": "這個地點尚未結束的盤點：",
  "counts.start.place": "地點",
  "counts.start.reading": "正在開始盤點 · 讀取 {n} 筆庫存量",
  "counts.start.title": "開始盤點",
  "counts.start.what": "盤點範圍",
  "counts.status.cancelled": "已取消",
  "counts.status.open": "盤點中",
  "counts.status.posted": "已過帳",
  "counts.status.posting": "過帳中",
  "counts.status.reversed": "已沖銷",
  "counts.status.reversing": "沖銷中",
  "counts.stopped": "{all} 行中已過帳 {done} 行。準備好後請繼續。",
  "counts.title": "盤點",
  "counts.toCheck.body": "這些品項已調整，並維持標記為待檢查：{items}",
  "counts.toCheck.title": "盤點後又有售出",
  "counts.totals": "{count, plural, other {# 筆差異}}",
  "counts.totalsMoney": "{count, plural, other {# 筆差異}} · {value}",
  "counts.uncounted": "{count, plural, other {還有 # 行未盤點}}"
};

export const rules: Readonly<Record<string, string>> = {
  "rules.add": "新增規則",
  "rules.added": "已新增 {table} 的規則",
  "rules.badge.app": "來自 {app}",
  "rules.badge.yours": "您的資料表",
  "rules.caughtUp": "已記錄 {planned} 筆，還有 {left} 筆等待中",
  "rules.edit": "編輯",
  "rules.empty.body": "規則用來說明您某個資料表的一列何時保留、取用或放回庫存。",
  "rules.empty.title": "還沒有資料表會取用庫存",
  "rules.fixed": "只有可以變更資料表運作方式的人才能變更這些規則。",
  "rules.itemsMade": "已建立 {made} 個品項，{skipped} 個先前已連結",
  "rules.makeItems": "從這個資料表建立庫存品項",
  "rules.makeItems.go": "建立品項",
  "rules.makeItems.label": "用來為每一列命名的欄位",
  "rules.needsUnit": "請先在「設定」中選擇預設單位",
  "rules.off": "關閉",
  "rules.on": "開啟",
  "rules.point.create": "該列建立",
  "rules.point.from": "{row}從{fromStates}移至{states}",
  "rules.point.in": "{column}變為{values}",
  "rules.point.parent": "其{column}",
  "rules.point.row": "該列",
  "rules.point.set": "{column}設定了值",
  "rules.point.to": "{row}移至{states}",
  "rules.recordNow": "立即記錄",
  "rules.remove": "移除規則",
  "rules.remove.confirm": "要移除這條規則嗎？這個資料表的列將不再取用庫存。",
  "rules.rule.back": "當{point}時，放回庫存。",
  "rules.rule.count": "依{multipliers}計算。",
  "rules.rule.from": "從{place}。",
  "rules.rule.fromColumn": "從{column}中的地點。",
  "rules.rule.give": "當{point}時，將{what}放回架上。",
  "rules.rule.hold": "當{point}時，保留庫存。",
  "rules.rule.take": "當{point}時，取用{what}。",
  "rules.saved": "已儲存 {table} 的規則",
  "rules.setBy": "由 {app} 設定。您可以將它關閉；其步驟只會隨 {app} 的更新而變更。",
  "rules.sheet.add": "新增規則",
  "rules.sheet.addRule": "新增規則",
  "rules.sheet.back": "放回",
  "rules.sheet.chooseColumn": "選擇欄位",
  "rules.sheet.chooseTable": "選擇資料表",
  "rules.sheet.defaultPlace": "預設地點",
  "rules.sheet.edit": "編輯規則",
  "rules.sheet.err.table": "請選擇資料表",
  "rules.sheet.err.take": "請選擇何時保留或取用庫存",
  "rules.sheet.err.until": "保留需要一個說明何時結束的欄位",
  "rules.sheet.err.when": "請完成您選擇的每個「何時」",
  "rules.sheet.guest": "依此欄位的每位住客計算",
  "rules.sheet.hold": "保留",
  "rules.sheet.linkColumn": "哪個欄位",
  "rules.sheet.night": "依此欄位的每晚計算",
  "rules.sheet.notNeeded": "不需要",
  "rules.sheet.one": "每次一個",
  "rules.sheet.place": "從哪個地點",
  "rules.sheet.placeColumn": "{column}中的地點",
  "rules.sheet.quantity": "數量多少",
  "rules.sheet.reads": "讀起來是",
  "rules.sheet.save": "儲存規則",
  "rules.sheet.table": "資料表",
  "rules.sheet.take": "取用",
  "rules.sheet.until": "到何時為止",
  "rules.sheet.used": "使用的是什麼",
  "rules.sheet.used.link": "連結的欄位",
  "rules.sheet.used.linkHelp": "該列指向所使用的東西。",
  "rules.sheet.used.row": "這一列",
  "rules.sheet.used.rowHelp": "資料表的每一列都是存放在庫存中的東西。",
  "rules.switchLabel": "{table} 規則",
  "rules.switchedOff": "{table} 規則已關閉",
  "rules.switchedOn": "{table} 規則已開啟",
  "rules.title": "庫存規則",
  "rules.unavailable": "庫存功能無法回應這個資料表。新的儲存會等待或被拒絕。",
  "rules.waiting": "{count, plural, other {有 # 筆儲存等待中}}",
  "rules.what.column": "{quantity} 個{column}",
  "rules.what.recorded": "其上記錄的內容",
  "rules.what.row": "這一列的品項",
  "rules.what.rowMany": "{quantity} 個這一列的品項",
  "rules.when.becomes": "當欄位變為",
  "rules.when.column": "{label}：哪個欄位",
  "rules.when.create": "當該列建立時",
  "rules.when.moves": "當該列移至",
  "rules.when.never": "永不",
  "rules.when.set": "當欄位設定了值時"
};
