/** Arabic strings for the Offers screens. Keys are those of en-US.ts. */
export const shared: Readonly<Record<string, string>> = {
  "shared.cancel": "إلغاء",
  "shared.close": "إغلاق",
  "shared.failed.title": "تعذّر تحميل هذا",
  "shared.loading": "جارٍ التحميل",
  "shared.refused.body": "اطلبه من المدير إن احتجت إليه.",
  "shared.refused.title": "ليست لديك صلاحية لفتح هذا",
  "shared.retry": "إعادة المحاولة"
};

export const refusal: Readonly<Record<string, string>> = {
  "refusal.askManager": "اسأل المدير.",
  "refusal.askToPrint": "اطلب من المدير طباعتها.",
  "refusal.batchFull": "هذه الدفعة فيها كل أكوادها بالفعل.",
  "refusal.cardPaysCard": "الجدول الذي يبيع بطاقات الهدايا لا يمكن أن يقبل بطاقة هدية كوسيلة دفع أيضًا.",
  "refusal.codeTaken": "هذا الكود مستخدَم بالفعل في خصم آخر.",
  "refusal.conflict": "غيّر شخص آخر هذا في الوقت نفسه. لم يُحفظ شيء. حاول مرة أخرى.",
  "refusal.empty": "البطاقة لا تحمل هذا المبلغ.",
  "refusal.emptyLeft": "المتبقي على البطاقة {left}. اخصم {left} أو أقل.",
  "refusal.expired": "انتهت صلاحية هذا. لم يُحفظ شيء.",
  "refusal.forbidden": "ليست لديك صلاحية لفعل هذا.",
  "refusal.inactive": "هذه البطاقة لم تُبَع بعد. لا يمكن استخدامها.",
  "refusal.noAnswer": "تعذّر على Offers الرد. لم يُحفظ شيء.",
  "refusal.noPrint": "لا يمكن طباعة هذا الآن.",
  "refusal.notAllowed": "هذا غير مسموح به هنا.",
  "refusal.notFound": "هذا لم يعد موجودًا.",
  "refusal.off": "Offers متوقف الآن.",
  "refusal.other": "تعذّر حفظ هذا. حاول مرة أخرى.",
  "refusal.overLimit": "هذا يتجاوز الحد. لم يُحفظ شيء.",
  "refusal.rate": "محاولات كثيرة جدًا. انتظر دقيقة.",
  "refusal.receiptOpen": "{rows, plural, zero {لا صفوف تحجز} one {صف واحد يحجز} two {صفان يحجزان} few {# صفوف تحجز} many {# صفًا تحجز} other {# صف تحجز}} مرة استخدام أو عملية دفع ببطاقة: أعدها أولًا.",
  "refusal.usedUp": "استُنفدت كل مرات الاستخدام. لم يُحفظ شيء.",
  "refusal.void": "أُلغي هذا. لم يُحفظ شيء."
};

export const discounts: Readonly<Record<string, string>> = {
  "discounts.aGroup": "مجموعة عملاء",
  "discounts.all": "كل الخصومات",
  "discounts.allDay": "طوال اليوم",
  "discounts.anyone": "أي شخص",
  "discounts.applies.lines": "هذه الأصناف فقط",
  "discounts.applies.linesHint": "أصناف أو فئات أو أنواع",
  "discounts.applies.order": "الطلب كله",
  "discounts.applies.orderHint": "كل ما في السلة",
  "discounts.applies.orderNo": "هذا النوع يحتاج إلى أصناف يُختار منها",
  "discounts.budget": "يتوقف بعد منح هذا المبلغ",
  "discounts.changeItems": "تغيير",
  "discounts.check.amount": "أدخل مبلغًا، مثل 5.00.",
  "discounts.check.buy": "أدخل رقمًا من 2 إلى 10.",
  "discounts.check.code": "أدخل كودًا، أو أنشئ واحدًا.",
  "discounts.check.count": "أدخل عددًا صحيحًا، 1 أو أكثر.",
  "discounts.check.hours": "أدخل الوقتين، أو شغّل «طوال اليوم».",
  "discounts.check.hoursOrder": "يجب أن يكون «حتى» بعد «من».",
  "discounts.check.name": "أعطه اسمًا يعرفه فريقك.",
  "discounts.check.noSteps": "أضف شريحة واحدة على الأقل.",
  "discounts.check.percent": "أدخل نسبة من 1 إلى 100.",
  "discounts.check.price": "أدخل سعرًا، مثل 10.00.",
  "discounts.check.publicName": "أضف السطر الذي يراه العملاء على الإيصال.",
  "discounts.check.stepFrom": "ابدأ كل شريحة من 2 أو أكثر.",
  "discounts.check.stepMore": "امنح خصمًا أكبر من الشريحة السابقة ({n} %).",
  "discounts.check.stepRising": "كل شريحة تبدأ أعلى من السابقة ({n} للواحد).",
  "discounts.check.targets": "اختر صنفًا أو فئة أو نوعًا واحدًا على الأقل.",
  "discounts.check.until": "«حتى» قبل «من»، فلن يُطبَّق هذا أبدًا. اختر تاريخًا في يوم «من» أو بعده.",
  "discounts.check.usesTaken": "استُخدم {n} بالفعل. أدخل {n} أو أكثر.",
  "discounts.chooseItems": "اختر الأصناف",
  "discounts.code": "الكود",
  "discounts.codeHint": "حروف وأرقام. يكتبه العملاء عند الدفع أو يذكرونه عند الكاشير.",
  "discounts.codeMade": "أُنشئ الكود {code}",
  "discounts.col.given": "الممنوح",
  "discounts.col.gives": "ما يمنحه",
  "discounts.col.limits": "الحدود",
  "discounts.col.name": "الاسم",
  "discounts.col.starts": "كيف يبدأ",
  "discounts.col.status": "الحالة",
  "discounts.col.uses": "مرات الاستخدام",
  "discounts.combinable": "يمكن جمعه مع غيره",
  "discounts.combineOff": "يُستخدم وحده، وفقط عندما يمنح أكثر من الخصومات الأخرى مجتمعة.",
  "discounts.combineOn": "يُضاف إلى الخصومات الأخرى القابلة للجمع على الطلب نفسه.",
  "discounts.count": "{n, plural, zero {لا خصومات} one {خصم واحد} two {خصمان} few {# خصومات} many {# خصمًا} other {# خصم}} · مرات الاستخدام والمبلغ الممنوح حتى اليوم",
  "discounts.days": "أيام الأسبوع",
  "discounts.daysHint": "عدم اختيار أي يوم يعني كل الأيام.",
  "discounts.each": "للواحد",
  "discounts.empty.body": "الخصم يخفّض قيمة الطلب تلقائيًا، أو بكود، أو عندما يمنحه الموظفون.",
  "discounts.empty.title": "لا توجد خصومات بعد",
  "discounts.end.body": "سيتوقف تطبيقه فورًا.",
  "discounts.end.title": "هل تريد إنهاء {name} الآن؟",
  "discounts.endNow": "إنهاء الآن",
  "discounts.ended.body": "شغّله مرة أخرى بتاريخ «حتى» لاحق.",
  "discounts.ended.title": "انتهى هذا الخصم",
  "discounts.endedNow": "انتهى {name}",
  "discounts.fewerLanguages": "لغات أقل",
  "discounts.firstOrder": "الطلب الأول فقط",
  "discounts.fix": "صحّح {n, plural, zero {ما يلزم} one {أمرًا واحدًا} two {أمرين} few {# أمور} many {# أمرًا} other {# أمر}} قبل الحفظ",
  "discounts.fixes": "{n, plural, zero {لا شيء يحتاج} one {أمر واحد يحتاج} two {أمران يحتاجان} few {# أمور تحتاج} many {# أمرًا تحتاج} other {# أمر تحتاج}} إلى تصحيح قبل أن تتمكن من الحفظ.",
  "discounts.from": "من",
  "discounts.fromHint": "من بداية ذلك اليوم، بتوقيت المكان.",
  "discounts.fromTime": "من، مثل 09:00",
  "discounts.givenSoFar": "مُنح {amount} حتى الآن",
  "discounts.gives.amount": "خصم {amount}",
  "discounts.gives.amountOn": "خصم {amount} على {what}",
  "discounts.gives.bonus": "{buy} بسعر {pay}",
  "discounts.gives.bonusOn": "{buy} بسعر {pay} على {what}",
  "discounts.gives.percent": "خصم {n} %",
  "discounts.gives.percentOn": "خصم {n} % على {what}",
  "discounts.gives.price": "{amount} للواحد",
  "discounts.gives.priceOn": "{what} بسعر {amount} للواحد",
  "discounts.gives.steps": "خصم أكبر كلما زاد الشراء",
  "discounts.gives.stepsOn": "خصم أكبر كلما زاد شراء {what}",
  "discounts.group": "مجموعة العملاء",
  "discounts.hoursHint": "لا يمكن أن تمتد الساعات إلى ما بعد منتصف الليل.",
  "discounts.houseRule": "يحصل العملاء على كل الخصومات القابلة للجمع، وعلى كود واحد، وفيما عدا ذلك على أفضل خصم منفرد.",
  "discounts.kind.amount": "خصم بمبلغ",
  "discounts.kind.bonus": "2 بسعر 1 وما شابه",
  "discounts.kind.percent": "خصم بنسبة",
  "discounts.kind.price": "سعر ثابت",
  "discounts.kind.steps": "السعر حسب الكمية",
  "discounts.leave.body": "ستفقد ما غيّرته.",
  "discounts.leave.go": "مغادرة",
  "discounts.leave.stay": "متابعة التعديل",
  "discounts.leave.title": "هل تغادر دون حفظ؟",
  "discounts.limit.first": "الطلب الأول فقط",
  "discounts.limit.from": "من {amount}",
  "discounts.limit.perCustomer": "{n} لكل عميل",
  "discounts.limit.until": "حتى {date}",
  "discounts.limit.uses": "{n, plural, zero {لا مرات استخدام} one {مرة استخدام واحدة} two {مرتا استخدام} few {# مرات استخدام} many {# مرة استخدام} other {# مرة استخدام}}",
  "discounts.lookAlike": "{typed} يشبه {code} ({name}) عند القراءة. قد يخلط العملاء بينهما.",
  "discounts.makeCode": "أنشئ لي واحدًا",
  "discounts.maxUses": "إجمالي مرات الاستخدام",
  "discounts.minQty": "الحد الأدنى للكمية",
  "discounts.minQtyHint": "مما ينطبق عليه.",
  "discounts.minSpend": "الحد الأدنى للإنفاق",
  "discounts.minSpendHint": "من قيمة البضاعة، بعد التخفيضات التي تسبقه.",
  "discounts.missing": "هذا الخصم غير موجود هنا",
  "discounts.missingBody": "ربما أُزيل، أو ربما لا تستطيع رؤيته.",
  "discounts.more": "المزيد",
  "discounts.moreCodes": "لهذا الخصم {n} من الأكواد. تجد الباقي ضمن «الأكواد».",
  "discounts.moreLanguages": "لغات أكثر",
  "discounts.name": "الاسم (داخلي)",
  "discounts.never": "لن يُطبَّق أبدًا",
  "discounts.new": "خصم جديد",
  "discounts.newTitle": "خصم جديد",
  "discounts.noMap": "تعذّرت قراءة ما تبيعه جداولك، فلا يمكن اختيار الأصناف ولا تجربة الخصم.",
  "discounts.noTables": "لا شيء هنا يحدد بعد ما تبيعه سطوره. أضف قاعدة ضمن «قواعد العروض» أولًا.",
  "discounts.notLive": "لم يبدأ العمل به بعد",
  "discounts.pause": "إيقاف مؤقت",
  "discounts.pauseUnsaved": "إيقاف مؤقت (تغييراتك غير محفوظة)",
  "discounts.paused": "{name} موقوف مؤقتًا",
  "discounts.perCustomer": "مرات الاستخدام لكل عميل",
  "discounts.pick.addTag": "إضافة",
  "discounts.pick.chosen": "المختار: {n}",
  "discounts.pick.done": "تم",
  "discounts.pick.none": "لا شيء يطابق هذا البحث.",
  "discounts.pick.search": "بحث",
  "discounts.pick.subtitle": "من الجداول المحددة لقبول الخصومات في «قواعد العروض».",
  "discounts.pick.tabCount": "{label} · {n}",
  "discounts.pick.tabs": "من أين تختار",
  "discounts.pick.tag": "وسم، كما هو مكتوب على السطر",
  "discounts.pick.tags": "الوسوم",
  "discounts.pick.title": "اختر ما ينطبق عليه",
  "discounts.pill.active": "نشط",
  "discounts.pill.draft": "مسودة",
  "discounts.pill.ended": "منتهٍ",
  "discounts.pill.paused": "موقوف مؤقتًا",
  "discounts.pill.usedUp": "مستنفَد",
  "discounts.publicName": "ما يراه العملاء",
  "discounts.publicNameHint": "السطر الذي يظهر على الإيصال.",
  "discounts.publicNameIn": "ما يراه العملاء · {language}",
  "discounts.ranAgain": "{name} يعمل مرة أخرى حتى {date}",
  "discounts.readOnly": "يمكنك قراءة هذا الخصم. المدير يستطيع تغييره.",
  "discounts.resume": "استئناف",
  "discounts.resumeUnsaved": "استئناف (تغييراتك غير محفوظة)",
  "discounts.resumed": "{name} يعمل من جديد",
  "discounts.run.ahead": "اختر اليوم أو يومًا لاحقًا.",
  "discounts.run.hint": "يستمر حتى نهاية ذلك اليوم.",
  "discounts.run.title": "تشغيل {name} مرة أخرى",
  "discounts.run.until": "حتى",
  "discounts.runAgain": "تشغيل مرة أخرى",
  "discounts.save": "حفظ",
  "discounts.saveDraft": "حفظ كمسودة",
  "discounts.saved": "حُفظ {name}",
  "discounts.section.applies": "ما ينطبق عليه",
  "discounts.section.combine": "مع الخصومات الأخرى",
  "discounts.section.gives": "ما يمنحه",
  "discounts.section.limits": "الحدود",
  "discounts.section.name": "الاسم",
  "discounts.section.starts": "كيف يبدأ",
  "discounts.section.when": "متى",
  "discounts.section.who": "من يحصل عليه",
  "discounts.signedInOnly": "فقط لعميل مسجّل الدخول، أو عميل يحدده موظفوك بالاسم. الزوار لا يحصلون عليه.",
  "discounts.staffNote": "يظهر في قائمة الخصومات عند الكاشير. حدود الموظفين والأسباب تظل سارية.",
  "discounts.starts.code": "كود",
  "discounts.starts.codes": "عدد الأكواد: {n}",
  "discounts.starts.itself": "تلقائيًا",
  "discounts.starts.itselfHint": "يُطبَّق عندما يستوفي الطلب الشروط",
  "discounts.starts.staff": "الموظفون فقط",
  "discounts.starts.staffHint": "يُختار عند الكاشير",
  "discounts.starts.staffOnly": "لا يمنحه إلا الموظفون",
  "discounts.starts.withCode": "بكود",
  "discounts.starts.withCodeHint": "العميل يقدّم كودًا",
  "discounts.steps.add": "إضافة شريحة",
  "discounts.steps.from": "من",
  "discounts.steps.off": "نسبة الخصم",
  "discounts.steps.remove": "إزالة هذه الشريحة",
  "discounts.steps.rule": "كلما زاد شراؤهم مما ينطبق عليه، زاد التخفيض. تُحتسب أعلى شريحة تم بلوغها.",
  "discounts.switchOn": "تشغيل",
  "discounts.switchedOn": "تم تشغيل {name}",
  "discounts.targets.more": "{first} و{n} غيره",
  "discounts.title": "الخصومات",
  "discounts.toTime": "حتى، مثل 17:00",
  "discounts.totals": "{uses, plural, zero {لا مرات استخدام} one {مرة استخدام واحدة} two {مرتا استخدام} few {# مرات استخدام} many {# مرة استخدام} other {# مرة استخدام}} · الممنوح {given}",
  "discounts.try.asIfOn": "تُجرَّب المسودة كما لو كانت مشغّلة.",
  "discounts.try.bar": "جرّبه · {n, plural, zero {لا خصومات} one {خصم واحد} two {خصمان} few {# خصومات} many {# خصمًا} other {# خصم}}",
  "discounts.try.barTotal": "جرّبه · {n, plural, zero {لا خصومات} one {خصم واحد} two {خصمان} few {# خصومات} many {# خصمًا} other {# خصم}} · {total}",
  "discounts.try.better": "استُخدم {name} بدلًا منه: يمنح أكثر.",
  "discounts.try.buyer": "من يشتري",
  "discounts.try.code": "الكود عند الدفع",
  "discounts.try.customer": "عميل مسجّل الدخول",
  "discounts.try.draftName": "{name} (مسودة)",
  "discounts.try.failed": "تعذّرت تجربة هذا",
  "discounts.try.guest": "زائر",
  "discounts.try.minus": "−{amount}",
  "discounts.try.noCode": "بدون كود",
  "discounts.try.noRows": "لا شيء محفوظ هناك بعد.",
  "discounts.try.none": "لا شيء يقبل الخصومات بعد",
  "discounts.try.noneBody": "حدّد أيّ جداولك يقبل الخصومات، وعندها يمكن تجربة هذا الخصم على صفوفه.",
  "discounts.try.notApplied": "لم يُطبَّق",
  "discounts.try.nothing": "لا خصم ينطبق على هذا الطلب.",
  "discounts.try.off": "المخصوم من الطلب",
  "discounts.try.refused": "{code}: {why}",
  "discounts.try.row": "جُرّب على",
  "discounts.try.rowHint": "صف محفوظ من {table}",
  "discounts.try.rules": "قواعد العروض",
  "discounts.try.taxLater": "تُضاف الضريبة عند حفظ الطلب",
  "discounts.try.title": "جرّبه",
  "discounts.try.total": "الإجمالي",
  "discounts.try.unnamed": "خصم",
  "discounts.try.whyNot": "{name} — {why}",
  "discounts.until": "حتى (اختياري)",
  "discounts.untilHint": "حتى نهاية ذلك اليوم، بتوقيت المكان.",
  "discounts.usedUp.body": "للقراءة فقط إلى أن ترفع الحد.",
  "discounts.usedUp.raise": "رفع الحد",
  "discounts.usedUp.title": "استُنفدت كل مرات الاستخدام ({n})",
  "discounts.usesSoFar": "استُخدم {n}",
  "discounts.value.amount": "مبلغ الخصم",
  "discounts.value.amountHint": "لا يزيد أبدًا على قيمة ما ينطبق عليه.",
  "discounts.value.buy": "اشترِ",
  "discounts.value.cheaper": "الأرخص علينا.",
  "discounts.value.cheapest": "الأرخص بينها علينا.",
  "discounts.value.percent": "نسبة الخصم",
  "discounts.value.price": "سعر البيع، للواحد",
  "discounts.value.priceHint": "الأصناف التي سعرها أقل بالفعل تحتفظ بسعرها.",
  "discounts.why.alone": "خصم آخر يمنح أكثر، وهذا يُستخدم وحده",
  "discounts.why.cancelled": "أُلغي",
  "discounts.why.days": "ليس في هذا اليوم",
  "discounts.why.draft": "ما زال مسودة",
  "discounts.why.ended": "انتهى",
  "discounts.why.first": "هذا ليس طلبًا أول",
  "discounts.why.group": "العميل ليس ضمن مجموعته",
  "discounts.why.hours": "ليس في هذا الوقت من اليوم",
  "discounts.why.items": "لا شيء في هذا الطلب مما يخصّه",
  "discounts.why.limit": "تجاوز أحد الحدود",
  "discounts.why.minimum": "الطلب أقل من الحد الأدنى للإنفاق",
  "discounts.why.noCode": "يحتاج إلى كوده",
  "discounts.why.notYet": "لم يبدأ بعد",
  "discounts.why.paused": "موقوف مؤقتًا",
  "discounts.why.quantity": "الكمية مما يخصّه غير كافية",
  "discounts.why.signIn": "يحتاج إلى عميل مسجّل الدخول",
  "discounts.why.unknown": "لا ينطبق هنا",
  "discounts.why.usedUp": "استُنفدت كل مرات الاستخدام"
};

export const lookup: Readonly<Record<string, string>> = {
  "lookup.addCredit": "إضافة رصيد",
  "lookup.added": "أُضيف {amount}",
  "lookup.adjust": "تعديل",
  "lookup.askManager": "المدير يستطيع إعادة شحنها أو تعديلها أو إلغاءها.",
  "lookup.batch": "الدفعة",
  "lookup.cancelCard": "إلغاء البطاقة",
  "lookup.cancelled": "أُلغيت البطاقة المنتهية بـ {last4}",
  "lookup.code": "الكود",
  "lookup.col.amount": "المبلغ",
  "lookup.col.date": "التاريخ",
  "lookup.col.leftAfter": "المتبقي بعدها",
  "lookup.col.what": "ماذا",
  "lookup.col.where": "أين",
  "lookup.creditGiven": "مُنح {address} رصيدًا قدره {amount}",
  "lookup.dialog.add": "إضافة",
  "lookup.dialog.adjust": "تعديل البطاقة المنتهية بـ {last4}",
  "lookup.dialog.amount": "المبلغ",
  "lookup.dialog.amountNeeded": "أدخل مبلغًا أكبر من صفر.",
  "lookup.dialog.byCard": "بطاقة",
  "lookup.dialog.cancel": "هل تريد إلغاء البطاقة المنتهية بـ {last4}؟",
  "lookup.dialog.cancelBody": "لن يمكن إنفاق ما تبقّى عليها. لا يمكن التراجع عن هذا الإجراء.",
  "lookup.dialog.cash": "نقدًا",
  "lookup.dialog.credit": "منح رصيد لـ {address}",
  "lookup.dialog.creditMail": "يُبلَّغ العميل بالبريد الإلكتروني.",
  "lookup.dialog.creditMore": "إضافة رصيد لـ {address}",
  "lookup.dialog.direction": "إضافة أو خصم",
  "lookup.dialog.movesTo": "ينتقل تاريخ «يُستخدم قبل» إلى {date}",
  "lookup.dialog.other": "أخرى",
  "lookup.dialog.paidBy": "طريقة الدفع",
  "lookup.dialog.paidHint": "يُسجَّل كمبلغ مُحصَّل عند الشباك. لا يُخصم شيء هنا.",
  "lookup.dialog.remove": "خصم",
  "lookup.dialog.topUp": "إعادة شحن البطاقة المنتهية بـ {last4}",
  "lookup.dialog.upTo": "البطاقة تحمل حتى {max}.",
  "lookup.dialog.why": "السبب",
  "lookup.dialog.whyHint": "يُحفظ مع سجل البطاقة.",
  "lookup.dialog.whyNeeded": "اذكر السبب.",
  "lookup.discount": "الخصم",
  "lookup.failed": "تعذّر البحث عن هذا",
  "lookup.field.empty": "اكتب كودًا أو امسحه أولًا.",
  "lookup.field.label": "اكتب كودًا أو امسحه، أو اكتب بريد العميل الإلكتروني",
  "lookup.field.placeholder": "GC-7K2M-W3HN-Q4XP أو name@example.com",
  "lookup.for": "إلى",
  "lookup.from": "من",
  "lookup.giveCredit": "منح رصيد",
  "lookup.go": "بحث",
  "lookup.issue": "إصدار",
  "lookup.issued": "تاريخ الإصدار",
  "lookup.kind.card": "بطاقة هدية",
  "lookup.kind.code": "كود خصم",
  "lookup.kind.credit": "رصيد",
  "lookup.kind.pack": "باقة",
  "lookup.kind.voucher": "قسيمة",
  "lookup.left": "المتبقي",
  "lookup.leftOf": "{left} من {total}",
  "lookup.markUsed": "تحديد كمستخدَمة",
  "lookup.markedUsed": "حُدّدت كمستخدَمة",
  "lookup.moved": "بطاقة أقدم · تعمل فقط عند شباك به موظف",
  "lookup.never": "لا تنتهي صلاحيتها",
  "lookup.noActivity": "لم يحدث عليها شيء بعد.",
  "lookup.noUses": "لم تُستخدم بعد.",
  "lookup.none.address": "لا رصيد لـ {typed}",
  "lookup.none.addressBody": "لا يوجد رصيد على هذا العنوان.",
  "lookup.none.code": "لا شيء يحمل هذا الكود · {typed}",
  "lookup.none.codeBody": "راجع الحروف والأرقام وجرّب كودًا آخر.",
  "lookup.openBatch": "فتح الدفعة",
  "lookup.openDiscount": "فتح الخصم",
  "lookup.percent": "{n}%",
  "lookup.pill.active": "نشط",
  "lookup.pill.cancelled": "ملغى",
  "lookup.pill.doesNot": "لا يعمل الآن",
  "lookup.pill.expired": "منتهي الصلاحية",
  "lookup.pill.inactive": "غير نشط",
  "lookup.pill.notSold": "لم يُبَع بعد",
  "lookup.pill.notUsed": "غير مستخدَم",
  "lookup.pill.used": "مستخدَم",
  "lookup.pill.usedUp": "مستنفَد",
  "lookup.pill.works": "يعمل",
  "lookup.print": "طباعة",
  "lookup.printing": "فُتح للطباعة",
  "lookup.queued": "في قائمة الانتظار لإعادة الإرسال",
  "lookup.queuedFor": "في قائمة الانتظار لـ {name}",
  "lookup.removed": "خُصم {amount}",
  "lookup.row.adjust": "تعديل",
  "lookup.row.expire": "انتهاء الصلاحية",
  "lookup.row.issue": "إصدار",
  "lookup.row.refund": "إعادة",
  "lookup.row.spend": "إنفاق",
  "lookup.row.topUp": "إعادة شحن",
  "lookup.row.void": "إلغاء",
  "lookup.said.card": "بطاقة هدية تنتهي بـ {last4}، {pill}، المتبقي {amount}",
  "lookup.said.cardNoBalance": "بطاقة هدية تنتهي بـ {last4}، {pill}",
  "lookup.said.code": "كود خصم يعمل",
  "lookup.said.codeNot": "كود خصم لا يعمل الآن",
  "lookup.said.credit": "رصيد، {pill}، المتبقي {amount}",
  "lookup.said.nothing": "لا شيء يحمل هذا الكود",
  "lookup.said.pack": "باقة تنتهي بـ {last4}، {pill}، المتبقي {left} من {total}",
  "lookup.said.voucher": "قسيمة تنتهي بـ {last4}، {pill}",
  "lookup.sendAgain": "إعادة الإرسال",
  "lookup.start.body": "امسح الكود الموجود على البطاقة أو القسيمة، أو اكتبه. للرصيد، اكتب بريد العميل الإلكتروني.",
  "lookup.start.title": "لم يُبحث عن شيء بعد",
  "lookup.subtitle": "بطاقات الهدايا والقسائم والباقات وأكواد الخصم والرصيد",
  "lookup.title": "بحث",
  "lookup.topUp": "إعادة الشحن",
  "lookup.toppedUp": "أُعيد الشحن بمبلغ {amount}",
  "lookup.use.counted": "مستخدَمة",
  "lookup.use.givenBack": "مُعادة",
  "lookup.use.held": "محجوزة",
  "lookup.useBy": "يُستخدم قبل",
  "lookup.useOne": "استخدام مرة الآن",
  "lookup.useRecorded": "سُجّلت مرة استخدام 1",
  "lookup.uses": "مرات الاستخدام",
  "lookup.usesLeft": "مرات الاستخدام المتبقية",
  "lookup.validUntil": "يعمل حتى",
  "lookup.what": "ما هو",
  "lookup.why.cancelled": "ملغى · لا يمكن استخدامه",
  "lookup.why.codeUsedUp": "استُنفدت كل مرات استخدام هذا الكود",
  "lookup.why.empty": "لم يتبقَّ عليه شيء",
  "lookup.why.expired": "منتهي الصلاحية",
  "lookup.why.expiredOn": "انتهت الصلاحية في {date}",
  "lookup.why.inactive": "لم يُبَع بعد · لا يمكن الإنفاق منه",
  "lookup.why.notSold": "لم يُبَع بعد · لا يمكن استخدامه",
  "lookup.why.off": "هذا الكود موقوف",
  "lookup.why.used": "استُخدم بالفعل",
  "lookup.why.usedUp": "استُنفدت كل مرات الاستخدام",
  "lookup.worth": "القيمة"
};

export const issue: Readonly<Record<string, string>> = {
  "issue.batch.again": "يمكنك تنزيلها مرة أخرى من «دفعات القسائم».",
  "issue.batch.count": "العدد",
  "issue.batch.countRange": "من 1 إلى {max}",
  "issue.batch.download": "تنزيل الأكواد (CSV)",
  "issue.batch.expiresNeeded": "حدّد متى تتوقف الأكواد عن العمل.",
  "issue.batch.made": "أُنشئ {count} من الأكواد",
  "issue.batch.making": "جارٍ إنشاء الأكواد",
  "issue.batch.name": "اسم الدفعة",
  "issue.batch.nameNeeded": "اكتب اسمًا للدفعة.",
  "issue.batch.open": "فتح الدفعة",
  "issue.batch.part": "أُنشئ {made} من {count}. أكملها ضمن «دفعات القسائم».",
  "issue.batch.progress": "{made} من {count}",
  "issue.batch.readBack": "{count, plural, zero {لا أكواد} one {كود واحد} two {كودان} few {# أكواد} many {# كودًا} other {# كود}}، كلٌّ منها صالح لمرة واحدة، حتى {date}",
  "issue.batch.save": "إنشاء الأكواد",
  "issue.card.amount": "المبلغ",
  "issue.card.amountNeeded": "أدخل مبلغًا أكبر من صفر.",
  "issue.card.amountRange": "من {min} إلى {max}",
  "issue.card.byCard": "بطاقة",
  "issue.card.cash": "نقدًا",
  "issue.card.dateAhead": "اختر يومًا من الغد فصاعدًا.",
  "issue.card.emailNeeded": "أدخل بريدًا إلكترونيًا، أو اختر عدم الإرسال.",
  "issue.card.issued": "تم إصدار بطاقة الهدية",
  "issue.card.message": "رسالة",
  "issue.card.messageLeft": "{n} من {max}",
  "issue.card.notSent": "لم تُرسَل",
  "issue.card.other": "أخرى",
  "issue.card.paidBy": "طريقة الدفع",
  "issue.card.paidHint": "تُسجَّل كمبيعة عند الشباك · لا يُخصم شيء هنا",
  "issue.card.paused": "يجري الآن جلب بطاقات الهدايا من الكاشير. حاول مرة أخرى بعد انتهاء ذلك.",
  "issue.card.queuedFor": "في قائمة الانتظار ليوم {date}",
  "issue.card.queuedNow": "في قائمة الانتظار الآن",
  "issue.card.save": "إصدار البطاقة",
  "issue.card.send": "الإرسال",
  "issue.card.sendDay": "تُرسَل يوم",
  "issue.card.sendNone": "لا ترسلها، سأطبعها",
  "issue.card.sendNow": "الآن",
  "issue.card.sendOn": "في تاريخ محدد",
  "issue.card.sending": "جارٍ الإرسال",
  "issue.done": "تم",
  "issue.email": "البريد الإلكتروني",
  "issue.emailWrong": "هذا ليس عنوان بريد إلكتروني.",
  "issue.expires": "تُستخدم قبل",
  "issue.expiresAhead": "اختر اليوم أو يومًا لاحقًا.",
  "issue.expiresHint": "اتركه فارغًا لقسيمة لا تنتهي صلاحيتها.",
  "issue.fixes": "{n, plural, zero {لا شيء يحتاج} one {أمر واحد يحتاج} two {أمران يحتاجان} few {# أمور تحتاج} many {# أمرًا تحتاج} other {# أمر تحتاج}} إلى تصحيح",
  "issue.for": "إلى",
  "issue.from": "من",
  "issue.never": "لا تنتهي صلاحيتها",
  "issue.notAllowed": "دورك لا يسمح بالإصدار.",
  "issue.note": "ملاحظة",
  "issue.noteHint": "للموظفين فقط.",
  "issue.print": "طباعة",
  "issue.result.code": "الكود",
  "issue.result.noCode": "المدير يستطيع قراءة كودها.",
  "issue.result.once": "الكود الكامل يُعرض هذه المرة فقط.",
  "issue.subtitle": "بطاقة هدية أو قسيمة أو دفعة أكواد",
  "issue.tab.batch": "دفعة أكواد",
  "issue.tab.card": "بطاقة هدية",
  "issue.tab.voucher": "قسيمة",
  "issue.tabs": "ما الذي تصدره",
  "issue.title": "إصدار",
  "issue.voucher.bearer": "أيّ من يحملها",
  "issue.voucher.emailNeeded": "القسيمة الصادرة لشخص محدد تحتاج إلى بريده الإلكتروني.",
  "issue.voucher.holder": "الاسم",
  "issue.voucher.issued": "تم إصدار القسيمة",
  "issue.voucher.name": "اسم القسيمة",
  "issue.voucher.nameHint": "ما يراه العميل، على القسيمة وعلى طلبه.",
  "issue.voucher.nameNeeded": "اكتب اسم القسيمة.",
  "issue.voucher.named": "شخص محدد",
  "issue.voucher.namedHint": "هذا العميل فقط، مسجّل الدخول أو يحدده الموظفون بالاسم",
  "issue.voucher.packIssued": "تم إصدار الباقة",
  "issue.voucher.save": "إصدار القسيمة",
  "issue.why": "السبب",
  "issue.whyNeeded": "اذكر السبب.",
  "issue.worth.amount": "مبلغ",
  "issue.worth.amountHint": "تخصم هذا المبلغ من الطلب",
  "issue.worth.amountValue": "المبلغ",
  "issue.worth.change": "تغيير",
  "issue.worth.choose": "اختر…",
  "issue.worth.label": "القيمة",
  "issue.worth.noTables": "لا شيء هنا يحدد بعد ما تبيعه سطوره.",
  "issue.worth.noTablesBody": "أضف قاعدة ضمن «قواعد العروض» أولًا.",
  "issue.worth.noneFound": "لم يُعثر على شيء.",
  "issue.worth.pack": "باقة",
  "issue.worth.packHint": "عدد من مرات الاستخدام لشيء واحد محدد",
  "issue.worth.percent": "نسبة",
  "issue.worth.percentHint": "تخصم هذه النسبة من الطلب",
  "issue.worth.percentMax": "النسبة 100 على الأكثر.",
  "issue.worth.percentValue": "النسبة",
  "issue.worth.search": "ابحث بالاسم",
  "issue.worth.table": "من",
  "issue.worth.thing": "شيء واحد",
  "issue.worth.thingHint": "تدفع ثمن شيء واحد محدد",
  "issue.worth.thingNeeded": "اختر ما تخصّه.",
  "issue.worth.uses": "مرات الاستخدام",
  "issue.worth.usesHint": "من 2 إلى 50",
  "issue.worth.usesRange": "الباقة فيها من 2 إلى 50 مرة استخدام.",
  "issue.worth.valueNeeded": "أدخل قيمة أكبر من صفر.",
  "issue.worth.what": "ما تخصّه"
};

export const rules: Readonly<Record<string, string>> = {
  "rules.add": "إضافة قاعدة",
  "rules.edit": "تعديل",
  "rules.from": "من {app}",
  "rules.holding": "{rows, plural, zero {لا صفوف تحجز} one {صف واحد يحجز} two {صفان يحجزان} few {# صفوف تحجز} many {# صفًا تحجز} other {# صف تحجز}} مرة استخدام أو عملية دفع ببطاقة.",
  "rules.inFile": "تم تحديد هذه القاعدة في ملف المشروع. غيّرها هناك.",
  "rules.kind.discounts": "يقبل الخصومات",
  "rules.kind.moved": "جُلبت إليه بطاقات هدايا أقدم",
  "rules.kind.pays": "يقبل بطاقة هدية كوسيلة دفع",
  "rules.kind.refunds": "يعيد مبلغًا دُفع ببطاقة",
  "rules.kind.sellsCards": "يبيع بطاقة هدية أو يعيد شحنها",
  "rules.kind.sellsVouchers": "يبيع قسيمة أو باقة",
  "rules.kind.uses": "يسجّل ما استُخدم",
  "rules.kindHint.discounts": "طلبات، حجوزات، تذاكر: أي شيء يمكن أن يخفّضه خصم أو كود.",
  "rules.kindHint.pays": "جدول مدفوعات، يمكن أن يذكر الصف فيه بطاقة هدية.",
  "rules.kindHint.sellsCards": "جدول سطور بيع، يمكن أن يذكر السطر فيه البطاقة التي يشحنها.",
  "rules.kindHint.sellsVouchers": "جدول سطور بيع، يمكن أن يذكر السطر فيه القسيمة التي يبيعها.",
  "rules.make.amounts": "أنشئه: دع Adminium يضيف المبلغ والإجمالي الفرعي والتخفيض والإجمالي، والقواعد التي تحسبها",
  "rules.make.codes": "أنشئه: أضف جدولًا للأكواد المكتوبة على الصف",
  "rules.make.column": "{column} في {table}",
  "rules.make.save": "أضف هذه واحفظ",
  "rules.make.table": "الجدول {table}",
  "rules.make.title": "سيضيف Adminium هذا مع القاعدة",
  "rules.none.body": "التطبيق الذي يقبل الخصومات أو بطاقات الهدايا يأتي بقواعده معه. لجدول من جداولك، أضف قاعدة.",
  "rules.none.title": "لا جدول له علاقة بالعروض بعد",
  "rules.on": "مفعّلة",
  "rules.part.back": "يُتراجع عنه",
  "rules.part.balanceAfter": "ما تحمله البطاقة بعد ذلك",
  "rules.part.cardLoads": "بطاقة الهدية التي يشحنها",
  "rules.part.cardPays": "بطاقة الهدية التي تدفع",
  "rules.part.category": "فئته، إن ذكر السطر فئة",
  "rules.part.final": "الصف نهائي",
  "rules.part.finalHint": "عندها يُسجَّل ما استُخدم، ولا يُحسب السعر مرة أخرى أبدًا.",
  "rules.part.item": "ما يبيعه السطر",
  "rules.part.lineDiscount": "تخفيض السطر",
  "rules.part.lines": "سطوره صفوف في",
  "rules.part.load": "المبلغ الذي يشحنه",
  "rules.part.orderDiscount": "تخفيض الصف نفسه",
  "rules.part.paid": "ما دفعته البطاقة",
  "rules.part.price": "سعر السطر",
  "rules.part.quantity": "كمية السطر",
  "rules.part.refundAmount": "المبلغ المُعاد",
  "rules.part.refundRow": "رابطه إلى عملية الدفع",
  "rules.part.refunds": "المبلغ المُعاد صف في",
  "rules.part.sold": "السعر الذي بيع به",
  "rules.part.taxLater": "تُحتسب الضريبة عند استخدامه",
  "rules.part.total": "إجمالي الصف",
  "rules.part.type": "نوعه، إن ذكر السطر نوعًا",
  "rules.part.undone": "يُعاد ما استُخدم",
  "rules.part.voucher": "القسيمة التي يبيعها",
  "rules.part.whenLoads": "تُشحن البطاقة",
  "rules.part.whenPays": "تدفع البطاقة",
  "rules.part.whenSold": "تُباع القسيمة",
  "rules.part.written": "يكتبه Adminium.",
  "rules.point.create": "يُنشأ الصف",
  "rules.point.in": "يصبح {column} {values}",
  "rules.point.never": "أبدًا",
  "rules.point.set": "تُحدَّد قيمة {column}",
  "rules.point.to": "ينتقل إلى {states}",
  "rules.readOnly": "لا يغيّر هذه إلا من يُسمح له بتغيير طريقة حساب Adminium لأعمدة الجدول.",
  "rules.remove": "إزالة القاعدة",
  "rules.remove.confirm": "هل تزيل هذه القاعدة؟ صفوف هذا الجدول لن تعود لها علاقة بالعروض.",
  "rules.removed": "أُزيلت القاعدة من {table}",
  "rules.removedPart": "أُزيلت القاعدة من {table}. {why}",
  "rules.saved": "حُفظت قاعدة {table}",
  "rules.saved.new": "أُضيفت قاعدة لـ {table}",
  "rules.says.back": "يُتراجع عنه عندما {when}.",
  "rules.says.discounts": "تُحسب الخصومات والأكواد لكل صف، سطرًا سطرًا من {lines}.",
  "rules.says.moved": "بطاقات الهدايا التي كانت محفوظة هنا من قبل جُلبت. يتم هذا مرة واحدة، ويقوم به Adminium.",
  "rules.says.noColumn": "لا عمود",
  "rules.says.noUses": "ما استُخدم لا يُسجَّل: الحدود حسب مرات الاستخدام غير مطبّقة.",
  "rules.says.pays": "الصف الذي يذكر بطاقة هدية في {card} يُدفع من البطاقة عندما {when}؛ وما دفعته البطاقة يُكتب في {amount}.",
  "rules.says.refunds": "الصف يعيد {amount} إلى البطاقة التي دفعت، عندما {when}.",
  "rules.says.sellsCards": "الصف الذي يذكر بطاقة هدية في {card} يضع عليها {amount} عندما {when}.",
  "rules.says.sellsVouchers": "الصف الذي يذكر قسيمة في {voucher} يحدّدها كمباعة عندما {when}.",
  "rules.says.uses": "ما استُخدم يُسجَّل عندما {when}، ويُعاد عندما {back}.",
  "rules.says.usesAlone": "ما استُخدم يُسجَّل عندما {when}، مع أن هذا الجدول لا يقبل الخصومات الآن. أزلها، أو أضف القاعدة من جديد.",
  "rules.says.usesKept": "يُسجَّل ما استُخدم عندما {when}، ولا يُعاد أبدًا.",
  "rules.sheet.add": "إضافة قاعدة",
  "rules.sheet.cannotMake": "لا يستطيع Adminium إضافة ما ينقص هنا: {reasons}",
  "rules.sheet.chooseColumn": "اختر عمودًا",
  "rules.sheet.chooseTable": "اختر جدولًا",
  "rules.sheet.edit": "تعديل القاعدة",
  "rules.sheet.err.needed": "اختر عمودًا.",
  "rules.sheet.err.part": "اختر عمودًا، أو دع Adminium يضيفه.",
  "rules.sheet.err.refunds": "اختر الرابط إلى عملية الدفع والمبلغ أيضًا.",
  "rules.sheet.err.table": "اختر جدولًا",
  "rules.sheet.err.when": "أكمل كل «متى» اخترته",
  "rules.sheet.err.whenNeeded": "اختر متى، وأكمله.",
  "rules.sheet.kind": "ما يفعله الجدول",
  "rules.sheet.noCardLink": "هذا الجدول ليس له رابط إلى «بطاقات الهدايا». أضف رابطًا أولًا، ضمن أعمدة الجدول.",
  "rules.sheet.noLines": "لا جدول يرتبط بهذا الجدول. الجدول الذي يقبل الخصومات يحتاج إلى جدول سطور.",
  "rules.sheet.noRefunds": "لا جدول للمبالغ المُعادة",
  "rules.sheet.noVoucherLink": "هذا الجدول ليس له رابط إلى «القسائم». أضف رابطًا أولًا، ضمن أعمدة الجدول.",
  "rules.sheet.notNeeded": "غير مطلوب",
  "rules.sheet.one": "واحد لكلٍّ",
  "rules.sheet.reads": "تُقرأ هكذا",
  "rules.sheet.save": "حفظ القاعدة",
  "rules.sheet.table": "الجدول",
  "rules.subtitle": "علاقة جداولك بالخصومات والقسائم وبطاقات الهدايا",
  "rules.switchedOff": "أُوقفت قاعدة {table}",
  "rules.switchedOn": "شُغّلت قاعدة {table}",
  "rules.title": "قواعد العروض",
  "rules.unavailable": "لا يمكن تشغيل هذه القاعدة الآن: Offers متوقف أو لا يرد.",
  "rules.when.becomes": "عندما يصبح عمود",
  "rules.when.column": "{label}: أي عمود",
  "rules.when.create": "عند إنشاء الصف",
  "rules.when.moves": "عندما ينتقل {table} إلى",
  "rules.when.never": "أبدًا",
  "rules.when.set": "عند تحديد قيمة عمود",
  "rules.yours": "جدولك"
};
