/** Czech strings for the Offers screens. Keys are those of en-US.ts. */
export const shared: Readonly<Record<string, string>> = {
  "shared.cancel": "Zrušit",
  "shared.close": "Zavřít",
  "shared.failed.title": "Tohle se nepodařilo načíst",
  "shared.loading": "Načítání",
  "shared.refused.body": "Pokud to potřebujete, požádejte vedoucího.",
  "shared.refused.title": "K otevření nemáte oprávnění",
  "shared.retry": "Zkusit znovu"
};

export const refusal: Readonly<Record<string, string>> = {
  "refusal.askManager": "Požádejte vedoucího.",
  "refusal.askToPrint": "Požádejte vedoucího, aby to vytiskl.",
  "refusal.batchFull": "Tato série už má všechny své kódy.",
  "refusal.cardPaysCard": "Tabulka, která prodává dárkové karty, nemůže zároveň přijímat dárkovou kartu jako platbu.",
  "refusal.codeTaken": "Tento kód už používá jiná sleva.",
  "refusal.conflict": "Někdo jiný to ve stejnou chvíli změnil. Nic se neuložilo. Zkuste to znovu.",
  "refusal.empty": "Na kartě tolik není.",
  "refusal.emptyLeft": "Na kartě zbývá {left}. Odeberte {left} nebo méně.",
  "refusal.expired": "Platnost už vypršela. Nic se neuložilo.",
  "refusal.forbidden": "K tomuto kroku nemáte oprávnění.",
  "refusal.inactive": "Tato karta ještě není prodaná. Nelze ji použít.",
  "refusal.noAnswer": "Offers neodpovědělo. Nic se neuložilo.",
  "refusal.noPrint": "Tohle teď nelze vytisknout.",
  "refusal.notAllowed": "Tohle zde není povoleno.",
  "refusal.notFound": "Tohle už tu není.",
  "refusal.off": "Offers je teď vypnuté.",
  "refusal.other": "Tohle se nepodařilo uložit. Zkuste to znovu.",
  "refusal.overLimit": "To je nad limit. Nic se neuložilo.",
  "refusal.rate": "Příliš mnoho pokusů. Počkejte minutu.",
  "refusal.receiptOpen": "{rows, plural, one {# záznam drží} few {# záznamy drží} many {# záznamu drží} other {# záznamů drží}} použití nebo platbu kartou: nejdřív je vraťte zpět.",
  "refusal.usedUp": "Všechna použití jsou vyčerpána. Nic se neuložilo.",
  "refusal.void": "Tohle bylo zrušeno. Nic se neuložilo."
};

export const discounts: Readonly<Record<string, string>> = {
  "discounts.aGroup": "Skupina zákazníků",
  "discounts.all": "Všechny slevy",
  "discounts.allDay": "Celý den",
  "discounts.anyone": "Kdokoli",
  "discounts.applies.lines": "Jen tyto položky",
  "discounts.applies.linesHint": "Položky, kategorie nebo typy",
  "discounts.applies.order": "Celá objednávka",
  "discounts.applies.orderHint": "Vše, co je v košíku",
  "discounts.applies.orderNo": "Tento druh potřebuje položky, ze kterých lze vybírat",
  "discounts.budget": "Zastavit, až bude poskytnuto tolik",
  "discounts.changeItems": "Změnit",
  "discounts.check.amount": "Zadejte částku, například 5.00.",
  "discounts.check.buy": "Zadejte číslo od 2 do 10.",
  "discounts.check.code": "Zadejte kód, nebo si ho nechte vytvořit.",
  "discounts.check.count": "Zadejte celé číslo, 1 nebo více.",
  "discounts.check.hours": "Zadejte oba časy, nebo zapněte Celý den.",
  "discounts.check.hoursOrder": "Čas Do musí být později než čas Od.",
  "discounts.check.name": "Dejte slevě název, který váš tým pozná.",
  "discounts.check.noSteps": "Přidejte alespoň jeden stupeň.",
  "discounts.check.percent": "Zadejte procento od 1 do 100.",
  "discounts.check.price": "Zadejte cenu, například 10.00.",
  "discounts.check.publicName": "Doplňte řádek, který zákazníci uvidí na účtence.",
  "discounts.check.stepFrom": "Každý stupeň musí začínat na 2 nebo výše.",
  "discounts.check.stepMore": "Dejte větší slevu než u předchozího stupně ({n} %).",
  "discounts.check.stepRising": "Každý stupeň začíná výš než ten předchozí ({n} ks).",
  "discounts.check.targets": "Vyberte alespoň jednu položku, kategorii nebo typ.",
  "discounts.check.until": "Datum Do je před datem Od, takže se sleva nikdy neuplatní. Vyberte den Od nebo pozdější.",
  "discounts.check.usesTaken": "Už je využito {n}. Zadejte {n} nebo více.",
  "discounts.chooseItems": "Vybrat položky",
  "discounts.code": "Kód",
  "discounts.codeHint": "Písmena a číslice. Zákazníci ho zadají při placení nebo řeknou u pokladny.",
  "discounts.codeMade": "Vytvořen kód {code}",
  "discounts.col.given": "Poskytnuto",
  "discounts.col.gives": "Co dává",
  "discounts.col.limits": "Limity",
  "discounts.col.name": "Název",
  "discounts.col.starts": "Jak se spouští",
  "discounts.col.status": "Stav",
  "discounts.col.uses": "Použití",
  "discounts.combinable": "Lze kombinovat",
  "discounts.combineOff": "Použije se samostatně, a jen když dá víc než ostatní dohromady.",
  "discounts.combineOn": "Přičte se k ostatním kombinovatelným slevám na téže objednávce.",
  "discounts.count": "{n, plural, one {# sleva} few {# slevy} many {# slevy} other {# slev}} · použití a poskytnutá částka k dnešnímu dni",
  "discounts.days": "Dny v týdnu",
  "discounts.daysHint": "Když nevyberete žádný, platí každý den.",
  "discounts.each": "za kus",
  "discounts.empty.body": "Sleva něco odečte z objednávky sama, po zadání kódu, nebo když ji poskytne personál.",
  "discounts.empty.title": "Zatím žádné slevy",
  "discounts.end.body": "Okamžitě se přestane uplatňovat.",
  "discounts.end.title": "Ukončit slevu {name} nyní?",
  "discounts.endNow": "Ukončit nyní",
  "discounts.ended.body": "Spusťte ji znovu s pozdějším datem Do.",
  "discounts.ended.title": "Tato sleva skončila",
  "discounts.endedNow": "Sleva {name} skončila",
  "discounts.fewerLanguages": "Méně jazyků",
  "discounts.firstOrder": "Jen první objednávka",
  "discounts.fix": "Před uložením opravte {n, plural, one {# věc} few {# věci} many {# věci} other {# věcí}}",
  "discounts.fixes": "Před uložením je třeba opravit {n, plural, one {# věc} few {# věci} many {# věci} other {# věcí}}.",
  "discounts.from": "Od",
  "discounts.fromHint": "Od začátku toho dne, podle času provozovny.",
  "discounts.fromTime": "Od, ve tvaru 09:00",
  "discounts.givenSoFar": "Dosud poskytnuto {amount}",
  "discounts.gives.amount": "Sleva {amount}",
  "discounts.gives.amountOn": "Sleva {amount}: {what}",
  "discounts.gives.bonus": "{buy} za cenu {pay}",
  "discounts.gives.bonusOn": "{buy} za cenu {pay}: {what}",
  "discounts.gives.percent": "Sleva {n} %",
  "discounts.gives.percentOn": "Sleva {n} %: {what}",
  "discounts.gives.price": "{amount} za kus",
  "discounts.gives.priceOn": "{what}: {amount} za kus",
  "discounts.gives.steps": "Čím větší nákup, tím větší sleva",
  "discounts.gives.stepsOn": "Čím větší nákup, tím větší sleva: {what}",
  "discounts.group": "Skupina zákazníků",
  "discounts.hoursHint": "Hodiny nemohou přesáhnout půlnoc.",
  "discounts.houseRule": "Zákazníci dostanou všechny kombinovatelné slevy, jeden kód a jinak tu jednu nejvýhodnější.",
  "discounts.kind.amount": "Sleva částkou",
  "discounts.kind.bonus": "2 za cenu 1 a podobně",
  "discounts.kind.percent": "Sleva v procentech",
  "discounts.kind.price": "Pevná cena",
  "discounts.kind.steps": "Cena podle množství",
  "discounts.leave.body": "Vaše změny se ztratí.",
  "discounts.leave.go": "Odejít",
  "discounts.leave.stay": "Pokračovat v úpravách",
  "discounts.leave.title": "Odejít bez uložení?",
  "discounts.limit.first": "jen první objednávka",
  "discounts.limit.from": "od {amount}",
  "discounts.limit.perCustomer": "{n} na zákazníka",
  "discounts.limit.until": "do {date}",
  "discounts.limit.uses": "{n, plural, one {# použití} few {# použití} many {# použití} other {# použití}}",
  "discounts.lookAlike": "Kód {typed} se čte podobně jako {code} ({name}). Zákazníci si je mohou splést.",
  "discounts.makeCode": "Vytvořit kód za mě",
  "discounts.maxUses": "Použití celkem",
  "discounts.minQty": "Minimální množství",
  "discounts.minQtyHint": "Toho, na co se sleva vztahuje.",
  "discounts.minSpend": "Minimální útrata",
  "discounts.minSpendHint": "Za zboží, po slevách, které přicházejí před ní.",
  "discounts.missing": "Tato sleva tu není",
  "discounts.missingBody": "Možná byla odstraněna, nebo ji nemůžete vidět.",
  "discounts.more": "Více",
  "discounts.moreCodes": "Tato sleva má více kódů ({n}). Ostatní najdete v části Kódy.",
  "discounts.moreLanguages": "Více jazyků",
  "discounts.name": "Název (interní)",
  "discounts.never": "Nikdy se nemůže uplatnit",
  "discounts.new": "Nová sleva",
  "discounts.newTitle": "Nová sleva",
  "discounts.noMap": "Nepodařilo se načíst, co vaše tabulky prodávají, takže nelze vybrat položky ani slevu vyzkoušet.",
  "discounts.noTables": "Zatím tu nic neuvádí, co se na jeho řádcích prodává. Nejdřív přidejte pravidlo v části Pravidla nabídek.",
  "discounts.notLive": "Zatím neběží",
  "discounts.pause": "Pozastavit",
  "discounts.pauseUnsaved": "Pozastavit (vaše změny nejsou uloženy)",
  "discounts.paused": "Sleva {name} je pozastavena",
  "discounts.perCustomer": "Použití na zákazníka",
  "discounts.pick.addTag": "Přidat",
  "discounts.pick.chosen": "Vybráno: {n}",
  "discounts.pick.done": "Hotovo",
  "discounts.pick.none": "Tomuto hledání nic neodpovídá.",
  "discounts.pick.search": "Hledat",
  "discounts.pick.subtitle": "Z tabulek, které podle Pravidel nabídek přijímají slevy.",
  "discounts.pick.tabCount": "{label} · {n}",
  "discounts.pick.tabs": "Odkud vybírat",
  "discounts.pick.tag": "Štítek, tak jak je napsán na řádku",
  "discounts.pick.tags": "Štítky",
  "discounts.pick.title": "Vyberte, na co se vztahuje",
  "discounts.pill.active": "Aktivní",
  "discounts.pill.draft": "Koncept",
  "discounts.pill.ended": "Ukončeno",
  "discounts.pill.paused": "Pozastaveno",
  "discounts.pill.usedUp": "Vyčerpáno",
  "discounts.publicName": "Co vidí zákazníci",
  "discounts.publicNameHint": "Řádek na účtence.",
  "discounts.publicNameIn": "Co vidí zákazníci · {language}",
  "discounts.ranAgain": "Sleva {name} znovu běží do {date}",
  "discounts.readOnly": "Tuto slevu si můžete přečíst. Změnit ji může vedoucí.",
  "discounts.resume": "Obnovit",
  "discounts.resumeUnsaved": "Obnovit (vaše změny nejsou uloženy)",
  "discounts.resumed": "Sleva {name} znovu běží",
  "discounts.run.ahead": "Vyberte dnešek nebo pozdější den.",
  "discounts.run.hint": "Poběží do konce toho dne.",
  "discounts.run.title": "Spustit slevu {name} znovu",
  "discounts.run.until": "Do",
  "discounts.runAgain": "Spustit znovu",
  "discounts.save": "Uložit",
  "discounts.saveDraft": "Uložit koncept",
  "discounts.saved": "Sleva {name} uložena",
  "discounts.section.applies": "Na co se vztahuje",
  "discounts.section.combine": "S ostatními slevami",
  "discounts.section.gives": "Co dává",
  "discounts.section.limits": "Limity",
  "discounts.section.name": "Název",
  "discounts.section.starts": "Jak se spouští",
  "discounts.section.when": "Kdy",
  "discounts.section.who": "Kdo ji dostane",
  "discounts.signedInOnly": "Jen přihlášenému zákazníkovi nebo tomu, koho uvede váš personál. Hosté ji nedostanou.",
  "discounts.staffNote": "Zobrazí se v seznamu slev na pokladně. Limity personálu a důvody platí dál.",
  "discounts.starts.code": "Kód",
  "discounts.starts.codes": "Kódy: {n}",
  "discounts.starts.itself": "Sama",
  "discounts.starts.itselfHint": "Uplatní se, když objednávka vyhovuje",
  "discounts.starts.staff": "Jen personál",
  "discounts.starts.staffHint": "Vybírá se na pokladně",
  "discounts.starts.staffOnly": "Poskytnout ji může jen personál",
  "discounts.starts.withCode": "Kódem",
  "discounts.starts.withCodeHint": "Zákazník zadá kód",
  "discounts.steps.add": "Přidat stupeň",
  "discounts.steps.from": "Od",
  "discounts.steps.off": "Sleva v procentech",
  "discounts.steps.remove": "Odebrat tento stupeň",
  "discounts.steps.rule": "Čím víc zákazník koupí toho, na co se sleva vztahuje, tím větší slevu dostane. Počítá se nejvyšší dosažený stupeň.",
  "discounts.switchOn": "Zapnout",
  "discounts.switchedOn": "Sleva {name} je zapnuta",
  "discounts.targets.more": "{first} a další ({n})",
  "discounts.title": "Slevy",
  "discounts.toTime": "Do, ve tvaru 17:00",
  "discounts.totals": "{uses, plural, one {# použití} few {# použití} many {# použití} other {# použití}} · poskytnuto {given}",
  "discounts.try.asIfOn": "Koncept se zkouší, jako by byl zapnutý.",
  "discounts.try.bar": "Vyzkoušet · {n, plural, one {# sleva} few {# slevy} many {# slevy} other {# slev}}",
  "discounts.try.barTotal": "Vyzkoušet · {n, plural, one {# sleva} few {# slevy} many {# slevy} other {# slev}} · {total}",
  "discounts.try.better": "Místo ní se použila sleva {name}: dává víc.",
  "discounts.try.buyer": "Kdo nakupuje",
  "discounts.try.code": "Kód při placení",
  "discounts.try.customer": "Přihlášený zákazník",
  "discounts.try.draftName": "{name} (koncept)",
  "discounts.try.failed": "Tohle se nepodařilo vyzkoušet",
  "discounts.try.guest": "Host",
  "discounts.try.minus": "−{amount}",
  "discounts.try.noCode": "Bez kódu",
  "discounts.try.noRows": "Zatím tam není nic uloženo.",
  "discounts.try.none": "Slevy zatím nic nepřijímá",
  "discounts.try.noneBody": "Určete, která z vašich tabulek přijímá slevy, a tuto slevu půjde vyzkoušet na jejích záznamech.",
  "discounts.try.notApplied": "Neuplatnilo se",
  "discounts.try.nothing": "Na tuto objednávku se nevztahuje žádná sleva.",
  "discounts.try.off": "Odečteno z objednávky",
  "discounts.try.refused": "{code}: {why}",
  "discounts.try.row": "Vyzkoušeno na",
  "discounts.try.rowHint": "Uložený záznam tabulky {table}",
  "discounts.try.rules": "Pravidla nabídek",
  "discounts.try.taxLater": "Daň se přičte při uložení objednávky",
  "discounts.try.title": "Vyzkoušet",
  "discounts.try.total": "Celkem",
  "discounts.try.unnamed": "Sleva",
  "discounts.try.whyNot": "{name} — {why}",
  "discounts.until": "Do (nepovinné)",
  "discounts.untilHint": "Do konce toho dne, podle času provozovny.",
  "discounts.usedUp.body": "Jen ke čtení, dokud nezvýšíte limit.",
  "discounts.usedUp.raise": "Zvýšit limit",
  "discounts.usedUp.title": "Všechna použití ({n}) jsou vyčerpána",
  "discounts.usesSoFar": "Použito: {n}",
  "discounts.value.amount": "Sleva částkou",
  "discounts.value.amountHint": "Nikdy víc, než kolik stojí to, na co se vztahuje.",
  "discounts.value.buy": "Kupte",
  "discounts.value.cheaper": "Ten levnější zaplatíme my.",
  "discounts.value.cheapest": "Ten nejlevnější zaplatíme my.",
  "discounts.value.percent": "Sleva v procentech",
  "discounts.value.price": "Prodejní cena za kus",
  "discounts.value.priceHint": "Položky, které už stojí méně, si svou cenu ponechají.",
  "discounts.why.alone": "jiná sleva dává víc a tato se používá samostatně",
  "discounts.why.cancelled": "byla zrušena",
  "discounts.why.days": "v tento den neplatí",
  "discounts.why.draft": "je to koncept",
  "discounts.why.ended": "už skončila",
  "discounts.why.first": "nejde o první objednávku",
  "discounts.why.group": "zákazník není v její skupině",
  "discounts.why.hours": "v tuto denní dobu neplatí",
  "discounts.why.items": "na objednávce není nic, na co se vztahuje",
  "discounts.why.limit": "překročen limit",
  "discounts.why.minimum": "objednávka nedosahuje minimální útraty",
  "discounts.why.noCode": "potřebuje svůj kód",
  "discounts.why.notYet": "ještě nezačala",
  "discounts.why.paused": "je pozastavena",
  "discounts.why.quantity": "není dost toho, na co se vztahuje",
  "discounts.why.signIn": "potřebuje přihlášeného zákazníka",
  "discounts.why.unknown": "zde se neuplatní",
  "discounts.why.usedUp": "všechna použití jsou vyčerpána"
};

export const lookup: Readonly<Record<string, string>> = {
  "lookup.addCredit": "Přidat kredit",
  "lookup.added": "Přidáno {amount}",
  "lookup.adjust": "Upravit",
  "lookup.askManager": "Dobít, upravit nebo zrušit ji může vedoucí.",
  "lookup.batch": "Série",
  "lookup.cancelCard": "Zrušit kartu",
  "lookup.cancelled": "Karta končící na {last4} je zrušena",
  "lookup.code": "Kód",
  "lookup.col.amount": "Částka",
  "lookup.col.date": "Datum",
  "lookup.col.leftAfter": "Zůstatek poté",
  "lookup.col.what": "Co",
  "lookup.col.where": "Kde",
  "lookup.creditGiven": "Kredit {amount} připsán na adresu {address}",
  "lookup.dialog.add": "Přidat",
  "lookup.dialog.adjust": "Upravit kartu končící na {last4}",
  "lookup.dialog.amount": "Částka",
  "lookup.dialog.amountNeeded": "Zadejte částku vyšší než nula.",
  "lookup.dialog.byCard": "Kartou",
  "lookup.dialog.cancel": "Zrušit kartu končící na {last4}?",
  "lookup.dialog.cancelBody": "Zbývající zůstatek už nepůjde utratit. Tuto akci nelze vrátit zpět.",
  "lookup.dialog.cash": "Hotově",
  "lookup.dialog.credit": "Připsat kredit na adresu {address}",
  "lookup.dialog.creditMail": "Zákazník se to dozví e-mailem.",
  "lookup.dialog.creditMore": "Přidat kredit na adresu {address}",
  "lookup.dialog.direction": "Přidat, nebo odebrat",
  "lookup.dialog.movesTo": "Platnost se posune na {date}",
  "lookup.dialog.other": "Jinak",
  "lookup.dialog.paidBy": "Zaplaceno",
  "lookup.dialog.paidHint": "Zaznamená se jako přijaté u pokladny. Tady se nic nestrhává.",
  "lookup.dialog.remove": "Odebrat",
  "lookup.dialog.topUp": "Dobít kartu končící na {last4}",
  "lookup.dialog.upTo": "Na kartě může být nejvýše {max}.",
  "lookup.dialog.why": "Důvod",
  "lookup.dialog.whyHint": "Uchová se v historii karty.",
  "lookup.dialog.whyNeeded": "Uveďte důvod.",
  "lookup.discount": "Sleva",
  "lookup.failed": "Tohle se nepodařilo vyhledat",
  "lookup.field.empty": "Nejdřív napište nebo naskenujte kód.",
  "lookup.field.label": "Napište nebo naskenujte kód, případně e-mail zákazníka",
  "lookup.field.placeholder": "GC-7K2M-W3HN-Q4XP nebo name@example.com",
  "lookup.for": "Komu",
  "lookup.from": "Od",
  "lookup.giveCredit": "Připsat kredit",
  "lookup.go": "Vyhledat",
  "lookup.issue": "Vystavit",
  "lookup.issued": "Vystaveno",
  "lookup.kind.card": "Dárková karta",
  "lookup.kind.code": "Slevový kód",
  "lookup.kind.credit": "Kredit",
  "lookup.kind.pack": "Balíček",
  "lookup.kind.voucher": "Poukaz",
  "lookup.left": "Zbývá",
  "lookup.leftOf": "{left} z {total}",
  "lookup.markUsed": "Označit jako použitý",
  "lookup.markedUsed": "Označeno jako použité",
  "lookup.moved": "Starší karta · funguje jen u pokladny s obsluhou",
  "lookup.never": "Platnost nekončí",
  "lookup.noActivity": "Zatím se s ní nic nedělo.",
  "lookup.noUses": "Zatím nebylo použito.",
  "lookup.none.address": "Žádný kredit u adresy {typed}",
  "lookup.none.addressBody": "U této adresy není žádný kredit.",
  "lookup.none.code": "Tento kód nic nemá · {typed}",
  "lookup.none.codeBody": "Zkontrolujte znaky a zkuste jiný kód.",
  "lookup.openBatch": "Otevřít sérii",
  "lookup.openDiscount": "Otevřít slevu",
  "lookup.percent": "{n} %",
  "lookup.pill.active": "Aktivní",
  "lookup.pill.cancelled": "Zrušeno",
  "lookup.pill.doesNot": "Teď neplatí",
  "lookup.pill.expired": "Platnost vypršela",
  "lookup.pill.inactive": "Neaktivní",
  "lookup.pill.notSold": "Ještě neprodáno",
  "lookup.pill.notUsed": "Nepoužito",
  "lookup.pill.used": "Použito",
  "lookup.pill.usedUp": "Vyčerpáno",
  "lookup.pill.works": "Platí",
  "lookup.print": "Tisk",
  "lookup.printing": "Otevřeno k tisku",
  "lookup.queued": "Zařazeno k opětovnému odeslání",
  "lookup.queuedFor": "Zařazeno k odeslání: {name}",
  "lookup.removed": "Odebráno {amount}",
  "lookup.row.adjust": "Upraveno",
  "lookup.row.expire": "Platnost vypršela",
  "lookup.row.issue": "Vystaveno",
  "lookup.row.refund": "Vráceno",
  "lookup.row.spend": "Utraceno",
  "lookup.row.topUp": "Dobito",
  "lookup.row.void": "Zrušeno",
  "lookup.said.card": "Dárková karta končící na {last4}, {pill}, zbývá {amount}",
  "lookup.said.cardNoBalance": "Dárková karta končící na {last4}, {pill}",
  "lookup.said.code": "Slevový kód, který platí",
  "lookup.said.codeNot": "Slevový kód, který teď neplatí",
  "lookup.said.credit": "Kredit, {pill}, zbývá {amount}",
  "lookup.said.nothing": "Tento kód nic nemá",
  "lookup.said.pack": "Balíček končící na {last4}, {pill}, zbývá {left} z {total}",
  "lookup.said.voucher": "Poukaz končící na {last4}, {pill}",
  "lookup.sendAgain": "Odeslat znovu",
  "lookup.start.body": "Naskenujte kód na kartě nebo poukazu, nebo ho napište. Kredit najdete podle e-mailu zákazníka.",
  "lookup.start.title": "Zatím nic nevyhledáno",
  "lookup.subtitle": "Dárkové karty, poukazy, balíčky, slevové kódy a kredit",
  "lookup.title": "Vyhledat",
  "lookup.topUp": "Dobít",
  "lookup.toppedUp": "Dobito {amount}",
  "lookup.use.counted": "Použito",
  "lookup.use.givenBack": "Vráceno",
  "lookup.use.held": "Drženo",
  "lookup.useBy": "Platnost do",
  "lookup.useOne": "Použít jedno teď",
  "lookup.useRecorded": "Zaznamenáno 1 použití",
  "lookup.uses": "Použití",
  "lookup.usesLeft": "Zbývající použití",
  "lookup.validUntil": "Platí do",
  "lookup.what": "Co to je",
  "lookup.why.cancelled": "Zrušeno · nelze použít",
  "lookup.why.codeUsedUp": "Všechna použití tohoto kódu jsou vyčerpána",
  "lookup.why.empty": "Nic na ní nezbývá",
  "lookup.why.expired": "Platnost vypršela",
  "lookup.why.expiredOn": "Platnost vypršela {date}",
  "lookup.why.inactive": "Ještě neprodáno · nelze z ní utrácet",
  "lookup.why.notSold": "Ještě neprodáno · nelze použít",
  "lookup.why.off": "Tento kód je vypnutý",
  "lookup.why.used": "Už použito",
  "lookup.why.usedUp": "Všechna použití jsou vyčerpána",
  "lookup.worth": "Hodnota"
};

export const issue: Readonly<Record<string, string>> = {
  "issue.batch.again": "Znovu si je můžete stáhnout v části Série poukazů.",
  "issue.batch.count": "Kolik",
  "issue.batch.countRange": "Od 1 do {max}",
  "issue.batch.download": "Stáhnout kódy (CSV)",
  "issue.batch.expiresNeeded": "Uveďte, kdy kódy přestanou platit.",
  "issue.batch.made": "Vytvořeno kódů: {count}",
  "issue.batch.making": "Vytvářejí se kódy",
  "issue.batch.name": "Název série",
  "issue.batch.nameNeeded": "Pojmenujte sérii.",
  "issue.batch.open": "Otevřít sérii",
  "issue.batch.part": "Vytvořeno {made} z {count}. Dokončete to v části Série poukazů.",
  "issue.batch.progress": "{made} z {count}",
  "issue.batch.readBack": "{count, plural, one {# kód} few {# kódy} many {# kódu} other {# kódů}}, každý platí jednou, do {date}",
  "issue.batch.save": "Vytvořit kódy",
  "issue.card.amount": "Částka",
  "issue.card.amountNeeded": "Zadejte částku vyšší než nula.",
  "issue.card.amountRange": "Od {min} do {max}",
  "issue.card.byCard": "Kartou",
  "issue.card.cash": "Hotově",
  "issue.card.dateAhead": "Vyberte zítřek nebo pozdější den.",
  "issue.card.emailNeeded": "Zadejte e-mail, nebo zvolte, že se karta nepošle.",
  "issue.card.issued": "Dárková karta vystavena",
  "issue.card.message": "Vzkaz",
  "issue.card.messageLeft": "{n} z {max}",
  "issue.card.notSent": "Neodesláno",
  "issue.card.other": "Jinak",
  "issue.card.paidBy": "Zaplaceno",
  "issue.card.paidHint": "Zaznamená se jako prodané u pokladny · Tady se nic nestrhává",
  "issue.card.paused": "Dárkové karty se právě přebírají z pokladny. Zkuste to znovu, až to skončí.",
  "issue.card.queuedFor": "Zařazeno k odeslání na {date}",
  "issue.card.queuedNow": "Zařazeno k odeslání nyní",
  "issue.card.save": "Vystavit kartu",
  "issue.card.send": "Odeslat",
  "issue.card.sendDay": "Odeslat dne",
  "issue.card.sendNone": "Neposílat, vytisknu ji",
  "issue.card.sendNow": "Nyní",
  "issue.card.sendOn": "Ve zvolený den",
  "issue.card.sending": "Odeslání",
  "issue.done": "Hotovo",
  "issue.email": "E-mail",
  "issue.emailWrong": "Tohle není e-mailová adresa.",
  "issue.expires": "Platnost do",
  "issue.expiresAhead": "Vyberte dnešek nebo pozdější den.",
  "issue.expiresHint": "Nechte prázdné u poukazu, jehož platnost nikdy neskončí.",
  "issue.fixes": "Je třeba opravit {n, plural, one {# věc} few {# věci} many {# věci} other {# věcí}}",
  "issue.for": "Komu",
  "issue.from": "Od",
  "issue.never": "Platnost nekončí",
  "issue.notAllowed": "Vaše role nemůže vystavovat.",
  "issue.note": "Poznámka",
  "issue.noteHint": "Vidí ji jen personál.",
  "issue.print": "Tisk",
  "issue.result.code": "Kód",
  "issue.result.noCode": "Jeho kód si může přečíst vedoucí.",
  "issue.result.once": "Celý kód se zobrazí jen teď, jedinkrát.",
  "issue.subtitle": "Dárková karta, poukaz nebo série kódů",
  "issue.tab.batch": "Série kódů",
  "issue.tab.card": "Dárková karta",
  "issue.tab.voucher": "Poukaz",
  "issue.tabs": "Co vystavit",
  "issue.title": "Vystavit",
  "issue.voucher.bearer": "Kdokoli, kdo ho má",
  "issue.voucher.emailNeeded": "Poukaz na jméno potřebuje e-mail dané osoby.",
  "issue.voucher.holder": "Jméno",
  "issue.voucher.issued": "Poukaz vystaven",
  "issue.voucher.name": "Název",
  "issue.voucher.nameHint": "Co zákazník uvidí na poukazu a ve své objednávce.",
  "issue.voucher.nameNeeded": "Uveďte, jak se poukaz jmenuje.",
  "issue.voucher.named": "Konkrétní osoba",
  "issue.voucher.namedHint": "Jen tento zákazník, přihlášený nebo uvedený personálem",
  "issue.voucher.packIssued": "Balíček vystaven",
  "issue.voucher.save": "Vystavit poukaz",
  "issue.why": "Důvod",
  "issue.whyNeeded": "Uveďte důvod.",
  "issue.worth.amount": "Částka",
  "issue.worth.amountHint": "Odečte tuto částku z objednávky",
  "issue.worth.amountValue": "Částka",
  "issue.worth.change": "Změnit",
  "issue.worth.choose": "Vybrat…",
  "issue.worth.label": "Hodnota",
  "issue.worth.noTables": "Zatím tu nic neuvádí, co se na jeho řádcích prodává.",
  "issue.worth.noTablesBody": "Nejdřív přidejte pravidlo v části Pravidla nabídek.",
  "issue.worth.noneFound": "Nic nenalezeno.",
  "issue.worth.pack": "Balíček",
  "issue.worth.packHint": "Několik použití jedné určené věci",
  "issue.worth.percent": "Procento",
  "issue.worth.percentHint": "Odečte tento podíl z objednávky",
  "issue.worth.percentMax": "Procento je nejvýše 100.",
  "issue.worth.percentValue": "Procento",
  "issue.worth.search": "Hledat podle názvu",
  "issue.worth.table": "Z tabulky",
  "issue.worth.thing": "Jedna věc",
  "issue.worth.thingHint": "Zaplatí jednu určenou věc",
  "issue.worth.thingNeeded": "Vyberte, na co platí.",
  "issue.worth.uses": "Použití",
  "issue.worth.usesHint": "Od 2 do 50",
  "issue.worth.usesRange": "Balíček má od 2 do 50 použití.",
  "issue.worth.valueNeeded": "Zadejte hodnotu vyšší než nula.",
  "issue.worth.what": "Na co platí"
};

export const rules: Readonly<Record<string, string>> = {
  "rules.add": "Přidat pravidlo",
  "rules.edit": "Upravit",
  "rules.from": "Z aplikace {app}",
  "rules.holding": "{rows, plural, one {# záznam drží} few {# záznamy drží} many {# záznamu drží} other {# záznamů drží}} použití nebo platbu kartou.",
  "rules.inFile": "Toto pravidlo bylo nastaveno v souboru projektu. Změňte ho tam.",
  "rules.kind.discounts": "Přijímá slevy",
  "rules.kind.moved": "Převzala starší dárkové karty",
  "rules.kind.pays": "Přijímá dárkovou kartu jako platbu",
  "rules.kind.refunds": "Vrací platbu kartou",
  "rules.kind.sellsCards": "Prodává nebo dobíjí dárkovou kartu",
  "rules.kind.sellsVouchers": "Prodává poukaz nebo balíček",
  "rules.kind.uses": "Zaznamenává, co bylo použito",
  "rules.kindHint.discounts": "Objednávky, rezervace, vstupenky: cokoli, co může sleva nebo kód zlevnit.",
  "rules.kindHint.pays": "Tabulka plateb, kde záznam může uvádět dárkovou kartu.",
  "rules.kindHint.sellsCards": "Tabulka prodejních řádků, kde řádek může uvádět kartu, kterou nabíjí.",
  "rules.kindHint.sellsVouchers": "Tabulka prodejních řádků, kde řádek může uvádět poukaz, který prodává.",
  "rules.make.amounts": "Vytvořit: ať Adminium přidá částku, mezisoučet, slevu a celkovou částku i pravidla, která je počítají",
  "rules.make.codes": "Vytvořit: přidat tabulku na kódy zadané u záznamu",
  "rules.make.column": "{column} v tabulce {table}",
  "rules.make.save": "Přidat to a uložit",
  "rules.make.table": "tabulka {table}",
  "rules.make.title": "Adminium spolu s pravidlem přidá toto",
  "rules.none.body": "Aplikace, která přijímá slevy nebo dárkové karty, si svá pravidla přináší sama. K vlastní tabulce přidejte pravidlo.",
  "rules.none.title": "S nabídkami zatím nesouvisí žádná tabulka",
  "rules.on": "Zapnuto",
  "rules.part.back": "Vrací se zpět",
  "rules.part.balanceAfter": "Kolik je na kartě poté",
  "rules.part.cardLoads": "Dárková karta, kterou nabíjí",
  "rules.part.cardPays": "Dárková karta, kterou se platí",
  "rules.part.category": "Jeho kategorie, pokud ji řádek uvádí",
  "rules.part.final": "Záznam je konečný",
  "rules.part.finalHint": "V tu chvíli se zaznamená, co bylo použito, a cena se už nikdy nepřepočítá.",
  "rules.part.item": "Co řádek prodává",
  "rules.part.itemHint": "Odkaz na prodávanou položku. Bez něj se zde sleva na vybrané položky neuplatní; sleva na celou objednávku platí dál.",
  "rules.part.lineDiscount": "Sleva na řádku",
  "rules.part.lines": "Jeho řádky jsou záznamy tabulky",
  "rules.part.load": "Částka, kterou nabíjí",
  "rules.part.orderDiscount": "Vlastní sleva záznamu",
  "rules.part.paid": "Kolik karta zaplatila",
  "rules.part.price": "Cena řádku",
  "rules.part.quantity": "Množství na řádku",
  "rules.part.refundAmount": "Vrácená částka",
  "rules.part.refundRow": "Jeho vazba na platbu",
  "rules.part.refunds": "Vrácené peníze jsou záznamem tabulky",
  "rules.part.sold": "Za kolik se prodal",
  "rules.part.taxLater": "Daň se účtuje až při použití",
  "rules.part.total": "Celková částka záznamu",
  "rules.part.type": "Jeho typ, pokud ho řádek uvádí",
  "rules.part.undone": "Co bylo použito, se vrací",
  "rules.part.voucher": "Poukaz, který prodává",
  "rules.part.whenLoads": "Karta se nabije",
  "rules.part.whenPays": "Karta zaplatí",
  "rules.part.whenSold": "Poukaz se prodá",
  "rules.part.written": "Zapisuje to Adminium.",
  "rules.point.create": "záznam vznikne",
  "rules.point.in": "{column} nabude hodnoty {values}",
  "rules.point.never": "nikdy",
  "rules.point.set": "{column} se vyplní",
  "rules.point.to": "přejde do stavu {states}",
  "rules.readOnly": "Měnit je může jen ten, kdo smí měnit, jak Adminium počítá sloupce tabulky.",
  "rules.remove": "Odebrat pravidlo",
  "rules.remove.confirm": "Odebrat toto pravidlo? Záznamy této tabulky přestanou s nabídkami jakkoli souviset.",
  "rules.removed": "Pravidlo odebráno: {table}",
  "rules.removedPart": "Pravidlo odebráno: {table}. {why}",
  "rules.saved": "Pravidlo uloženo: {table}",
  "rules.saved.new": "Pravidlo přidáno: {table}",
  "rules.says.back": "Vrací se zpět, když {when}.",
  "rules.says.discounts": "Slevy a kódy se počítají u každého záznamu, řádek po řádku z tabulky {lines}.",
  "rules.says.moved": "Dárkové karty, které se dříve vedly zde, byly převzaty. Dělá to Adminium, jen jednou.",
  "rules.says.noColumn": "žádný sloupec",
  "rules.says.noUses": "Co bylo použito, se nezaznamenává: limity podle použití se nehlídají.",
  "rules.says.pays": "Záznam, který uvádí dárkovou kartu ({card}), se z karty zaplatí, když {when}; kolik karta zaplatila, se zapíše sem: {amount}.",
  "rules.says.refunds": "Záznam vrátí částku ({amount}) na kartu, kterou se platilo, když {when}.",
  "rules.says.sellsCards": "Záznam, který uvádí dárkovou kartu ({card}), na ni nabije částku ({amount}), když {when}.",
  "rules.says.sellsVouchers": "Záznam, který uvádí poukaz ({voucher}), ho označí jako prodaný, když {when}.",
  "rules.says.uses": "Co bylo použito, se zaznamená, když {when}, a vrátí, když {back}.",
  "rules.says.usesAlone": "Co bylo použito, se zaznamená, když {when}, ačkoli tato tabulka teď žádné slevy nepřijímá. Odeberte to, nebo pravidlo přidejte znovu.",
  "rules.says.usesKept": "Co bylo použito, se zaznamená, když {when}, a nikdy se nevrací.",
  "rules.sheet.add": "Přidat pravidlo",
  "rules.sheet.cannotMake": "Adminium nemůže přidat, co zde chybí: {reasons}",
  "rules.sheet.chooseColumn": "Vyberte sloupec",
  "rules.sheet.chooseTable": "Vyberte tabulku",
  "rules.sheet.edit": "Upravit pravidlo",
  "rules.sheet.err.needed": "Vyberte sloupec.",
  "rules.sheet.err.part": "Vyberte sloupec, nebo ho nechte přidat Adminium.",
  "rules.sheet.err.refunds": "Vyberte také vazbu na platbu a částku.",
  "rules.sheet.err.table": "Vyberte tabulku",
  "rules.sheet.err.when": "Dokončete každé „kdy“, které jste zvolili",
  "rules.sheet.err.whenNeeded": "Vyberte, kdy, a dokončete to.",
  "rules.sheet.kind": "Co tabulka dělá",
  "rules.sheet.noCardLink": "Tato tabulka nemá vazbu na Dárkové karty. Nejdřív ji přidejte mezi sloupci tabulky.",
  "rules.sheet.noLines": "Na tuto tabulku neodkazuje žádná jiná. Tabulka, která přijímá slevy, potřebuje tabulku řádků.",
  "rules.sheet.noRefunds": "Žádná tabulka vrácených plateb",
  "rules.sheet.noVoucherLink": "Tato tabulka nemá vazbu na Poukazy. Nejdřív ji přidejte mezi sloupci tabulky.",
  "rules.sheet.notNeeded": "Není potřeba",
  "rules.sheet.one": "Vždy jeden kus",
  "rules.sheet.reads": "Čte se takto",
  "rules.sheet.save": "Uložit pravidlo",
  "rules.sheet.table": "Tabulka",
  "rules.subtitle": "Jak vaše vlastní tabulky souvisejí se slevami, poukazy a dárkovými kartami",
  "rules.switchedOff": "Pravidlo vypnuto: {table}",
  "rules.switchedOn": "Pravidlo zapnuto: {table}",
  "rules.title": "Pravidla nabídek",
  "rules.unavailable": "Toto pravidlo teď nemůže běžet: Offers je vypnuté nebo neodpovídá.",
  "rules.when.becomes": "Když sloupec nabude hodnoty",
  "rules.when.column": "{label}: který sloupec",
  "rules.when.create": "Když záznam vznikne",
  "rules.when.moves": "Když {table} přejde do stavu",
  "rules.when.never": "Nikdy",
  "rules.when.set": "Když se sloupec vyplní",
  "rules.yours": "Vaše tabulka"
};
