/** Danish strings for the Offers screens. Keys are those of en-US.ts. */
export const shared: Readonly<Record<string, string>> = {
  "shared.cancel": "Annuller",
  "shared.close": "Luk",
  "shared.failed.title": "Dette kunne ikke indlæses",
  "shared.loading": "Indlæser",
  "shared.refused.body": "Spørg en leder, hvis du har brug for det.",
  "shared.refused.title": "Du har ikke tilladelse til at åbne dette",
  "shared.retry": "Prøv igen"
};

export const refusal: Readonly<Record<string, string>> = {
  "refusal.askManager": "Spørg en leder.",
  "refusal.askToPrint": "Bed en leder om at udskrive den.",
  "refusal.batchFull": "Denne serie har allerede alle sine koder.",
  "refusal.cardPaysCard": "En tabel, der sælger gavekort, kan ikke også tage et gavekort som betaling.",
  "refusal.codeTaken": "Den kode bruges allerede af en anden rabat.",
  "refusal.conflict": "En anden ændrede dette på samme tid. Intet blev gemt. Prøv igen.",
  "refusal.empty": "Der står ikke så meget på kortet.",
  "refusal.emptyLeft": "Der står {left} tilbage på kortet. Træk {left} eller mindre.",
  "refusal.expired": "Dette er udløbet. Intet blev gemt.",
  "refusal.forbidden": "Du har ikke tilladelse til at gøre dette.",
  "refusal.inactive": "Dette kort er ikke solgt endnu. Det kan ikke bruges.",
  "refusal.noAnswer": "Offers kunne ikke svare. Intet blev gemt.",
  "refusal.noPrint": "Dette kan ikke udskrives lige nu.",
  "refusal.notAllowed": "Det er ikke tilladt her.",
  "refusal.notFound": "Dette findes ikke længere.",
  "refusal.off": "Offers er slået fra lige nu.",
  "refusal.other": "Dette kunne ikke gemmes. Prøv igen.",
  "refusal.overLimit": "Det er over grænsen. Intet blev gemt.",
  "refusal.rate": "For mange forsøg. Vent et minut.",
  "refusal.receiptOpen": "{rows, plural, one {# række holder} other {# rækker holder}} på en anvendelse eller en kortbetaling: læg dem tilbage først.",
  "refusal.usedUp": "Alle anvendelser er brugt. Intet blev gemt.",
  "refusal.void": "Dette blev annulleret. Intet blev gemt."
};

export const discounts: Readonly<Record<string, string>> = {
  "discounts.aGroup": "En kundegruppe",
  "discounts.all": "Alle rabatter",
  "discounts.allDay": "Hele dagen",
  "discounts.anyone": "Alle",
  "discounts.applies.lines": "Kun disse varer",
  "discounts.applies.linesHint": "Varer, kategorier eller typer",
  "discounts.applies.order": "Hele ordren",
  "discounts.applies.orderHint": "Alt i kurven",
  "discounts.applies.orderNo": "Denne slags skal have varer at vælge imellem",
  "discounts.budget": "Stop, når så meget er givet",
  "discounts.changeItems": "Skift",
  "discounts.check.amount": "Angiv et beløb som 5.00.",
  "discounts.check.buy": "Angiv et tal fra 2 til 10.",
  "discounts.check.code": "Angiv en kode, eller få lavet en.",
  "discounts.check.count": "Angiv et helt tal, 1 eller mere.",
  "discounts.check.hours": "Angiv begge tidspunkter, eller slå Hele dagen til.",
  "discounts.check.hoursOrder": "Til skal være senere end Fra.",
  "discounts.check.name": "Giv den et navn, dit team kender.",
  "discounts.check.noSteps": "Tilføj mindst ét trin.",
  "discounts.check.percent": "Angiv en procent fra 1 til 100.",
  "discounts.check.price": "Angiv en pris som 10.00.",
  "discounts.check.publicName": "Tilføj den linje, kunderne ser på kvitteringen.",
  "discounts.check.stepFrom": "Lad hvert trin starte ved 2 eller mere.",
  "discounts.check.stepMore": "Giv mere rabat end trinnet før ({n} %).",
  "discounts.check.stepRising": "Hvert trin starter over det forrige ({n} stk.).",
  "discounts.check.targets": "Vælg mindst én vare, kategori eller type.",
  "discounts.check.until": "Til ligger før Fra, så rabatten kan aldrig gælde. Vælg en dato på eller efter Fra.",
  "discounts.check.usesTaken": "{n} er allerede brugt. Angiv {n} eller mere.",
  "discounts.chooseItems": "Vælg varer",
  "discounts.code": "Kode",
  "discounts.codeHint": "Bogstaver og tal. Kunderne skriver den ved betaling eller siger den ved kassen.",
  "discounts.codeMade": "Lavede koden {code}",
  "discounts.col.given": "Givet",
  "discounts.col.gives": "Hvad den giver",
  "discounts.col.limits": "Grænser",
  "discounts.col.name": "Navn",
  "discounts.col.starts": "Hvordan den starter",
  "discounts.col.status": "Status",
  "discounts.col.uses": "Anvendelser",
  "discounts.combinable": "Kan kombineres",
  "discounts.combineOff": "Bruges alene, og kun når den giver mere end de andre tilsammen.",
  "discounts.combineOn": "Lægges oven i andre rabatter, der kan kombineres, på samme ordre.",
  "discounts.count": "{n, plural, one {# rabat} other {# rabatter}} · anvendelser og givet beløb til dato",
  "discounts.days": "Ugedage",
  "discounts.daysHint": "Ingen valgt betyder alle dage.",
  "discounts.each": "pr. stk.",
  "discounts.empty.body": "En rabat trækker noget fra en ordre af sig selv, med en kode, eller når personalet giver den.",
  "discounts.empty.title": "Ingen rabatter endnu",
  "discounts.end.body": "Den holder op med at gælde med det samme.",
  "discounts.end.title": "Afslut {name} nu?",
  "discounts.endNow": "Afslut nu",
  "discounts.ended.body": "Kør den igen med en senere Til-dato.",
  "discounts.ended.title": "Denne rabat er afsluttet",
  "discounts.endedNow": "{name} er afsluttet",
  "discounts.fewerLanguages": "Færre sprog",
  "discounts.firstOrder": "Kun første ordre",
  "discounts.fix": "Ret {n, plural, one {# ting} other {# ting}}, før du gemmer",
  "discounts.fixes": "{n, plural, one {# ting skal} other {# ting skal}} rettes, før du kan gemme.",
  "discounts.from": "Fra",
  "discounts.fromHint": "Fra dagens begyndelse, efter stedets ur.",
  "discounts.fromTime": "Fra, som 09:00",
  "discounts.givenSoFar": "{amount} givet indtil nu",
  "discounts.gives.amount": "{amount} i rabat",
  "discounts.gives.amountOn": "{amount} i rabat på {what}",
  "discounts.gives.bonus": "{buy} for {pay}",
  "discounts.gives.bonusOn": "{buy} for {pay} på {what}",
  "discounts.gives.percent": "{n} % rabat",
  "discounts.gives.percentOn": "{n} % rabat på {what}",
  "discounts.gives.price": "{amount} pr. stk.",
  "discounts.gives.priceOn": "{what} til {amount} pr. stk.",
  "discounts.gives.steps": "Mere rabat, jo mere de køber",
  "discounts.gives.stepsOn": "Mere rabat, jo mere {what} de køber",
  "discounts.group": "Kundegruppe",
  "discounts.hoursHint": "Tidsrummet kan ikke gå over midnat.",
  "discounts.houseRule": "Kunderne får alle rabatter, der kan kombineres, én kode og ellers den bedste enkelte rabat.",
  "discounts.kind.amount": "Beløb i rabat",
  "discounts.kind.bonus": "2 for 1 og lignende",
  "discounts.kind.percent": "Procent i rabat",
  "discounts.kind.price": "Fast pris",
  "discounts.kind.steps": "Pris efter antal",
  "discounts.leave.body": "Det, du har ændret, går tabt.",
  "discounts.leave.go": "Forlad",
  "discounts.leave.stay": "Bliv og rediger",
  "discounts.leave.title": "Vil du forlade siden uden at gemme?",
  "discounts.limit.first": "kun første ordre",
  "discounts.limit.from": "fra {amount}",
  "discounts.limit.perCustomer": "{n} pr. kunde",
  "discounts.limit.until": "til {date}",
  "discounts.limit.uses": "{n, plural, one {# anvendelse} other {# anvendelser}}",
  "discounts.lookAlike": "{typed} ligner {code} ({name}). Kunderne kan forveksle dem.",
  "discounts.makeCode": "Lav en til mig",
  "discounts.maxUses": "Anvendelser i alt",
  "discounts.minQty": "Mindste antal",
  "discounts.minQtyHint": "Af det, den gælder for.",
  "discounts.minSpend": "Mindste køb",
  "discounts.minSpendHint": "Af varerne, efter de nedslag, der kommer før den.",
  "discounts.missing": "Denne rabat findes ikke her",
  "discounts.missingBody": "Den er måske blevet fjernet, eller du kan måske ikke se den.",
  "discounts.more": "Mere",
  "discounts.moreCodes": "Denne rabat har {n} koder. De andre står under Koder.",
  "discounts.moreLanguages": "Flere sprog",
  "discounts.name": "Navn (internt)",
  "discounts.never": "Kan aldrig gælde",
  "discounts.new": "Ny rabat",
  "discounts.newTitle": "Ny rabat",
  "discounts.noMap": "Det kunne ikke læses, hvad dine tabeller sælger, så der kan ikke vælges varer, og rabatten kan ikke prøves.",
  "discounts.noTables": "Intet her siger endnu, hvad dets linjer sælger. Tilføj først en regel under Tilbudsregler.",
  "discounts.notLive": "Ikke i gang endnu",
  "discounts.pause": "Sæt på pause",
  "discounts.pauseUnsaved": "Sæt på pause (dine ændringer er ikke gemt)",
  "discounts.paused": "{name} er sat på pause",
  "discounts.perCustomer": "Anvendelser pr. kunde",
  "discounts.pick.addTag": "Tilføj",
  "discounts.pick.chosen": "{n} valgt",
  "discounts.pick.done": "Færdig",
  "discounts.pick.none": "Intet matcher den søgning.",
  "discounts.pick.search": "Søg",
  "discounts.pick.subtitle": "Fra de tabeller, der er sat til at tage rabatter i Tilbudsregler.",
  "discounts.pick.tabCount": "{label} · {n}",
  "discounts.pick.tabs": "Hvor der vælges fra",
  "discounts.pick.tag": "Et mærke, sådan som det står på linjen",
  "discounts.pick.tags": "Mærker",
  "discounts.pick.title": "Vælg, hvad den gælder for",
  "discounts.pill.active": "Aktiv",
  "discounts.pill.draft": "Kladde",
  "discounts.pill.ended": "Afsluttet",
  "discounts.pill.paused": "På pause",
  "discounts.pill.usedUp": "Opbrugt",
  "discounts.publicName": "Hvad kunderne ser",
  "discounts.publicNameHint": "Linjen på en kvittering.",
  "discounts.publicNameIn": "Hvad kunderne ser · {language}",
  "discounts.ranAgain": "{name} kører igen til {date}",
  "discounts.readOnly": "Du kan læse denne rabat. En leder kan ændre den.",
  "discounts.resume": "Genoptag",
  "discounts.resumeUnsaved": "Genoptag (dine ændringer er ikke gemt)",
  "discounts.resumed": "{name} er i gang igen",
  "discounts.run.ahead": "Vælg i dag eller en senere dag.",
  "discounts.run.hint": "Den kører til den dag er slut.",
  "discounts.run.title": "Kør {name} igen",
  "discounts.run.until": "Til",
  "discounts.runAgain": "Kør igen",
  "discounts.save": "Gem",
  "discounts.saveDraft": "Gem som kladde",
  "discounts.saved": "{name} gemt",
  "discounts.section.applies": "Hvad den gælder for",
  "discounts.section.combine": "Sammen med andre rabatter",
  "discounts.section.gives": "Hvad den giver",
  "discounts.section.limits": "Grænser",
  "discounts.section.name": "Navn",
  "discounts.section.starts": "Hvordan den starter",
  "discounts.section.when": "Hvornår",
  "discounts.section.who": "Hvem får den",
  "discounts.signedInOnly": "Kun til en kunde, der er logget ind, eller som dit personale nævner ved navn. Gæster får den ikke.",
  "discounts.staffNote": "Vises i kassens liste over rabatter. Grænser for personale og årsager gælder stadig.",
  "discounts.starts.code": "Kode",
  "discounts.starts.codes": "{n} koder",
  "discounts.starts.itself": "Af sig selv",
  "discounts.starts.itselfHint": "Gælder, når ordren passer",
  "discounts.starts.staff": "Kun personale",
  "discounts.starts.staffHint": "Vælges ved kassen",
  "discounts.starts.staffOnly": "Kun personalet kan give den",
  "discounts.starts.withCode": "Med en kode",
  "discounts.starts.withCodeHint": "Kunden oplyser en kode",
  "discounts.steps.add": "Tilføj et trin",
  "discounts.steps.from": "Fra",
  "discounts.steps.off": "Procent i rabat",
  "discounts.steps.remove": "Fjern dette trin",
  "discounts.steps.rule": "Jo mere de køber af det, den gælder for, jo større bliver nedslaget. Det højeste trin, der nås, tæller.",
  "discounts.switchOn": "Slå til",
  "discounts.switchedOn": "{name} er slået til",
  "discounts.targets.more": "{first} og {n} mere",
  "discounts.title": "Rabatter",
  "discounts.toTime": "Til, som 17:00",
  "discounts.totals": "{uses, plural, one {# anvendelse} other {# anvendelser}} · {given} givet",
  "discounts.try.asIfOn": "En kladde prøves, som om den var slået til.",
  "discounts.try.bar": "Prøv den · {n, plural, one {# rabat} other {# rabatter}}",
  "discounts.try.barTotal": "Prøv den · {n, plural, one {# rabat} other {# rabatter}} · {total}",
  "discounts.try.better": "{name} blev brugt i stedet: den giver mere.",
  "discounts.try.buyer": "Hvem køber",
  "discounts.try.code": "Kode ved betaling",
  "discounts.try.customer": "En kunde, der er logget ind",
  "discounts.try.draftName": "{name} (kladde)",
  "discounts.try.failed": "Dette kunne ikke prøves",
  "discounts.try.guest": "En gæst",
  "discounts.try.minus": "−{amount}",
  "discounts.try.noCode": "Ingen kode",
  "discounts.try.noRows": "Intet gemt der endnu.",
  "discounts.try.none": "Intet tager rabatter endnu",
  "discounts.try.noneBody": "Sig, hvilken af dine tabeller der tager rabatter, så kan denne rabat prøves på dens rækker.",
  "discounts.try.notApplied": "Gjaldt ikke",
  "discounts.try.nothing": "Ingen rabat gælder for denne ordre.",
  "discounts.try.off": "Trukket fra ordren",
  "discounts.try.refused": "{code}: {why}",
  "discounts.try.row": "Prøvet på",
  "discounts.try.rowHint": "En gemt række i {table}",
  "discounts.try.rules": "Tilbudsregler",
  "discounts.try.taxLater": "Moms lægges til, når ordren gemmes",
  "discounts.try.title": "Prøv den",
  "discounts.try.total": "I alt",
  "discounts.try.unnamed": "En rabat",
  "discounts.try.whyNot": "{name} — {why}",
  "discounts.until": "Til (valgfrit)",
  "discounts.untilHint": "Til dagens slutning, efter stedets ur.",
  "discounts.usedUp.body": "Kan kun læses, indtil du hæver grænsen.",
  "discounts.usedUp.raise": "Hæv grænsen",
  "discounts.usedUp.title": "Alle {n} anvendelser er brugt",
  "discounts.usesSoFar": "{n} brugt",
  "discounts.value.amount": "Beløb i rabat",
  "discounts.value.amountHint": "Aldrig mere end det, den gælder for.",
  "discounts.value.buy": "Køb",
  "discounts.value.cheaper": "Den billigste af de to giver vi.",
  "discounts.value.cheapest": "Den billigste af dem giver vi.",
  "discounts.value.percent": "Procent i rabat",
  "discounts.value.price": "Sælges for, pr. stk.",
  "discounts.value.priceHint": "Varer, der allerede koster mindre, beholder deres pris.",
  "discounts.why.alone": "en anden rabat giver mere, og den bruges alene",
  "discounts.why.cancelled": "den blev annulleret",
  "discounts.why.days": "ikke på denne dag",
  "discounts.why.draft": "den er en kladde",
  "discounts.why.ended": "den er afsluttet",
  "discounts.why.first": "dette er ikke en første ordre",
  "discounts.why.group": "kunden er ikke i dens gruppe",
  "discounts.why.hours": "ikke på dette tidspunkt af dagen",
  "discounts.why.items": "intet på denne ordre er det, den gælder for",
  "discounts.why.limit": "over en grænse",
  "discounts.why.minimum": "ordren er under dens mindste køb",
  "discounts.why.noCode": "kræver sin kode",
  "discounts.why.notYet": "den er ikke startet",
  "discounts.why.paused": "den er på pause",
  "discounts.why.quantity": "ikke nok af det, den gælder for",
  "discounts.why.signIn": "kræver en kunde, der er logget ind",
  "discounts.why.unknown": "den gælder ikke her",
  "discounts.why.usedUp": "alle anvendelser er brugt"
};

export const lookup: Readonly<Record<string, string>> = {
  "lookup.addCredit": "Tilføj tilgodehavende",
  "lookup.added": "Tilføjede {amount}",
  "lookup.adjust": "Justér",
  "lookup.askManager": "En leder kan fylde det op, justere det eller annullere det.",
  "lookup.batch": "Serie",
  "lookup.cancelCard": "Annullér kortet",
  "lookup.cancelled": "Kortet, der ender på {last4}, er annulleret",
  "lookup.code": "Kode",
  "lookup.col.amount": "Beløb",
  "lookup.col.date": "Dato",
  "lookup.col.leftAfter": "Tilbage bagefter",
  "lookup.col.what": "Hvad",
  "lookup.col.where": "Hvor",
  "lookup.creditGiven": "{amount} i tilgodehavende givet til {address}",
  "lookup.dialog.add": "Tilføj",
  "lookup.dialog.adjust": "Justér kortet, der ender på {last4}",
  "lookup.dialog.amount": "Beløb",
  "lookup.dialog.amountNeeded": "Angiv et beløb over nul.",
  "lookup.dialog.byCard": "Kort",
  "lookup.dialog.cancel": "Annullér kortet, der ender på {last4}?",
  "lookup.dialog.cancelBody": "Det, der står tilbage på kortet, kan ikke længere bruges. Dette kan ikke fortrydes.",
  "lookup.dialog.cash": "Kontant",
  "lookup.dialog.credit": "Giv tilgodehavende til {address}",
  "lookup.dialog.creditMail": "Kunden får besked på e-mail.",
  "lookup.dialog.creditMore": "Tilføj tilgodehavende til {address}",
  "lookup.dialog.direction": "Tilføj eller træk fra",
  "lookup.dialog.movesTo": "Bruges senest flyttes til {date}",
  "lookup.dialog.other": "Andet",
  "lookup.dialog.paidBy": "Betalt med",
  "lookup.dialog.paidHint": "Noteres som modtaget ved disken. Intet opkræves her.",
  "lookup.dialog.remove": "Træk fra",
  "lookup.dialog.topUp": "Fyld kortet, der ender på {last4}, op",
  "lookup.dialog.upTo": "Der må højst stå {max} på kortet.",
  "lookup.dialog.why": "Hvorfor",
  "lookup.dialog.whyHint": "Gemmes i kortets historik.",
  "lookup.dialog.whyNeeded": "Skriv hvorfor.",
  "lookup.discount": "Rabat",
  "lookup.failed": "Dette kunne ikke slås op",
  "lookup.field.empty": "Skriv eller scan først en kode.",
  "lookup.field.label": "Skriv eller scan en kode, eller skriv en kundes e-mail",
  "lookup.field.placeholder": "GC-7K2M-W3HN-Q4XP eller name@example.com",
  "lookup.for": "Til",
  "lookup.from": "Fra",
  "lookup.giveCredit": "Giv tilgodehavende",
  "lookup.go": "Slå op",
  "lookup.issue": "Udsted",
  "lookup.issued": "Udstedt",
  "lookup.kind.card": "Gavekort",
  "lookup.kind.code": "Rabatkode",
  "lookup.kind.credit": "Tilgodehavende",
  "lookup.kind.pack": "Klippekort",
  "lookup.kind.voucher": "Voucher",
  "lookup.left": "Tilbage",
  "lookup.leftOf": "{left} af {total}",
  "lookup.markUsed": "Markér som brugt",
  "lookup.markedUsed": "Markeret som brugt",
  "lookup.moved": "Et ældre kort · det virker kun ved en bemandet disk",
  "lookup.never": "Udløber aldrig",
  "lookup.noActivity": "Der er ikke sket noget med det endnu.",
  "lookup.noUses": "Den er ikke brugt endnu.",
  "lookup.none.address": "Intet tilgodehavende for {typed}",
  "lookup.none.addressBody": "Denne adresse har intet tilgodehavende.",
  "lookup.none.code": "Intet har denne kode · {typed}",
  "lookup.none.codeBody": "Tjek tegnene, og prøv en anden kode.",
  "lookup.openBatch": "Åbn serien",
  "lookup.openDiscount": "Åbn rabatten",
  "lookup.percent": "{n} %",
  "lookup.pill.active": "Aktiv",
  "lookup.pill.cancelled": "Annulleret",
  "lookup.pill.doesNot": "Virker ikke nu",
  "lookup.pill.expired": "Udløbet",
  "lookup.pill.inactive": "Inaktiv",
  "lookup.pill.notSold": "Ikke solgt endnu",
  "lookup.pill.notUsed": "Ikke brugt",
  "lookup.pill.used": "Brugt",
  "lookup.pill.usedUp": "Opbrugt",
  "lookup.pill.works": "Virker",
  "lookup.print": "Udskriv",
  "lookup.printing": "Åbnet til udskrift",
  "lookup.queued": "Sat i kø til at blive sendt igen",
  "lookup.queuedFor": "Sat i kø til {name}",
  "lookup.removed": "Trak {amount} fra",
  "lookup.row.adjust": "Justeret",
  "lookup.row.expire": "Udløbet",
  "lookup.row.issue": "Udstedt",
  "lookup.row.refund": "Lagt tilbage",
  "lookup.row.spend": "Brugt",
  "lookup.row.topUp": "Fyldt op",
  "lookup.row.void": "Annulleret",
  "lookup.said.card": "Gavekort, der ender på {last4}, {pill}, {amount} tilbage",
  "lookup.said.cardNoBalance": "Gavekort, der ender på {last4}, {pill}",
  "lookup.said.code": "En rabatkode, der virker",
  "lookup.said.codeNot": "En rabatkode, der ikke virker nu",
  "lookup.said.credit": "Tilgodehavende, {pill}, {amount} tilbage",
  "lookup.said.nothing": "Intet har denne kode",
  "lookup.said.pack": "Klippekort, der ender på {last4}, {pill}, {left} af {total} tilbage",
  "lookup.said.voucher": "Voucher, der ender på {last4}, {pill}",
  "lookup.sendAgain": "Send igen",
  "lookup.start.body": "Scan koden på et kort eller en voucher, eller skriv den. For et tilgodehavende skriver du kundens e-mail.",
  "lookup.start.title": "Intet slået op endnu",
  "lookup.subtitle": "Gavekort, vouchere, klippekort, rabatkoder og tilgodehavender",
  "lookup.title": "Slå op",
  "lookup.topUp": "Fyld op",
  "lookup.toppedUp": "Fyldte {amount} på",
  "lookup.use.counted": "Brugt",
  "lookup.use.givenBack": "Givet tilbage",
  "lookup.use.held": "Holdt",
  "lookup.useBy": "Bruges senest",
  "lookup.useOne": "Brug et klip nu",
  "lookup.useRecorded": "1 klip registreret",
  "lookup.uses": "Indløsninger",
  "lookup.usesLeft": "Klip tilbage",
  "lookup.validUntil": "Virker til",
  "lookup.what": "Hvad det er",
  "lookup.why.cancelled": "Annulleret · kan ikke bruges",
  "lookup.why.codeUsedUp": "Alle anvendelser af denne kode er brugt",
  "lookup.why.empty": "Der står intet tilbage på det",
  "lookup.why.expired": "Udløbet",
  "lookup.why.expiredOn": "Udløb {date}",
  "lookup.why.inactive": "Ikke solgt endnu · der kan ikke betales med det",
  "lookup.why.notSold": "Ikke solgt endnu · kan ikke bruges",
  "lookup.why.off": "Denne kode er slået fra",
  "lookup.why.used": "Allerede brugt",
  "lookup.why.usedUp": "Alle anvendelser er brugt",
  "lookup.worth": "Værdi"
};

export const issue: Readonly<Record<string, string>> = {
  "issue.batch.again": "Du kan hente dem igen under Voucherserier.",
  "issue.batch.count": "Hvor mange",
  "issue.batch.countRange": "Fra 1 til {max}",
  "issue.batch.download": "Hent koderne (CSV)",
  "issue.batch.expiresNeeded": "Angiv, hvornår koderne holder op med at virke.",
  "issue.batch.made": "{count} koder lavet",
  "issue.batch.making": "Laver koderne",
  "issue.batch.name": "Seriens navn",
  "issue.batch.nameNeeded": "Giv serien et navn.",
  "issue.batch.open": "Åbn serien",
  "issue.batch.part": "{made} af {count} lavet. Gør den færdig under Voucherserier.",
  "issue.batch.progress": "{made} af {count}",
  "issue.batch.readBack": "{count, plural, one {# kode, der} other {# koder, der hver}} gælder én gang, til {date}",
  "issue.batch.save": "Lav koderne",
  "issue.card.amount": "Beløb",
  "issue.card.amountNeeded": "Angiv et beløb over nul.",
  "issue.card.amountRange": "Fra {min} til {max}",
  "issue.card.byCard": "Kort",
  "issue.card.cash": "Kontant",
  "issue.card.dateAhead": "Vælg en dag fra i morgen og frem.",
  "issue.card.emailNeeded": "Angiv en e-mail, eller vælg ikke at sende det.",
  "issue.card.issued": "Gavekort udstedt",
  "issue.card.message": "En besked",
  "issue.card.messageLeft": "{n} af {max}",
  "issue.card.notSent": "Ikke sendt",
  "issue.card.other": "Andet",
  "issue.card.paidBy": "Betalt med",
  "issue.card.paidHint": "Noteres som solgt ved disken · Intet opkræves her",
  "issue.card.paused": "Gavekort er ved at blive hentet ind fra kassen. Prøv igen, når det er færdigt.",
  "issue.card.queuedFor": "Sat i kø til {date}",
  "issue.card.queuedNow": "Sat i kø nu",
  "issue.card.save": "Udsted kortet",
  "issue.card.send": "Send",
  "issue.card.sendDay": "Send det den",
  "issue.card.sendNone": "Send ikke, jeg udskriver det",
  "issue.card.sendNow": "Nu",
  "issue.card.sendOn": "På en dato",
  "issue.card.sending": "Sender",
  "issue.done": "Færdig",
  "issue.email": "E-mail",
  "issue.emailWrong": "Dette er ikke en e-mailadresse.",
  "issue.expires": "Bruges senest",
  "issue.expiresAhead": "Vælg i dag eller en senere dag.",
  "issue.expiresHint": "Lad feltet stå tomt for en voucher, der aldrig udløber.",
  "issue.fixes": "{n, plural, one {# ting skal} other {# ting skal}} rettes",
  "issue.for": "Til",
  "issue.from": "Fra",
  "issue.never": "Udløber aldrig",
  "issue.notAllowed": "Din rolle må ikke udstede.",
  "issue.note": "Note",
  "issue.noteHint": "Kun til personalet.",
  "issue.print": "Udskriv",
  "issue.result.code": "Koden",
  "issue.result.noCode": "En leder kan læse koden.",
  "issue.result.once": "Hele koden vises kun denne ene gang.",
  "issue.subtitle": "Et gavekort, en voucher eller en serie koder",
  "issue.tab.batch": "Serie af koder",
  "issue.tab.card": "Gavekort",
  "issue.tab.voucher": "Voucher",
  "issue.tabs": "Hvad der skal udstedes",
  "issue.title": "Udsted",
  "issue.voucher.bearer": "Den, der har den",
  "issue.voucher.emailNeeded": "En voucher til en navngiven person skal have personens e-mail.",
  "issue.voucher.holder": "Navn",
  "issue.voucher.issued": "Voucher udstedt",
  "issue.voucher.name": "Hedder",
  "issue.voucher.nameHint": "Det, kunden ser, på voucheren og på sin ordre.",
  "issue.voucher.nameNeeded": "Skriv, hvad voucheren hedder.",
  "issue.voucher.named": "En navngiven person",
  "issue.voucher.namedHint": "Kun denne kunde, logget ind eller nævnt ved navn af personalet",
  "issue.voucher.packIssued": "Klippekort udstedt",
  "issue.voucher.save": "Udsted voucheren",
  "issue.why": "Hvorfor",
  "issue.whyNeeded": "Skriv hvorfor.",
  "issue.worth.amount": "Et beløb",
  "issue.worth.amountHint": "Trækker så meget fra en ordre",
  "issue.worth.amountValue": "Beløb",
  "issue.worth.change": "Skift",
  "issue.worth.choose": "Vælg…",
  "issue.worth.label": "Værdi",
  "issue.worth.noTables": "Intet her siger endnu, hvad dets linjer sælger.",
  "issue.worth.noTablesBody": "Tilføj først en regel under Tilbudsregler.",
  "issue.worth.noneFound": "Intet fundet.",
  "issue.worth.pack": "Et klippekort",
  "issue.worth.packHint": "Så mange klip til én bestemt ting",
  "issue.worth.percent": "En procent",
  "issue.worth.percentHint": "Trækker denne andel fra en ordre",
  "issue.worth.percentMax": "En procent er højst 100.",
  "issue.worth.percentValue": "Procent",
  "issue.worth.search": "Søg på navn",
  "issue.worth.table": "Fra",
  "issue.worth.thing": "Én ting",
  "issue.worth.thingHint": "Betaler for én bestemt ting",
  "issue.worth.thingNeeded": "Vælg, hvad den er til.",
  "issue.worth.uses": "Klip",
  "issue.worth.usesHint": "Fra 2 til 50",
  "issue.worth.usesRange": "Et klippekort har fra 2 til 50 klip.",
  "issue.worth.valueNeeded": "Angiv en værdi over nul.",
  "issue.worth.what": "Hvad den er til"
};

export const rules: Readonly<Record<string, string>> = {
  "rules.add": "Tilføj en regel",
  "rules.edit": "Rediger",
  "rules.from": "Fra {app}",
  "rules.holding": "{rows, plural, one {# række holder} other {# rækker holder}} på en anvendelse eller en kortbetaling.",
  "rules.kind.discounts": "Tager rabatter",
  "rules.kind.moved": "Har hentet ældre gavekort ind",
  "rules.kind.pays": "Tager et gavekort som betaling",
  "rules.kind.refunds": "Giver en kortbetaling tilbage",
  "rules.kind.sellsCards": "Sælger eller fylder et gavekort op",
  "rules.kind.sellsVouchers": "Sælger en voucher eller et klippekort",
  "rules.kind.uses": "Registrerer, hvad der blev brugt",
  "rules.kindHint.discounts": "Ordrer, bookinger, billetter: alt, hvad en rabat eller en kode kan sætte ned.",
  "rules.kindHint.pays": "En tabel med betalinger, hvor en række kan nævne et gavekort.",
  "rules.kindHint.sellsCards": "En tabel med salgslinjer, hvor en linje kan nævne det kort, den fylder op.",
  "rules.kindHint.sellsVouchers": "En tabel med salgslinjer, hvor en linje kan nævne den voucher, den sælger.",
  "rules.make.amounts": "Lav det: lad Adminium tilføje beløb, subtotal, nedslag og total samt de regler, der regner dem ud",
  "rules.make.codes": "Lav det: tilføj en tabel til de koder, der skrives på en række",
  "rules.make.column": "{column} i {table}",
  "rules.make.save": "Tilføj disse, og gem",
  "rules.make.table": "tabellen {table}",
  "rules.make.title": "Adminium tilføjer dette sammen med reglen",
  "rules.none.body": "En app, der tager rabatter eller gavekort, har sine regler med. Til din egen tabel tilføjer du en regel.",
  "rules.none.title": "Ingen tabel har noget med tilbud at gøre endnu",
  "rules.on": "Til",
  "rules.part.back": "Det fortrydes",
  "rules.part.balanceAfter": "Hvad der står på kortet bagefter",
  "rules.part.cardLoads": "Det gavekort, den fylder op",
  "rules.part.cardPays": "Det gavekort, der betaler",
  "rules.part.category": "Dens kategori, hvis linjen nævner en",
  "rules.part.due": "Hvad der mangler at blive betalt",
  "rules.part.final": "Rækken er endelig",
  "rules.part.finalHint": "Da registreres det, der blev brugt, og prisen regnes aldrig ud igen.",
  "rules.part.item": "Hvad linjen sælger",
  "rules.part.lineDiscount": "Linjens nedslag",
  "rules.part.lines": "Dens linjer er rækker i",
  "rules.part.load": "Det beløb, den fylder på",
  "rules.part.order": "Den række, den hører til",
  "rules.part.orderDiscount": "Rækkens eget nedslag",
  "rules.part.orderHint": "For en linje eller en betaling på en ordre: linket til ordren.",
  "rules.part.paid": "Hvad kortet betalte",
  "rules.part.price": "Linjens pris",
  "rules.part.quantity": "Linjens antal",
  "rules.part.refundAmount": "Det beløb, der gives tilbage",
  "rules.part.refundRow": "Dens link til betalingen",
  "rules.part.refunds": "Penge, der gives tilbage, er en række i",
  "rules.part.sold": "Hvad den blev solgt for",
  "rules.part.taxLater": "Moms opkræves, når den bruges",
  "rules.part.total": "Rækkens total",
  "rules.part.type": "Dens type, hvis linjen nævner en",
  "rules.part.undone": "Det, der blev brugt, gives tilbage",
  "rules.part.voucher": "Den voucher, den sælger",
  "rules.part.whenLoads": "Kortet fyldes op",
  "rules.part.whenPays": "Kortet betaler",
  "rules.part.whenSold": "Voucheren sælges",
  "rules.part.written": "Adminium skriver det.",
  "rules.point.create": "rækken oprettes",
  "rules.point.in": "{column} bliver {values}",
  "rules.point.never": "aldrig",
  "rules.point.set": "{column} bliver udfyldt",
  "rules.point.to": "den skifter til {states}",
  "rules.readOnly": "Kun en, der må ændre, hvordan Adminium regner en tabels kolonner ud, kan ændre disse.",
  "rules.remove": "Fjern regel",
  "rules.remove.confirm": "Vil du fjerne denne regel? Rækker i denne tabel holder op med at have noget med tilbud at gøre.",
  "rules.removed": "Regel fjernet fra {table}",
  "rules.removedPart": "Regel fjernet fra {table}. {why}",
  "rules.saved": "Regel gemt for {table}",
  "rules.saved.new": "Regel tilføjet for {table}",
  "rules.says.back": "Det fortrydes, når {when}.",
  "rules.says.discounts": "Rabatter og koder regnes ud for hver række, linje for linje fra {lines}.",
  "rules.says.moved": "Gavekort, der før blev holdt her, er hentet ind. Det gøres én gang, af Adminium.",
  "rules.says.noColumn": "ingen kolonne",
  "rules.says.noUses": "Det, der blev brugt, registreres ikke: grænser pr. anvendelse holdes ikke.",
  "rules.says.pays": "En række, der nævner et gavekort i {card}, betales fra kortet, når {when}; det, kortet betalte, skrives i {amount}.",
  "rules.says.refunds": "En række giver {amount} tilbage til det kort, der betalte, når {when}.",
  "rules.says.sellsCards": "En række, der nævner et gavekort i {card}, sætter {amount} ind på det, når {when}.",
  "rules.says.sellsVouchers": "En række, der nævner en voucher i {voucher}, markerer den som solgt, når {when}.",
  "rules.says.uses": "Det, der blev brugt, registreres, når {when}, og gives tilbage, når {back}.",
  "rules.says.usesAlone": "Det, der blev brugt, registreres, når {when}, selv om denne tabel ikke tager rabatter nu. Fjern det, eller tilføj reglen igen.",
  "rules.says.usesKept": "Det, der blev brugt, registreres, når {when}, og gives aldrig tilbage.",
  "rules.sheet.add": "Tilføj en regel",
  "rules.sheet.cannotMake": "Adminium kan ikke tilføje det, der mangler her: {reasons}",
  "rules.sheet.chooseColumn": "Vælg en kolonne",
  "rules.sheet.chooseTable": "Vælg en tabel",
  "rules.sheet.edit": "Rediger regel",
  "rules.sheet.err.needed": "Vælg en kolonne.",
  "rules.sheet.err.part": "Vælg en kolonne, eller lad Adminium tilføje den.",
  "rules.sheet.err.refunds": "Vælg også linket til betalingen og beløbet.",
  "rules.sheet.err.table": "Vælg en tabel",
  "rules.sheet.err.when": "Gør hvert \"hvornår\", du valgte, færdigt",
  "rules.sheet.err.whenNeeded": "Vælg hvornår, og gør det færdigt.",
  "rules.sheet.itself": "Den står for sig selv",
  "rules.sheet.kind": "Hvad tabellen gør",
  "rules.sheet.noCardLink": "Denne tabel har intet link til Gavekort. Tilføj først et under tabellens kolonner.",
  "rules.sheet.noLines": "Ingen tabel linker til denne. En tabel, der tager rabatter, skal have en tabel med linjer.",
  "rules.sheet.noRefunds": "Ingen tabel med tilbagebetalinger",
  "rules.sheet.noVoucherLink": "Denne tabel har intet link til Vouchere. Tilføj først et under tabellens kolonner.",
  "rules.sheet.notNeeded": "Ikke nødvendig",
  "rules.sheet.one": "Én hver",
  "rules.sheet.reads": "Læses som",
  "rules.sheet.save": "Gem regel",
  "rules.sheet.table": "Tabel",
  "rules.subtitle": "Hvad dine egne tabeller har at gøre med rabatter, vouchere og gavekort",
  "rules.switchedOff": "Regel for {table} slået fra",
  "rules.switchedOn": "Regel for {table} slået til",
  "rules.title": "Tilbudsregler",
  "rules.unavailable": "Denne regel kan ikke køre lige nu: Offers er slået fra eller svarer ikke.",
  "rules.when.becomes": "Når en kolonne bliver",
  "rules.when.column": "{label}: hvilken kolonne",
  "rules.when.create": "Når rækken oprettes",
  "rules.when.moves": "Når {table} skifter til",
  "rules.when.never": "Aldrig",
  "rules.when.set": "Når en kolonne bliver udfyldt",
  "rules.yours": "Din tabel"
};
