/** German strings for the Offers screens. Keys are those of en-US.ts. */
export const shared: Readonly<Record<string, string>> = {
  "shared.cancel": "Abbrechen",
  "shared.close": "Schließen",
  "shared.failed.title": "Das konnte nicht geladen werden",
  "shared.loading": "Wird geladen",
  "shared.refused.body": "Fragen Sie die Leitung, wenn Sie es brauchen.",
  "shared.refused.title": "Sie dürfen das nicht öffnen",
  "shared.retry": "Erneut versuchen"
};

export const refusal: Readonly<Record<string, string>> = {
  "refusal.askManager": "Fragen Sie die Leitung.",
  "refusal.askToPrint": "Bitten Sie die Leitung, es zu drucken.",
  "refusal.batchFull": "Diese Serie hat bereits alle ihre Codes.",
  "refusal.cardPaysCard": "Eine Tabelle, die Geschenkkarten verkauft, kann nicht zugleich eine Geschenkkarte als Zahlung annehmen.",
  "refusal.codeTaken": "Diesen Code verwendet bereits ein anderer Rabatt.",
  "refusal.conflict": "Jemand anderes hat das gleichzeitig geändert. Es wurde nichts gespeichert. Versuchen Sie es erneut.",
  "refusal.empty": "Auf der Karte ist nicht so viel.",
  "refusal.emptyLeft": "Auf der Karte sind noch {left}. Buchen Sie höchstens {left} ab.",
  "refusal.expired": "Das ist abgelaufen. Es wurde nichts gespeichert.",
  "refusal.forbidden": "Sie dürfen das nicht tun.",
  "refusal.inactive": "Diese Karte ist noch nicht verkauft. Sie kann nicht verwendet werden.",
  "refusal.noAnswer": "Offers konnte nicht antworten. Es wurde nichts gespeichert.",
  "refusal.noPrint": "Das kann gerade nicht gedruckt werden.",
  "refusal.notAllowed": "Das ist hier nicht erlaubt.",
  "refusal.notFound": "Das ist nicht mehr vorhanden.",
  "refusal.off": "Offers ist gerade ausgeschaltet.",
  "refusal.other": "Das konnte nicht gespeichert werden. Versuchen Sie es erneut.",
  "refusal.overLimit": "Das liegt über dem Limit. Es wurde nichts gespeichert.",
  "refusal.rate": "Zu viele Versuche. Warten Sie eine Minute.",
  "refusal.receiptOpen": "{rows, plural, one {# Zeile hält} other {# Zeilen halten}} eine Einlösung oder eine Kartenzahlung: Geben Sie diese zuerst zurück.",
  "refusal.usedUp": "Alle Einlösungen sind verbraucht. Es wurde nichts gespeichert.",
  "refusal.void": "Das wurde storniert. Es wurde nichts gespeichert."
};

export const discounts: Readonly<Record<string, string>> = {
  "discounts.aGroup": "Eine Kundengruppe",
  "discounts.all": "Alle Rabatte",
  "discounts.allDay": "Ganztägig",
  "discounts.anyone": "Alle",
  "discounts.applies.lines": "Nur diese Artikel",
  "discounts.applies.linesHint": "Artikel, Kategorien oder Arten",
  "discounts.applies.order": "Die ganze Bestellung",
  "discounts.applies.orderHint": "Alles im Warenkorb",
  "discounts.applies.orderNo": "Diese Art braucht Artikel zur Auswahl",
  "discounts.budget": "Beenden, sobald so viel gewährt wurde",
  "discounts.changeItems": "Ändern",
  "discounts.check.amount": "Geben Sie einen Betrag wie 5.00 ein.",
  "discounts.check.buy": "Geben Sie eine Zahl von 2 bis 10 ein.",
  "discounts.check.code": "Geben Sie einen Code ein oder lassen Sie einen erstellen.",
  "discounts.check.count": "Geben Sie eine ganze Zahl ab 1 ein.",
  "discounts.check.hours": "Geben Sie beide Uhrzeiten ein oder schalten Sie Ganztägig ein.",
  "discounts.check.hoursOrder": "Bis muss später als Von sein.",
  "discounts.check.name": "Geben Sie einen Namen ein, den Ihr Team erkennt.",
  "discounts.check.noSteps": "Fügen Sie mindestens eine Stufe hinzu.",
  "discounts.check.percent": "Geben Sie einen Prozentsatz von 1 bis 100 ein.",
  "discounts.check.price": "Geben Sie einen Preis wie 10.00 ein.",
  "discounts.check.publicName": "Fügen Sie die Zeile hinzu, die Kunden auf dem Beleg sehen.",
  "discounts.check.stepFrom": "Jede Stufe muss bei 2 oder mehr beginnen.",
  "discounts.check.stepMore": "Geben Sie mehr Nachlass als in der Stufe davor ({n} %).",
  "discounts.check.stepRising": "Jede Stufe beginnt über der davor (ab {n} Stück).",
  "discounts.check.targets": "Wählen Sie mindestens einen Artikel, eine Kategorie oder eine Art.",
  "discounts.check.until": "Bis liegt vor Von, der Rabatt kann also nie gelten. Wählen Sie ein Datum am oder nach dem Von-Datum.",
  "discounts.check.usesTaken": "{n} sind bereits eingelöst. Geben Sie {n} oder mehr ein.",
  "discounts.chooseItems": "Artikel wählen",
  "discounts.code": "Code",
  "discounts.codeHint": "Buchstaben und Ziffern. Kunden geben ihn beim Bezahlen ein oder nennen ihn an der Kasse.",
  "discounts.codeMade": "Code {code} erstellt",
  "discounts.col.given": "Gewährt",
  "discounts.col.gives": "Was er gibt",
  "discounts.col.limits": "Grenzen",
  "discounts.col.name": "Name",
  "discounts.col.starts": "Wie er ausgelöst wird",
  "discounts.col.status": "Status",
  "discounts.col.uses": "Einlösungen",
  "discounts.combinable": "Kombinierbar",
  "discounts.combineOff": "Gilt allein, und nur, wenn er mehr gibt als die anderen zusammen.",
  "discounts.combineOn": "Kommt zu anderen kombinierbaren Rabatten auf derselben Bestellung hinzu.",
  "discounts.count": "{n, plural, one {# Rabatt} other {# Rabatte}} · Einlösungen und gewährter Betrag bis heute",
  "discounts.days": "Wochentage",
  "discounts.daysHint": "Ohne Auswahl gilt er an jedem Tag.",
  "discounts.each": "je Stück",
  "discounts.empty.body": "Ein Rabatt zieht etwas von einer Bestellung ab: von selbst, mit einem Code oder wenn das Personal ihn gewährt.",
  "discounts.empty.title": "Noch keine Rabatte",
  "discounts.end.body": "Er wird sofort nicht mehr angewendet.",
  "discounts.end.title": "{name} jetzt beenden?",
  "discounts.endNow": "Jetzt beenden",
  "discounts.ended.body": "Starten Sie ihn erneut mit einem späteren Bis-Datum.",
  "discounts.ended.title": "Dieser Rabatt ist beendet",
  "discounts.endedNow": "{name} ist beendet",
  "discounts.fewerLanguages": "Weniger Sprachen",
  "discounts.firstOrder": "Nur erste Bestellung",
  "discounts.fix": "Vor dem Speichern {n, plural, one {# Angabe} other {# Angaben}} korrigieren",
  "discounts.fixes": "{n, plural, one {# Angabe muss} other {# Angaben müssen}} korrigiert werden, bevor Sie speichern können.",
  "discounts.from": "Von",
  "discounts.fromHint": "Ab Beginn dieses Tages, nach der Uhrzeit des Standorts.",
  "discounts.fromTime": "Von, als 09:00",
  "discounts.givenSoFar": "Bisher {amount} gewährt",
  "discounts.gives.amount": "{amount} Nachlass",
  "discounts.gives.amountOn": "{amount} Nachlass auf {what}",
  "discounts.gives.bonus": "{buy} für {pay}",
  "discounts.gives.bonusOn": "{buy} für {pay} auf {what}",
  "discounts.gives.percent": "{n} % Nachlass",
  "discounts.gives.percentOn": "{n} % Nachlass auf {what}",
  "discounts.gives.price": "je {amount}",
  "discounts.gives.priceOn": "{what} für je {amount}",
  "discounts.gives.steps": "Mehr Nachlass, je mehr gekauft wird",
  "discounts.gives.stepsOn": "Mehr Nachlass, je mehr {what} gekauft wird",
  "discounts.group": "Kundengruppe",
  "discounts.hoursHint": "Die Uhrzeiten können nicht über Mitternacht hinausgehen.",
  "discounts.houseRule": "Kunden erhalten jeden kombinierbaren Rabatt, einen Code und ansonsten den besten einzelnen Rabatt.",
  "discounts.kind.amount": "Betrag als Nachlass",
  "discounts.kind.bonus": "2 für 1 und Ähnliches",
  "discounts.kind.percent": "Prozent Nachlass",
  "discounts.kind.price": "Festpreis",
  "discounts.kind.steps": "Preis nach Menge",
  "discounts.leave.body": "Ihre Änderungen gehen verloren.",
  "discounts.leave.go": "Verlassen",
  "discounts.leave.stay": "Weiter bearbeiten",
  "discounts.leave.title": "Ohne Speichern verlassen?",
  "discounts.limit.first": "nur erste Bestellung",
  "discounts.limit.from": "ab {amount}",
  "discounts.limit.perCustomer": "{n} je Kunde",
  "discounts.limit.until": "bis {date}",
  "discounts.limit.uses": "{n, plural, one {# Einlösung} other {# Einlösungen}}",
  "discounts.lookAlike": "{typed} liest sich wie {code} ({name}). Kunden könnten die beiden verwechseln.",
  "discounts.makeCode": "Einen für mich erstellen",
  "discounts.maxUses": "Einlösungen insgesamt",
  "discounts.minQty": "Mindestmenge",
  "discounts.minQtyHint": "Von dem, wofür er gilt.",
  "discounts.minSpend": "Mindestumsatz",
  "discounts.minSpendHint": "Der Waren, nach den Nachlässen, die vorher greifen.",
  "discounts.missing": "Dieser Rabatt ist nicht vorhanden",
  "discounts.missingBody": "Er wurde vielleicht entfernt, oder Sie dürfen ihn nicht sehen.",
  "discounts.more": "Mehr",
  "discounts.moreCodes": "Dieser Rabatt hat {n} Codes. Die anderen finden Sie unter Codes.",
  "discounts.moreLanguages": "Mehr Sprachen",
  "discounts.name": "Name (intern)",
  "discounts.never": "Kann nie gelten",
  "discounts.new": "Neuer Rabatt",
  "discounts.newTitle": "Neuer Rabatt",
  "discounts.noMap": "Was Ihre Tabellen verkaufen, konnte nicht gelesen werden. Daher lassen sich keine Artikel wählen und der Rabatt lässt sich nicht ausprobieren.",
  "discounts.noTables": "Hier ist noch nicht festgelegt, was die Positionen verkaufen. Fügen Sie zuerst unter Angebotsregeln eine Regel hinzu.",
  "discounts.notLive": "Noch nicht aktiv",
  "discounts.pause": "Pausieren",
  "discounts.pauseUnsaved": "Pausieren (Ihre Änderungen sind nicht gespeichert)",
  "discounts.paused": "{name} ist pausiert",
  "discounts.perCustomer": "Einlösungen je Kunde",
  "discounts.pick.addTag": "Hinzufügen",
  "discounts.pick.chosen": "{n} gewählt",
  "discounts.pick.done": "Fertig",
  "discounts.pick.none": "Zu dieser Suche passt nichts.",
  "discounts.pick.search": "Suchen",
  "discounts.pick.subtitle": "Aus den Tabellen, die laut Angebotsregeln Rabatte annehmen.",
  "discounts.pick.tabCount": "{label} · {n}",
  "discounts.pick.tabs": "Woraus gewählt wird",
  "discounts.pick.tag": "Ein Schlagwort, so wie es an der Position steht",
  "discounts.pick.tags": "Schlagwörter",
  "discounts.pick.title": "Wählen, wofür er gilt",
  "discounts.pill.active": "Aktiv",
  "discounts.pill.draft": "Entwurf",
  "discounts.pill.ended": "Beendet",
  "discounts.pill.paused": "Pausiert",
  "discounts.pill.usedUp": "Aufgebraucht",
  "discounts.publicName": "Was Kunden sehen",
  "discounts.publicNameHint": "Die Zeile auf einem Beleg.",
  "discounts.publicNameIn": "Was Kunden sehen · {language}",
  "discounts.ranAgain": "{name} läuft wieder, bis {date}",
  "discounts.readOnly": "Sie können diesen Rabatt lesen. Die Leitung kann ihn ändern.",
  "discounts.resume": "Fortsetzen",
  "discounts.resumeUnsaved": "Fortsetzen (Ihre Änderungen sind nicht gespeichert)",
  "discounts.resumed": "{name} läuft wieder",
  "discounts.run.ahead": "Wählen Sie heute oder einen späteren Tag.",
  "discounts.run.hint": "Er läuft bis zum Ende dieses Tages.",
  "discounts.run.title": "{name} erneut starten",
  "discounts.run.until": "Bis",
  "discounts.runAgain": "Erneut starten",
  "discounts.save": "Speichern",
  "discounts.saveDraft": "Entwurf speichern",
  "discounts.saved": "{name} gespeichert",
  "discounts.section.applies": "Wofür er gilt",
  "discounts.section.combine": "Mit anderen Rabatten",
  "discounts.section.gives": "Was er gibt",
  "discounts.section.limits": "Grenzen",
  "discounts.section.name": "Name",
  "discounts.section.starts": "Wie er ausgelöst wird",
  "discounts.section.when": "Wann",
  "discounts.section.who": "Wer ihn bekommt",
  "discounts.signedInOnly": "Nur für angemeldete Kunden oder solche, die Ihr Personal benennt. Gäste erhalten ihn nicht.",
  "discounts.staffNote": "Erscheint in der Rabattliste der Kasse. Mitarbeiterlimits und Gründe gelten weiterhin.",
  "discounts.starts.code": "Code",
  "discounts.starts.codes": "{n} Codes",
  "discounts.starts.itself": "Von selbst",
  "discounts.starts.itselfHint": "Gilt, wenn die Bestellung passt",
  "discounts.starts.staff": "Nur Personal",
  "discounts.starts.staffHint": "An der Kasse gewählt",
  "discounts.starts.staffOnly": "Nur das Personal kann ihn gewähren",
  "discounts.starts.withCode": "Mit einem Code",
  "discounts.starts.withCodeHint": "Kunde nennt einen Code",
  "discounts.steps.add": "Stufe hinzufügen",
  "discounts.steps.from": "Ab",
  "discounts.steps.off": "Prozent Nachlass",
  "discounts.steps.remove": "Diese Stufe entfernen",
  "discounts.steps.rule": "Je mehr von dem gekauft wird, wofür er gilt, desto größer der Nachlass. Es zählt die höchste erreichte Stufe.",
  "discounts.switchOn": "Einschalten",
  "discounts.switchedOn": "{name} ist eingeschaltet",
  "discounts.targets.more": "{first} und {n} weitere",
  "discounts.title": "Rabatte",
  "discounts.toTime": "Bis, als 17:00",
  "discounts.totals": "{uses, plural, one {# Einlösung} other {# Einlösungen}} · {given} gewährt",
  "discounts.try.asIfOn": "Ein Entwurf wird so ausprobiert, als wäre er eingeschaltet.",
  "discounts.try.bar": "Ausprobieren · {n, plural, one {# Rabatt} other {# Rabatte}}",
  "discounts.try.barTotal": "Ausprobieren · {n, plural, one {# Rabatt} other {# Rabatte}} · {total}",
  "discounts.try.better": "Stattdessen wurde {name} verwendet: Er gibt mehr.",
  "discounts.try.buyer": "Wer kauft",
  "discounts.try.code": "Code beim Bezahlen",
  "discounts.try.customer": "Ein angemeldeter Kunde",
  "discounts.try.draftName": "{name} (Entwurf)",
  "discounts.try.failed": "Das konnte nicht ausprobiert werden",
  "discounts.try.guest": "Ein Gast",
  "discounts.try.minus": "−{amount}",
  "discounts.try.noCode": "Kein Code",
  "discounts.try.noRows": "Dort ist noch nichts gespeichert.",
  "discounts.try.none": "Noch nimmt nichts Rabatte an",
  "discounts.try.noneBody": "Legen Sie fest, welche Ihrer Tabellen Rabatte annimmt, dann lässt sich dieser Rabatt an ihren Zeilen ausprobieren.",
  "discounts.try.notApplied": "Nicht angewendet",
  "discounts.try.nothing": "Für diese Bestellung gilt kein Rabatt.",
  "discounts.try.off": "Von der Bestellung abgezogen",
  "discounts.try.refused": "{code}: {why}",
  "discounts.try.row": "Ausprobiert an",
  "discounts.try.rowHint": "Eine gespeicherte Zeile aus {table}",
  "discounts.try.rules": "Angebotsregeln",
  "discounts.try.taxLater": "Die Steuer kommt hinzu, wenn die Bestellung gespeichert wird",
  "discounts.try.title": "Ausprobieren",
  "discounts.try.total": "Summe",
  "discounts.try.unnamed": "Ein Rabatt",
  "discounts.try.whyNot": "{name} — {why}",
  "discounts.until": "Bis (optional)",
  "discounts.untilHint": "Bis zum Ende dieses Tages, nach der Uhrzeit des Standorts.",
  "discounts.usedUp.body": "Nur lesbar, bis Sie das Limit erhöhen.",
  "discounts.usedUp.raise": "Limit erhöhen",
  "discounts.usedUp.title": "Alle {n} Einlösungen sind verbraucht",
  "discounts.usesSoFar": "{n} eingelöst",
  "discounts.value.amount": "Betrag als Nachlass",
  "discounts.value.amountHint": "Nie mehr als das, wofür er gilt.",
  "discounts.value.buy": "Kaufen",
  "discounts.value.cheaper": "Der günstigere geht auf uns.",
  "discounts.value.cheapest": "Der günstigste geht auf uns.",
  "discounts.value.percent": "Prozent Nachlass",
  "discounts.value.price": "Verkaufspreis je Stück",
  "discounts.value.priceHint": "Artikel, die schon weniger kosten, behalten ihren Preis.",
  "discounts.why.alone": "ein anderer Rabatt gibt mehr, und dieser gilt nur allein",
  "discounts.why.cancelled": "er wurde storniert",
  "discounts.why.days": "nicht an diesem Tag",
  "discounts.why.draft": "er ist ein Entwurf",
  "discounts.why.ended": "er ist beendet",
  "discounts.why.first": "dies ist keine erste Bestellung",
  "discounts.why.group": "der Kunde gehört nicht zu seiner Gruppe",
  "discounts.why.hours": "nicht zu dieser Tageszeit",
  "discounts.why.items": "nichts in dieser Bestellung ist das, wofür er gilt",
  "discounts.why.limit": "über einem Limit",
  "discounts.why.minimum": "die Bestellung liegt unter seinem Mindestumsatz",
  "discounts.why.noCode": "braucht seinen Code",
  "discounts.why.notYet": "er hat noch nicht begonnen",
  "discounts.why.paused": "er ist pausiert",
  "discounts.why.quantity": "nicht genug von dem, wofür er gilt",
  "discounts.why.signIn": "braucht einen angemeldeten Kunden",
  "discounts.why.unknown": "er gilt hier nicht",
  "discounts.why.usedUp": "alle Einlösungen sind verbraucht"
};

export const lookup: Readonly<Record<string, string>> = {
  "lookup.addCredit": "Guthaben hinzufügen",
  "lookup.added": "{amount} hinzugefügt",
  "lookup.adjust": "Anpassen",
  "lookup.askManager": "Die Leitung kann sie aufladen, anpassen oder stornieren.",
  "lookup.batch": "Serie",
  "lookup.cancelCard": "Karte stornieren",
  "lookup.cancelled": "Die Karte mit der Endung {last4} ist storniert",
  "lookup.code": "Code",
  "lookup.col.amount": "Betrag",
  "lookup.col.date": "Datum",
  "lookup.col.leftAfter": "Danach übrig",
  "lookup.col.what": "Was",
  "lookup.col.where": "Wo",
  "lookup.creditGiven": "{amount} Guthaben an {address} gegeben",
  "lookup.dialog.add": "Hinzufügen",
  "lookup.dialog.adjust": "Karte mit der Endung {last4} anpassen",
  "lookup.dialog.amount": "Betrag",
  "lookup.dialog.amountNeeded": "Geben Sie einen Betrag über null ein.",
  "lookup.dialog.byCard": "Karte",
  "lookup.dialog.cancel": "Karte mit der Endung {last4} stornieren?",
  "lookup.dialog.cancelBody": "Das Restguthaben kann nicht mehr ausgegeben werden. Dies kann nicht rückgängig gemacht werden.",
  "lookup.dialog.cash": "Bar",
  "lookup.dialog.credit": "Guthaben an {address} geben",
  "lookup.dialog.creditMail": "Der Kunde wird per E-Mail benachrichtigt.",
  "lookup.dialog.creditMore": "Guthaben für {address} hinzufügen",
  "lookup.dialog.direction": "Hinzufügen oder abbuchen",
  "lookup.dialog.movesTo": "„Einlösbar bis“ verschiebt sich auf {date}",
  "lookup.dialog.other": "Sonstiges",
  "lookup.dialog.paidBy": "Bezahlt mit",
  "lookup.dialog.paidHint": "Wird als an der Theke eingenommen erfasst. Hier wird nichts abgebucht.",
  "lookup.dialog.remove": "Abbuchen",
  "lookup.dialog.topUp": "Karte mit der Endung {last4} aufladen",
  "lookup.dialog.upTo": "Die Karte darf höchstens {max} enthalten.",
  "lookup.dialog.why": "Grund",
  "lookup.dialog.whyHint": "Wird im Verlauf der Karte festgehalten.",
  "lookup.dialog.whyNeeded": "Geben Sie den Grund an.",
  "lookup.discount": "Rabatt",
  "lookup.failed": "Das konnte nicht nachgeschlagen werden",
  "lookup.field.empty": "Geben Sie zuerst einen Code ein oder scannen Sie ihn.",
  "lookup.field.label": "Code eingeben oder scannen, oder die E-Mail-Adresse eines Kunden",
  "lookup.field.placeholder": "GC-7K2M-W3HN-Q4XP oder name@example.com",
  "lookup.for": "Für",
  "lookup.from": "Von",
  "lookup.giveCredit": "Guthaben geben",
  "lookup.go": "Nachschlagen",
  "lookup.issue": "Ausstellen",
  "lookup.issued": "Ausgestellt",
  "lookup.kind.card": "Geschenkkarte",
  "lookup.kind.code": "Rabattcode",
  "lookup.kind.credit": "Guthaben",
  "lookup.kind.pack": "Paket",
  "lookup.kind.voucher": "Gutschein",
  "lookup.left": "Übrig",
  "lookup.leftOf": "{left} von {total}",
  "lookup.markUsed": "Als eingelöst markieren",
  "lookup.markedUsed": "Als eingelöst markiert",
  "lookup.moved": "Eine ältere Karte · sie gilt nur an einer besetzten Theke",
  "lookup.never": "Läuft nie ab",
  "lookup.noActivity": "Bisher ist damit nichts geschehen.",
  "lookup.noUses": "Noch nicht eingelöst.",
  "lookup.none.address": "Kein Guthaben für {typed}",
  "lookup.none.addressBody": "Zu dieser Adresse gibt es kein Guthaben.",
  "lookup.none.code": "Nichts hat diesen Code · {typed}",
  "lookup.none.codeBody": "Prüfen Sie die Zeichen und versuchen Sie einen anderen Code.",
  "lookup.openBatch": "Serie öffnen",
  "lookup.openDiscount": "Rabatt öffnen",
  "lookup.percent": "{n} %",
  "lookup.pill.active": "Aktiv",
  "lookup.pill.cancelled": "Storniert",
  "lookup.pill.doesNot": "Gilt derzeit nicht",
  "lookup.pill.expired": "Abgelaufen",
  "lookup.pill.inactive": "Inaktiv",
  "lookup.pill.notSold": "Noch nicht verkauft",
  "lookup.pill.notUsed": "Nicht eingelöst",
  "lookup.pill.used": "Eingelöst",
  "lookup.pill.usedUp": "Aufgebraucht",
  "lookup.pill.works": "Gültig",
  "lookup.print": "Drucken",
  "lookup.printing": "Zum Drucken geöffnet",
  "lookup.queued": "Zum erneuten Senden eingereiht",
  "lookup.queuedFor": "Eingereiht für {name}",
  "lookup.removed": "{amount} abgebucht",
  "lookup.row.adjust": "Angepasst",
  "lookup.row.expire": "Abgelaufen",
  "lookup.row.issue": "Ausgestellt",
  "lookup.row.refund": "Zurückgebucht",
  "lookup.row.spend": "Ausgegeben",
  "lookup.row.topUp": "Aufgeladen",
  "lookup.row.void": "Storniert",
  "lookup.said.card": "Geschenkkarte mit der Endung {last4}, {pill}, {amount} übrig",
  "lookup.said.cardNoBalance": "Geschenkkarte mit der Endung {last4}, {pill}",
  "lookup.said.code": "Ein gültiger Rabattcode",
  "lookup.said.codeNot": "Ein Rabattcode, der derzeit nicht gilt",
  "lookup.said.credit": "Guthaben, {pill}, {amount} übrig",
  "lookup.said.nothing": "Nichts hat diesen Code",
  "lookup.said.pack": "Paket mit der Endung {last4}, {pill}, {left} von {total} übrig",
  "lookup.said.voucher": "Gutschein mit der Endung {last4}, {pill}",
  "lookup.sendAgain": "Erneut senden",
  "lookup.start.body": "Scannen Sie den Code auf einer Karte oder einem Gutschein, oder geben Sie ihn ein. Für Guthaben geben Sie die E-Mail-Adresse des Kunden ein.",
  "lookup.start.title": "Noch nichts nachgeschlagen",
  "lookup.subtitle": "Geschenkkarten, Gutscheine, Pakete, Rabattcodes und Guthaben",
  "lookup.title": "Nachschlagen",
  "lookup.topUp": "Aufladen",
  "lookup.toppedUp": "{amount} aufgeladen",
  "lookup.use.counted": "Eingelöst",
  "lookup.use.givenBack": "Zurückgegeben",
  "lookup.use.held": "Vorgemerkt",
  "lookup.useBy": "Einlösbar bis",
  "lookup.useOne": "Jetzt eine einlösen",
  "lookup.useRecorded": "1 Einlösung erfasst",
  "lookup.uses": "Einlösungen",
  "lookup.usesLeft": "Einlösungen übrig",
  "lookup.validUntil": "Gültig bis",
  "lookup.what": "Was es ist",
  "lookup.why.cancelled": "Storniert · kann nicht verwendet werden",
  "lookup.why.codeUsedUp": "Alle Einlösungen dieses Codes sind verbraucht",
  "lookup.why.empty": "Darauf ist nichts mehr übrig",
  "lookup.why.expired": "Abgelaufen",
  "lookup.why.expiredOn": "Abgelaufen am {date}",
  "lookup.why.inactive": "Noch nicht verkauft · kann nicht ausgegeben werden",
  "lookup.why.notSold": "Noch nicht verkauft · kann nicht verwendet werden",
  "lookup.why.off": "Dieser Code ist ausgeschaltet",
  "lookup.why.used": "Bereits eingelöst",
  "lookup.why.usedUp": "Alle Einlösungen sind verbraucht",
  "lookup.worth": "Wert"
};

export const issue: Readonly<Record<string, string>> = {
  "issue.batch.again": "Sie können sie unter Gutscheinserien erneut herunterladen.",
  "issue.batch.count": "Wie viele",
  "issue.batch.countRange": "Von 1 bis {max}",
  "issue.batch.download": "Codes herunterladen (CSV)",
  "issue.batch.expiresNeeded": "Geben Sie an, bis wann die Codes gelten.",
  "issue.batch.made": "{count} Codes erstellt",
  "issue.batch.making": "Codes werden erstellt",
  "issue.batch.name": "Name der Serie",
  "issue.batch.nameNeeded": "Geben Sie der Serie einen Namen.",
  "issue.batch.open": "Serie öffnen",
  "issue.batch.part": "{made} von {count} erstellt. Schließen Sie die Serie unter Gutscheinserien ab.",
  "issue.batch.progress": "{made} von {count}",
  "issue.batch.readBack": "{count, plural, one {# Code} other {# Codes}}, jeweils einmal einlösbar, bis {date}",
  "issue.batch.save": "Codes erstellen",
  "issue.card.amount": "Betrag",
  "issue.card.amountNeeded": "Geben Sie einen Betrag über null ein.",
  "issue.card.amountRange": "Von {min} bis {max}",
  "issue.card.byCard": "Karte",
  "issue.card.cash": "Bar",
  "issue.card.dateAhead": "Wählen Sie einen Tag ab morgen.",
  "issue.card.emailNeeded": "Geben Sie eine E-Mail-Adresse ein oder wählen Sie, sie nicht zu senden.",
  "issue.card.issued": "Geschenkkarte ausgestellt",
  "issue.card.message": "Eine Nachricht",
  "issue.card.messageLeft": "{n} von {max}",
  "issue.card.notSent": "Nicht gesendet",
  "issue.card.other": "Sonstiges",
  "issue.card.paidBy": "Bezahlt mit",
  "issue.card.paidHint": "Wird als an der Theke verkauft erfasst · Hier wird nichts abgebucht",
  "issue.card.paused": "Geschenkkarten werden gerade aus der Kasse übernommen. Versuchen Sie es erneut, wenn das abgeschlossen ist.",
  "issue.card.queuedFor": "Eingereiht für {date}",
  "issue.card.queuedNow": "Jetzt eingereiht",
  "issue.card.save": "Karte ausstellen",
  "issue.card.send": "Senden",
  "issue.card.sendDay": "Senden am",
  "issue.card.sendNone": "Nicht senden, ich drucke sie",
  "issue.card.sendNow": "Jetzt",
  "issue.card.sendOn": "An einem Datum",
  "issue.card.sending": "Versand",
  "issue.done": "Fertig",
  "issue.email": "E-Mail",
  "issue.emailWrong": "Das ist keine E-Mail-Adresse.",
  "issue.expires": "Einlösbar bis",
  "issue.expiresAhead": "Wählen Sie heute oder einen späteren Tag.",
  "issue.expiresHint": "Leer lassen für einen Gutschein, der nie abläuft.",
  "issue.fixes": "{n, plural, one {# Angabe muss} other {# Angaben müssen}} korrigiert werden",
  "issue.for": "Für",
  "issue.from": "Von",
  "issue.never": "Läuft nie ab",
  "issue.notAllowed": "Ihre Rolle darf nichts ausstellen.",
  "issue.note": "Notiz",
  "issue.noteHint": "Nur für das Personal.",
  "issue.print": "Drucken",
  "issue.result.code": "Der Code",
  "issue.result.noCode": "Den Code kann die Leitung einsehen.",
  "issue.result.once": "Der vollständige Code wird nur dieses eine Mal angezeigt.",
  "issue.subtitle": "Eine Geschenkkarte, ein Gutschein oder eine Serie von Codes",
  "issue.tab.batch": "Serie von Codes",
  "issue.tab.card": "Geschenkkarte",
  "issue.tab.voucher": "Gutschein",
  "issue.tabs": "Was ausgestellt wird",
  "issue.title": "Ausstellen",
  "issue.voucher.bearer": "Wer ihn vorlegt",
  "issue.voucher.emailNeeded": "Ein Gutschein für eine benannte Person braucht deren E-Mail-Adresse.",
  "issue.voucher.holder": "Name",
  "issue.voucher.issued": "Gutschein ausgestellt",
  "issue.voucher.name": "Bezeichnung",
  "issue.voucher.nameHint": "Was der Kunde sieht, auf dem Gutschein und in seiner Bestellung.",
  "issue.voucher.nameNeeded": "Geben Sie an, wie der Gutschein heißt.",
  "issue.voucher.named": "Eine benannte Person",
  "issue.voucher.namedHint": "Nur dieser Kunde, angemeldet oder vom Personal benannt",
  "issue.voucher.packIssued": "Paket ausgestellt",
  "issue.voucher.save": "Gutschein ausstellen",
  "issue.why": "Grund",
  "issue.whyNeeded": "Geben Sie den Grund an.",
  "issue.worth.amount": "Ein Betrag",
  "issue.worth.amountHint": "Zieht so viel von einer Bestellung ab",
  "issue.worth.amountValue": "Betrag",
  "issue.worth.change": "Ändern",
  "issue.worth.choose": "Wählen…",
  "issue.worth.label": "Wert",
  "issue.worth.noTables": "Hier ist noch nicht festgelegt, was die Positionen verkaufen.",
  "issue.worth.noTablesBody": "Fügen Sie zuerst unter Angebotsregeln eine Regel hinzu.",
  "issue.worth.noneFound": "Nichts gefunden.",
  "issue.worth.pack": "Ein Paket",
  "issue.worth.packHint": "Mehrere Einlösungen einer benannten Sache",
  "issue.worth.percent": "Ein Prozentsatz",
  "issue.worth.percentHint": "Zieht diesen Anteil von einer Bestellung ab",
  "issue.worth.percentMax": "Ein Prozentsatz beträgt höchstens 100.",
  "issue.worth.percentValue": "Prozent",
  "issue.worth.search": "Nach Namen suchen",
  "issue.worth.table": "Aus",
  "issue.worth.thing": "Eine Sache",
  "issue.worth.thingHint": "Bezahlt eine benannte Sache",
  "issue.worth.thingNeeded": "Wählen Sie, wofür er gilt.",
  "issue.worth.uses": "Einlösungen",
  "issue.worth.usesHint": "Von 2 bis 50",
  "issue.worth.usesRange": "Ein Paket hat 2 bis 50 Einlösungen.",
  "issue.worth.valueNeeded": "Geben Sie einen Wert über null ein.",
  "issue.worth.what": "Wofür er gilt"
};

export const rules: Readonly<Record<string, string>> = {
  "rules.add": "Regel hinzufügen",
  "rules.edit": "Bearbeiten",
  "rules.from": "Aus {app}",
  "rules.holding": "{rows, plural, one {# Zeile hält} other {# Zeilen halten}} eine Einlösung oder eine Kartenzahlung.",
  "rules.inFile": "Diese Regel wurde in einer Projektdatei festgelegt. Ändern Sie sie dort.",
  "rules.kind.discounts": "Nimmt Rabatte an",
  "rules.kind.moved": "Hat ältere Geschenkkarten übernommen",
  "rules.kind.pays": "Nimmt eine Geschenkkarte als Zahlung an",
  "rules.kind.refunds": "Gibt eine Kartenzahlung zurück",
  "rules.kind.sellsCards": "Verkauft eine Geschenkkarte oder lädt sie auf",
  "rules.kind.sellsVouchers": "Verkauft einen Gutschein oder ein Paket",
  "rules.kind.uses": "Erfasst, was eingelöst wurde",
  "rules.kindHint.discounts": "Bestellungen, Buchungen, Tickets: alles, was ein Rabatt oder ein Code verringern kann.",
  "rules.kindHint.pays": "Eine Tabelle mit Zahlungen, in der eine Zeile eine Geschenkkarte nennen kann.",
  "rules.kindHint.sellsCards": "Eine Tabelle mit Verkaufspositionen, in der eine Position die Karte nennen kann, die sie auflädt.",
  "rules.kindHint.sellsVouchers": "Eine Tabelle mit Verkaufspositionen, in der eine Position den Gutschein nennen kann, den sie verkauft.",
  "rules.make.amounts": "Anlegen: Adminium fügt Betrag, Zwischensumme, Nachlass und Summe hinzu, dazu die Regeln, die sie berechnen",
  "rules.make.codes": "Anlegen: eine Tabelle für die Codes hinzufügen, die in einer Zeile eingegeben werden",
  "rules.make.column": "{column} in {table}",
  "rules.make.save": "Diese hinzufügen und speichern",
  "rules.make.table": "die Tabelle {table}",
  "rules.make.title": "Adminium fügt dies zusammen mit der Regel hinzu",
  "rules.none.body": "Eine App, die Rabatte oder Geschenkkarten annimmt, bringt ihre Regeln mit. Für eine eigene Tabelle fügen Sie eine Regel hinzu.",
  "rules.none.title": "Noch hat keine Tabelle etwas mit Angeboten zu tun",
  "rules.on": "Ein",
  "rules.part.back": "Es wird rückgängig gemacht",
  "rules.part.balanceAfter": "Was danach auf der Karte ist",
  "rules.part.cardLoads": "Die Geschenkkarte, die sie auflädt",
  "rules.part.cardPays": "Die Geschenkkarte, die bezahlt",
  "rules.part.category": "Ihre Kategorie, wenn die Position eine nennt",
  "rules.part.final": "Die Zeile ist endgültig",
  "rules.part.finalHint": "Dann wird erfasst, was eingelöst wurde, und der Preis wird nie wieder neu berechnet.",
  "rules.part.item": "Was die Position verkauft",
  "rules.part.itemHint": "Eine Verknüpfung zum verkauften Artikel. Ohne sie gilt hier kein Rabatt auf bestimmte Artikel; ein Rabatt auf die ganze Bestellung gilt weiterhin.",
  "rules.part.lineDiscount": "Der Nachlass der Position",
  "rules.part.lines": "Ihre Positionen sind Zeilen von",
  "rules.part.load": "Der Betrag, den sie auflädt",
  "rules.part.orderDiscount": "Der eigene Nachlass der Zeile",
  "rules.part.paid": "Was die Karte bezahlt hat",
  "rules.part.price": "Der Preis der Position",
  "rules.part.quantity": "Die Menge der Position",
  "rules.part.refundAmount": "Der zurückgegebene Betrag",
  "rules.part.refundRow": "Ihre Verknüpfung zur Zahlung",
  "rules.part.refunds": "Zurückgegebenes Geld ist eine Zeile von",
  "rules.part.sold": "Wofür es verkauft wurde",
  "rules.part.taxLater": "Die Steuer fällt bei der Einlösung an",
  "rules.part.total": "Die Summe der Zeile",
  "rules.part.type": "Ihre Art, wenn die Position eine nennt",
  "rules.part.undone": "Was eingelöst wurde, wird zurückgegeben",
  "rules.part.voucher": "Der Gutschein, den sie verkauft",
  "rules.part.whenLoads": "Die Karte wird aufgeladen",
  "rules.part.whenPays": "Die Karte bezahlt",
  "rules.part.whenSold": "Der Gutschein wird verkauft",
  "rules.part.written": "Adminium schreibt es.",
  "rules.point.create": "die Zeile angelegt wird",
  "rules.point.in": "{column} zu {values} wird",
  "rules.point.never": "nie",
  "rules.point.set": "{column} gesetzt ist",
  "rules.point.to": "sie zu {states} wechselt",
  "rules.readOnly": "Nur wer ändern darf, wie Adminium die Spalten einer Tabelle berechnet, kann diese Regeln ändern.",
  "rules.remove": "Regel entfernen",
  "rules.remove.confirm": "Diese Regel entfernen? Zeilen dieser Tabelle haben dann nichts mehr mit Angeboten zu tun.",
  "rules.removed": "Regel aus {table} entfernt",
  "rules.removedPart": "Regel aus {table} entfernt. {why}",
  "rules.saved": "Regel für {table} gespeichert",
  "rules.saved.new": "Regel für {table} hinzugefügt",
  "rules.says.back": "Es wird rückgängig gemacht, wenn {when}.",
  "rules.says.discounts": "Rabatte und Codes werden für jede Zeile berechnet, Position für Position aus {lines}.",
  "rules.says.moved": "Geschenkkarten, die bisher hier geführt wurden, wurden übernommen. Das erledigt Adminium einmalig.",
  "rules.says.noColumn": "keine Spalte",
  "rules.says.noUses": "Was eingelöst wurde, wird nicht erfasst: Grenzen nach Einlösungen werden nicht eingehalten.",
  "rules.says.pays": "Eine Zeile, die in {card} eine Geschenkkarte nennt, wird von der Karte bezahlt, wenn {when}; was die Karte bezahlt hat, wird in {amount} geschrieben.",
  "rules.says.refunds": "Eine Zeile gibt {amount} an die Karte zurück, die bezahlt hat, wenn {when}.",
  "rules.says.sellsCards": "Eine Zeile, die in {card} eine Geschenkkarte nennt, lädt {amount} darauf, wenn {when}.",
  "rules.says.sellsVouchers": "Eine Zeile, die in {voucher} einen Gutschein nennt, markiert ihn als verkauft, wenn {when}.",
  "rules.says.uses": "Was eingelöst wurde, wird erfasst, wenn {when}, und zurückgegeben, wenn {back}.",
  "rules.says.usesAlone": "Was eingelöst wurde, wird erfasst, wenn {when}, obwohl diese Tabelle derzeit keine Rabatte annimmt. Entfernen Sie dies oder fügen Sie die Regel wieder hinzu.",
  "rules.says.usesKept": "Was eingelöst wurde, wird erfasst, wenn {when}, und nie zurückgegeben.",
  "rules.sheet.add": "Regel hinzufügen",
  "rules.sheet.cannotMake": "Adminium kann das Fehlende hier nicht hinzufügen: {reasons}",
  "rules.sheet.chooseColumn": "Spalte wählen",
  "rules.sheet.chooseTable": "Tabelle wählen",
  "rules.sheet.edit": "Regel bearbeiten",
  "rules.sheet.err.needed": "Wählen Sie eine Spalte.",
  "rules.sheet.err.part": "Wählen Sie eine Spalte oder lassen Sie Adminium sie hinzufügen.",
  "rules.sheet.err.refunds": "Wählen Sie auch die Verknüpfung zur Zahlung und den Betrag.",
  "rules.sheet.err.table": "Wählen Sie eine Tabelle",
  "rules.sheet.err.when": "Vervollständigen Sie jedes gewählte „Wann“",
  "rules.sheet.err.whenNeeded": "Wählen Sie, wann, und vervollständigen Sie die Angabe.",
  "rules.sheet.kind": "Was die Tabelle tut",
  "rules.sheet.noCardLink": "Diese Tabelle hat keine Verknüpfung zu Geschenkkarten. Fügen Sie zuerst eine bei den Spalten der Tabelle hinzu.",
  "rules.sheet.noLines": "Keine Tabelle ist mit dieser verknüpft. Eine Tabelle, die Rabatte annimmt, braucht eine Tabelle mit Positionen.",
  "rules.sheet.noRefunds": "Keine Tabelle mit Rückzahlungen",
  "rules.sheet.noVoucherLink": "Diese Tabelle hat keine Verknüpfung zu Gutscheinen. Fügen Sie zuerst eine bei den Spalten der Tabelle hinzu.",
  "rules.sheet.notNeeded": "Nicht nötig",
  "rules.sheet.one": "Je eine",
  "rules.sheet.reads": "Liest sich als",
  "rules.sheet.save": "Regel speichern",
  "rules.sheet.table": "Tabelle",
  "rules.subtitle": "Was Ihre eigenen Tabellen mit Rabatten, Gutscheinen und Geschenkkarten zu tun haben",
  "rules.switchedOff": "Regel für {table} ausgeschaltet",
  "rules.switchedOn": "Regel für {table} eingeschaltet",
  "rules.title": "Angebotsregeln",
  "rules.unavailable": "Diese Regel kann gerade nicht ausgeführt werden: Offers ist ausgeschaltet oder antwortet nicht.",
  "rules.when.becomes": "Wenn eine Spalte zu einem Wert wird",
  "rules.when.column": "{label}: welche Spalte",
  "rules.when.create": "Wenn die Zeile angelegt wird",
  "rules.when.moves": "Wenn {table} wechselt zu",
  "rules.when.never": "Nie",
  "rules.when.set": "Wenn eine Spalte gesetzt ist",
  "rules.yours": "Ihre Tabelle"
};
