/** French strings for the Offers screens. Keys are those of en-US.ts. */
export const shared: Readonly<Record<string, string>> = {
  "shared.cancel": "Annuler",
  "shared.close": "Fermer",
  "shared.failed.title": "Le chargement a échoué",
  "shared.loading": "Chargement",
  "shared.refused.body": "Demandez à un responsable si vous en avez besoin.",
  "shared.refused.title": "Vous n’avez pas la permission d’ouvrir ceci",
  "shared.retry": "Réessayer"
};

export const refusal: Readonly<Record<string, string>> = {
  "refusal.askManager": "Demandez à un responsable.",
  "refusal.askToPrint": "Demandez à un responsable de l’imprimer.",
  "refusal.batchFull": "Cette série contient déjà tous ses codes.",
  "refusal.cardPaysCard": "Une table qui vend des cartes cadeaux ne peut pas aussi accepter une carte cadeau en paiement.",
  "refusal.codeTaken": "Ce code est déjà utilisé par une autre remise.",
  "refusal.conflict": "Quelqu’un d’autre a modifié ceci au même moment. Rien n’a été enregistré. Réessayez.",
  "refusal.empty": "Le solde de la carte est insuffisant.",
  "refusal.emptyLeft": "Il reste {left} sur la carte. Retirez {left} ou moins.",
  "refusal.expired": "Ceci a expiré. Rien n’a été enregistré.",
  "refusal.forbidden": "Vous n’avez pas la permission de faire cela.",
  "refusal.inactive": "Cette carte n’est pas encore vendue. Elle ne peut pas être utilisée.",
  "refusal.noAnswer": "Offers n’a pas pu répondre. Rien n’a été enregistré.",
  "refusal.noPrint": "L’impression est impossible pour le moment.",
  "refusal.notAllowed": "Ce n’est pas autorisé ici.",
  "refusal.notFound": "Ceci n’existe plus.",
  "refusal.off": "Offers est désactivé pour le moment.",
  "refusal.other": "L’enregistrement a échoué. Réessayez.",
  "refusal.overLimit": "La limite est dépassée. Rien n’a été enregistré.",
  "refusal.rate": "Trop de tentatives. Patientez une minute.",
  "refusal.receiptOpen": "{rows, plural, one {# enregistrement retient} other {# enregistrements retiennent}} une utilisation ou un paiement par carte : rendez-les d’abord.",
  "refusal.usedUp": "Toutes les utilisations sont prises. Rien n’a été enregistré.",
  "refusal.void": "Ceci a été annulé. Rien n’a été enregistré."
};

export const discounts: Readonly<Record<string, string>> = {
  "discounts.aGroup": "Un groupe de clients",
  "discounts.all": "Toutes les remises",
  "discounts.allDay": "Toute la journée",
  "discounts.anyone": "Tout le monde",
  "discounts.applies.lines": "Seulement ces articles",
  "discounts.applies.linesHint": "Articles, catégories ou types",
  "discounts.applies.order": "Toute la commande",
  "discounts.applies.orderHint": "Tout ce que contient le panier",
  "discounts.applies.orderNo": "Ce type de remise demande de choisir des articles",
  "discounts.budget": "Arrêter une fois ce montant accordé",
  "discounts.changeItems": "Modifier",
  "discounts.check.amount": "Saisissez un montant, par exemple 5.00.",
  "discounts.check.buy": "Saisissez un nombre de 2 à 10.",
  "discounts.check.code": "Saisissez un code, ou faites-en créer un.",
  "discounts.check.count": "Saisissez un nombre entier, 1 ou plus.",
  "discounts.check.hours": "Saisissez les deux heures, ou activez Toute la journée.",
  "discounts.check.hoursOrder": "L’heure de fin doit être postérieure à l’heure de début.",
  "discounts.check.name": "Donnez-lui un nom que votre équipe reconnaîtra.",
  "discounts.check.noSteps": "Ajoutez au moins un palier.",
  "discounts.check.percent": "Saisissez un pourcentage de 1 à 100.",
  "discounts.check.price": "Saisissez un prix, par exemple 10.00.",
  "discounts.check.publicName": "Ajoutez la ligne que les clients voient sur le ticket.",
  "discounts.check.stepFrom": "Chaque palier commence à 2 ou plus.",
  "discounts.check.stepMore": "Accordez davantage qu’au palier précédent ({n} %).",
  "discounts.check.stepRising": "Chaque palier commence plus haut que le précédent ({n} unités).",
  "discounts.check.targets": "Choisissez au moins un article, une catégorie ou un type.",
  "discounts.check.until": "La fin précède le début : cette remise ne pourra jamais s’appliquer. Choisissez une date égale ou postérieure au début.",
  "discounts.check.usesTaken": "{n} sont déjà utilisées. Saisissez {n} ou plus.",
  "discounts.chooseItems": "Choisir des articles",
  "discounts.code": "Code",
  "discounts.codeHint": "Lettres et chiffres. Les clients le saisissent au moment de payer ou le donnent en caisse.",
  "discounts.codeMade": "Code {code} créé",
  "discounts.col.given": "Accordé",
  "discounts.col.gives": "Ce qu’elle accorde",
  "discounts.col.limits": "Limites",
  "discounts.col.name": "Nom",
  "discounts.col.starts": "Déclenchement",
  "discounts.col.status": "État",
  "discounts.col.uses": "Utilisations",
  "discounts.combinable": "Cumulable",
  "discounts.combineOff": "Utilisée seule, uniquement si elle accorde plus que les autres réunies.",
  "discounts.combineOn": "S’ajoute aux autres remises cumulables de la même commande.",
  "discounts.count": "{n, plural, one {# remise} other {# remises}} · utilisations et montant accordé à ce jour",
  "discounts.days": "Jours de la semaine",
  "discounts.daysHint": "Aucun jour choisi signifie tous les jours.",
  "discounts.each": "unités",
  "discounts.empty.body": "Une remise réduit une commande d’elle-même, avec un code, ou lorsque le personnel l’accorde.",
  "discounts.empty.title": "Aucune remise pour l’instant",
  "discounts.end.body": "Elle cesse de s’appliquer immédiatement.",
  "discounts.end.title": "Terminer {name} maintenant ?",
  "discounts.endNow": "Terminer maintenant",
  "discounts.ended.body": "Relancez-la avec une date de fin plus tardive.",
  "discounts.ended.title": "Cette remise est terminée",
  "discounts.endedNow": "{name} est terminée",
  "discounts.fewerLanguages": "Moins de langues",
  "discounts.firstOrder": "Première commande uniquement",
  "discounts.fix": "Corrigez {n, plural, one {# point} other {# points}} avant d’enregistrer",
  "discounts.fixes": "{n, plural, one {# point est} other {# points sont}} à corriger avant de pouvoir enregistrer.",
  "discounts.from": "Début",
  "discounts.fromHint": "Dès le début de ce jour, à l’heure de l’établissement.",
  "discounts.fromTime": "Début, par exemple 09:00",
  "discounts.givenSoFar": "{amount} accordés à ce jour",
  "discounts.gives.amount": "{amount} de remise",
  "discounts.gives.amountOn": "{amount} de remise sur {what}",
  "discounts.gives.bonus": "{buy} pour {pay}",
  "discounts.gives.bonusOn": "{buy} pour {pay} sur {what}",
  "discounts.gives.percent": "{n} % de remise",
  "discounts.gives.percentOn": "{n} % de remise sur {what}",
  "discounts.gives.price": "{amount} l’unité",
  "discounts.gives.priceOn": "{what} à {amount} l’unité",
  "discounts.gives.steps": "Remise croissante selon la quantité achetée",
  "discounts.gives.stepsOn": "Remise croissante selon la quantité achetée : {what}",
  "discounts.group": "Groupe de clients",
  "discounts.hoursHint": "Les horaires ne peuvent pas dépasser minuit.",
  "discounts.houseRule": "Les clients obtiennent toutes les remises cumulables, un seul code, et sinon la meilleure remise seule.",
  "discounts.kind.amount": "Montant en moins",
  "discounts.kind.bonus": "2 pour 1 et offres similaires",
  "discounts.kind.percent": "Pourcentage en moins",
  "discounts.kind.price": "Prix fixe",
  "discounts.kind.steps": "Prix selon la quantité",
  "discounts.leave.body": "Vos modifications seront perdues.",
  "discounts.leave.go": "Quitter",
  "discounts.leave.stay": "Continuer la modification",
  "discounts.leave.title": "Quitter sans enregistrer ?",
  "discounts.limit.first": "première commande uniquement",
  "discounts.limit.from": "à partir de {amount}",
  "discounts.limit.perCustomer": "{n} par client",
  "discounts.limit.until": "jusqu’au {date}",
  "discounts.limit.uses": "{n, plural, one {# utilisation} other {# utilisations}}",
  "discounts.lookAlike": "{typed} ressemble à {code} ({name}). Les clients risquent de les confondre.",
  "discounts.makeCode": "En créer un pour moi",
  "discounts.maxUses": "Nombre total d’utilisations",
  "discounts.minQty": "Quantité minimale",
  "discounts.minQtyHint": "De ce à quoi elle s’applique.",
  "discounts.minSpend": "Montant minimal d’achat",
  "discounts.minSpendHint": "Des marchandises, après les réductions qui la précèdent.",
  "discounts.missing": "Cette remise est introuvable",
  "discounts.missingBody": "Elle a peut-être été supprimée, ou vous n’avez peut-être pas le droit de la voir.",
  "discounts.more": "Plus",
  "discounts.moreCodes": "Cette remise a {n} codes. Les autres se trouvent dans Codes.",
  "discounts.moreLanguages": "Plus de langues",
  "discounts.name": "Nom (interne)",
  "discounts.never": "Ne peut jamais s’appliquer",
  "discounts.new": "Nouvelle remise",
  "discounts.newTitle": "Nouvelle remise",
  "discounts.noMap": "Impossible de lire ce que vendent vos tables : les articles ne peuvent donc pas être choisis et la remise ne peut pas être essayée.",
  "discounts.noTables": "Rien ici n’indique encore ce que vendent ses lignes. Ajoutez d’abord une règle dans Règles des offres.",
  "discounts.notLive": "Pas encore active",
  "discounts.pause": "Mettre en pause",
  "discounts.pauseUnsaved": "Mettre en pause (vos modifications ne sont pas enregistrées)",
  "discounts.paused": "{name} est en pause",
  "discounts.perCustomer": "Utilisations par client",
  "discounts.pick.addTag": "Ajouter",
  "discounts.pick.chosen": "{n} sélectionnés",
  "discounts.pick.done": "Terminé",
  "discounts.pick.none": "Aucun résultat pour cette recherche.",
  "discounts.pick.search": "Rechercher",
  "discounts.pick.subtitle": "Parmi les tables qui acceptent les remises selon les Règles des offres.",
  "discounts.pick.tabCount": "{label} · {n}",
  "discounts.pick.tabs": "Où choisir",
  "discounts.pick.tag": "Une étiquette, telle qu’elle est écrite sur la ligne",
  "discounts.pick.tags": "Étiquettes",
  "discounts.pick.title": "Choisir ce à quoi elle s’applique",
  "discounts.pill.active": "Active",
  "discounts.pill.draft": "Brouillon",
  "discounts.pill.ended": "Terminée",
  "discounts.pill.paused": "En pause",
  "discounts.pill.usedUp": "Épuisée",
  "discounts.publicName": "Ce que voient les clients",
  "discounts.publicNameHint": "La ligne sur le ticket.",
  "discounts.publicNameIn": "Ce que voient les clients · {language}",
  "discounts.ranAgain": "{name} est relancée jusqu’au {date}",
  "discounts.readOnly": "Vous pouvez consulter cette remise. Un responsable peut la modifier.",
  "discounts.resume": "Reprendre",
  "discounts.resumeUnsaved": "Reprendre (vos modifications ne sont pas enregistrées)",
  "discounts.resumed": "{name} est de nouveau active",
  "discounts.run.ahead": "Choisissez aujourd’hui ou un jour ultérieur.",
  "discounts.run.hint": "Elle s’applique jusqu’à la fin de ce jour.",
  "discounts.run.title": "Relancer {name}",
  "discounts.run.until": "Fin",
  "discounts.runAgain": "Relancer",
  "discounts.save": "Enregistrer",
  "discounts.saveDraft": "Enregistrer le brouillon",
  "discounts.saved": "{name} enregistrée",
  "discounts.section.applies": "Ce à quoi elle s’applique",
  "discounts.section.combine": "Avec d’autres remises",
  "discounts.section.gives": "Ce qu’elle accorde",
  "discounts.section.limits": "Limites",
  "discounts.section.name": "Nom",
  "discounts.section.starts": "Déclenchement",
  "discounts.section.when": "Quand",
  "discounts.section.who": "Qui en bénéficie",
  "discounts.signedInOnly": "Réservée à un client connecté, ou à un client que votre personnel désigne. Les invités n’en bénéficient pas.",
  "discounts.staffNote": "Apparaît dans la liste des remises de la caisse. Les plafonds du personnel et les motifs s’appliquent toujours.",
  "discounts.starts.code": "Code",
  "discounts.starts.codes": "{n} codes",
  "discounts.starts.itself": "D’elle-même",
  "discounts.starts.itselfHint": "S’applique quand la commande correspond",
  "discounts.starts.staff": "Personnel uniquement",
  "discounts.starts.staffHint": "Choisie en caisse",
  "discounts.starts.staffOnly": "Seul le personnel peut l’accorder",
  "discounts.starts.withCode": "Avec un code",
  "discounts.starts.withCodeHint": "Le client donne un code",
  "discounts.steps.add": "Ajouter un palier",
  "discounts.steps.from": "À partir de",
  "discounts.steps.off": "Pourcentage en moins",
  "discounts.steps.remove": "Supprimer ce palier",
  "discounts.steps.rule": "Plus le client achète de ce à quoi elle s’applique, plus la réduction est forte. Le palier le plus élevé atteint est retenu.",
  "discounts.switchOn": "Activer",
  "discounts.switchedOn": "{name} est activée",
  "discounts.targets.more": "{first} et {n} de plus",
  "discounts.title": "Remises",
  "discounts.toTime": "Fin, par exemple 17:00",
  "discounts.totals": "{uses, plural, one {# utilisation} other {# utilisations}} · {given} accordés",
  "discounts.try.asIfOn": "Un brouillon est essayé comme s’il était activé.",
  "discounts.try.bar": "Essayer · {n, plural, one {# remise} other {# remises}}",
  "discounts.try.barTotal": "Essayer · {n, plural, one {# remise} other {# remises}} · {total}",
  "discounts.try.better": "{name} a été utilisée à la place : elle accorde davantage.",
  "discounts.try.buyer": "Qui achète",
  "discounts.try.code": "Code saisi au paiement",
  "discounts.try.customer": "Un client connecté",
  "discounts.try.draftName": "{name} (brouillon)",
  "discounts.try.failed": "L’essai a échoué",
  "discounts.try.guest": "Un invité",
  "discounts.try.minus": "−{amount}",
  "discounts.try.noCode": "Aucun code",
  "discounts.try.noRows": "Rien d’enregistré ici pour l’instant.",
  "discounts.try.none": "Rien n’accepte encore les remises",
  "discounts.try.noneBody": "Indiquez laquelle de vos tables accepte les remises, et cette remise pourra être essayée sur ses enregistrements.",
  "discounts.try.notApplied": "Non appliquées",
  "discounts.try.nothing": "Aucune remise ne s’applique à cette commande.",
  "discounts.try.off": "Déduit de la commande",
  "discounts.try.refused": "{code} : {why}",
  "discounts.try.row": "Essayée sur",
  "discounts.try.rowHint": "Un enregistrement existant de {table}",
  "discounts.try.rules": "Règles des offres",
  "discounts.try.taxLater": "La taxe est ajoutée à l’enregistrement de la commande",
  "discounts.try.title": "Essayer",
  "discounts.try.total": "Total",
  "discounts.try.unnamed": "Une remise",
  "discounts.try.whyNot": "{name} — {why}",
  "discounts.until": "Fin (facultatif)",
  "discounts.untilHint": "Jusqu’à la fin de ce jour, à l’heure de l’établissement.",
  "discounts.usedUp.body": "En lecture seule tant que vous n’augmentez pas la limite.",
  "discounts.usedUp.raise": "Augmenter la limite",
  "discounts.usedUp.title": "Les {n} utilisations sont toutes prises",
  "discounts.usesSoFar": "{n} utilisées",
  "discounts.value.amount": "Montant en moins",
  "discounts.value.amountHint": "Jamais plus que ce à quoi elle s’applique.",
  "discounts.value.buy": "Achetez",
  "discounts.value.cheaper": "Le moins cher des deux est offert.",
  "discounts.value.cheapest": "Le moins cher est offert.",
  "discounts.value.percent": "Pourcentage en moins",
  "discounts.value.price": "Prix de vente à l’unité",
  "discounts.value.priceHint": "Les articles qui coûtent déjà moins gardent leur prix.",
  "discounts.why.alone": "une autre remise accorde davantage, et elle s’utilise seule",
  "discounts.why.cancelled": "elle a été annulée",
  "discounts.why.days": "pas ce jour-là",
  "discounts.why.draft": "c’est un brouillon",
  "discounts.why.ended": "elle est terminée",
  "discounts.why.first": "ce n’est pas une première commande",
  "discounts.why.group": "le client ne fait pas partie de son groupe",
  "discounts.why.hours": "pas à cette heure de la journée",
  "discounts.why.items": "rien dans cette commande n’est concerné",
  "discounts.why.limit": "une limite est dépassée",
  "discounts.why.minimum": "la commande est inférieure à son montant minimal d’achat",
  "discounts.why.noCode": "son code est nécessaire",
  "discounts.why.notYet": "elle n’a pas encore commencé",
  "discounts.why.paused": "elle est en pause",
  "discounts.why.quantity": "quantité insuffisante de ce qu’elle concerne",
  "discounts.why.signIn": "un client connecté est nécessaire",
  "discounts.why.unknown": "elle ne s’applique pas ici",
  "discounts.why.usedUp": "toutes les utilisations sont prises"
};

export const lookup: Readonly<Record<string, string>> = {
  "lookup.addCredit": "Ajouter un avoir",
  "lookup.added": "{amount} ajoutés",
  "lookup.adjust": "Ajuster",
  "lookup.askManager": "Un responsable peut la recharger, l’ajuster ou l’annuler.",
  "lookup.batch": "Série",
  "lookup.cancelCard": "Annuler la carte",
  "lookup.cancelled": "La carte se terminant par {last4} est annulée",
  "lookup.code": "Code",
  "lookup.col.amount": "Montant",
  "lookup.col.date": "Date",
  "lookup.col.leftAfter": "Reste après",
  "lookup.col.what": "Opération",
  "lookup.col.where": "Où",
  "lookup.creditGiven": "Avoir de {amount} accordé à {address}",
  "lookup.dialog.add": "Ajouter",
  "lookup.dialog.adjust": "Ajuster la carte se terminant par {last4}",
  "lookup.dialog.amount": "Montant",
  "lookup.dialog.amountNeeded": "Saisissez un montant supérieur à zéro.",
  "lookup.dialog.byCard": "Carte bancaire",
  "lookup.dialog.cancel": "Annuler la carte se terminant par {last4} ?",
  "lookup.dialog.cancelBody": "Le solde restant ne pourra plus être dépensé. Cette action est irréversible.",
  "lookup.dialog.cash": "Espèces",
  "lookup.dialog.credit": "Accorder un avoir à {address}",
  "lookup.dialog.creditMail": "Le client est prévenu par e-mail.",
  "lookup.dialog.creditMore": "Ajouter un avoir pour {address}",
  "lookup.dialog.direction": "Ajouter ou retirer",
  "lookup.dialog.movesTo": "La date limite d’utilisation passe au {date}",
  "lookup.dialog.other": "Autre",
  "lookup.dialog.paidBy": "Payé par",
  "lookup.dialog.paidHint": "Enregistré comme encaissé au comptoir. Rien n’est débité ici.",
  "lookup.dialog.remove": "Retirer",
  "lookup.dialog.topUp": "Recharger la carte se terminant par {last4}",
  "lookup.dialog.upTo": "La carte peut contenir jusqu’à {max}.",
  "lookup.dialog.why": "Motif",
  "lookup.dialog.whyHint": "Conservé dans l’historique de la carte.",
  "lookup.dialog.whyNeeded": "Indiquez le motif.",
  "lookup.discount": "Remise",
  "lookup.failed": "La recherche a échoué",
  "lookup.field.empty": "Saisissez ou scannez d’abord un code.",
  "lookup.field.label": "Saisissez ou scannez un code, ou l’e-mail d’un client",
  "lookup.field.placeholder": "GC-7K2M-W3HN-Q4XP ou name@example.com",
  "lookup.for": "Pour",
  "lookup.from": "De la part de",
  "lookup.giveCredit": "Accorder un avoir",
  "lookup.go": "Rechercher",
  "lookup.issue": "Émettre",
  "lookup.issued": "Émis le",
  "lookup.kind.card": "Carte cadeau",
  "lookup.kind.code": "Code de remise",
  "lookup.kind.credit": "Avoir",
  "lookup.kind.pack": "Forfait",
  "lookup.kind.voucher": "Bon",
  "lookup.left": "Reste",
  "lookup.leftOf": "{left} sur {total}",
  "lookup.markUsed": "Marquer comme utilisé",
  "lookup.markedUsed": "Marqué comme utilisé",
  "lookup.moved": "Une ancienne carte · elle ne fonctionne qu’à un comptoir tenu par le personnel",
  "lookup.never": "N’expire jamais",
  "lookup.noActivity": "Aucune opération pour l’instant.",
  "lookup.noUses": "Pas encore utilisé.",
  "lookup.none.address": "Aucun avoir pour {typed}",
  "lookup.none.addressBody": "Cette adresse ne détient aucun avoir.",
  "lookup.none.code": "Rien ne porte ce code · {typed}",
  "lookup.none.codeBody": "Vérifiez les caractères et essayez un autre code.",
  "lookup.openBatch": "Ouvrir la série",
  "lookup.openDiscount": "Ouvrir la remise",
  "lookup.percent": "{n} %",
  "lookup.pill.active": "Active",
  "lookup.pill.cancelled": "Annulé",
  "lookup.pill.doesNot": "Ne fonctionne pas actuellement",
  "lookup.pill.expired": "Expiré",
  "lookup.pill.inactive": "Inactive",
  "lookup.pill.notSold": "Pas encore vendu",
  "lookup.pill.notUsed": "Non utilisé",
  "lookup.pill.used": "Utilisé",
  "lookup.pill.usedUp": "Épuisé",
  "lookup.pill.works": "Fonctionne",
  "lookup.print": "Imprimer",
  "lookup.printing": "Ouvert pour l’impression",
  "lookup.queued": "Nouvel envoi mis en file d’attente",
  "lookup.queuedFor": "Envoi en file d’attente pour {name}",
  "lookup.removed": "{amount} retirés",
  "lookup.row.adjust": "Ajustement",
  "lookup.row.expire": "Expiration",
  "lookup.row.issue": "Émission",
  "lookup.row.refund": "Recrédité",
  "lookup.row.spend": "Dépense",
  "lookup.row.topUp": "Rechargement",
  "lookup.row.void": "Annulation",
  "lookup.said.card": "Carte cadeau se terminant par {last4}, {pill}, il reste {amount}",
  "lookup.said.cardNoBalance": "Carte cadeau se terminant par {last4}, {pill}",
  "lookup.said.code": "Un code de remise qui fonctionne",
  "lookup.said.codeNot": "Un code de remise qui ne fonctionne pas actuellement",
  "lookup.said.credit": "Avoir, {pill}, il reste {amount}",
  "lookup.said.nothing": "Rien ne porte ce code",
  "lookup.said.pack": "Forfait se terminant par {last4}, {pill}, il reste {left} sur {total}",
  "lookup.said.voucher": "Bon se terminant par {last4}, {pill}",
  "lookup.sendAgain": "Renvoyer",
  "lookup.start.body": "Scannez le code d’une carte ou d’un bon, ou saisissez-le. Pour un avoir, saisissez l’e-mail du client.",
  "lookup.start.title": "Aucune recherche pour l’instant",
  "lookup.subtitle": "Cartes cadeaux, bons, forfaits, codes de remise et avoirs",
  "lookup.title": "Rechercher",
  "lookup.topUp": "Recharger",
  "lookup.toppedUp": "{amount} rechargés",
  "lookup.use.counted": "Utilisée",
  "lookup.use.givenBack": "Rendue",
  "lookup.use.held": "Retenue",
  "lookup.useBy": "À utiliser jusqu’au",
  "lookup.useOne": "En utiliser une maintenant",
  "lookup.useRecorded": "1 utilisation enregistrée",
  "lookup.uses": "Utilisations",
  "lookup.usesLeft": "Utilisations restantes",
  "lookup.validUntil": "Valable jusqu’au",
  "lookup.what": "De quoi il s’agit",
  "lookup.why.cancelled": "Annulé · ne peut pas être utilisé",
  "lookup.why.codeUsedUp": "Toutes les utilisations de ce code sont prises",
  "lookup.why.empty": "Il ne reste rien dessus",
  "lookup.why.expired": "Expiré",
  "lookup.why.expiredOn": "Expiré le {date}",
  "lookup.why.inactive": "Pas encore vendue · elle ne peut pas être dépensée",
  "lookup.why.notSold": "Pas encore vendu · ne peut pas être utilisé",
  "lookup.why.off": "Ce code est désactivé",
  "lookup.why.used": "Déjà utilisé",
  "lookup.why.usedUp": "Toutes les utilisations sont prises",
  "lookup.worth": "Valeur"
};

export const issue: Readonly<Record<string, string>> = {
  "issue.batch.again": "Vous pouvez les télécharger de nouveau depuis Séries de bons.",
  "issue.batch.count": "Combien",
  "issue.batch.countRange": "De 1 à {max}",
  "issue.batch.download": "Télécharger les codes (CSV)",
  "issue.batch.expiresNeeded": "Indiquez quand les codes cessent de fonctionner.",
  "issue.batch.made": "{count} codes créés",
  "issue.batch.making": "Création des codes",
  "issue.batch.name": "Nom de la série",
  "issue.batch.nameNeeded": "Donnez un nom à la série.",
  "issue.batch.open": "Ouvrir la série",
  "issue.batch.part": "{made} créés sur {count}. Terminez-la dans Séries de bons.",
  "issue.batch.progress": "{made} sur {count}",
  "issue.batch.readBack": "{count, plural, one {# code valable} other {# codes valables}} une seule fois, jusqu’au {date}",
  "issue.batch.save": "Créer les codes",
  "issue.card.amount": "Montant",
  "issue.card.amountNeeded": "Saisissez un montant supérieur à zéro.",
  "issue.card.amountRange": "De {min} à {max}",
  "issue.card.byCard": "Carte bancaire",
  "issue.card.cash": "Espèces",
  "issue.card.dateAhead": "Choisissez un jour à partir de demain.",
  "issue.card.emailNeeded": "Saisissez un e-mail, ou choisissez de ne pas l’envoyer.",
  "issue.card.issued": "Carte cadeau émise",
  "issue.card.message": "Un message",
  "issue.card.messageLeft": "{n} sur {max}",
  "issue.card.notSent": "Non envoyée",
  "issue.card.other": "Autre",
  "issue.card.paidBy": "Payé par",
  "issue.card.paidHint": "Enregistré comme vendu au comptoir · Rien n’est débité ici",
  "issue.card.paused": "Les cartes cadeaux sont en cours de reprise depuis la caisse. Réessayez une fois l’opération terminée.",
  "issue.card.queuedFor": "Envoi prévu le {date}",
  "issue.card.queuedNow": "Envoi mis en file d’attente",
  "issue.card.save": "Émettre la carte",
  "issue.card.send": "Envoyer",
  "issue.card.sendDay": "L’envoyer le",
  "issue.card.sendNone": "Ne pas envoyer, je l’imprimerai",
  "issue.card.sendNow": "Maintenant",
  "issue.card.sendOn": "À une date",
  "issue.card.sending": "Envoi",
  "issue.done": "Terminé",
  "issue.email": "E-mail",
  "issue.emailWrong": "Ce n’est pas une adresse e-mail.",
  "issue.expires": "À utiliser jusqu’au",
  "issue.expiresAhead": "Choisissez aujourd’hui ou un jour ultérieur.",
  "issue.expiresHint": "Laissez vide pour un bon qui n’expire jamais.",
  "issue.fixes": "{n, plural, one {# point est} other {# points sont}} à corriger",
  "issue.for": "Pour",
  "issue.from": "De la part de",
  "issue.never": "N’expire jamais",
  "issue.notAllowed": "Votre rôle ne permet pas d’émettre.",
  "issue.note": "Note",
  "issue.noteHint": "Réservée au personnel.",
  "issue.print": "Imprimer",
  "issue.result.code": "Le code",
  "issue.result.noCode": "Un responsable peut consulter son code.",
  "issue.result.once": "Le code complet n’est affiché que cette seule fois.",
  "issue.subtitle": "Une carte cadeau, un bon ou une série de codes",
  "issue.tab.batch": "Série de codes",
  "issue.tab.card": "Carte cadeau",
  "issue.tab.voucher": "Bon",
  "issue.tabs": "Que souhaitez-vous émettre",
  "issue.title": "Émettre",
  "issue.voucher.bearer": "La personne qui le détient",
  "issue.voucher.emailNeeded": "Un bon nominatif a besoin de l’e-mail de la personne.",
  "issue.voucher.holder": "Nom",
  "issue.voucher.issued": "Bon émis",
  "issue.voucher.name": "Intitulé",
  "issue.voucher.nameHint": "Ce que voit le client, sur le bon et sur sa commande.",
  "issue.voucher.nameNeeded": "Indiquez l’intitulé du bon.",
  "issue.voucher.named": "Une personne désignée",
  "issue.voucher.namedHint": "Ce client uniquement, connecté ou désigné par le personnel",
  "issue.voucher.packIssued": "Forfait émis",
  "issue.voucher.save": "Émettre le bon",
  "issue.why": "Motif",
  "issue.whyNeeded": "Indiquez le motif.",
  "issue.worth.amount": "Un montant",
  "issue.worth.amountHint": "Déduit ce montant d’une commande",
  "issue.worth.amountValue": "Montant",
  "issue.worth.change": "Modifier",
  "issue.worth.choose": "Choisir…",
  "issue.worth.label": "Valeur",
  "issue.worth.noTables": "Rien ici n’indique encore ce que vendent ses lignes.",
  "issue.worth.noTablesBody": "Ajoutez d’abord une règle dans Règles des offres.",
  "issue.worth.noneFound": "Aucun résultat.",
  "issue.worth.pack": "Un forfait",
  "issue.worth.packHint": "Plusieurs utilisations d’une même prestation",
  "issue.worth.percent": "Un pourcentage",
  "issue.worth.percentHint": "Déduit cette part d’une commande",
  "issue.worth.percentMax": "Un pourcentage est de 100 au maximum.",
  "issue.worth.percentValue": "Pourcentage",
  "issue.worth.search": "Rechercher par nom",
  "issue.worth.table": "Dans",
  "issue.worth.thing": "Un article précis",
  "issue.worth.thingHint": "Paie un article précis",
  "issue.worth.thingNeeded": "Choisissez ce à quoi il donne droit.",
  "issue.worth.uses": "Utilisations",
  "issue.worth.usesHint": "De 2 à 50",
  "issue.worth.usesRange": "Un forfait compte de 2 à 50 utilisations.",
  "issue.worth.valueNeeded": "Saisissez une valeur supérieure à zéro.",
  "issue.worth.what": "Ce à quoi il donne droit"
};

export const rules: Readonly<Record<string, string>> = {
  "rules.add": "Ajouter une règle",
  "rules.edit": "Modifier",
  "rules.from": "Fournie par {app}",
  "rules.holding": "{rows, plural, one {# enregistrement retient} other {# enregistrements retiennent}} une utilisation ou un paiement par carte.",
  "rules.inFile": "Cette règle a été définie dans un fichier du projet. Modifiez-la à cet endroit.",
  "rules.kind.discounts": "Accepte les remises",
  "rules.kind.moved": "A repris d’anciennes cartes cadeaux",
  "rules.kind.pays": "Accepte une carte cadeau en paiement",
  "rules.kind.refunds": "Rend un paiement par carte",
  "rules.kind.sellsCards": "Vend ou recharge une carte cadeau",
  "rules.kind.sellsVouchers": "Vend un bon ou un forfait",
  "rules.kind.uses": "Enregistre ce qui a été utilisé",
  "rules.kindHint.discounts": "Commandes, réservations, billets : tout ce qu’une remise ou un code peut réduire.",
  "rules.kindHint.pays": "Une table de paiements, où un enregistrement peut désigner une carte cadeau.",
  "rules.kindHint.sellsCards": "Une table de lignes de vente, où une ligne peut désigner la carte qu’elle charge.",
  "rules.kindHint.sellsVouchers": "Une table de lignes de vente, où une ligne peut désigner le bon qu’elle vend.",
  "rules.make.amounts": "Le créer : laisser Adminium ajouter le montant, le sous-total, la réduction et le total, ainsi que les règles qui les calculent",
  "rules.make.codes": "La créer : ajouter une table pour les codes saisis sur un enregistrement",
  "rules.make.column": "{column} dans {table}",
  "rules.make.save": "Ajouter ces éléments et enregistrer",
  "rules.make.table": "la table {table}",
  "rules.make.title": "Adminium ajoutera ceci, avec la règle",
  "rules.none.body": "Une application qui accepte les remises ou les cartes cadeaux apporte ses propres règles. Pour une table à vous, ajoutez une règle.",
  "rules.none.title": "Aucune table n’est encore concernée par les offres",
  "rules.on": "Activée",
  "rules.part.back": "C’est annulé",
  "rules.part.balanceAfter": "Ce que la carte contient ensuite",
  "rules.part.cardLoads": "La carte cadeau qu’elle charge",
  "rules.part.cardPays": "La carte cadeau qui paie",
  "rules.part.category": "Sa catégorie, si la ligne en désigne une",
  "rules.part.final": "L’enregistrement est définitif",
  "rules.part.finalHint": "Ce qui a été utilisé est alors enregistré, et le prix n’est plus jamais recalculé.",
  "rules.part.item": "Ce que vend la ligne",
  "rules.part.itemHint": "Un lien vers l’article vendu. Sans lui, une remise sur des articles précis ne s’applique pas ici ; une remise sur toute la commande s’applique toujours.",
  "rules.part.lineDiscount": "La réduction de la ligne",
  "rules.part.lines": "Ses lignes sont des enregistrements de",
  "rules.part.load": "Le montant qu’elle charge",
  "rules.part.orderDiscount": "La réduction propre à l’enregistrement",
  "rules.part.paid": "Ce que la carte a payé",
  "rules.part.price": "Le prix de la ligne",
  "rules.part.quantity": "La quantité de la ligne",
  "rules.part.refundAmount": "Le montant rendu",
  "rules.part.refundRow": "Son lien vers le paiement",
  "rules.part.refunds": "L’argent rendu est un enregistrement de",
  "rules.part.sold": "Son prix de vente",
  "rules.part.taxLater": "La taxe est appliquée au moment de l’utilisation",
  "rules.part.total": "Le total de l’enregistrement",
  "rules.part.type": "Son type, si la ligne en désigne un",
  "rules.part.undone": "Ce qui a été utilisé est rendu",
  "rules.part.voucher": "Le bon qu’elle vend",
  "rules.part.whenLoads": "La carte est chargée",
  "rules.part.whenPays": "La carte paie",
  "rules.part.whenSold": "Le bon est vendu",
  "rules.part.written": "Adminium l’écrit.",
  "rules.point.create": "l’enregistrement est créé",
  "rules.point.in": "{column} devient {values}",
  "rules.point.never": "jamais",
  "rules.point.set": "{column} reçoit une valeur",
  "rules.point.to": "il passe à {states}",
  "rules.readOnly": "Seule une personne autorisée à modifier la façon dont Adminium calcule les colonnes d’une table peut changer ces règles.",
  "rules.remove": "Supprimer la règle",
  "rules.remove.confirm": "Supprimer cette règle ? Les enregistrements de cette table ne seront plus concernés par les offres.",
  "rules.removed": "Règle supprimée de {table}",
  "rules.removedPart": "Règle supprimée de {table}. {why}",
  "rules.saved": "Règle enregistrée pour {table}",
  "rules.saved.new": "Règle ajoutée pour {table}",
  "rules.says.back": "C’est annulé quand {when}.",
  "rules.says.discounts": "Les remises et les codes sont calculés pour chaque enregistrement, ligne par ligne à partir de {lines}.",
  "rules.says.moved": "Les cartes cadeaux conservées ici auparavant ont été reprises. Adminium le fait une seule fois.",
  "rules.says.noColumn": "aucune colonne",
  "rules.says.noUses": "Ce qui a été utilisé n’est pas enregistré : les limites par utilisation ne sont pas tenues.",
  "rules.says.pays": "Un enregistrement qui désigne une carte cadeau dans {card} est payé avec la carte quand {when} ; ce que la carte a payé est écrit dans {amount}.",
  "rules.says.refunds": "Un enregistrement rend {amount} à la carte qui a payé, quand {when}.",
  "rules.says.sellsCards": "Un enregistrement qui désigne une carte cadeau dans {card} y charge {amount} quand {when}.",
  "rules.says.sellsVouchers": "Un enregistrement qui désigne un bon dans {voucher} le marque comme vendu quand {when}.",
  "rules.says.uses": "Ce qui a été utilisé est enregistré quand {when}, et rendu quand {back}.",
  "rules.says.usesAlone": "Ce qui a été utilisé est enregistré quand {when}, bien que cette table n’accepte plus les remises. Supprimez cette règle, ou ajoutez de nouveau la règle des remises.",
  "rules.says.usesKept": "Ce qui a été utilisé est enregistré quand {when}, et n’est jamais rendu.",
  "rules.sheet.add": "Ajouter une règle",
  "rules.sheet.cannotMake": "Adminium ne peut pas ajouter ce qui manque ici : {reasons}",
  "rules.sheet.chooseColumn": "Choisir une colonne",
  "rules.sheet.chooseTable": "Choisir une table",
  "rules.sheet.edit": "Modifier la règle",
  "rules.sheet.err.needed": "Choisissez une colonne.",
  "rules.sheet.err.part": "Choisissez une colonne, ou laissez Adminium l’ajouter.",
  "rules.sheet.err.refunds": "Choisissez aussi le lien vers le paiement et le montant.",
  "rules.sheet.err.table": "Choisissez une table",
  "rules.sheet.err.when": "Complétez chaque « quand » que vous avez choisi",
  "rules.sheet.err.whenNeeded": "Choisissez quand, et complétez ce choix.",
  "rules.sheet.kind": "Ce que fait la table",
  "rules.sheet.noCardLink": "Cette table n’a aucun lien vers Cartes cadeaux. Ajoutez-en un d’abord, dans les colonnes de la table.",
  "rules.sheet.noLines": "Aucune table n’est liée à celle-ci. Une table qui accepte les remises a besoin d’une table de lignes.",
  "rules.sheet.noRefunds": "Aucune table de remboursements",
  "rules.sheet.noVoucherLink": "Cette table n’a aucun lien vers Bons. Ajoutez-en un d’abord, dans les colonnes de la table.",
  "rules.sheet.notNeeded": "Pas nécessaire",
  "rules.sheet.one": "Une unité par ligne",
  "rules.sheet.reads": "Se lit ainsi",
  "rules.sheet.save": "Enregistrer la règle",
  "rules.sheet.table": "Table",
  "rules.subtitle": "Le lien entre vos propres tables et les remises, les bons et les cartes cadeaux",
  "rules.switchedOff": "Règle {table} désactivée",
  "rules.switchedOn": "Règle {table} activée",
  "rules.title": "Règles des offres",
  "rules.unavailable": "Cette règle ne peut pas s’exécuter pour le moment : Offers est désactivé ou ne répond pas.",
  "rules.when.becomes": "Quand une colonne devient",
  "rules.when.column": "{label} : quelle colonne",
  "rules.when.create": "Quand l’enregistrement est créé",
  "rules.when.moves": "Quand {table} passe à",
  "rules.when.never": "Jamais",
  "rules.when.set": "Quand une colonne reçoit une valeur",
  "rules.yours": "Votre table"
};
