/** Simplified Chinese strings for the Offers screens. Keys are those of en-US.ts. */
export const shared: Readonly<Record<string, string>> = {
  "shared.cancel": "取消",
  "shared.close": "关闭",
  "shared.failed.title": "无法加载此内容",
  "shared.loading": "正在加载",
  "shared.refused.body": "如有需要，请联系经理。",
  "shared.refused.title": "你没有权限打开此页面",
  "shared.retry": "重试"
};

export const refusal: Readonly<Record<string, string>> = {
  "refusal.askManager": "请联系经理。",
  "refusal.askToPrint": "请让经理打印。",
  "refusal.batchFull": "此批次的券码已全部生成。",
  "refusal.cardPaysCard": "出售礼品卡的表不能同时用礼品卡收款。",
  "refusal.codeTaken": "该优惠码已被另一个折扣使用。",
  "refusal.conflict": "有人同时修改了此内容。未保存任何更改。请重试。",
  "refusal.empty": "卡内余额不足。",
  "refusal.emptyLeft": "卡内还剩 {left}。请扣除 {left} 或更少。",
  "refusal.expired": "已过期。未保存任何更改。",
  "refusal.forbidden": "你没有权限执行此操作。",
  "refusal.inactive": "此卡尚未售出，无法使用。",
  "refusal.noAnswer": "Offers 没有响应。未保存任何更改。",
  "refusal.noPrint": "暂时无法打印。",
  "refusal.notAllowed": "此处不允许这样做。",
  "refusal.notFound": "此内容已不存在。",
  "refusal.off": "Offers 目前已停用。",
  "refusal.other": "无法保存。请重试。",
  "refusal.overLimit": "已超出限额。未保存任何更改。",
  "refusal.rate": "尝试次数过多。请稍等一分钟。",
  "refusal.receiptOpen": "{rows, plural, other {# 行}}仍占用着一次使用或一笔卡支付：请先退回。",
  "refusal.usedUp": "次数已全部用完。未保存任何更改。",
  "refusal.void": "已作废。未保存任何更改。"
};

export const discounts: Readonly<Record<string, string>> = {
  "discounts.aGroup": "某个顾客分组",
  "discounts.all": "全部折扣",
  "discounts.allDay": "全天",
  "discounts.anyone": "所有人",
  "discounts.applies.lines": "仅限这些商品",
  "discounts.applies.linesHint": "商品、类别或类型",
  "discounts.applies.order": "整笔订单",
  "discounts.applies.orderHint": "购物篮中的全部商品",
  "discounts.applies.orderNo": "这种折扣需要指定商品",
  "discounts.budget": "优惠累计达到此金额后停止",
  "discounts.changeItems": "更改",
  "discounts.check.amount": "请输入金额，例如 5.00。",
  "discounts.check.buy": "请输入 2 到 10 之间的数字。",
  "discounts.check.code": "请输入优惠码，或自动生成一个。",
  "discounts.check.count": "请输入不小于 1 的整数。",
  "discounts.check.hours": "请填写两个时间，或打开“全天”。",
  "discounts.check.hoursOrder": "“结束”必须晚于“开始”。",
  "discounts.check.name": "请起一个团队成员都能认出的名称。",
  "discounts.check.noSteps": "请至少添加一档。",
  "discounts.check.percent": "请输入 1 到 100 之间的百分比。",
  "discounts.check.price": "请输入价格，例如 10.00。",
  "discounts.check.publicName": "请填写顾客在小票上看到的那一行文字。",
  "discounts.check.stepFrom": "每一档的起始数量须为 2 或以上。",
  "discounts.check.stepMore": "优惠幅度须高于上一档（{n}%）。",
  "discounts.check.stepRising": "每一档的起始数量须高于上一档（{n} 件）。",
  "discounts.check.targets": "请至少选择一个商品、类别或类型。",
  "discounts.check.until": "“结束”早于“开始”，此折扣将永远无法生效。请选择“开始”当天或之后的日期。",
  "discounts.check.usesTaken": "已使用 {n} 次。请输入 {n} 或更大的数字。",
  "discounts.chooseItems": "选择商品",
  "discounts.code": "优惠码",
  "discounts.codeHint": "字母和数字。顾客在结账时输入，或在收银台报出。",
  "discounts.codeMade": "已生成优惠码 {code}",
  "discounts.col.given": "已优惠",
  "discounts.col.gives": "优惠内容",
  "discounts.col.limits": "限制",
  "discounts.col.name": "名称",
  "discounts.col.starts": "生效方式",
  "discounts.col.status": "状态",
  "discounts.col.uses": "使用次数",
  "discounts.combinable": "可叠加",
  "discounts.combineOff": "单独使用，仅当它比其他折扣加起来更优惠时才生效。",
  "discounts.combineOn": "与同一订单上其他可叠加的折扣一并生效。",
  "discounts.count": "{n, plural, other {# 个折扣}} · 截至目前的使用次数和优惠金额",
  "discounts.days": "星期几",
  "discounts.daysHint": "不选表示每天。",
  "discounts.each": "每件",
  "discounts.empty.body": "折扣可为订单减价：自动生效、凭优惠码生效，或由员工给予。",
  "discounts.empty.title": "尚无折扣",
  "discounts.end.body": "它将立即停止生效。",
  "discounts.end.title": "现在结束“{name}”吗？",
  "discounts.endNow": "立即结束",
  "discounts.ended.body": "选一个更晚的结束日期，即可再次启用。",
  "discounts.ended.title": "此折扣已结束",
  "discounts.endedNow": "“{name}”已结束",
  "discounts.fewerLanguages": "收起语言",
  "discounts.firstOrder": "仅限首单",
  "discounts.fix": "保存前请修正{n, plural, other {# 处}}",
  "discounts.fixes": "有{n, plural, other {# 处}}需要修正后才能保存。",
  "discounts.from": "开始",
  "discounts.fromHint": "从当天开始时起，按门店时间。",
  "discounts.fromTime": "开始时间，如 09:00",
  "discounts.givenSoFar": "目前已优惠 {amount}",
  "discounts.gives.amount": "减 {amount}",
  "discounts.gives.amountOn": "{what}减 {amount}",
  "discounts.gives.bonus": "买 {buy} 付 {pay}",
  "discounts.gives.bonusOn": "{what}买 {buy} 付 {pay}",
  "discounts.gives.percent": "减 {n}%",
  "discounts.gives.percentOn": "{what}减 {n}%",
  "discounts.gives.price": "每件 {amount}",
  "discounts.gives.priceOn": "{what}每件 {amount}",
  "discounts.gives.steps": "买得越多，优惠越多",
  "discounts.gives.stepsOn": "{what}买得越多，优惠越多",
  "discounts.group": "顾客分组",
  "discounts.hoursHint": "时段不能跨过午夜。",
  "discounts.houseRule": "顾客可享受所有可叠加的折扣和一个优惠码；其余折扣中只取最优惠的一个。",
  "discounts.kind.amount": "立减金额",
  "discounts.kind.bonus": "买二付一及类似优惠",
  "discounts.kind.percent": "按百分比减价",
  "discounts.kind.price": "固定价格",
  "discounts.kind.steps": "按数量定价",
  "discounts.leave.body": "你所做的更改将会丢失。",
  "discounts.leave.go": "离开",
  "discounts.leave.stay": "继续编辑",
  "discounts.leave.title": "不保存就离开吗？",
  "discounts.limit.first": "仅限首单",
  "discounts.limit.from": "满 {amount}",
  "discounts.limit.perCustomer": "每位顾客 {n} 次",
  "discounts.limit.until": "至 {date}",
  "discounts.limit.uses": "{n, plural, other {# 次}}",
  "discounts.lookAlike": "{typed} 看起来很像 {code}（{name}）。顾客可能会混淆。",
  "discounts.makeCode": "帮我生成一个",
  "discounts.maxUses": "总使用次数",
  "discounts.minQty": "最低数量",
  "discounts.minQtyHint": "按适用商品计算。",
  "discounts.minSpend": "最低消费",
  "discounts.minSpendHint": "按商品金额计算，已扣除排在它之前的优惠。",
  "discounts.missing": "找不到此折扣",
  "discounts.missingBody": "它可能已被移除，或者你无权查看。",
  "discounts.more": "更多",
  "discounts.moreCodes": "此折扣有 {n} 个优惠码。其余的在“优惠码”中。",
  "discounts.moreLanguages": "更多语言",
  "discounts.name": "名称（内部使用）",
  "discounts.never": "永远无法生效",
  "discounts.new": "新建折扣",
  "discounts.newTitle": "新建折扣",
  "discounts.noMap": "无法读取你的表出售的内容，因此不能选择商品，也不能试算此折扣。",
  "discounts.noTables": "这里还没有说明明细行出售什么的规则。请先在“优惠规则”中添加一条规则。",
  "discounts.notLive": "尚未生效",
  "discounts.pause": "暂停",
  "discounts.pauseUnsaved": "暂停（你的更改不会保存）",
  "discounts.paused": "“{name}”已暂停",
  "discounts.perCustomer": "每位顾客可用次数",
  "discounts.pick.addTag": "添加",
  "discounts.pick.chosen": "已选 {n} 项",
  "discounts.pick.done": "完成",
  "discounts.pick.none": "没有符合搜索的内容。",
  "discounts.pick.search": "搜索",
  "discounts.pick.subtitle": "来自“优惠规则”中设为可用折扣的表。",
  "discounts.pick.tabCount": "{label} · {n}",
  "discounts.pick.tabs": "从哪里选择",
  "discounts.pick.tag": "标签，按明细行上的写法填写",
  "discounts.pick.tags": "标签",
  "discounts.pick.title": "选择适用范围",
  "discounts.pill.active": "生效中",
  "discounts.pill.draft": "草稿",
  "discounts.pill.ended": "已结束",
  "discounts.pill.paused": "已暂停",
  "discounts.pill.usedUp": "已用完",
  "discounts.publicName": "顾客看到的名称",
  "discounts.publicNameHint": "小票上的那一行文字。",
  "discounts.publicNameIn": "顾客看到的名称 · {language}",
  "discounts.ranAgain": "“{name}”已再次启用，至 {date}",
  "discounts.readOnly": "你可以查看此折扣。经理可以修改。",
  "discounts.resume": "恢复",
  "discounts.resumeUnsaved": "恢复（你的更改不会保存）",
  "discounts.resumed": "“{name}”已恢复",
  "discounts.run.ahead": "请选择今天或之后的日期。",
  "discounts.run.hint": "它将持续到当天结束。",
  "discounts.run.title": "再次启用“{name}”",
  "discounts.run.until": "结束",
  "discounts.runAgain": "再次启用",
  "discounts.save": "保存",
  "discounts.saveDraft": "保存草稿",
  "discounts.saved": "“{name}”已保存",
  "discounts.section.applies": "适用范围",
  "discounts.section.combine": "与其他折扣",
  "discounts.section.gives": "优惠内容",
  "discounts.section.limits": "限制",
  "discounts.section.name": "名称",
  "discounts.section.starts": "生效方式",
  "discounts.section.when": "时间",
  "discounts.section.who": "适用对象",
  "discounts.signedInOnly": "仅限已登录的顾客，或由员工指定的顾客。访客不能享受。",
  "discounts.staffNote": "会显示在收银台的折扣列表中。员工限额和原因仍然适用。",
  "discounts.starts.code": "优惠码",
  "discounts.starts.codes": "{n} 个优惠码",
  "discounts.starts.itself": "自动生效",
  "discounts.starts.itselfHint": "订单符合条件时生效",
  "discounts.starts.staff": "仅限员工",
  "discounts.starts.staffHint": "在收银台选择",
  "discounts.starts.staffOnly": "只有员工可以给予",
  "discounts.starts.withCode": "凭优惠码",
  "discounts.starts.withCodeHint": "顾客提供优惠码",
  "discounts.steps.add": "添加一档",
  "discounts.steps.from": "起始数量",
  "discounts.steps.off": "减价百分比",
  "discounts.steps.remove": "移除这一档",
  "discounts.steps.rule": "适用商品买得越多，优惠越大。以达到的最高一档为准。",
  "discounts.switchOn": "启用",
  "discounts.switchedOn": "“{name}”已启用",
  "discounts.targets.more": "{first} 等另外 {n} 项",
  "discounts.title": "折扣",
  "discounts.toTime": "结束时间，如 17:00",
  "discounts.totals": "{uses, plural, other {# 次使用}} · 已优惠 {given}",
  "discounts.try.asIfOn": "草稿会按已启用的状态试算。",
  "discounts.try.bar": "试算 · {n, plural, other {# 个折扣}}",
  "discounts.try.barTotal": "试算 · {n, plural, other {# 个折扣}} · {total}",
  "discounts.try.better": "改用了“{name}”：它更优惠。",
  "discounts.try.buyer": "购买者",
  "discounts.try.code": "结账时的优惠码",
  "discounts.try.customer": "已登录的顾客",
  "discounts.try.draftName": "{name}（草稿）",
  "discounts.try.failed": "无法试算",
  "discounts.try.guest": "访客",
  "discounts.try.minus": "−{amount}",
  "discounts.try.noCode": "无优惠码",
  "discounts.try.noRows": "那里还没有保存任何内容。",
  "discounts.try.none": "还没有可用折扣的表",
  "discounts.try.noneBody": "指定你的哪张表可用折扣后，就能在它的行上试算此折扣。",
  "discounts.try.notApplied": "未生效",
  "discounts.try.nothing": "没有折扣适用于此订单。",
  "discounts.try.off": "订单已减",
  "discounts.try.refused": "{code}：{why}",
  "discounts.try.row": "试算对象",
  "discounts.try.rowHint": "“{table}”中已保存的一行",
  "discounts.try.rules": "优惠规则",
  "discounts.try.taxLater": "税款在保存订单时计入",
  "discounts.try.title": "试算",
  "discounts.try.total": "合计",
  "discounts.try.unnamed": "某个折扣",
  "discounts.try.whyNot": "{name} — {why}",
  "discounts.until": "结束（可选）",
  "discounts.untilHint": "到当天结束时止，按门店时间。",
  "discounts.usedUp.body": "提高上限之前只能查看。",
  "discounts.usedUp.raise": "提高上限",
  "discounts.usedUp.title": "{n} 次已全部用完",
  "discounts.usesSoFar": "已使用 {n} 次",
  "discounts.value.amount": "立减金额",
  "discounts.value.amountHint": "不会超过适用商品的金额。",
  "discounts.value.buy": "购买数量",
  "discounts.value.cheaper": "较便宜的那件由我们承担。",
  "discounts.value.cheapest": "最便宜的那件由我们承担。",
  "discounts.value.percent": "减价百分比",
  "discounts.value.price": "每件售价",
  "discounts.value.priceHint": "原本就更便宜的商品保持原价。",
  "discounts.why.alone": "另一个折扣更优惠，而它只能单独使用",
  "discounts.why.cancelled": "它已被取消",
  "discounts.why.days": "今天不在适用日期内",
  "discounts.why.draft": "它还是草稿",
  "discounts.why.ended": "它已结束",
  "discounts.why.first": "这不是首单",
  "discounts.why.group": "顾客不在它的分组内",
  "discounts.why.hours": "现在不在适用时段内",
  "discounts.why.items": "此订单中没有它适用的商品",
  "discounts.why.limit": "已超出限制",
  "discounts.why.minimum": "订单未达到它的最低消费",
  "discounts.why.noCode": "需要它的优惠码",
  "discounts.why.notYet": "它尚未开始",
  "discounts.why.paused": "它已暂停",
  "discounts.why.quantity": "它适用的商品数量不够",
  "discounts.why.signIn": "需要已登录的顾客",
  "discounts.why.unknown": "它在此处不适用",
  "discounts.why.usedUp": "次数已全部用完"
};

export const lookup: Readonly<Record<string, string>> = {
  "lookup.addCredit": "增加储值",
  "lookup.added": "已增加 {amount}",
  "lookup.adjust": "调整",
  "lookup.askManager": "经理可以充值、调整或作废。",
  "lookup.batch": "批次",
  "lookup.cancelCard": "作废此卡",
  "lookup.cancelled": "尾号 {last4} 的卡已作废",
  "lookup.code": "券码",
  "lookup.col.amount": "金额",
  "lookup.col.date": "日期",
  "lookup.col.leftAfter": "之后余额",
  "lookup.col.what": "内容",
  "lookup.col.where": "位置",
  "lookup.creditGiven": "已向 {address} 给予 {amount} 储值",
  "lookup.dialog.add": "增加",
  "lookup.dialog.adjust": "调整尾号 {last4} 的卡",
  "lookup.dialog.amount": "金额",
  "lookup.dialog.amountNeeded": "请输入大于零的金额。",
  "lookup.dialog.byCard": "刷卡",
  "lookup.dialog.cancel": "作废尾号 {last4} 的卡吗？",
  "lookup.dialog.cancelBody": "卡内余额将无法再使用。此操作无法撤销。",
  "lookup.dialog.cash": "现金",
  "lookup.dialog.credit": "向 {address} 给予储值",
  "lookup.dialog.creditMail": "系统会发邮件通知顾客。",
  "lookup.dialog.creditMore": "为 {address} 增加储值",
  "lookup.dialog.direction": "增加或扣除",
  "lookup.dialog.movesTo": "有效期将改为 {date}",
  "lookup.dialog.other": "其他",
  "lookup.dialog.paidBy": "支付方式",
  "lookup.dialog.paidHint": "记为已在柜台收款。此处不会扣款。",
  "lookup.dialog.remove": "扣除",
  "lookup.dialog.topUp": "为尾号 {last4} 的卡充值",
  "lookup.dialog.upTo": "此卡余额最多为 {max}。",
  "lookup.dialog.why": "原因",
  "lookup.dialog.whyHint": "会保存在此卡的记录中。",
  "lookup.dialog.whyNeeded": "请填写原因。",
  "lookup.discount": "折扣",
  "lookup.failed": "无法查询",
  "lookup.field.empty": "请先输入或扫描券码。",
  "lookup.field.label": "输入或扫描券码，或输入顾客的邮箱",
  "lookup.field.placeholder": "GC-7K2M-W3HN-Q4XP 或 name@example.com",
  "lookup.for": "接收人",
  "lookup.from": "赠送人",
  "lookup.giveCredit": "给予储值",
  "lookup.go": "查询",
  "lookup.issue": "发放",
  "lookup.issued": "发放时间",
  "lookup.kind.card": "礼品卡",
  "lookup.kind.code": "优惠码",
  "lookup.kind.credit": "储值",
  "lookup.kind.pack": "次卡",
  "lookup.kind.voucher": "代金券",
  "lookup.left": "剩余",
  "lookup.leftOf": "{left} / {total}",
  "lookup.markUsed": "标记为已使用",
  "lookup.markedUsed": "已标记为已使用",
  "lookup.moved": "旧卡 · 仅可在有员工值守的柜台使用",
  "lookup.never": "永不过期",
  "lookup.noActivity": "尚无任何记录。",
  "lookup.noUses": "尚未使用。",
  "lookup.none.address": "{typed} 没有储值",
  "lookup.none.addressBody": "此地址名下没有储值。",
  "lookup.none.code": "没有使用此券码的内容 · {typed}",
  "lookup.none.codeBody": "请核对字符，或换一个券码再试。",
  "lookup.openBatch": "打开批次",
  "lookup.openDiscount": "打开折扣",
  "lookup.percent": "{n}%",
  "lookup.pill.active": "有效",
  "lookup.pill.cancelled": "已作废",
  "lookup.pill.doesNot": "目前不可用",
  "lookup.pill.expired": "已过期",
  "lookup.pill.inactive": "未激活",
  "lookup.pill.notSold": "尚未售出",
  "lookup.pill.notUsed": "未使用",
  "lookup.pill.used": "已使用",
  "lookup.pill.usedUp": "已用完",
  "lookup.pill.works": "可用",
  "lookup.print": "打印",
  "lookup.printing": "已打开以便打印",
  "lookup.queued": "已排队，等待重新发送",
  "lookup.queuedFor": "已排队，将发送给 {name}",
  "lookup.removed": "已扣除 {amount}",
  "lookup.row.adjust": "调整",
  "lookup.row.expire": "过期",
  "lookup.row.issue": "发放",
  "lookup.row.refund": "退回",
  "lookup.row.spend": "消费",
  "lookup.row.topUp": "充值",
  "lookup.row.void": "作废",
  "lookup.said.card": "礼品卡，尾号 {last4}，{pill}，剩余 {amount}",
  "lookup.said.cardNoBalance": "礼品卡，尾号 {last4}，{pill}",
  "lookup.said.code": "可用的优惠码",
  "lookup.said.codeNot": "目前不可用的优惠码",
  "lookup.said.credit": "储值，{pill}，剩余 {amount}",
  "lookup.said.nothing": "没有使用此券码的内容",
  "lookup.said.pack": "次卡，尾号 {last4}，{pill}，剩余 {left} / {total}",
  "lookup.said.voucher": "代金券，尾号 {last4}，{pill}",
  "lookup.sendAgain": "重新发送",
  "lookup.start.body": "扫描礼品卡或代金券上的券码，或手动输入。查询储值请输入顾客的邮箱。",
  "lookup.start.title": "尚未查询",
  "lookup.subtitle": "礼品卡、代金券、次卡、优惠码和储值",
  "lookup.title": "查询",
  "lookup.topUp": "充值",
  "lookup.toppedUp": "已充值 {amount}",
  "lookup.use.counted": "已使用",
  "lookup.use.givenBack": "已退回",
  "lookup.use.held": "已占用",
  "lookup.useBy": "有效期至",
  "lookup.useOne": "现在使用一次",
  "lookup.useRecorded": "已记录 1 次使用",
  "lookup.uses": "使用记录",
  "lookup.usesLeft": "剩余次数",
  "lookup.validUntil": "可用至",
  "lookup.what": "类型",
  "lookup.why.cancelled": "已作废 · 无法使用",
  "lookup.why.codeUsedUp": "此优惠码的次数已全部用完",
  "lookup.why.empty": "卡内已无余额",
  "lookup.why.expired": "已过期",
  "lookup.why.expiredOn": "已于 {date} 过期",
  "lookup.why.inactive": "尚未售出 · 无法消费",
  "lookup.why.notSold": "尚未售出 · 无法使用",
  "lookup.why.off": "此优惠码已停用",
  "lookup.why.used": "已使用",
  "lookup.why.usedUp": "次数已全部用完",
  "lookup.worth": "面值"
};

export const issue: Readonly<Record<string, string>> = {
  "issue.batch.again": "可在“代金券批次”中再次下载。",
  "issue.batch.count": "数量",
  "issue.batch.countRange": "1 到 {max}",
  "issue.batch.download": "下载券码 (CSV)",
  "issue.batch.expiresNeeded": "请填写券码何时失效。",
  "issue.batch.made": "已生成 {count} 个券码",
  "issue.batch.making": "正在生成券码",
  "issue.batch.name": "批次名称",
  "issue.batch.nameNeeded": "请为批次命名。",
  "issue.batch.open": "打开批次",
  "issue.batch.part": "已生成 {made} / {count}。请在“代金券批次”中完成。",
  "issue.batch.progress": "{made} / {count}",
  "issue.batch.readBack": "{count, plural, other {# 个券码}}，每个可用一次，有效期至 {date}",
  "issue.batch.save": "生成券码",
  "issue.card.amount": "金额",
  "issue.card.amountNeeded": "请输入大于零的金额。",
  "issue.card.amountRange": "{min} 到 {max}",
  "issue.card.byCard": "刷卡",
  "issue.card.cash": "现金",
  "issue.card.dateAhead": "请选择明天或之后的日期。",
  "issue.card.emailNeeded": "请输入邮箱，或选择不发送。",
  "issue.card.issued": "礼品卡已发放",
  "issue.card.message": "留言",
  "issue.card.messageLeft": "{n} / {max}",
  "issue.card.notSent": "未发送",
  "issue.card.other": "其他",
  "issue.card.paidBy": "支付方式",
  "issue.card.paidHint": "记为已在柜台售出 · 此处不会扣款",
  "issue.card.paused": "正在从收银台导入礼品卡。请在导入完成后重试。",
  "issue.card.queuedFor": "已排队，将于 {date} 发送",
  "issue.card.queuedNow": "已排队，即将发送",
  "issue.card.save": "发放礼品卡",
  "issue.card.send": "发送",
  "issue.card.sendDay": "发送日期",
  "issue.card.sendNone": "不发送，我自己打印",
  "issue.card.sendNow": "现在",
  "issue.card.sendOn": "指定日期",
  "issue.card.sending": "发送方式",
  "issue.done": "完成",
  "issue.email": "邮箱",
  "issue.emailWrong": "这不是有效的邮箱地址。",
  "issue.expires": "有效期至",
  "issue.expiresAhead": "请选择今天或之后的日期。",
  "issue.expiresHint": "留空表示代金券永不过期。",
  "issue.fixes": "有{n, plural, other {# 处}}需要修正",
  "issue.for": "接收人",
  "issue.from": "赠送人",
  "issue.never": "永不过期",
  "issue.notAllowed": "你的角色不能发放。",
  "issue.note": "备注",
  "issue.noteHint": "仅员工可见。",
  "issue.print": "打印",
  "issue.result.code": "券码",
  "issue.result.noCode": "经理可以查看它的券码。",
  "issue.result.once": "完整券码只在这里显示一次。",
  "issue.subtitle": "礼品卡、代金券或一批券码",
  "issue.tab.batch": "一批券码",
  "issue.tab.card": "礼品卡",
  "issue.tab.voucher": "代金券",
  "issue.tabs": "发放什么",
  "issue.title": "发放",
  "issue.voucher.bearer": "持券人",
  "issue.voucher.emailNeeded": "发给指定顾客的代金券需要填写对方的邮箱。",
  "issue.voucher.holder": "姓名",
  "issue.voucher.issued": "代金券已发放",
  "issue.voucher.name": "名称",
  "issue.voucher.nameHint": "顾客在代金券和订单上看到的名称。",
  "issue.voucher.nameNeeded": "请填写代金券的名称。",
  "issue.voucher.named": "指定顾客",
  "issue.voucher.namedHint": "仅限这位顾客，须已登录或由员工指定",
  "issue.voucher.packIssued": "次卡已发放",
  "issue.voucher.save": "发放代金券",
  "issue.why": "原因",
  "issue.whyNeeded": "请填写原因。",
  "issue.worth.amount": "金额",
  "issue.worth.amountHint": "从订单中减去这一金额",
  "issue.worth.amountValue": "金额",
  "issue.worth.change": "更改",
  "issue.worth.choose": "请选择…",
  "issue.worth.label": "面值",
  "issue.worth.noTables": "这里还没有说明明细行出售什么的规则。",
  "issue.worth.noTablesBody": "请先在“优惠规则”中添加一条规则。",
  "issue.worth.noneFound": "未找到任何内容。",
  "issue.worth.pack": "次卡",
  "issue.worth.packHint": "某一指定项目的若干次使用",
  "issue.worth.percent": "百分比",
  "issue.worth.percentHint": "从订单中减去这一比例",
  "issue.worth.percentMax": "百分比最大为 100。",
  "issue.worth.percentValue": "百分比",
  "issue.worth.search": "按名称搜索",
  "issue.worth.table": "来源表",
  "issue.worth.thing": "单个项目",
  "issue.worth.thingHint": "抵付某一指定项目",
  "issue.worth.thingNeeded": "请选择它用于什么。",
  "issue.worth.uses": "次数",
  "issue.worth.usesHint": "2 到 50",
  "issue.worth.usesRange": "次卡的次数为 2 到 50。",
  "issue.worth.valueNeeded": "请输入大于零的数值。",
  "issue.worth.what": "用于什么"
};

export const rules: Readonly<Record<string, string>> = {
  "rules.add": "添加规则",
  "rules.edit": "编辑",
  "rules.from": "来自 {app}",
  "rules.holding": "{rows, plural, other {# 行}}仍占用着一次使用或一笔卡支付。",
  "rules.inFile": "此规则在项目文件中定义，请在该文件中修改。",
  "rules.kind.discounts": "可用折扣",
  "rules.kind.moved": "已导入旧礼品卡",
  "rules.kind.pays": "可用礼品卡支付",
  "rules.kind.refunds": "退回礼品卡支付",
  "rules.kind.sellsCards": "出售礼品卡或为其充值",
  "rules.kind.sellsVouchers": "出售代金券或次卡",
  "rules.kind.uses": "记录使用情况",
  "rules.kindHint.discounts": "订单、预约、门票：凡是折扣或优惠码可以减价的内容。",
  "rules.kindHint.pays": "付款表，其中的行可以指明一张礼品卡。",
  "rules.kindHint.sellsCards": "销售明细表，其中的明细行可以指明它充值的礼品卡。",
  "rules.kindHint.sellsVouchers": "销售明细表，其中的明细行可以指明它出售的代金券。",
  "rules.make.amounts": "自动创建：让 Adminium 添加金额、小计、优惠和合计，以及计算它们的规则",
  "rules.make.codes": "自动创建：添加一张表，用来保存在行上输入的优惠码",
  "rules.make.column": "“{table}”上的 {column}",
  "rules.make.save": "添加这些并保存",
  "rules.make.table": "表“{table}”",
  "rules.make.title": "Adminium 会随规则一并添加以下内容",
  "rules.none.body": "可用折扣或礼品卡的应用会自带规则。对于你自己的表，请添加一条规则。",
  "rules.none.title": "还没有任何表与优惠相关",
  "rules.on": "开启",
  "rules.part.back": "撤销时机",
  "rules.part.balanceAfter": "之后的卡内余额",
  "rules.part.cardLoads": "它充值的礼品卡",
  "rules.part.cardPays": "用于支付的礼品卡",
  "rules.part.category": "它的类别（如果明细行指明了类别）",
  "rules.part.final": "行已最终确定",
  "rules.part.finalHint": "届时会记录使用情况，价格此后不再重新计算。",
  "rules.part.item": "明细行出售的内容",
  "rules.part.itemHint": "指向所售商品的关联。请选择此项、类别、类型或行上的一个词：至少选一项。",
  "rules.part.lineDiscount": "明细行的优惠",
  "rules.part.lines": "它的明细行所在的表",
  "rules.part.load": "它充值的金额",
  "rules.part.orderDiscount": "行本身的优惠",
  "rules.part.paid": "礼品卡支付的金额",
  "rules.part.price": "明细行的价格",
  "rules.part.quantity": "明细行的数量",
  "rules.part.refundAmount": "退回的金额",
  "rules.part.refundRow": "它与付款的关联",
  "rules.part.refunds": "退款所在的表",
  "rules.part.sold": "它的售价",
  "rules.part.tag": "行上说明它是什么的一个词",
  "rules.part.tagHint": "文本列。之后折扣可以针对带有指定词的行。",
  "rules.part.taxLater": "税款在使用时收取",
  "rules.part.total": "行的合计",
  "rules.part.type": "它的类型（如果明细行指明了类型）",
  "rules.part.undone": "已使用的次数被退回",
  "rules.part.voucher": "它出售的代金券",
  "rules.part.whenLoads": "礼品卡充值时机",
  "rules.part.whenPays": "礼品卡支付时机",
  "rules.part.whenSold": "代金券售出时机",
  "rules.part.written": "由 Adminium 写入。",
  "rules.point.create": "行创建时",
  "rules.point.in": "{column} 变为 {values} 时",
  "rules.point.never": "从不",
  "rules.point.set": "{column} 有值时",
  "rules.point.to": "它进入 {states} 时",
  "rules.readOnly": "只有可以修改 Adminium 如何计算表中各列的人才能更改这些规则。",
  "rules.remove": "移除规则",
  "rules.remove.confirm": "移除这条规则吗？此表的行将不再与优惠相关。",
  "rules.removed": "已移除“{table}”的规则",
  "rules.removedPart": "已移除“{table}”的规则。{why}",
  "rules.saved": "已保存“{table}”的规则",
  "rules.saved.new": "已为“{table}”添加规则",
  "rules.says.back": "在{when}撤销。",
  "rules.says.discounts": "折扣和优惠码按行计算，并根据“{lines}”逐条明细行计算。",
  "rules.says.moved": "以前保存在这里的礼品卡已导入。此操作由 Adminium 执行一次。",
  "rules.says.noColumn": "无对应列",
  "rules.says.noUses": "不记录使用情况：按使用次数的限制不会生效。",
  "rules.says.pays": "在 {card} 中指明礼品卡的行，会在{when}从卡中扣款；礼品卡支付的金额写入 {amount}。",
  "rules.says.refunds": "在{when}，行会把 {amount} 退回到付款的礼品卡。",
  "rules.says.sellsCards": "在 {card} 中指明礼品卡的行，会在{when}向卡内存入 {amount}。",
  "rules.says.sellsVouchers": "在 {voucher} 中指明代金券的行，会在{when}把它标记为已售出。",
  "rules.says.uses": "使用情况在{when}记录，在{back}退回。",
  "rules.says.usesAlone": "使用情况在{when}记录，但此表目前不可用折扣。请移除它，或重新添加规则。",
  "rules.says.usesKept": "在{when}记录已使用的内容，且不会退回。",
  "rules.sheet.add": "添加规则",
  "rules.sheet.cannotMake": "Adminium 无法在此添加缺少的内容：{reasons}",
  "rules.sheet.chooseColumn": "选择列",
  "rules.sheet.chooseTable": "选择表",
  "rules.sheet.edit": "编辑规则",
  "rules.sheet.err.needed": "请选择一列。",
  "rules.sheet.err.part": "请选择一列，或让 Adminium 添加。",
  "rules.sheet.err.refunds": "还请选择与付款的关联以及金额。",
  "rules.sheet.err.table": "请选择一张表",
  "rules.sheet.err.what": "请说明一行卖的是什么：一个关联，或行上的一个词。",
  "rules.sheet.err.when": "请把你选择的每个“时机”填写完整",
  "rules.sheet.err.whenNeeded": "请选择时机，并填写完整。",
  "rules.sheet.kind": "此表的作用",
  "rules.sheet.noCardLink": "此表没有与“礼品卡”的关联。请先在此表的列中添加一个。",
  "rules.sheet.noLines": "没有表关联到此表。可用折扣的表需要一张明细表。",
  "rules.sheet.noRefunds": "没有退款表",
  "rules.sheet.noVoucherLink": "此表没有与“代金券”的关联。请先在此表的列中添加一个。",
  "rules.sheet.notNeeded": "不需要",
  "rules.sheet.one": "每行一件",
  "rules.sheet.reads": "规则说明",
  "rules.sheet.save": "保存规则",
  "rules.sheet.table": "表",
  "rules.subtitle": "你自己的表与折扣、代金券和礼品卡的关系",
  "rules.switchedOff": "“{table}”的规则已关闭",
  "rules.switchedOn": "“{table}”的规则已开启",
  "rules.title": "优惠规则",
  "rules.unavailable": "这条规则暂时无法运行：Offers 已停用或没有响应。",
  "rules.when.becomes": "某一列变为指定值时",
  "rules.when.column": "{label}：哪一列",
  "rules.when.create": "行创建时",
  "rules.when.moves": "“{table}”进入以下状态时",
  "rules.when.never": "从不",
  "rules.when.set": "某一列有值时",
  "rules.yours": "你的表"
};
