/** Traditional Chinese strings for the Offers screens. Keys are those of en-US.ts. */
export const shared: Readonly<Record<string, string>> = {
  "shared.cancel": "取消",
  "shared.close": "關閉",
  "shared.failed.title": "無法載入",
  "shared.loading": "載入中",
  "shared.refused.body": "如有需要，請洽主管。",
  "shared.refused.title": "您沒有開啟此頁面的權限",
  "shared.retry": "重試"
};

export const refusal: Readonly<Record<string, string>> = {
  "refusal.askManager": "請洽主管。",
  "refusal.askToPrint": "請主管代為列印。",
  "refusal.batchFull": "這個批次的代碼已全部產生。",
  "refusal.cardPaysCard": "販售禮品卡的資料表不能同時接受以禮品卡付款。",
  "refusal.codeTaken": "這組代碼已被另一個折扣使用。",
  "refusal.conflict": "有其他人同時變更了這筆資料。沒有儲存任何內容。請再試一次。",
  "refusal.empty": "卡內餘額不足。",
  "refusal.emptyLeft": "卡內還剩 {left}。請扣除 {left} 或更少的金額。",
  "refusal.expired": "這已過期。沒有儲存任何內容。",
  "refusal.forbidden": "您沒有執行此動作的權限。",
  "refusal.inactive": "此卡尚未售出，無法使用。",
  "refusal.noAnswer": "Offers 沒有回應。沒有儲存任何內容。",
  "refusal.noPrint": "目前無法列印。",
  "refusal.notAllowed": "這裡不允許此動作。",
  "refusal.notFound": "這筆資料已不存在。",
  "refusal.off": "Offers 目前已關閉。",
  "refusal.other": "無法儲存。請再試一次。",
  "refusal.overLimit": "已超過上限。沒有儲存任何內容。",
  "refusal.rate": "嘗試次數過多。請稍候一分鐘。",
  "refusal.receiptOpen": "{rows, plural, other {有 # 列}}正保留著一次使用或一筆卡片付款：請先放回。",
  "refusal.usedUp": "使用次數已全部用完。沒有儲存任何內容。",
  "refusal.void": "這已作廢。沒有儲存任何內容。"
};

export const discounts: Readonly<Record<string, string>> = {
  "discounts.aGroup": "某個顧客群組",
  "discounts.all": "所有折扣",
  "discounts.allDay": "全天",
  "discounts.anyone": "任何人",
  "discounts.applies.lines": "僅限這些品項",
  "discounts.applies.linesHint": "品項、分類或類型",
  "discounts.applies.order": "整筆訂單",
  "discounts.applies.orderHint": "購物籃中的所有品項",
  "discounts.applies.orderNo": "這種折扣需要指定品項",
  "discounts.budget": "折抵達到此金額後停止",
  "discounts.changeItems": "變更",
  "discounts.check.amount": "請輸入金額，例如 5.00。",
  "discounts.check.buy": "請輸入 2 到 10 之間的數字。",
  "discounts.check.code": "請輸入代碼，或自動產生一組。",
  "discounts.check.count": "請輸入 1 以上的整數。",
  "discounts.check.hours": "請輸入起訖時間，或開啟「全天」。",
  "discounts.check.hoursOrder": "結束時間必須晚於開始時間。",
  "discounts.check.name": "請取一個團隊成員看得懂的名稱。",
  "discounts.check.noSteps": "請至少新增一個級距。",
  "discounts.check.percent": "請輸入 1 到 100 之間的百分比。",
  "discounts.check.price": "請輸入價格，例如 10.00。",
  "discounts.check.publicName": "請填寫顧客在收據上看到的文字。",
  "discounts.check.stepFrom": "每個級距的起始數量須為 2 以上。",
  "discounts.check.stepMore": "折扣必須高於前一個級距（{n} %）。",
  "discounts.check.stepRising": "每個級距的起始數量必須高於前一個（{n} 件）。",
  "discounts.check.targets": "請至少選擇一個品項、分類或類型。",
  "discounts.check.until": "結束日早於開始日，這個折扣永遠不會生效。請選擇開始日當天或之後的日期。",
  "discounts.check.usesTaken": "已使用 {n} 次。請輸入 {n} 以上的數字。",
  "discounts.chooseItems": "選擇品項",
  "discounts.code": "代碼",
  "discounts.codeHint": "英文字母與數字。顧客在結帳時輸入，或在櫃檯告知店員。",
  "discounts.codeMade": "已產生代碼 {code}",
  "discounts.col.given": "已折抵",
  "discounts.col.gives": "優惠內容",
  "discounts.col.limits": "限制",
  "discounts.col.name": "名稱",
  "discounts.col.starts": "啟用方式",
  "discounts.col.status": "狀態",
  "discounts.col.uses": "使用次數",
  "discounts.combinable": "可合併使用",
  "discounts.combineOff": "單獨使用，只有在折抵金額高於其他折扣合計時才會套用。",
  "discounts.combineOn": "會與同一筆訂單上其他可合併的折扣一起計算。",
  "discounts.count": "{n, plural, other {# 個折扣}} · 截至目前的使用次數與折抵金額",
  "discounts.days": "星期",
  "discounts.daysHint": "未選擇表示每天。",
  "discounts.each": "每件",
  "discounts.empty.body": "折扣會從訂單中折抵金額：可以自動套用、憑代碼套用，或由員工給予。",
  "discounts.empty.title": "尚無折扣",
  "discounts.end.body": "它將立即停止生效。",
  "discounts.end.title": "現在結束「{name}」嗎？",
  "discounts.endNow": "立即結束",
  "discounts.ended.body": "設定較晚的結束日即可再次啟用。",
  "discounts.ended.title": "這個折扣已結束",
  "discounts.endedNow": "「{name}」已結束",
  "discounts.fewerLanguages": "較少語言",
  "discounts.firstOrder": "僅限首次訂購",
  "discounts.fix": "{n, plural, other {儲存前請先修正 # 個項目}}",
  "discounts.fixes": "{n, plural, other {有 # 個項目需要修正後才能儲存。}}",
  "discounts.from": "開始日",
  "discounts.fromHint": "從當天開始時起算，以店家的時間為準。",
  "discounts.fromTime": "開始時間，格式如 09:00",
  "discounts.givenSoFar": "目前已折抵 {amount}",
  "discounts.gives.amount": "折抵 {amount}",
  "discounts.gives.amountOn": "{what}折抵 {amount}",
  "discounts.gives.bonus": "買 {buy} 付 {pay}",
  "discounts.gives.bonusOn": "{what}買 {buy} 付 {pay}",
  "discounts.gives.percent": "折抵 {n} %",
  "discounts.gives.percentOn": "{what}折抵 {n} %",
  "discounts.gives.price": "每件 {amount}",
  "discounts.gives.priceOn": "{what}每件 {amount}",
  "discounts.gives.steps": "買越多折越多",
  "discounts.gives.stepsOn": "{what}買越多折越多",
  "discounts.group": "顧客群組",
  "discounts.hoursHint": "時段不能跨越午夜。",
  "discounts.houseRule": "顧客可享有所有可合併的折扣和一組代碼；其餘則套用最優惠的那一個。",
  "discounts.kind.amount": "金額折抵",
  "discounts.kind.bonus": "買一送一及類似優惠",
  "discounts.kind.percent": "百分比折抵",
  "discounts.kind.price": "固定價格",
  "discounts.kind.steps": "依數量定價",
  "discounts.leave.body": "您所做的變更將會遺失。",
  "discounts.leave.go": "離開",
  "discounts.leave.stay": "繼續編輯",
  "discounts.leave.title": "不儲存就離開嗎？",
  "discounts.limit.first": "僅限首次訂購",
  "discounts.limit.from": "滿 {amount}",
  "discounts.limit.perCustomer": "每位顧客 {n} 次",
  "discounts.limit.until": "至 {date}",
  "discounts.limit.uses": "{n, plural, other {# 次}}",
  "discounts.lookAlike": "{typed} 看起來很像 {code}（{name}）。顧客可能會混淆。",
  "discounts.makeCode": "幫我產生一組",
  "discounts.maxUses": "總使用次數",
  "discounts.minQty": "最低數量",
  "discounts.minQtyHint": "以適用的品項計算。",
  "discounts.minSpend": "最低消費",
  "discounts.minSpendHint": "以商品金額計算，並先扣除排在前面的折抵。",
  "discounts.missing": "找不到這個折扣",
  "discounts.missingBody": "它可能已被移除，或您無法檢視。",
  "discounts.more": "更多",
  "discounts.moreCodes": "這個折扣有 {n} 組代碼。其餘的列在「優惠碼」中。",
  "discounts.moreLanguages": "更多語言",
  "discounts.name": "名稱（內部使用）",
  "discounts.never": "永遠不會生效",
  "discounts.new": "新增折扣",
  "discounts.newTitle": "新增折扣",
  "discounts.noMap": "無法讀取您的資料表販售的內容，因此無法選擇品項，也無法試算這個折扣。",
  "discounts.noTables": "這裡還沒有任何設定說明各行販售的內容。請先在「優惠規則」中新增一條規則。",
  "discounts.notLive": "尚未生效",
  "discounts.pause": "暫停",
  "discounts.pauseUnsaved": "暫停（您的變更尚未儲存）",
  "discounts.paused": "「{name}」已暫停",
  "discounts.perCustomer": "每位顧客的使用次數",
  "discounts.pick.addTag": "新增",
  "discounts.pick.chosen": "已選擇 {n} 項",
  "discounts.pick.done": "完成",
  "discounts.pick.none": "沒有符合搜尋的項目。",
  "discounts.pick.search": "搜尋",
  "discounts.pick.subtitle": "來自「優惠規則」中設定為可套用折扣的資料表。",
  "discounts.pick.tabCount": "{label} · {n}",
  "discounts.pick.tabs": "選擇來源",
  "discounts.pick.tag": "標籤，須與行上的寫法相同",
  "discounts.pick.tags": "標籤",
  "discounts.pick.title": "選擇適用對象",
  "discounts.pill.active": "生效中",
  "discounts.pill.draft": "草稿",
  "discounts.pill.ended": "已結束",
  "discounts.pill.paused": "已暫停",
  "discounts.pill.usedUp": "已用完",
  "discounts.publicName": "顧客看到的名稱",
  "discounts.publicNameHint": "收據上的那一行文字。",
  "discounts.publicNameIn": "顧客看到的名稱 · {language}",
  "discounts.ranAgain": "「{name}」已再次啟用，至 {date} 為止",
  "discounts.readOnly": "您可以檢視這個折扣。主管才能變更。",
  "discounts.resume": "恢復",
  "discounts.resumeUnsaved": "恢復（您的變更尚未儲存）",
  "discounts.resumed": "「{name}」已恢復",
  "discounts.run.ahead": "請選擇今天或之後的日期。",
  "discounts.run.hint": "會持續到當天結束。",
  "discounts.run.title": "再次啟用「{name}」",
  "discounts.run.until": "結束日",
  "discounts.runAgain": "再次啟用",
  "discounts.save": "儲存",
  "discounts.saveDraft": "儲存草稿",
  "discounts.saved": "「{name}」已儲存",
  "discounts.section.applies": "適用對象",
  "discounts.section.combine": "與其他折扣",
  "discounts.section.gives": "優惠內容",
  "discounts.section.limits": "限制",
  "discounts.section.name": "名稱",
  "discounts.section.starts": "啟用方式",
  "discounts.section.when": "時間",
  "discounts.section.who": "適用顧客",
  "discounts.signedInOnly": "僅限已登入的顧客，或由員工指名的顧客。訪客無法使用。",
  "discounts.staffNote": "會顯示在收銀台的折扣清單中。員工限額與原因仍然適用。",
  "discounts.starts.code": "代碼",
  "discounts.starts.codes": "{n} 組代碼",
  "discounts.starts.itself": "自動套用",
  "discounts.starts.itselfHint": "訂單符合條件時套用",
  "discounts.starts.staff": "僅限員工",
  "discounts.starts.staffHint": "在收銀台選取",
  "discounts.starts.staffOnly": "只有員工可以給予",
  "discounts.starts.withCode": "憑代碼",
  "discounts.starts.withCodeHint": "顧客提供代碼",
  "discounts.steps.add": "新增級距",
  "discounts.steps.from": "起始數量",
  "discounts.steps.off": "折抵百分比",
  "discounts.steps.remove": "移除這個級距",
  "discounts.steps.rule": "適用品項買得越多，折抵越多。以達到的最高級距計算。",
  "discounts.switchOn": "啟用",
  "discounts.switchedOn": "「{name}」已啟用",
  "discounts.targets.more": "{first}及其他 {n} 項",
  "discounts.title": "折扣",
  "discounts.toTime": "結束時間，格式如 17:00",
  "discounts.totals": "{uses, plural, other {使用 # 次}} · 已折抵 {given}",
  "discounts.try.asIfOn": "草稿會以已啟用的狀態試算。",
  "discounts.try.bar": "試算 · {n, plural, other {# 個折扣}}",
  "discounts.try.barTotal": "試算 · {n, plural, other {# 個折扣}} · {total}",
  "discounts.try.better": "改為套用「{name}」：它折抵得更多。",
  "discounts.try.buyer": "購買者",
  "discounts.try.code": "結帳時的代碼",
  "discounts.try.customer": "已登入的顧客",
  "discounts.try.draftName": "{name}（草稿）",
  "discounts.try.failed": "無法試算",
  "discounts.try.guest": "訪客",
  "discounts.try.minus": "−{amount}",
  "discounts.try.noCode": "無代碼",
  "discounts.try.noRows": "那裡還沒有已儲存的資料。",
  "discounts.try.none": "還沒有資料表可套用折扣",
  "discounts.try.noneBody": "指定您的哪個資料表可套用折扣後，就能用其中的列來試算這個折扣。",
  "discounts.try.notApplied": "未套用",
  "discounts.try.nothing": "這筆訂單沒有適用的折扣。",
  "discounts.try.off": "訂單折抵金額",
  "discounts.try.refused": "{code}：{why}",
  "discounts.try.row": "試算對象",
  "discounts.try.rowHint": "「{table}」中已儲存的一列",
  "discounts.try.rules": "優惠規則",
  "discounts.try.taxLater": "稅金會在訂單儲存時加上",
  "discounts.try.title": "試算",
  "discounts.try.total": "合計",
  "discounts.try.unnamed": "某個折扣",
  "discounts.try.whyNot": "{name} — {why}",
  "discounts.until": "結束日（選填）",
  "discounts.untilHint": "到當天結束為止，以店家的時間為準。",
  "discounts.usedUp.body": "提高上限之前只能檢視。",
  "discounts.usedUp.raise": "提高上限",
  "discounts.usedUp.title": "{n} 次使用已全部用完",
  "discounts.usesSoFar": "已使用 {n} 次",
  "discounts.value.amount": "折抵金額",
  "discounts.value.amountHint": "不會超過適用品項的金額。",
  "discounts.value.buy": "購買數量",
  "discounts.value.cheaper": "較便宜的那件由本店招待。",
  "discounts.value.cheapest": "最便宜的那件由本店招待。",
  "discounts.value.percent": "折抵百分比",
  "discounts.value.price": "每件售價",
  "discounts.value.priceHint": "原本就比較便宜的品項維持原價。",
  "discounts.why.alone": "另一個折扣折抵得更多，而它只能單獨使用",
  "discounts.why.cancelled": "已作廢",
  "discounts.why.days": "今天不適用",
  "discounts.why.draft": "仍是草稿",
  "discounts.why.ended": "已結束",
  "discounts.why.first": "這不是首次訂購",
  "discounts.why.group": "顧客不在適用的群組中",
  "discounts.why.hours": "此時段不適用",
  "discounts.why.items": "這筆訂單中沒有適用的品項",
  "discounts.why.limit": "已超過上限",
  "discounts.why.minimum": "訂單未達最低消費",
  "discounts.why.noCode": "需要輸入代碼",
  "discounts.why.notYet": "尚未開始",
  "discounts.why.paused": "已暫停",
  "discounts.why.quantity": "適用品項的數量不足",
  "discounts.why.signIn": "需要已登入的顧客",
  "discounts.why.unknown": "這裡不適用",
  "discounts.why.usedUp": "使用次數已全部用完"
};

export const lookup: Readonly<Record<string, string>> = {
  "lookup.addCredit": "增加儲值金",
  "lookup.added": "已增加 {amount}",
  "lookup.adjust": "調整",
  "lookup.askManager": "主管可以為它儲值、調整或作廢。",
  "lookup.batch": "批次",
  "lookup.cancelCard": "作廢此卡",
  "lookup.cancelled": "尾碼 {last4} 的卡已作廢",
  "lookup.code": "代碼",
  "lookup.col.amount": "金額",
  "lookup.col.date": "日期",
  "lookup.col.leftAfter": "之後餘額",
  "lookup.col.what": "項目",
  "lookup.col.where": "地點",
  "lookup.creditGiven": "已給予 {address} {amount} 儲值金",
  "lookup.dialog.add": "增加",
  "lookup.dialog.adjust": "調整尾碼 {last4} 的卡",
  "lookup.dialog.amount": "金額",
  "lookup.dialog.amountNeeded": "請輸入大於零的金額。",
  "lookup.dialog.byCard": "刷卡",
  "lookup.dialog.cancel": "要作廢尾碼 {last4} 的卡嗎？",
  "lookup.dialog.cancelBody": "卡內餘額將無法再使用。此操作無法復原。",
  "lookup.dialog.cash": "現金",
  "lookup.dialog.credit": "給予 {address} 儲值金",
  "lookup.dialog.creditMail": "系統會以電子郵件通知顧客。",
  "lookup.dialog.creditMore": "為 {address} 增加儲值金",
  "lookup.dialog.direction": "增加或扣除",
  "lookup.dialog.movesTo": "使用期限將改為 {date}",
  "lookup.dialog.other": "其他",
  "lookup.dialog.paidBy": "付款方式",
  "lookup.dialog.paidHint": "會記錄為已在櫃檯收款。這裡不會進行任何扣款。",
  "lookup.dialog.remove": "扣除",
  "lookup.dialog.topUp": "為尾碼 {last4} 的卡儲值",
  "lookup.dialog.upTo": "此卡最多可存入 {max}。",
  "lookup.dialog.why": "原因",
  "lookup.dialog.whyHint": "會與此卡的紀錄一併保存。",
  "lookup.dialog.whyNeeded": "請說明原因。",
  "lookup.discount": "折扣",
  "lookup.failed": "無法查詢",
  "lookup.field.empty": "請先輸入或掃描代碼。",
  "lookup.field.label": "輸入或掃描代碼，或輸入顧客的電子郵件",
  "lookup.field.placeholder": "GC-7K2M-W3HN-Q4XP 或 name@example.com",
  "lookup.for": "收件人",
  "lookup.from": "贈送人",
  "lookup.giveCredit": "給予儲值金",
  "lookup.go": "查詢",
  "lookup.issue": "發放",
  "lookup.issued": "發放日",
  "lookup.kind.card": "禮品卡",
  "lookup.kind.code": "優惠碼",
  "lookup.kind.credit": "儲值金",
  "lookup.kind.pack": "次卡",
  "lookup.kind.voucher": "兌換券",
  "lookup.left": "剩餘",
  "lookup.leftOf": "{left}／{total}",
  "lookup.markUsed": "標記為已使用",
  "lookup.markedUsed": "已標記為已使用",
  "lookup.moved": "舊卡 · 只能在有店員的櫃檯使用",
  "lookup.never": "永不過期",
  "lookup.noActivity": "它還沒有任何紀錄。",
  "lookup.noUses": "它尚未被使用。",
  "lookup.none.address": "{typed} 沒有儲值金",
  "lookup.none.addressBody": "這個地址名下沒有儲值金。",
  "lookup.none.code": "沒有項目使用此代碼 · {typed}",
  "lookup.none.codeBody": "請檢查字元，再試另一組代碼。",
  "lookup.openBatch": "開啟批次",
  "lookup.openDiscount": "開啟折扣",
  "lookup.percent": "{n}%",
  "lookup.pill.active": "使用中",
  "lookup.pill.cancelled": "已作廢",
  "lookup.pill.doesNot": "目前無法使用",
  "lookup.pill.expired": "已過期",
  "lookup.pill.inactive": "未啟用",
  "lookup.pill.notSold": "尚未售出",
  "lookup.pill.notUsed": "尚未使用",
  "lookup.pill.used": "已使用",
  "lookup.pill.usedUp": "已用完",
  "lookup.pill.works": "可使用",
  "lookup.print": "列印",
  "lookup.printing": "已開啟以供列印",
  "lookup.queued": "已排入重新寄送",
  "lookup.queuedFor": "已排入寄送給 {name}",
  "lookup.removed": "已扣除 {amount}",
  "lookup.row.adjust": "已調整",
  "lookup.row.expire": "已過期",
  "lookup.row.issue": "已發放",
  "lookup.row.refund": "已退回",
  "lookup.row.spend": "已消費",
  "lookup.row.topUp": "已儲值",
  "lookup.row.void": "已作廢",
  "lookup.said.card": "尾碼 {last4} 的禮品卡，{pill}，剩餘 {amount}",
  "lookup.said.cardNoBalance": "尾碼 {last4} 的禮品卡，{pill}",
  "lookup.said.code": "可使用的優惠碼",
  "lookup.said.codeNot": "目前無法使用的優惠碼",
  "lookup.said.credit": "儲值金，{pill}，剩餘 {amount}",
  "lookup.said.nothing": "沒有項目使用此代碼",
  "lookup.said.pack": "尾碼 {last4} 的次卡，{pill}，剩餘 {left}／{total}",
  "lookup.said.voucher": "尾碼 {last4} 的兌換券，{pill}",
  "lookup.sendAgain": "重新寄送",
  "lookup.start.body": "掃描卡片或兌換券上的代碼，或直接輸入。查詢儲值金請輸入顧客的電子郵件。",
  "lookup.start.title": "尚未查詢任何項目",
  "lookup.subtitle": "禮品卡、兌換券、次卡、優惠碼與儲值金",
  "lookup.title": "查詢",
  "lookup.topUp": "儲值",
  "lookup.toppedUp": "已儲值 {amount}",
  "lookup.use.counted": "已使用",
  "lookup.use.givenBack": "已退回",
  "lookup.use.held": "保留中",
  "lookup.useBy": "使用期限",
  "lookup.useOne": "立即使用一次",
  "lookup.useRecorded": "已記錄 1 次使用",
  "lookup.uses": "使用次數",
  "lookup.usesLeft": "剩餘次數",
  "lookup.validUntil": "有效期限",
  "lookup.what": "類型",
  "lookup.why.cancelled": "已作廢 · 無法使用",
  "lookup.why.codeUsedUp": "這組代碼的使用次數已全部用完",
  "lookup.why.empty": "卡內已無餘額",
  "lookup.why.expired": "已過期",
  "lookup.why.expiredOn": "已於 {date} 過期",
  "lookup.why.inactive": "尚未售出 · 無法消費",
  "lookup.why.notSold": "尚未售出 · 無法使用",
  "lookup.why.off": "這組代碼已停用",
  "lookup.why.used": "已使用過",
  "lookup.why.usedUp": "使用次數已全部用完",
  "lookup.worth": "面額"
};

export const issue: Readonly<Record<string, string>> = {
  "issue.batch.again": "您可以在「兌換券批次」中再次下載。",
  "issue.batch.count": "數量",
  "issue.batch.countRange": "1 到 {max}",
  "issue.batch.download": "下載代碼 (CSV)",
  "issue.batch.expiresNeeded": "請指定代碼的失效日期。",
  "issue.batch.made": "已產生 {count} 組代碼",
  "issue.batch.making": "正在產生代碼",
  "issue.batch.name": "批次名稱",
  "issue.batch.nameNeeded": "請為批次命名。",
  "issue.batch.open": "開啟批次",
  "issue.batch.part": "{count} 組中已產生 {made} 組。請到「兌換券批次」完成其餘部分。",
  "issue.batch.progress": "{made}／{count}",
  "issue.batch.readBack": "{count, plural, other {# 組代碼}}，每組限用一次，至 {date} 為止",
  "issue.batch.save": "產生代碼",
  "issue.card.amount": "金額",
  "issue.card.amountNeeded": "請輸入大於零的金額。",
  "issue.card.amountRange": "{min} 到 {max}",
  "issue.card.byCard": "刷卡",
  "issue.card.cash": "現金",
  "issue.card.dateAhead": "請選擇明天或之後的日期。",
  "issue.card.emailNeeded": "請輸入電子郵件，或選擇不寄送。",
  "issue.card.issued": "禮品卡已發放",
  "issue.card.message": "留言",
  "issue.card.messageLeft": "{n}／{max}",
  "issue.card.notSent": "未寄送",
  "issue.card.other": "其他",
  "issue.card.paidBy": "付款方式",
  "issue.card.paidHint": "會記錄為已在櫃檯售出 · 這裡不會進行任何扣款",
  "issue.card.paused": "禮品卡正從收銀台匯入中。請在匯入完成後再試一次。",
  "issue.card.queuedFor": "已排定於 {date} 寄送",
  "issue.card.queuedNow": "已排入寄送",
  "issue.card.save": "發放此卡",
  "issue.card.send": "寄送",
  "issue.card.sendDay": "寄送日期",
  "issue.card.sendNone": "不寄送，我會自行列印",
  "issue.card.sendNow": "立即",
  "issue.card.sendOn": "指定日期",
  "issue.card.sending": "寄送方式",
  "issue.done": "完成",
  "issue.email": "電子郵件",
  "issue.emailWrong": "這不是有效的電子郵件地址。",
  "issue.expires": "使用期限",
  "issue.expiresAhead": "請選擇今天或之後的日期。",
  "issue.expiresHint": "留空表示兌換券永不過期。",
  "issue.fixes": "{n, plural, other {有 # 個項目需要修正}}",
  "issue.for": "收件人",
  "issue.from": "贈送人",
  "issue.never": "永不過期",
  "issue.notAllowed": "您的角色無法發放。",
  "issue.note": "備註",
  "issue.noteHint": "僅供員工檢視。",
  "issue.print": "列印",
  "issue.result.code": "代碼",
  "issue.result.noCode": "主管可以查看它的代碼。",
  "issue.result.once": "完整代碼只會顯示這一次。",
  "issue.subtitle": "禮品卡、兌換券或一批代碼",
  "issue.tab.batch": "一批代碼",
  "issue.tab.card": "禮品卡",
  "issue.tab.voucher": "兌換券",
  "issue.tabs": "要發放的項目",
  "issue.title": "發放",
  "issue.voucher.bearer": "持有者皆可使用",
  "issue.voucher.emailNeeded": "指名的兌換券需要對方的電子郵件。",
  "issue.voucher.holder": "姓名",
  "issue.voucher.issued": "兌換券已發放",
  "issue.voucher.name": "名稱",
  "issue.voucher.nameHint": "顧客在兌換券和訂單上看到的名稱。",
  "issue.voucher.nameNeeded": "請填寫兌換券的名稱。",
  "issue.voucher.named": "指名對象",
  "issue.voucher.namedHint": "僅限這位顧客，須已登入或由員工指名",
  "issue.voucher.packIssued": "次卡已發放",
  "issue.voucher.save": "發放兌換券",
  "issue.why": "原因",
  "issue.whyNeeded": "請說明原因。",
  "issue.worth.amount": "金額",
  "issue.worth.amountHint": "從訂單中折抵這個金額",
  "issue.worth.amountValue": "金額",
  "issue.worth.change": "變更",
  "issue.worth.choose": "選擇…",
  "issue.worth.label": "面額",
  "issue.worth.noTables": "這裡還沒有任何設定說明各行販售的內容。",
  "issue.worth.noTablesBody": "請先在「優惠規則」中新增一條規則。",
  "issue.worth.noneFound": "找不到任何項目。",
  "issue.worth.pack": "次卡",
  "issue.worth.packHint": "可多次兌換同一個指定項目",
  "issue.worth.percent": "百分比",
  "issue.worth.percentHint": "從訂單中折抵這個比例",
  "issue.worth.percentMax": "百分比最高為 100。",
  "issue.worth.percentValue": "百分比",
  "issue.worth.search": "依名稱搜尋",
  "issue.worth.table": "來源",
  "issue.worth.thing": "單一項目",
  "issue.worth.thingHint": "可兌換一個指定項目",
  "issue.worth.thingNeeded": "請選擇可兌換的項目。",
  "issue.worth.uses": "使用次數",
  "issue.worth.usesHint": "2 到 50",
  "issue.worth.usesRange": "次卡的使用次數為 2 到 50 次。",
  "issue.worth.valueNeeded": "請輸入大於零的數值。",
  "issue.worth.what": "可兌換的項目"
};

export const rules: Readonly<Record<string, string>> = {
  "rules.add": "新增規則",
  "rules.edit": "編輯",
  "rules.from": "來自 {app}",
  "rules.holding": "{rows, plural, other {有 # 列}}正保留著一次使用或一筆卡片付款。",
  "rules.kind.discounts": "可套用折扣",
  "rules.kind.moved": "已匯入舊有的禮品卡",
  "rules.kind.pays": "接受以禮品卡付款",
  "rules.kind.refunds": "將卡片付款退回",
  "rules.kind.sellsCards": "販售禮品卡或為禮品卡儲值",
  "rules.kind.sellsVouchers": "販售兌換券或次卡",
  "rules.kind.uses": "記錄使用情形",
  "rules.kindHint.discounts": "訂單、預約、票券：任何可以用折扣或代碼折抵的項目。",
  "rules.kindHint.pays": "付款的資料表，其中的一列可以指定一張禮品卡。",
  "rules.kindHint.sellsCards": "銷售明細行的資料表，其中的一行可以指定要儲值的卡。",
  "rules.kindHint.sellsVouchers": "銷售明細行的資料表，其中的一行可以指定所販售的兌換券。",
  "rules.make.amounts": "自動建立：讓 Adminium 新增金額、小計、折抵與合計，以及計算這些欄位的規則",
  "rules.make.codes": "自動建立：新增一個資料表，存放在一列上輸入的代碼",
  "rules.make.column": "「{table}」的「{column}」",
  "rules.make.save": "新增這些並儲存",
  "rules.make.table": "資料表「{table}」",
  "rules.make.title": "Adminium 會連同規則一併新增以下內容",
  "rules.none.body": "可套用折扣或禮品卡的應用程式會自帶規則。若是您自己的資料表，請新增一條規則。",
  "rules.none.title": "還沒有資料表與優惠有關",
  "rules.on": "啟用",
  "rules.part.back": "復原的時機",
  "rules.part.balanceAfter": "卡片之後的餘額",
  "rules.part.cardLoads": "要儲值的禮品卡",
  "rules.part.cardPays": "用來付款的禮品卡",
  "rules.part.category": "分類（若該行有指定）",
  "rules.part.due": "尚待支付的金額",
  "rules.part.final": "該列定案的時機",
  "rules.part.finalHint": "屆時會記錄使用情形，價格也不會再重新計算。",
  "rules.part.item": "該行販售的項目",
  "rules.part.lineDiscount": "該行的折抵",
  "rules.part.lines": "它的明細行存放在",
  "rules.part.load": "儲值的金額",
  "rules.part.order": "所屬的列",
  "rules.part.orderDiscount": "該列本身的折抵",
  "rules.part.orderHint": "用於訂單的明細行或付款：連到訂單的連結。",
  "rules.part.paid": "卡片支付的金額",
  "rules.part.price": "該行的價格",
  "rules.part.quantity": "該行的數量",
  "rules.part.refundAmount": "退回的金額",
  "rules.part.refundRow": "連到付款的連結",
  "rules.part.refunds": "退款存放在",
  "rules.part.sold": "售出的價格",
  "rules.part.taxLater": "使用時才課稅",
  "rules.part.total": "該列的合計",
  "rules.part.type": "類型（若該行有指定）",
  "rules.part.undone": "退回使用次數的時機",
  "rules.part.voucher": "所販售的兌換券",
  "rules.part.whenLoads": "為卡片儲值的時機",
  "rules.part.whenPays": "以卡片付款的時機",
  "rules.part.whenSold": "兌換券售出的時機",
  "rules.part.written": "由 Adminium 寫入。",
  "rules.point.create": "該列建立時",
  "rules.point.in": "「{column}」變為 {values} 時",
  "rules.point.never": "永不",
  "rules.point.set": "「{column}」有值時",
  "rules.point.to": "它移至 {states} 時",
  "rules.readOnly": "只有可以變更 Adminium 如何計算資料表欄位的人才能變更這些規則。",
  "rules.remove": "移除規則",
  "rules.remove.confirm": "要移除這條規則嗎？這個資料表的列將不再與優惠有關。",
  "rules.removed": "已移除「{table}」的規則",
  "rules.removedPart": "已移除「{table}」的規則。{why}",
  "rules.saved": "已儲存「{table}」的規則",
  "rules.saved.new": "已為「{table}」新增規則",
  "rules.says.back": "復原時機：{when}。",
  "rules.says.discounts": "折扣與代碼會依據「{lines}」的明細行，逐行為每一列計算。",
  "rules.says.moved": "先前存放在這裡的禮品卡已匯入。這個動作由 Adminium 執行，只做一次。",
  "rules.says.noColumn": "無欄位",
  "rules.says.noUses": "不記錄使用情形：依使用次數設定的限制不會生效。",
  "rules.says.pays": "在「{card}」指定了禮品卡的列，會在以下時機從卡片扣款：{when}；卡片支付的金額會寫入「{amount}」。",
  "rules.says.refunds": "一列會在以下時機將「{amount}」退回到付款的卡片：{when}。",
  "rules.says.sellsCards": "在「{card}」指定了禮品卡的列，會在以下時機將「{amount}」存入該卡：{when}。",
  "rules.says.sellsVouchers": "在「{voucher}」指定了兌換券的列，會在以下時機將它標記為已售出：{when}。",
  "rules.says.uses": "記錄使用情形的時機：{when}；退回的時機：{back}。",
  "rules.says.usesAlone": "記錄使用情形的時機：{when}，但這個資料表目前不套用折扣。請將它移除，或重新新增規則。",
  "rules.says.usesKept": "已使用的內容會記錄，時機：{when}；且不會退回。",
  "rules.sheet.add": "新增規則",
  "rules.sheet.cannotMake": "Adminium 無法新增這裡缺少的內容：{reasons}",
  "rules.sheet.chooseColumn": "選擇欄位",
  "rules.sheet.chooseTable": "選擇資料表",
  "rules.sheet.edit": "編輯規則",
  "rules.sheet.err.needed": "請選擇欄位。",
  "rules.sheet.err.part": "請選擇欄位，或讓 Adminium 新增。",
  "rules.sheet.err.refunds": "也請選擇連到付款的連結與金額。",
  "rules.sheet.err.table": "請選擇資料表",
  "rules.sheet.err.when": "請完成您選擇的每個「時機」",
  "rules.sheet.err.whenNeeded": "請選擇時機並填寫完整。",
  "rules.sheet.itself": "它獨立存在",
  "rules.sheet.kind": "資料表的用途",
  "rules.sheet.noCardLink": "這個資料表沒有連到「禮品卡」的連結。請先在資料表的欄位中新增一個。",
  "rules.sheet.noLines": "沒有資料表連到這個資料表。可套用折扣的資料表需要一個明細行的資料表。",
  "rules.sheet.noRefunds": "沒有退款的資料表",
  "rules.sheet.noVoucherLink": "這個資料表沒有連到「兌換券」的連結。請先在資料表的欄位中新增一個。",
  "rules.sheet.notNeeded": "不需要",
  "rules.sheet.one": "每列一個",
  "rules.sheet.reads": "規則說明",
  "rules.sheet.save": "儲存規則",
  "rules.sheet.table": "資料表",
  "rules.subtitle": "您自己的資料表與折扣、兌換券和禮品卡的關係",
  "rules.switchedOff": "「{table}」的規則已停用",
  "rules.switchedOn": "「{table}」的規則已啟用",
  "rules.title": "優惠規則",
  "rules.unavailable": "這條規則目前無法執行：Offers 已關閉或沒有回應。",
  "rules.when.becomes": "當某個欄位變為",
  "rules.when.column": "{label}：哪個欄位",
  "rules.when.create": "當該列建立時",
  "rules.when.moves": "當「{table}」移至",
  "rules.when.never": "永不",
  "rules.when.set": "當某個欄位有值時",
  "rules.yours": "您的資料表"
};
