/**
 * The screens' English, gathered from where it is written.
 *
 * Every sentence a screen shows is written once, beside the call that shows
 * it: `t('receive.title', 'Receive stock')`. This reads those calls and
 * writes `src/pages/strings/en-US.ts`, one object per section (a key's first
 * word), so the file the other languages are translated from can never say
 * something the screen does not. `--check` writes nothing and fails when the
 * file is behind; `src/pages/strings.test.ts` runs the same comparison.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export const SECTIONS = ['shared', 'refusal', 'receive', 'transfer', 'opening', 'counts', 'rules'];
const here = dirname(fileURLToPath(import.meta.url));
export const PAGES = resolve(here, '../src/pages');
export const TARGET = join(PAGES, 'strings/en-US.ts');

function sources(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) return entry.name === 'strings' || entry.name === 'testing' ? [] : sources(path);
    return /\.tsx?$/.test(entry.name) && !/\.test\.tsx?$/.test(entry.name) ? [path] : [];
  });
}

const CALL = /\bt\(\s*'([A-Za-z0-9_.-]+)',\s*('(?:[^'\\\n]|\\.)*'|"(?:[^"\\\n]|\\.)*")/g;

/** Every key with its English, by section; throws on a key written with two different sentences. */
export function gather() {
  const found = new Map();
  for (const file of sources(PAGES)) {
    const text = readFileSync(file, 'utf8');
    for (const match of text.matchAll(CALL)) {
      const key = match[1];
      const words = new Function(`return ${match[2]}`)();
      const section = key.split('.')[0];
      if (!SECTIONS.includes(section)) throw new Error(`${file}: "${key}" belongs to no section (${SECTIONS.join(', ')})`);
      if (found.has(key) && found.get(key) !== words) throw new Error(`"${key}" is written with two sentences:\n  ${found.get(key)}\n  ${words}`);
      found.set(key, words);
    }
  }
  return Object.fromEntries(SECTIONS.map((section) => [section, Object.fromEntries([...found].filter(([key]) => key.split('.')[0] === section).sort(([a], [b]) => (a < b ? -1 : 1)))]));
}

export function render(sections) {
  const body = SECTIONS.map((section) => `export const ${section}: Readonly<Record<string, string>> = ${JSON.stringify(sections[section], null, 2)};`).join('\n\n');
  return `/** GENERATED by scripts/page-strings.mjs from the sentences written in the screens. Do not edit by hand. */\n${body}\n`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const next = render(gather());
  if (process.argv.includes('--check')) {
    if (readFileSync(TARGET, 'utf8') !== next) {
      console.error('src/pages/strings/en-US.ts is behind the screens: run `node scripts/page-strings.mjs`.');
      process.exit(1);
    }
  } else writeFileSync(TARGET, next);
}
