// SPDX-License-Identifier: AGPL-3.0-only
/** GENERATED — ar-EG strings for the invoices page. Do not edit by hand. */
export default {
  "add.allOn": "كل الكتل القياسية موجودة بالفعل في هذه الفاتورة.",
  "add.custom": "صمّم قسمك الخاص",
  "add.standard": "الكتل القياسية",
  "add.subtitle": "صمّم قسمك الخاص، أو فعّل إحدى الكتل القياسية.",
  "add.title": "إضافة قسم",
  "canvas.addSection": "إضافة قسم",
  "canvas.approval.approved": "مُعتمَد",
  "canvas.approval.pending": "قيد الانتظار",
  "canvas.approval.rejected": "مرفوض",
  "canvas.approval.title": "الاعتماد",
  "canvas.attachments": "المرفقات",
  "canvas.blocks.parties": "من وفاتورة إلى",
  "canvas.blocks.paynotes": "الدفع والملاحظات",
  "canvas.brandName": "اسم العلامة",
  "canvas.brandingHint": "الهوية · انقر للتعديل",
  "canvas.contact": "هل لديك سؤال؟ تواصل معنا",
  "canvas.custom.addRow": "إضافة صف",
  "canvas.custom.body": "متن القسم",
  "canvas.custom.caption": "تعليق",
  "canvas.custom.clearImage": "إزالة الصورة",
  "canvas.custom.clearSlot": "إزالة",
  "canvas.custom.clearSlotOf": "إزالة الصورة {n}",
  "canvas.custom.remove": "إزالة القسم",
  "canvas.custom.removeOf": "إزالة القسم: {title}",
  "canvas.custom.removeRow": "إزالة الصف",
  "canvas.custom.removeRowOf": "إزالة الصف {n}",
  "canvas.custom.rowLabel": "تسمية الصف {n}",
  "canvas.custom.rowValue": "قيمة الصف {n}",
  "canvas.custom.titleLabel": "عنوان القسم",
  "canvas.custom.upload": "انقر لرفع صورة",
  "canvas.custom.uploadSlot": "رفع الصورة {n}",
  "canvas.customerName": "اسم العميل",
  "canvas.dateSigned": "تاريخ التوقيع",
  "canvas.delivery.title": "مراحل التسليم",
  "canvas.discount.title": "رموز الخصم",
  "canvas.due": "تاريخ الاستحقاق",
  "canvas.from": "من",
  "canvas.insertAbove": "إضافة قسم فوق {label}",
  "canvas.insertHere": "إضافة قسم هنا",
  "canvas.invoiceTo": "فاتورة إلى",
  "canvas.issued": "تاريخ الإصدار",
  "canvas.items.add": "إضافة بند",
  "canvas.items.amount": "المبلغ",
  "canvas.items.description": "الوصف",
  "canvas.items.descriptionOf": "وصف البند {n}",
  "canvas.items.qty": "الكمية",
  "canvas.items.qtyOf": "كمية البند {n}",
  "canvas.items.rate": "السعر",
  "canvas.items.rateOf": "سعر البند {n}",
  "canvas.items.remove": "إزالة البند: {name}",
  "canvas.items.reorder": "اسحب لإعادة الترتيب",
  "canvas.items.reorderOf": "اسحب لإعادة الترتيب: {name}",
  "canvas.items.row": "البند {n}",
  "canvas.latefees.sentence": "تُطبَّق غرامة تأخير قدرها {rate}% شهريًا على المبالغ غير المسددة بعد مرور أكثر من {days} يومًا على تاريخ الاستحقاق.",
  "canvas.latefees.title": "غرامة تأخير السداد",
  "canvas.legal": "بيان قانوني",
  "canvas.lines.customer": "سطر العميل {n}",
  "canvas.lines.from": "سطر المُرسِل {n}",
  "canvas.lines.payment": "سطر الدفع {n}",
  "canvas.lines.ship": "سطر الشحن {n}",
  "canvas.loyalty.balance": "{balance} نقطة · {level}",
  "canvas.loyalty.title": "رصيد نقاط الولاء",
  "canvas.multicurrency.note": "محوَّل من {total} بأسعار صرف استرشادية.",
  "canvas.multicurrency.title": "يمكن السداد أيضًا بـ",
  "canvas.notes": "ملاحظات",
  "canvas.payhistory.title": "سجل المدفوعات",
  "canvas.payment": "الدفع",
  "canvas.poNumber": "رقم أمر الشراء",
  "canvas.poTerms": "شروط أمر الشراء",
  "canvas.qr.due": "المبلغ المستحق · {total}",
  "canvas.qr.title": "الدفع عبر رمز QR",
  "canvas.recurring.next": "التالي في {next} · {count}",
  "canvas.recurring.title": "متكرر — {freq}",
  "canvas.refund": "سياسة الاسترداد",
  "canvas.reorderSection": "اسحب لإعادة ترتيب القسم",
  "canvas.reorderSectionOf": "اسحب لإعادة ترتيب القسم: {label}",
  "canvas.select": "تعديل {label}",
  "canvas.shipName": "اسم المُستلِم",
  "canvas.shipTo": "الشحن إلى",
  "canvas.sigName": "اسم الموقّع",
  "canvas.sigTitle": "صفة الموقّع",
  "canvas.signature": "التوقيع",
  "canvas.taxbreak.title": "تفصيل الضريبة",
  "canvas.terms": "الشروط",
  "canvas.termsAccepted": "تمت الموافقة على الشروط",
  "canvas.termsLabel": "تسمية الشروط",
  "canvas.totals.discount": "الخصم ({rate})",
  "canvas.totals.subtotal": "المجموع الفرعي",
  "canvas.totals.tax": "الضريبة ({rate})",
  "canvas.totals.total": "الإجمالي",
  "card.delete": "حذف",
  "card.duplicate": "تكرار",
  "card.edit": "تعديل",
  "card.rename": "إعادة تسمية",
  "card.renameLabel": "الاسم الجديد",
  "card.total": "الإجمالي",
  "custom.gallery.hint": "صورتان أو ثلاث جنبًا إلى جنب",
  "custom.gallery.label": "صف صور",
  "custom.image.hint": "ارفع صورة أو رسمًا أو شهادة",
  "custom.image.label": "كتلة صورة",
  "custom.kv.hint": "أزواج تسمية / قيمة",
  "custom.kv.label": "صفوف تفاصيل",
  "custom.text.hint": "نصك الخاص — ملاحظات أو نطاق عمل أو شروط",
  "custom.text.label": "قسم نصي",
  "delete.body.invoice": "لا يمكن التراجع عن هذا. ستُزال الفاتورة نهائيًا.",
  "delete.body.template": "لا يمكن التراجع عن هذا. سيُزال القالب نهائيًا.",
  "delete.confirm": "حذف",
  "delete.title": "حذف {name}؟",
  "editor.delete": "حذف",
  "editor.discard.body": "ستفقد تعديلاتك على {name}.",
  "editor.discard.confirm": "تجاهل",
  "editor.discard.keep": "متابعة التعديل",
  "editor.discard.title": "تجاهل التغييرات غير المحفوظة؟",
  "editor.duplicate": "تكرار",
  "editor.images": "الصور",
  "editor.kind.invoice": "فاتورة",
  "editor.kind.template": "قالب",
  "editor.loadFailed": "تعذّر تحميل هذا المستند",
  "editor.nameLabel": "الاسم",
  "editor.redo": "إعادة",
  "editor.saveFailed": "تعذّر الحفظ",
  "editor.saveInvoice": "حفظ الفاتورة",
  "editor.saveState.dirty": "تغييرات غير محفوظة",
  "editor.saveState.error": "تعذّر الحفظ",
  "editor.saveState.saved": "حُفظت كل التغييرات",
  "editor.saveState.saving": "جارٍ الحفظ…",
  "editor.saveTemplate": "حفظ القالب",
  "editor.sendInvoice": "إرسال الفاتورة",
  "editor.shortcutSave": "حفظ المستند",
  "editor.undo": "تراجع",
  "empty.invoices.body": "أنشئ فاتورتك الأولى من قالب أو من لوحة فارغة.",
  "empty.invoices.title": "لا توجد فواتير بعد",
  "empty.noMatch.body": "جرّب كلمة بحث أخرى.",
  "empty.noMatch.invoices": "لا توجد فواتير مطابقة",
  "empty.noMatch.templates": "لا توجد قوالب مطابقة",
  "empty.templates.body": "أنشئ قالب فاتورة قابلًا لإعادة الاستخدام ينطلق منه فريقك.",
  "empty.templates.title": "لا توجد قوالب بعد",
  "inspector.addLine": "إضافة سطر",
  "inspector.approval.name": "اسم المُعتمِد",
  "inspector.approval.status.approved": "مُعتمَد",
  "inspector.approval.status.pending": "قيد الانتظار",
  "inspector.approval.status.rejected": "مرفوض",
  "inspector.approval.statusLabel": "الحالة",
  "inspector.approval.title": "الدور / الصفة",
  "inspector.attachments.add": "إضافة ملف",
  "inspector.attachments.files": "الملفات",
  "inspector.attachments.name": "اسم الملف {n}",
  "inspector.attachments.removeRow": "إزالة الملف {n}",
  "inspector.attachments.seedName": "ملف جديد.pdf",
  "inspector.attachments.size": "حجم الملف {n}",
  "inspector.branding.accentHintAfter": "والمظهر.",
  "inspector.branding.accentHintBefore": "غيّر لون التمييز من قسم",
  "inspector.branding.accentHintBold": "العنوان",
  "inspector.branding.brandName": "اسم العلامة",
  "inspector.branding.logoImage": "صورة الشعار",
  "inspector.branding.logoMark": "رمز الشعار",
  "inspector.branding.logoNoteAfter": "في شريط الأدوات.",
  "inspector.branding.logoNoteBefore": "الشعار المرفوع يحلّ محل الرمز أعلاه. وكل الصور الثابتة تجدها ضمن",
  "inspector.branding.logoNoteBold": "الصور",
  "inspector.branding.removeLogo": "إزالة",
  "inspector.branding.uploadLogo": "رفع شعار",
  "inspector.contact.email": "البريد الإلكتروني",
  "inspector.contact.name": "اسم جهة الاتصال",
  "inspector.contact.phone": "الهاتف",
  "inspector.custom.addRow": "إضافة صف",
  "inspector.custom.body": "نص المتن",
  "inspector.custom.caption": "تعليق",
  "inspector.custom.galleryHint": "انقر كل خانة على الفاتورة لرفع صورة.",
  "inspector.custom.height": "الارتفاع",
  "inspector.custom.image": "الصورة",
  "inspector.custom.remove": "إزالة القسم",
  "inspector.custom.title": "عنوان القسم",
  "inspector.custom.upload": "رفع / استبدال",
  "inspector.customer.addressContact": "العنوان وبيانات الاتصال",
  "inspector.customer.clientName": "اسم العميل",
  "inspector.delivery.add": "إضافة خطوة",
  "inspector.delivery.cycle": "حالة الخطوة {n}: {status}",
  "inspector.delivery.label": "الخطوة {n}",
  "inspector.delivery.note": "انقر الحالة للتنقّل بينها: قيد الانتظار ← قيد التنفيذ ← منجز.",
  "inspector.delivery.removeRow": "إزالة الخطوة {n}",
  "inspector.delivery.seedLabel": "خطوة جديدة",
  "inspector.delivery.status.current": "قيد التنفيذ",
  "inspector.delivery.status.done": "منجز",
  "inspector.delivery.status.todo": "قيد الانتظار",
  "inspector.delivery.steps": "الخطوات",
  "inspector.discount.add": "إضافة رمز",
  "inspector.discount.amount": "قيمة الرمز {n}",
  "inspector.discount.code": "الرمز {n}",
  "inspector.discount.codePlaceholder": "الرمز",
  "inspector.discount.codes": "رموز الخصم",
  "inspector.discount.label": "وصف الرمز {n}",
  "inspector.discount.labelPlaceholder": "الوصف",
  "inspector.discount.removeRow": "إزالة الرمز {n}",
  "inspector.discount.seedLabel": "خصم جديد",
  "inspector.fallback.title": "تعديل",
  "inspector.from.companyDetails": "بيانات الشركة",
  "inspector.images.addSection": "إضافة قسم صور",
  "inspector.images.background": "الخلفية",
  "inspector.images.backgroundHint": "علامة مائية خلف الفاتورة",
  "inspector.images.intro": "صور ثابتة ترافق الفاتورة. ارفعها مرة واحدة ليحتفظ بها كل مستند يُبنى من هذا القالب.",
  "inspector.images.logo": "الشعار",
  "inspector.images.logoHint": "يحلّ محل رمز الشعار",
  "inspector.images.qr": "رمز QR",
  "inspector.images.qrHint": "يظهر في كتلة الدفع عبر رمز QR",
  "inspector.images.remove": "إزالة",
  "inspector.images.replace": "استبدال",
  "inspector.images.signature": "التوقيع",
  "inspector.images.signatureHint": "صورة توقيع ممسوحة ضوئيًا",
  "inspector.images.stamp": "الختم",
  "inspector.images.stampHint": "ختم السداد أو الاعتماد",
  "inspector.images.upload": "رفع",
  "inspector.images.uploadSlot": "رفع {label}",
  "inspector.items.add": "إضافة بند",
  "inspector.items.count": "البنود",
  "inspector.items.hint": "عدّل أي خانة مباشرةً على الفاتورة، أو اسحب المقبض لإعادة الترتيب.",
  "inspector.items.subtotal": "المجموع الفرعي",
  "inspector.latefees.grace": "مهلة السماح",
  "inspector.latefees.graceUnit": "يوم",
  "inspector.latefees.rate": "نسبة غرامة التأخير",
  "inspector.latefees.rateUnit": "% شهريًا",
  "inspector.legal.footer": "التذييل القانوني",
  "inspector.line": "{label} {n}",
  "inspector.loyalty.balance": "رصيد النقاط",
  "inspector.loyalty.earned": "النقاط المكتسبة",
  "inspector.loyalty.level": "المستوى",
  "inspector.meta.due": "تاريخ الاستحقاق",
  "inspector.meta.issued": "تاريخ الإصدار",
  "inspector.meta.number": "رقم الفاتورة",
  "inspector.meta.poNumber": "رقم أمر الشراء",
  "inspector.meta.terms": "شروط الدفع",
  "inspector.multicurrency.add": "إضافة عملة",
  "inspector.multicurrency.code": "رمز العملة {n}",
  "inspector.multicurrency.note": "يُضرب السعر في إجمالي الفاتورة. الرمز، ثم العلامة، ثم السعر.",
  "inspector.multicurrency.rate": "سعر العملة {n}",
  "inspector.multicurrency.rates": "العملات والأسعار",
  "inspector.multicurrency.removeRow": "إزالة العملة {n}",
  "inspector.multicurrency.symbol": "علامة العملة {n}",
  "inspector.notes.footerNotes": "ملاحظات التذييل",
  "inspector.notes.hint": "تظهر أسفل الفاتورة — شروط أو كلمة شكر أو نص قانوني.",
  "inspector.payhistory.add": "إضافة دفعة",
  "inspector.payhistory.amount": "مبلغ الدفعة {n}",
  "inspector.payhistory.amountPlaceholder": "المبلغ",
  "inspector.payhistory.date": "تاريخ الدفعة {n}",
  "inspector.payhistory.datePlaceholder": "التاريخ",
  "inspector.payhistory.method": "طريقة الدفعة {n}",
  "inspector.payhistory.methodPlaceholder": "الطريقة",
  "inspector.payhistory.payments": "المدفوعات",
  "inspector.payhistory.removeRow": "إزالة الدفعة {n}",
  "inspector.payment.instructions": "تعليمات الدفع",
  "inspector.poterms.terms": "شروط أمر الشراء",
  "inspector.qr.caption": "تعليق",
  "inspector.qr.hint": "يرمّز «المبلغ المستحق · {total}». والرمز المعروض هو الصورة التي ترفعها ضمن قسم الصور.",
  "inspector.recurring.annually": "سنويًا",
  "inspector.recurring.frequency": "التكرار",
  "inspector.recurring.monthly": "شهريًا",
  "inspector.recurring.next": "تاريخ الإصدار التالي",
  "inspector.recurring.note": "ملاحظة الدورة",
  "inspector.recurring.quarterly": "ربع سنويًا",
  "inspector.recurring.weekly": "أسبوعيًا",
  "inspector.refund.policy": "سياسة الاسترداد",
  "inspector.removeLine": "إزالة {label} {n}",
  "inspector.removeSection": "إزالة القسم",
  "inspector.shipto.addressLines": "أسطر العنوان",
  "inspector.shipto.name": "اسم المُستلِم",
  "inspector.signature.hint": "يظهر على الفاتورة سطر توقيع وخانة تاريخ للتوقيع باليد.",
  "inspector.signature.name": "اسم الموقّع",
  "inspector.signature.title": "الصفة / الدور",
  "inspector.tax.discount": "الخصم",
  "inspector.tax.discountRow": "الخصم",
  "inspector.tax.subtotal": "المجموع الفرعي",
  "inspector.tax.tax": "الضريبة",
  "inspector.tax.taxRate": "نسبة الضريبة",
  "inspector.tax.total": "الإجمالي",
  "inspector.taxbreak.add": "إضافة بند ضريبة",
  "inspector.taxbreak.components": "مكوّنات الضريبة",
  "inspector.taxbreak.label": "تسمية بند الضريبة {n}",
  "inspector.taxbreak.note": "تُطبَّق كل نسبة على المجموع الفرعي بعد أي خصم.",
  "inspector.taxbreak.rate": "نسبة بند الضريبة {n}",
  "inspector.taxbreak.removeRow": "إزالة بند الضريبة {n}",
  "inspector.taxbreak.seedLabel": "ضريبة جديدة",
  "inspector.terms.checkboxLabel": "تسمية مربع الاختيار",
  "inspector.terms.preChecked": "محدَّد مسبقًا",
  "inspector.terms.preCheckedHint": "يظهر المربع محدَّدًا منذ البداية",
  "inspector.theme.accentColour": "لون التمييز",
  "inspector.theme.backgroundHint": "يضيف خلفية تملأ الصفحة خلف الفاتورة كلها — مثالية للترويسة الرسمية أو لعلامة مائية.",
  "inspector.theme.backgroundImage": "صورة الخلفية",
  "inspector.theme.currency": "العملة",
  "inspector.theme.documentTitle": "عنوان المستند",
  "inspector.theme.language": "اللغة",
  "inspector.theme.languageNote": "استخدم زر اللغة في شريط الأدوات لإنشاء نسخة مرتبطة، بدل تغيير لغة هذه النسخة.",
  "inspector.theme.overlay": "التعتيم {pct}%",
  "inspector.theme.overlayLabel": "التعتيم",
  "inspector.theme.removeBackground": "إزالة",
  "inspector.theme.replaceBackground": "استبدال",
  "inspector.theme.showDecimals": "إظهار الكسور العشرية",
  "inspector.theme.showDecimalsHint": "مثال: $290.00 مقابل $290",
  "inspector.theme.status.draft": "مسودة",
  "inspector.theme.status.live": "مفعّل",
  "inspector.theme.status.overdue": "متأخّر",
  "inspector.theme.status.paid": "مدفوع",
  "inspector.theme.status.sent": "مُرسَل",
  "inspector.theme.statusLabel": "الحالة",
  "inspector.theme.topic.logistics": "الشحن والخدمات اللوجستية",
  "inspector.theme.topic.other": "غير مصنّف",
  "inspector.theme.topic.receipts": "الإيصالات والاستردادات",
  "inspector.theme.topic.recurring": "متكرر",
  "inspector.theme.topic.sales": "المبيعات وعروض الأسعار",
  "inspector.theme.topic.services": "الخدمات المهنية",
  "inspector.theme.topicLabel": "الموضوع",
  "inspector.theme.uploadBackground": "رفع خلفية",
  "languages.de": "الألمانية",
  "languages.en": "الإنجليزية",
  "languages.es": "الإسبانية",
  "languages.footnote": "إنشاء لغة يُنشئ نسخة مرتبطة، مجمّعة تحت الموضوع نفسه.",
  "languages.fr": "الفرنسية",
  "languages.ja": "اليابانية",
  "languages.pt": "البرتغالية",
  "languages.state.create": "إنشاء",
  "languages.state.editing": "قيد التعديل",
  "languages.state.open": "فتح",
  "languages.title": "النسخ اللغوية",
  "list.actions": "الإجراءات",
  "list.name": "الاسم",
  "list.status": "الحالة",
  "list.updated": "آخر تحديث",
  "manager.group.documents": "{count, plural, zero {لا مستندات} one {مستند واحد} two {مستندان} few {# مستندات} many {# مستندًا} other {# مستند}}",
  "manager.group.label": "التجميع",
  "manager.group.language": "اللغة",
  "manager.group.languages": "{count, plural, zero {لا لغات} one {لغة واحدة} two {لغتان} few {# لغات} many {# لغة} other {# لغة}}",
  "manager.group.none": "بلا تجميع",
  "manager.group.topic": "الموضوع",
  "manager.layout.gallery": "معرض",
  "manager.layout.label": "التخطيط",
  "manager.layout.list": "قائمة",
  "manager.loadFailed": "تعذّر تحميل الفواتير",
  "manager.search.clear": "مسح البحث",
  "manager.search.invoices": "البحث في الفواتير…",
  "manager.search.templates": "البحث في القوالب…",
  "manager.subtitle": "قوالب قابلة لإعادة الاستخدام والفواتير التي تنشئها منها.",
  "manager.tabs.invoices": "الفواتير",
  "manager.tabs.label": "النوع",
  "manager.tabs.templates": "القوالب",
  "manager.title": "الفواتير",
  "manager.untitled": "بلا عنوان",
  "new.blank": "فاتورة فارغة",
  "new.blankHint": "ابدأ من الصفر",
  "new.category.adjustments": "التسويات",
  "new.category.business": "الأعمال",
  "new.category.nonprofit": "المنظمات غير الربحية",
  "new.category.payments": "المدفوعات",
  "new.category.projects": "المشاريع",
  "new.category.recurring": "متكرر",
  "new.category.sales": "المبيعات",
  "new.category.services": "الخدمات",
  "new.category.shipping": "الشحن",
  "new.failed": "تعذّر الإنشاء",
  "new.invoice": "فاتورة جديدة",
  "new.startersFailed": "تعذّر تحميل القوالب الجاهزة. ابدأ من فاتورة فارغة أو حاول مجددًا.",
  "new.subtitle": "ابدأ من لوحة فارغة أو من قالب جاهز.",
  "new.template": "قالب جديد",
  "new.yourTemplates": "قوالبك",
  "optional.approvalShow": "الاعتماد",
  "optional.attachShow": "المرفقات",
  "optional.conShow": "جهة الاتصال",
  "optional.delShow": "مراحل التسليم",
  "optional.discShow": "رموز الخصم",
  "optional.lateShow": "غرامات التأخير",
  "optional.legalShow": "التذييل القانوني",
  "optional.loyShow": "نقاط الولاء",
  "optional.mcShow": "تعدد العملات",
  "optional.payhShow": "سجل المدفوعات",
  "optional.poShow": "شروط أمر الشراء",
  "optional.qrShow": "الدفع عبر رمز QR",
  "optional.recurShow": "متكرر",
  "optional.refShow": "سياسة الاسترداد",
  "optional.shipShow": "الشحن إلى",
  "optional.sigShow": "التوقيع",
  "optional.taxbShow": "تفصيل الضريبة",
  "optional.termsShow": "الموافقة على الشروط",
  "section.approval.hint": "حالة الاعتماد",
  "section.approval.title": "الاعتماد",
  "section.attachments.hint": "ملفات مرفقة",
  "section.attachments.title": "المرفقات",
  "section.branding.hint": "الشعار واسم العلامة",
  "section.branding.title": "الهوية",
  "section.contact.hint": "بيانات الدعم",
  "section.contact.title": "جهة الاتصال",
  "section.custom.hint": "قسم من إنشائك",
  "section.custom.title": "قسم مخصّص",
  "section.customer.hint": "بيانات العميل",
  "section.customer.title": "فاتورة إلى",
  "section.delivery.hint": "حالة التنفيذ",
  "section.delivery.title": "مراحل التسليم",
  "section.discount.hint": "رموز العروض المطبَّقة",
  "section.discount.title": "رموز الخصم",
  "section.from.hint": "بيانات شركتك",
  "section.from.title": "من",
  "section.images.hint": "الشعار والخلفية ورمز QR والصور",
  "section.images.title": "الصور",
  "section.items.hint": "المنتجات والخدمات",
  "section.items.title": "البنود",
  "section.latefees.hint": "غرامة التأخير في السداد",
  "section.latefees.title": "غرامات التأخير",
  "section.legal.hint": "الشروط الدقيقة",
  "section.legal.title": "التذييل القانوني",
  "section.loyalty.hint": "رصيد المكافآت",
  "section.loyalty.title": "نقاط الولاء",
  "section.meta.hint": "الرقم والتواريخ وأمر الشراء والشروط",
  "section.meta.title": "بيانات الفاتورة",
  "section.multicurrency.hint": "الإجماليات بعملات أخرى",
  "section.multicurrency.title": "تعدد العملات",
  "section.notes.hint": "نص التذييل",
  "section.notes.title": "ملاحظات",
  "section.payhistory.hint": "دفعات سابقة",
  "section.payhistory.title": "سجل المدفوعات",
  "section.payment.hint": "كيفية الدفع",
  "section.payment.title": "الدفع",
  "section.poterms.hint": "أحكام أمر الشراء",
  "section.poterms.title": "شروط أمر الشراء",
  "section.qr.hint": "رمز يُمسح للدفع",
  "section.qr.title": "الدفع عبر رمز QR",
  "section.recurring.hint": "دورة التحصيل",
  "section.recurring.title": "متكرر",
  "section.refund.hint": "المرتجعات والاستردادات",
  "section.refund.title": "سياسة الاسترداد",
  "section.shipto.hint": "عنوان التسليم",
  "section.shipto.title": "الشحن إلى",
  "section.signature.hint": "توقيع معتمَد",
  "section.signature.title": "التوقيع",
  "section.tax.hint": "النسب والخصومات",
  "section.tax.title": "الضريبة والإجماليات",
  "section.taxbreak.hint": "مكوّنات الضريبة",
  "section.taxbreak.title": "تفصيل الضريبة",
  "section.terms.hint": "مربع الموافقة",
  "section.terms.title": "الشروط",
  "section.theme.hint": "اللون والعملة والحالة",
  "section.theme.title": "العنوان والمظهر",
  "seed.gallery.title": "صور",
  "seed.image.caption": "أضف تعليقًا",
  "seed.image.title": "صورة",
  "seed.item": "عنصر جديد",
  "seed.kv.label": "التسمية",
  "seed.kv.row1k": "مركز التكلفة",
  "seed.kv.row2k": "العقد",
  "seed.kv.title": "بيانات مرجعية",
  "seed.kv.value": "القيمة",
  "seed.text.body": "أضف نصك هنا — نطاق العمل أو ملاحظات التسليم أو الشروط أو رسالة إلى العميل.",
  "seed.text.title": "ملاحظات إضافية",
  "status.draft": "مسودة",
  "status.live": "مفعّل",
  "status.overdue": "متأخّر",
  "status.paid": "مدفوع",
  "status.sent": "مُرسَل",
  "toast.deleteFailed": "تعذّر الحذف",
  "toast.duplicateFailed": "تعذّر التكرار",
  "toast.duplicated.invoice": "تم تكرار الفاتورة",
  "toast.duplicated.template": "تم تكرار القالب",
  "toast.imageTooLarge": "الصورة كبيرة جدًا (الحد الأقصى {max})",
  "toast.imageUnreadable": "تعذّرت قراءة هذا الملف",
  "toast.languageFailed": "تعذّرت إضافة هذه اللغة",
  "toast.notAnImage": "هذا الملف ليس صورة",
  "toast.renameFailed": "تعذّرت إعادة التسمية",
  "topic.logistics": "الشحن والخدمات اللوجستية",
  "topic.other": "غير مصنّف",
  "topic.receipts": "الإيصالات والاستردادات",
  "topic.recurring": "متكرر",
  "topic.sales": "المبيعات وعروض الأسعار",
  "topic.services": "الخدمات المهنية"
} as Record<string, string>;
