// SPDX-License-Identifier: AGPL-3.0-only
/** GENERATED — cs-CZ strings for the invoices page. Do not edit by hand. */
export default {
  "add.allOn": "Na této faktuře už jsou všechny standardní bloky.",
  "add.custom": "Vytvořte si vlastní",
  "add.standard": "Standardní bloky",
  "add.subtitle": "Vytvořte si vlastní, nebo zapněte některý ze standardních bloků.",
  "add.title": "Přidat sekci",
  "canvas.addSection": "Přidat sekci",
  "canvas.approval.approved": "Schváleno",
  "canvas.approval.pending": "Čeká na schválení",
  "canvas.approval.rejected": "Zamítnuto",
  "canvas.approval.title": "Schválení",
  "canvas.attachments": "Přílohy",
  "canvas.blocks.parties": "Dodavatel a odběratel",
  "canvas.blocks.paynotes": "Platba a poznámky",
  "canvas.brandName": "Název značky",
  "canvas.brandingHint": "Značka · kliknutím upravíte",
  "canvas.contact": "Máte dotaz? Ozvěte se nám",
  "canvas.custom.addRow": "Přidat řádek",
  "canvas.custom.body": "Text sekce",
  "canvas.custom.caption": "Popisek",
  "canvas.custom.clearImage": "Odebrat obrázek",
  "canvas.custom.clearSlot": "Odebrat",
  "canvas.custom.clearSlotOf": "Odebrat obrázek {n}",
  "canvas.custom.remove": "Odebrat sekci",
  "canvas.custom.removeOf": "Odebrat sekci: {title}",
  "canvas.custom.removeRow": "Odebrat řádek",
  "canvas.custom.removeRowOf": "Odebrat řádek {n}",
  "canvas.custom.rowLabel": "Popis řádku {n}",
  "canvas.custom.rowValue": "Hodnota řádku {n}",
  "canvas.custom.titleLabel": "Název sekce",
  "canvas.custom.upload": "Kliknutím nahrajete obrázek",
  "canvas.custom.uploadSlot": "Nahrát obrázek {n}",
  "canvas.customerName": "Jméno odběratele",
  "canvas.dateSigned": "Datum podpisu",
  "canvas.delivery.title": "Harmonogram dodání",
  "canvas.discount.title": "Slevové kódy",
  "canvas.due": "Splatnost",
  "canvas.from": "Dodavatel",
  "canvas.insertAbove": "Přidat sekci nad sekcí {label}",
  "canvas.insertHere": "Přidat sekci sem",
  "canvas.invoiceTo": "Odběratel",
  "canvas.issued": "Vystaveno",
  "canvas.items.add": "Přidat položku",
  "canvas.items.amount": "Částka",
  "canvas.items.description": "Popis",
  "canvas.items.descriptionOf": "Popis položky {n}",
  "canvas.items.qty": "Počet",
  "canvas.items.qtyOf": "Množství položky {n}",
  "canvas.items.rate": "Cena",
  "canvas.items.rateOf": "Jednotková cena položky {n}",
  "canvas.items.remove": "Odebrat položku: {name}",
  "canvas.items.reorder": "Přetažením změníte pořadí",
  "canvas.items.reorderOf": "Přetažením změníte pořadí: {name}",
  "canvas.items.row": "Položka {n}",
  "canvas.latefees.sentence": "Z částky neuhrazené déle než {days} dní po splatnosti účtujeme úrok z prodlení {rate} % měsíčně.",
  "canvas.latefees.title": "Úrok z prodlení",
  "canvas.legal": "Právní ujednání",
  "canvas.lines.customer": "Řádek odběratele {n}",
  "canvas.lines.from": "Řádek dodavatele {n}",
  "canvas.lines.payment": "Řádek platby {n}",
  "canvas.lines.ship": "Řádek dodací adresy {n}",
  "canvas.loyalty.balance": "{balance} b. · {level}",
  "canvas.loyalty.title": "Stav věrnostních bodů",
  "canvas.multicurrency.note": "Přepočteno z {total} orientačním kurzem.",
  "canvas.multicurrency.title": "Lze uhradit také v",
  "canvas.notes": "Poznámky",
  "canvas.payhistory.title": "Historie plateb",
  "canvas.payment": "Platba",
  "canvas.poNumber": "Číslo objednávky",
  "canvas.poTerms": "Podmínky objednávky",
  "canvas.qr.due": "K úhradě · {total}",
  "canvas.qr.title": "Platba QR kódem",
  "canvas.recurring.next": "Příště {next} · {count}",
  "canvas.recurring.title": "Opakované – {freq}",
  "canvas.refund": "Podmínky vrácení",
  "canvas.reorderSection": "Přetažením změníte pořadí sekcí",
  "canvas.reorderSectionOf": "Přetažením změníte pořadí sekce: {label}",
  "canvas.select": "Upravit sekci {label}",
  "canvas.shipName": "Jméno příjemce",
  "canvas.shipTo": "Dodací adresa",
  "canvas.sigName": "Jméno podepisujícího",
  "canvas.sigTitle": "Funkce podepisujícího",
  "canvas.signature": "Podpis",
  "canvas.taxbreak.title": "Rozpis daně",
  "canvas.terms": "Podmínky",
  "canvas.termsAccepted": "Podmínky přijaty",
  "canvas.termsLabel": "Popisek podmínek",
  "canvas.totals.discount": "Sleva ({rate})",
  "canvas.totals.subtotal": "Mezisoučet",
  "canvas.totals.tax": "Daň ({rate})",
  "canvas.totals.total": "Celkem",
  "card.delete": "Smazat",
  "card.duplicate": "Duplikovat",
  "card.edit": "Upravit",
  "card.rename": "Přejmenovat",
  "card.renameLabel": "Nový název",
  "card.total": "CELKEM",
  "custom.gallery.hint": "Dva nebo tři obrázky vedle sebe",
  "custom.gallery.label": "Řada obrázků",
  "custom.image.hint": "Nahrajte fotku, kresbu nebo certifikát",
  "custom.image.label": "Blok s obrázkem",
  "custom.kv.hint": "Dvojice popis / hodnota",
  "custom.kv.label": "Řádky s údaji",
  "custom.text.hint": "Vlastní text – poznámky, rozsah, podmínky",
  "custom.text.label": "Textová sekce",
  "delete.body.invoice": "Tohle nejde vrátit zpět. Faktura bude trvale odstraněna.",
  "delete.body.template": "Tohle nejde vrátit zpět. Šablona bude trvale odstraněna.",
  "delete.confirm": "Smazat",
  "delete.title": "Smazat {name}?",
  "editor.delete": "Smazat",
  "editor.discard.body": "Vaše úpravy v {name} se ztratí.",
  "editor.discard.confirm": "Zahodit",
  "editor.discard.keep": "Pokračovat v úpravách",
  "editor.discard.title": "Zahodit neuložené změny?",
  "editor.duplicate": "Duplikovat",
  "editor.images": "Obrázky",
  "editor.kind.invoice": "Faktura",
  "editor.kind.template": "Šablona",
  "editor.loadFailed": "Tento dokument se nepodařilo načíst",
  "editor.nameLabel": "Název",
  "editor.redo": "Znovu",
  "editor.saveFailed": "Nepodařilo se uložit",
  "editor.saveInvoice": "Uložit fakturu",
  "editor.saveState.dirty": "Neuložené změny",
  "editor.saveState.error": "Uložení selhalo",
  "editor.saveState.saved": "Všechny změny uloženy",
  "editor.saveState.saving": "Ukládá se…",
  "editor.saveTemplate": "Uložit šablonu",
  "editor.sendInvoice": "Odeslat fakturu",
  "editor.shortcutSave": "Uložit dokument",
  "editor.undo": "Zpět",
  "empty.invoices.body": "Vytvořte první fakturu ze šablony nebo z prázdného plátna.",
  "empty.invoices.title": "Zatím žádné faktury",
  "empty.noMatch.body": "Zkuste jiný hledaný výraz.",
  "empty.noMatch.invoices": "Žádné faktury neodpovídají",
  "empty.noMatch.templates": "Žádné šablony neodpovídají",
  "empty.templates.body": "Vytvořte opakovaně použitelnou šablonu faktury, ze které může váš tým vycházet.",
  "empty.templates.title": "Zatím žádné šablony",
  "inspector.addLine": "Přidat řádek",
  "inspector.approval.name": "Jméno schvalovatele",
  "inspector.approval.status.approved": "Schváleno",
  "inspector.approval.status.pending": "Čeká na schválení",
  "inspector.approval.status.rejected": "Zamítnuto",
  "inspector.approval.statusLabel": "Stav",
  "inspector.approval.title": "Role / funkce",
  "inspector.attachments.add": "Přidat soubor",
  "inspector.attachments.files": "Soubory",
  "inspector.attachments.name": "Název souboru {n}",
  "inspector.attachments.removeRow": "Odebrat soubor {n}",
  "inspector.attachments.seedName": "Nový soubor.pdf",
  "inspector.attachments.size": "Velikost souboru {n}",
  "inspector.branding.accentHintAfter": "a motiv.",
  "inspector.branding.accentHintBefore": "Barvu zvýraznění změníte v sekci",
  "inspector.branding.accentHintBold": "Název",
  "inspector.branding.brandName": "Název značky",
  "inspector.branding.logoImage": "Obrázek loga",
  "inspector.branding.logoMark": "Symbol loga",
  "inspector.branding.logoNoteAfter": "v nástrojové liště.",
  "inspector.branding.logoNoteBefore": "Nahrané logo nahradí symbol výše. Všechny pevné obrázky najdete pod položkou",
  "inspector.branding.logoNoteBold": "Obrázky",
  "inspector.branding.removeLogo": "Odebrat",
  "inspector.branding.uploadLogo": "Nahrát logo",
  "inspector.contact.email": "E-mail",
  "inspector.contact.name": "Kontaktní osoba",
  "inspector.contact.phone": "Telefon",
  "inspector.custom.addRow": "Přidat řádek",
  "inspector.custom.body": "Text",
  "inspector.custom.caption": "Popisek",
  "inspector.custom.galleryHint": "Kliknutím na jednotlivá místa na faktuře nahrajete obrázek.",
  "inspector.custom.height": "Výška",
  "inspector.custom.image": "Obrázek",
  "inspector.custom.remove": "Odebrat sekci",
  "inspector.custom.title": "Název sekce",
  "inspector.custom.upload": "Nahrát / nahradit",
  "inspector.customer.addressContact": "Adresa a kontakt",
  "inspector.customer.clientName": "Název odběratele",
  "inspector.delivery.add": "Přidat krok",
  "inspector.delivery.cycle": "Stav kroku {n}: {status}",
  "inspector.delivery.label": "Krok {n}",
  "inspector.delivery.note": "Klepnutím na stav přepínáte Čeká → Probíhá → Hotovo.",
  "inspector.delivery.removeRow": "Odebrat krok {n}",
  "inspector.delivery.seedLabel": "Nový krok",
  "inspector.delivery.status.current": "Probíhá",
  "inspector.delivery.status.done": "Hotovo",
  "inspector.delivery.status.todo": "Čeká",
  "inspector.delivery.steps": "Kroky",
  "inspector.discount.add": "Přidat kód",
  "inspector.discount.amount": "Částka kódu {n}",
  "inspector.discount.code": "Kód {n}",
  "inspector.discount.codePlaceholder": "KÓD",
  "inspector.discount.codes": "Slevové kódy",
  "inspector.discount.label": "Popis kódu {n}",
  "inspector.discount.labelPlaceholder": "Popis",
  "inspector.discount.removeRow": "Odebrat kód {n}",
  "inspector.discount.seedLabel": "Nová sleva",
  "inspector.fallback.title": "Upravit",
  "inspector.from.companyDetails": "Údaje firmy",
  "inspector.images.addSection": "Přidat obrázkovou sekci",
  "inspector.images.background": "Pozadí",
  "inspector.images.backgroundHint": "Vodoznak za fakturou",
  "inspector.images.intro": "Pevné obrázky, které putují s fakturou. Nahrajte je jednou a zůstanou v každém dokumentu vytvořeném z této šablony.",
  "inspector.images.logo": "Logo",
  "inspector.images.logoHint": "Nahradí symbol loga",
  "inspector.images.qr": "QR kód",
  "inspector.images.qrHint": "Zobrazí se v bloku platby QR kódem",
  "inspector.images.remove": "Odebrat",
  "inspector.images.replace": "Nahradit",
  "inspector.images.signature": "Podpis",
  "inspector.images.signatureHint": "Naskenovaný obrázek podpisu",
  "inspector.images.stamp": "Razítko / pečeť",
  "inspector.images.stampHint": "Razítko o zaplacení nebo schválení",
  "inspector.images.upload": "Nahrát",
  "inspector.images.uploadSlot": "Nahrát: {label}",
  "inspector.items.add": "Přidat položku",
  "inspector.items.count": "Položky",
  "inspector.items.hint": "Kterékoli pole upravíte přímo na faktuře, pořadí změníte přetažením úchytu.",
  "inspector.items.subtotal": "Mezisoučet",
  "inspector.latefees.grace": "Odkladná lhůta",
  "inspector.latefees.graceUnit": "dní",
  "inspector.latefees.rate": "Sazba úroku",
  "inspector.latefees.rateUnit": "% měsíčně",
  "inspector.legal.footer": "Právní doložka",
  "inspector.line": "{label} {n}",
  "inspector.loyalty.balance": "Stav bodů",
  "inspector.loyalty.earned": "Získané body",
  "inspector.loyalty.level": "Úroveň",
  "inspector.meta.due": "Datum splatnosti",
  "inspector.meta.issued": "Datum vystavení",
  "inspector.meta.number": "Číslo faktury",
  "inspector.meta.poNumber": "Číslo objednávky",
  "inspector.meta.terms": "Platební podmínky",
  "inspector.multicurrency.add": "Přidat měnu",
  "inspector.multicurrency.code": "Kód měny {n}",
  "inspector.multicurrency.note": "Kurzem se násobí celková částka faktury. Nejprve kód, pak symbol a kurz.",
  "inspector.multicurrency.rate": "Kurz měny {n}",
  "inspector.multicurrency.rates": "Měny a kurzy",
  "inspector.multicurrency.removeRow": "Odebrat měnu {n}",
  "inspector.multicurrency.symbol": "Symbol měny {n}",
  "inspector.notes.footerNotes": "Poznámky v patičce",
  "inspector.notes.hint": "Zobrazí se v dolní části faktury – podmínky, poděkování nebo právní text.",
  "inspector.payhistory.add": "Přidat platbu",
  "inspector.payhistory.amount": "Částka platby {n}",
  "inspector.payhistory.amountPlaceholder": "Částka",
  "inspector.payhistory.date": "Datum platby {n}",
  "inspector.payhistory.datePlaceholder": "Datum",
  "inspector.payhistory.method": "Způsob platby {n}",
  "inspector.payhistory.methodPlaceholder": "Způsob",
  "inspector.payhistory.payments": "Platby",
  "inspector.payhistory.removeRow": "Odebrat platbu {n}",
  "inspector.payment.instructions": "Platební pokyny",
  "inspector.poterms.terms": "Podmínky objednávky",
  "inspector.qr.caption": "Popisek",
  "inspector.qr.hint": "Zakóduje K úhradě · {total}. Zobrazený kód je obrázek, který nahrajete v sekci Obrázky.",
  "inspector.recurring.annually": "Ročně",
  "inspector.recurring.frequency": "Četnost",
  "inspector.recurring.monthly": "Měsíčně",
  "inspector.recurring.next": "Datum dalšího vystavení",
  "inspector.recurring.note": "Poznámka k opakování",
  "inspector.recurring.quarterly": "Čtvrtletně",
  "inspector.recurring.weekly": "Týdně",
  "inspector.refund.policy": "Podmínky vrácení",
  "inspector.removeLine": "Odebrat: {label} {n}",
  "inspector.removeSection": "Odebrat sekci",
  "inspector.shipto.addressLines": "Řádky adresy",
  "inspector.shipto.name": "Jméno příjemce",
  "inspector.signature.hint": "Na faktuře se objeví podpisový řádek a pole s datem k vlastnoručnímu podpisu.",
  "inspector.signature.name": "Jméno podepisujícího",
  "inspector.signature.title": "Funkce / role",
  "inspector.tax.discount": "Sleva",
  "inspector.tax.discountRow": "Sleva",
  "inspector.tax.subtotal": "Mezisoučet",
  "inspector.tax.tax": "Daň",
  "inspector.tax.taxRate": "Sazba daně",
  "inspector.tax.total": "Celkem",
  "inspector.taxbreak.add": "Přidat daňový řádek",
  "inspector.taxbreak.components": "Složky daně",
  "inspector.taxbreak.label": "Popis daňového řádku {n}",
  "inspector.taxbreak.note": "Každá sazba se počítá z mezisoučtu po odečtení slevy.",
  "inspector.taxbreak.rate": "Sazba daňového řádku {n}",
  "inspector.taxbreak.removeRow": "Odebrat daňový řádek {n}",
  "inspector.taxbreak.seedLabel": "Nová daň",
  "inspector.terms.checkboxLabel": "Popisek zaškrtávacího pole",
  "inspector.terms.preChecked": "Předem zaškrtnuto",
  "inspector.terms.preCheckedHint": "Zobrazit pole už zaškrtnuté",
  "inspector.theme.accentColour": "Barva zvýraznění",
  "inspector.theme.backgroundHint": "Přidá pozadí přes celou fakturu – hodí se na hlavičkový papír nebo vodoznak.",
  "inspector.theme.backgroundImage": "Obrázek pozadí",
  "inspector.theme.currency": "Měna",
  "inspector.theme.documentTitle": "Název dokumentu",
  "inspector.theme.language": "Jazyk",
  "inspector.theme.languageNote": "Propojenou variantu vytvoříte tlačítkem jazyka v nástrojové liště; neoznačujte znovu tuto.",
  "inspector.theme.overlay": "Překryv {pct} %",
  "inspector.theme.overlayLabel": "Překryv",
  "inspector.theme.removeBackground": "Odebrat",
  "inspector.theme.replaceBackground": "Nahradit",
  "inspector.theme.showDecimals": "Zobrazit desetinná místa",
  "inspector.theme.showDecimalsHint": "např. $290.00 oproti $290",
  "inspector.theme.status.draft": "Koncept",
  "inspector.theme.status.live": "Aktivní",
  "inspector.theme.status.overdue": "Po splatnosti",
  "inspector.theme.status.paid": "Zaplaceno",
  "inspector.theme.status.sent": "Odesláno",
  "inspector.theme.statusLabel": "Stav",
  "inspector.theme.topic.logistics": "Doprava a logistika",
  "inspector.theme.topic.other": "Nezařazeno",
  "inspector.theme.topic.receipts": "Doklady a vratky",
  "inspector.theme.topic.recurring": "Opakované",
  "inspector.theme.topic.sales": "Prodej a nabídky",
  "inspector.theme.topic.services": "Odborné služby",
  "inspector.theme.topicLabel": "Téma",
  "inspector.theme.uploadBackground": "Nahrát pozadí",
  "languages.de": "Němčina",
  "languages.en": "Angličtina",
  "languages.es": "Španělština",
  "languages.footnote": "Vytvořením jazyka vznikne propojená kopie zařazená pod stejné téma.",
  "languages.fr": "Francouzština",
  "languages.ja": "Japonština",
  "languages.pt": "Portugalština",
  "languages.state.create": "Vytvořit",
  "languages.state.editing": "Upravuje se",
  "languages.state.open": "Otevřít",
  "languages.title": "Jazykové varianty",
  "list.actions": "Akce",
  "list.name": "Název",
  "list.status": "Stav",
  "list.updated": "Aktualizováno",
  "manager.group.documents": "{count, plural, one {# dokument} few {# dokumenty} other {# dokumentů}}",
  "manager.group.label": "Seskupit podle",
  "manager.group.language": "Jazyk",
  "manager.group.languages": "{count, plural, one {# jazyk} few {# jazyky} other {# jazyků}}",
  "manager.group.none": "Nic",
  "manager.group.topic": "Téma",
  "manager.layout.gallery": "Galerie",
  "manager.layout.label": "Zobrazení",
  "manager.layout.list": "Seznam",
  "manager.loadFailed": "Faktury se nepodařilo načíst",
  "manager.search.clear": "Vymazat hledání",
  "manager.search.invoices": "Hledat faktury…",
  "manager.search.templates": "Hledat šablony…",
  "manager.subtitle": "Opakovaně použitelné šablony a faktury, které z nich vytváříte.",
  "manager.tabs.invoices": "Faktury",
  "manager.tabs.label": "Druh",
  "manager.tabs.templates": "Šablony",
  "manager.title": "Faktury",
  "manager.untitled": "Bez názvu",
  "new.blank": "Prázdná faktura",
  "new.blankHint": "Začít od nuly",
  "new.category.adjustments": "Opravy",
  "new.category.business": "Podnikání",
  "new.category.nonprofit": "Neziskové organizace",
  "new.category.payments": "Platby",
  "new.category.projects": "Projekty",
  "new.category.recurring": "Opakované",
  "new.category.sales": "Prodej",
  "new.category.services": "Služby",
  "new.category.shipping": "Doprava",
  "new.failed": "Nepodařilo se vytvořit",
  "new.invoice": "Nová faktura",
  "new.startersFailed": "Výchozí návrhy se nepodařilo načíst. Začněte s prázdnou fakturou nebo to zkuste znovu.",
  "new.subtitle": "Začněte s prázdným plátnem nebo s hotovou šablonou.",
  "new.template": "Nová šablona",
  "new.yourTemplates": "Vaše šablony",
  "optional.approvalShow": "Schválení",
  "optional.attachShow": "Přílohy",
  "optional.conShow": "Kontakt",
  "optional.delShow": "Harmonogram dodání",
  "optional.discShow": "Slevové kódy",
  "optional.lateShow": "Úrok z prodlení",
  "optional.legalShow": "Právní doložka",
  "optional.loyShow": "Věrnostní body",
  "optional.mcShow": "Více měn",
  "optional.payhShow": "Historie plateb",
  "optional.poShow": "Podmínky objednávky",
  "optional.qrShow": "Platba QR kódem",
  "optional.recurShow": "Opakované",
  "optional.refShow": "Podmínky vrácení",
  "optional.shipShow": "Dodací adresa",
  "optional.sigShow": "Podpis",
  "optional.taxbShow": "Rozpis daně",
  "optional.termsShow": "Přijetí podmínek",
  "section.approval.hint": "Stav schválení",
  "section.approval.title": "Schválení",
  "section.attachments.hint": "Přiložené soubory",
  "section.attachments.title": "Přílohy",
  "section.branding.hint": "Logo a název značky",
  "section.branding.title": "Značka",
  "section.contact.hint": "Kontakt na podporu",
  "section.contact.title": "Kontakt",
  "section.custom.hint": "Vaše vlastní sekce",
  "section.custom.title": "Vlastní sekce",
  "section.customer.hint": "Údaje odběratele",
  "section.customer.title": "Odběratel",
  "section.delivery.hint": "Stav vyřízení",
  "section.delivery.title": "Harmonogram dodání",
  "section.discount.hint": "Uplatněné slevové kódy",
  "section.discount.title": "Slevové kódy",
  "section.from.hint": "Údaje vaší firmy",
  "section.from.title": "Dodavatel",
  "section.images.hint": "Logo, pozadí, QR a fotky",
  "section.images.title": "Obrázky",
  "section.items.hint": "Zboží a služby",
  "section.items.title": "Položky",
  "section.latefees.hint": "Sankce po splatnosti",
  "section.latefees.title": "Úrok z prodlení",
  "section.legal.hint": "Drobné písmo",
  "section.legal.title": "Právní doložka",
  "section.loyalty.hint": "Stav odměn",
  "section.loyalty.title": "Věrnostní body",
  "section.meta.hint": "Číslo, data, objednávka a podmínky",
  "section.meta.title": "Údaje faktury",
  "section.multicurrency.hint": "Celkové částky v dalších měnách",
  "section.multicurrency.title": "Více měn",
  "section.notes.hint": "Text v patičce",
  "section.notes.title": "Poznámky",
  "section.payhistory.hint": "Dřívější platby",
  "section.payhistory.title": "Historie plateb",
  "section.payment.hint": "Jak zaplatit",
  "section.payment.title": "Platba",
  "section.poterms.hint": "Podmínky objednávky",
  "section.poterms.title": "Podmínky objednávky",
  "section.qr.hint": "Kód k platbě naskenováním",
  "section.qr.title": "Platba QR kódem",
  "section.recurring.hint": "Rozvrh účtování",
  "section.recurring.title": "Opakované",
  "section.refund.hint": "Vrácení zboží a peněz",
  "section.refund.title": "Podmínky vrácení",
  "section.shipto.hint": "Adresa doručení",
  "section.shipto.title": "Dodací adresa",
  "section.signature.hint": "Schválení oprávněnou osobou",
  "section.signature.title": "Podpis",
  "section.tax.hint": "Sazby a slevy",
  "section.tax.title": "Daň a součty",
  "section.taxbreak.hint": "Složky daně",
  "section.taxbreak.title": "Rozpis daně",
  "section.terms.hint": "Zaškrtávací pole přijetí",
  "section.terms.title": "Podmínky",
  "section.theme.hint": "Barva, měna, stav",
  "section.theme.title": "Název a motiv",
  "seed.gallery.title": "Obrázky",
  "seed.image.caption": "Přidejte popisek",
  "seed.image.title": "Obrázek",
  "seed.item": "Nová položka",
  "seed.kv.label": "Popis",
  "seed.kv.row1k": "Nákladové středisko",
  "seed.kv.row2k": "Smlouva",
  "seed.kv.title": "Referenční údaje",
  "seed.kv.value": "Hodnota",
  "seed.text.body": "Sem doplňte vlastní text – rozsah, poznámky k dodání, podmínky nebo vzkaz odběrateli.",
  "seed.text.title": "Doplňující poznámky",
  "status.draft": "Koncept",
  "status.live": "Aktivní",
  "status.overdue": "Po splatnosti",
  "status.paid": "Zaplaceno",
  "status.sent": "Odesláno",
  "toast.deleteFailed": "Nepodařilo se smazat",
  "toast.duplicateFailed": "Nepodařilo se duplikovat",
  "toast.duplicated.invoice": "Faktura duplikována",
  "toast.duplicated.template": "Šablona duplikována",
  "toast.imageTooLarge": "Obrázek je příliš velký (max. {max})",
  "toast.imageUnreadable": "Soubor se nepodařilo přečíst",
  "toast.languageFailed": "Jazyk se nepodařilo přidat",
  "toast.notAnImage": "Tento soubor není obrázek",
  "toast.renameFailed": "Nepodařilo se přejmenovat",
  "topic.logistics": "Doprava a logistika",
  "topic.other": "Nezařazeno",
  "topic.receipts": "Doklady a vratky",
  "topic.recurring": "Opakované",
  "topic.sales": "Prodej a nabídky",
  "topic.services": "Odborné služby"
} as Record<string, string>;
