// SPDX-License-Identifier: AGPL-3.0-only
/** GENERATED — da-DK strings for the invoices page. Do not edit by hand. */
export default {
  "add.allOn": "Alle standardblokke er allerede på denne faktura.",
  "add.custom": "Byg din egen",
  "add.standard": "Standardblokke",
  "add.subtitle": "Byg din egen, eller slå en af standardblokkene til.",
  "add.title": "Tilføj en sektion",
  "canvas.addSection": "Tilføj sektion",
  "canvas.approval.approved": "Godkendt",
  "canvas.approval.pending": "Afventer",
  "canvas.approval.rejected": "Afvist",
  "canvas.approval.title": "Godkendelse",
  "canvas.attachments": "Bilag",
  "canvas.blocks.parties": "Fra og Faktureres til",
  "canvas.blocks.paynotes": "Betaling og noter",
  "canvas.brandName": "Brandnavn",
  "canvas.brandingHint": "Branding · klik for at redigere",
  "canvas.contact": "Spørgsmål? Kontakt os",
  "canvas.custom.addRow": "Tilføj række",
  "canvas.custom.body": "Sektionens brødtekst",
  "canvas.custom.caption": "Billedtekst",
  "canvas.custom.clearImage": "Fjern billede",
  "canvas.custom.clearSlot": "Fjern",
  "canvas.custom.clearSlotOf": "Fjern billede {n}",
  "canvas.custom.remove": "Fjern sektion",
  "canvas.custom.removeOf": "Fjern sektion: {title}",
  "canvas.custom.removeRow": "Fjern række",
  "canvas.custom.removeRowOf": "Fjern række {n}",
  "canvas.custom.rowLabel": "Etiket for række {n}",
  "canvas.custom.rowValue": "Værdi for række {n}",
  "canvas.custom.titleLabel": "Sektionstitel",
  "canvas.custom.upload": "Klik for at uploade et billede",
  "canvas.custom.uploadSlot": "Upload billede {n}",
  "canvas.customerName": "Kundenavn",
  "canvas.dateSigned": "Underskriftsdato",
  "canvas.delivery.title": "Leveringsforløb",
  "canvas.discount.title": "Rabatkoder",
  "canvas.due": "Forfald",
  "canvas.from": "Fra",
  "canvas.insertAbove": "Tilføj en sektion over {label}",
  "canvas.insertHere": "Tilføj en sektion her",
  "canvas.invoiceTo": "Faktureres til",
  "canvas.issued": "Udstedt",
  "canvas.items.add": "Tilføj fakturalinje",
  "canvas.items.amount": "Beløb",
  "canvas.items.description": "Beskrivelse",
  "canvas.items.descriptionOf": "Beskrivelse for linje {n}",
  "canvas.items.qty": "Antal",
  "canvas.items.qtyOf": "Antal for linje {n}",
  "canvas.items.rate": "Pris",
  "canvas.items.rateOf": "Pris for linje {n}",
  "canvas.items.remove": "Fjern fakturalinje: {name}",
  "canvas.items.reorder": "Træk for at ændre rækkefølgen",
  "canvas.items.reorderOf": "Træk for at ændre rækkefølgen: {name}",
  "canvas.items.row": "Fakturalinje {n}",
  "canvas.latefees.sentence": "Der beregnes et gebyr på {rate} % pr. måned af beløb, der ikke er betalt mere end {days} dage efter forfaldsdatoen.",
  "canvas.latefees.title": "Gebyr ved for sen betaling",
  "canvas.legal": "Juridisk",
  "canvas.lines.customer": "Kundelinje {n}",
  "canvas.lines.from": "Fra-linje {n}",
  "canvas.lines.payment": "Betalingslinje {n}",
  "canvas.lines.ship": "Leveringslinje {n}",
  "canvas.loyalty.balance": "{balance} point · {level}",
  "canvas.loyalty.title": "Loyalitetssaldo",
  "canvas.multicurrency.note": "Omregnet fra {total} til vejledende kurser.",
  "canvas.multicurrency.title": "Kan også betales i",
  "canvas.notes": "Noter",
  "canvas.payhistory.title": "Betalingshistorik",
  "canvas.payment": "Betaling",
  "canvas.poNumber": "Indkøbsordrenr.",
  "canvas.poTerms": "Betingelser for indkøbsordren",
  "canvas.qr.due": "Beløb til betaling · {total}",
  "canvas.qr.title": "Betal med QR",
  "canvas.recurring.next": "Næste {next} · {count}",
  "canvas.recurring.title": "Tilbagevendende — {freq}",
  "canvas.refund": "Refusionspolitik",
  "canvas.reorderSection": "Træk for at flytte sektionen",
  "canvas.reorderSectionOf": "Træk for at flytte sektionen: {label}",
  "canvas.select": "Redigér {label}",
  "canvas.shipName": "Modtagernavn",
  "canvas.shipTo": "Leveres til",
  "canvas.sigName": "Underskrivers navn",
  "canvas.sigTitle": "Underskrivers titel",
  "canvas.signature": "Underskrift",
  "canvas.taxbreak.title": "Momsoversigt",
  "canvas.terms": "Betingelser",
  "canvas.termsAccepted": "Betingelser accepteret",
  "canvas.termsLabel": "Etiket for betingelser",
  "canvas.totals.discount": "Rabat ({rate})",
  "canvas.totals.subtotal": "Subtotal",
  "canvas.totals.tax": "Moms ({rate})",
  "canvas.totals.total": "I alt",
  "card.delete": "Slet",
  "card.duplicate": "Duplikér",
  "card.edit": "Redigér",
  "card.rename": "Omdøb",
  "card.renameLabel": "Nyt navn",
  "card.total": "I ALT",
  "custom.gallery.hint": "To eller tre billeder side om side",
  "custom.gallery.label": "Billedrække",
  "custom.image.hint": "Upload et foto, en tegning eller et certifikat",
  "custom.image.label": "Billedblok",
  "custom.kv.hint": "Etiket/værdi-par",
  "custom.kv.label": "Detaljerækker",
  "custom.text.hint": "Din egen tekst — noter, omfang, betingelser",
  "custom.text.label": "Tekstsektion",
  "delete.body.invoice": "Dette kan ikke fortrydes. Fakturaen fjernes permanent.",
  "delete.body.template": "Dette kan ikke fortrydes. Skabelonen fjernes permanent.",
  "delete.confirm": "Slet",
  "delete.title": "Slet {name}?",
  "editor.delete": "Slet",
  "editor.discard.body": "Dine ændringer i {name} går tabt.",
  "editor.discard.confirm": "Kassér",
  "editor.discard.keep": "Fortsæt redigering",
  "editor.discard.title": "Kassér ugemte ændringer?",
  "editor.duplicate": "Duplikér",
  "editor.images": "Billeder",
  "editor.kind.invoice": "Faktura",
  "editor.kind.template": "Skabelon",
  "editor.loadFailed": "Dette dokument kunne ikke indlæses",
  "editor.nameLabel": "Navn",
  "editor.redo": "Gentag",
  "editor.saveFailed": "Kunne ikke gemme",
  "editor.saveInvoice": "Gem faktura",
  "editor.saveState.dirty": "Ugemte ændringer",
  "editor.saveState.error": "Kunne ikke gemme",
  "editor.saveState.saved": "Alle ændringer er gemt",
  "editor.saveState.saving": "Gemmer…",
  "editor.saveTemplate": "Gem skabelon",
  "editor.sendInvoice": "Send faktura",
  "editor.shortcutSave": "Gem dokumentet",
  "editor.undo": "Fortryd",
  "empty.invoices.body": "Byg din første faktura ud fra en skabelon eller et tomt lærred.",
  "empty.invoices.title": "Ingen fakturaer endnu",
  "empty.noMatch.body": "Prøv et andet søgeord.",
  "empty.noMatch.invoices": "Ingen fakturaer matcher",
  "empty.noMatch.templates": "Ingen skabeloner matcher",
  "empty.templates.body": "Opret en genbrugelig fakturaskabelon, som dit team kan bygge videre på.",
  "empty.templates.title": "Ingen skabeloner endnu",
  "inspector.addLine": "Tilføj linje",
  "inspector.approval.name": "Godkenders navn",
  "inspector.approval.status.approved": "Godkendt",
  "inspector.approval.status.pending": "Afventer",
  "inspector.approval.status.rejected": "Afvist",
  "inspector.approval.statusLabel": "Status",
  "inspector.approval.title": "Rolle/titel",
  "inspector.attachments.add": "Tilføj fil",
  "inspector.attachments.files": "Filer",
  "inspector.attachments.name": "Navn på fil {n}",
  "inspector.attachments.removeRow": "Fjern fil {n}",
  "inspector.attachments.seedName": "Ny fil.pdf",
  "inspector.attachments.size": "Størrelse på fil {n}",
  "inspector.branding.accentHintAfter": "og tema.",
  "inspector.branding.accentHintBefore": "Skift accentfarven i sektionen",
  "inspector.branding.accentHintBold": "Titel",
  "inspector.branding.brandName": "Brandnavn",
  "inspector.branding.logoImage": "Logobillede",
  "inspector.branding.logoMark": "Logomærke",
  "inspector.branding.logoNoteAfter": "i værktøjslinjen.",
  "inspector.branding.logoNoteBefore": "Et uploadet logo erstatter mærket ovenfor. Alle faste billeder ligger under",
  "inspector.branding.logoNoteBold": "Billeder",
  "inspector.branding.removeLogo": "Fjern",
  "inspector.branding.uploadLogo": "Upload logo",
  "inspector.contact.email": "E-mail",
  "inspector.contact.name": "Kontaktnavn",
  "inspector.contact.phone": "Telefon",
  "inspector.custom.addRow": "Tilføj række",
  "inspector.custom.body": "Brødtekst",
  "inspector.custom.caption": "Billedtekst",
  "inspector.custom.galleryHint": "Klik på hver plads på fakturaen for at uploade et billede.",
  "inspector.custom.height": "Højde",
  "inspector.custom.image": "Billede",
  "inspector.custom.remove": "Fjern sektion",
  "inspector.custom.title": "Sektionstitel",
  "inspector.custom.upload": "Upload/erstat",
  "inspector.customer.addressContact": "Adresse og kontakt",
  "inspector.customer.clientName": "Kundens navn",
  "inspector.delivery.add": "Tilføj trin",
  "inspector.delivery.cycle": "Status for trin {n}: {status}",
  "inspector.delivery.label": "Trin {n}",
  "inspector.delivery.note": "Tryk på statussen for at skifte mellem Afventer → I gang → Færdig.",
  "inspector.delivery.removeRow": "Fjern trin {n}",
  "inspector.delivery.seedLabel": "Nyt trin",
  "inspector.delivery.status.current": "I gang",
  "inspector.delivery.status.done": "Færdig",
  "inspector.delivery.status.todo": "Afventer",
  "inspector.delivery.steps": "Trin",
  "inspector.discount.add": "Tilføj kode",
  "inspector.discount.amount": "Beløb for kode {n}",
  "inspector.discount.code": "Kode {n}",
  "inspector.discount.codePlaceholder": "KODE",
  "inspector.discount.codes": "Rabatkoder",
  "inspector.discount.label": "Beskrivelse af kode {n}",
  "inspector.discount.labelPlaceholder": "Beskrivelse",
  "inspector.discount.removeRow": "Fjern kode {n}",
  "inspector.discount.seedLabel": "Ny rabat",
  "inspector.fallback.title": "Redigér",
  "inspector.from.companyDetails": "Virksomhedsoplysninger",
  "inspector.images.addSection": "Tilføj en billedsektion",
  "inspector.images.background": "Baggrund",
  "inspector.images.backgroundHint": "Vandmærke bag fakturaen",
  "inspector.images.intro": "Faste billeder, der følger med fakturaen. Upload dem én gang, så går de igen i alle dokumenter, der bygges ud fra denne skabelon.",
  "inspector.images.logo": "Logo",
  "inspector.images.logoHint": "Erstatter logomærket",
  "inspector.images.qr": "QR-kode",
  "inspector.images.qrHint": "Vises i QR-betalingsblokken",
  "inspector.images.remove": "Fjern",
  "inspector.images.replace": "Erstat",
  "inspector.images.signature": "Underskrift",
  "inspector.images.signatureHint": "Scannet billede af underskriften",
  "inspector.images.stamp": "Stempel/segl",
  "inspector.images.stampHint": "Betalt- eller godkendelsesstempel",
  "inspector.images.upload": "Upload",
  "inspector.images.uploadSlot": "Upload {label}",
  "inspector.items.add": "Tilføj fakturalinje",
  "inspector.items.count": "Fakturalinjer",
  "inspector.items.hint": "Redigér cellerne direkte på fakturaen, eller træk i håndtaget for at ændre rækkefølgen.",
  "inspector.items.subtotal": "Subtotal",
  "inspector.latefees.grace": "Henstandsperiode",
  "inspector.latefees.graceUnit": "dage",
  "inspector.latefees.rate": "Gebyrsats",
  "inspector.latefees.rateUnit": "% pr. måned",
  "inspector.legal.footer": "Juridisk sidefod",
  "inspector.line": "{label} {n}",
  "inspector.loyalty.balance": "Pointsaldo",
  "inspector.loyalty.earned": "Optjente point",
  "inspector.loyalty.level": "Niveau",
  "inspector.meta.due": "Forfaldsdato",
  "inspector.meta.issued": "Udstedelsesdato",
  "inspector.meta.number": "Fakturanummer",
  "inspector.meta.poNumber": "Indkøbsordrenr.",
  "inspector.meta.terms": "Betalingsbetingelser",
  "inspector.multicurrency.add": "Tilføj valuta",
  "inspector.multicurrency.code": "Kode for valuta {n}",
  "inspector.multicurrency.note": "Kursen ganges med fakturaens total. Først kode, så symbol og til sidst kurs.",
  "inspector.multicurrency.rate": "Kurs for valuta {n}",
  "inspector.multicurrency.rates": "Valutaer og kurser",
  "inspector.multicurrency.removeRow": "Fjern valuta {n}",
  "inspector.multicurrency.symbol": "Symbol for valuta {n}",
  "inspector.notes.footerNotes": "Noter i sidefoden",
  "inspector.notes.hint": "Vises nederst på fakturaen — betingelser, en tak eller juridisk tekst.",
  "inspector.payhistory.add": "Tilføj betaling",
  "inspector.payhistory.amount": "Beløb for betaling {n}",
  "inspector.payhistory.amountPlaceholder": "Beløb",
  "inspector.payhistory.date": "Dato for betaling {n}",
  "inspector.payhistory.datePlaceholder": "Dato",
  "inspector.payhistory.method": "Metode for betaling {n}",
  "inspector.payhistory.methodPlaceholder": "Metode",
  "inspector.payhistory.payments": "Betalinger",
  "inspector.payhistory.removeRow": "Fjern betaling {n}",
  "inspector.payment.instructions": "Betalingsoplysninger",
  "inspector.poterms.terms": "Betingelser for indkøbsordren",
  "inspector.qr.caption": "Billedtekst",
  "inspector.qr.hint": "Koder Beløb til betaling · {total}. Koden, der vises, er det billede, du uploader under Billeder.",
  "inspector.recurring.annually": "Årligt",
  "inspector.recurring.frequency": "Hyppighed",
  "inspector.recurring.monthly": "Månedligt",
  "inspector.recurring.next": "Næste udstedelsesdato",
  "inspector.recurring.note": "Note til rytmen",
  "inspector.recurring.quarterly": "Kvartalsvis",
  "inspector.recurring.weekly": "Ugentligt",
  "inspector.refund.policy": "Refusionspolitik",
  "inspector.removeLine": "Fjern {label} {n}",
  "inspector.removeSection": "Fjern sektion",
  "inspector.shipto.addressLines": "Adresselinjer",
  "inspector.shipto.name": "Modtagernavn",
  "inspector.signature.hint": "På fakturaen vises en underskriftslinje og et datofelt til underskrift i hånden.",
  "inspector.signature.name": "Underskrivers navn",
  "inspector.signature.title": "Titel/rolle",
  "inspector.tax.discount": "Rabat",
  "inspector.tax.discountRow": "Rabat",
  "inspector.tax.subtotal": "Subtotal",
  "inspector.tax.tax": "Moms",
  "inspector.tax.taxRate": "Momssats",
  "inspector.tax.total": "I alt",
  "inspector.taxbreak.add": "Tilføj momslinje",
  "inspector.taxbreak.components": "Momskomponenter",
  "inspector.taxbreak.label": "Etiket for momslinje {n}",
  "inspector.taxbreak.note": "Hver sats beregnes af subtotalen efter eventuel rabat.",
  "inspector.taxbreak.rate": "Sats for momslinje {n}",
  "inspector.taxbreak.removeRow": "Fjern momslinje {n}",
  "inspector.taxbreak.seedLabel": "Ny moms",
  "inspector.terms.checkboxLabel": "Etiket for afkrydsningsfelt",
  "inspector.terms.preChecked": "Forudkrydset",
  "inspector.terms.preCheckedHint": "Vis feltet som allerede afkrydset",
  "inspector.theme.accentColour": "Accentfarve",
  "inspector.theme.backgroundHint": "Lægger en baggrund i fuld bredde bag hele fakturaen — perfekt til brevpapir eller et vandmærke.",
  "inspector.theme.backgroundImage": "Baggrundsbillede",
  "inspector.theme.currency": "Valuta",
  "inspector.theme.documentTitle": "Dokumenttitel",
  "inspector.theme.language": "Sprog",
  "inspector.theme.languageNote": "Brug sprogknappen i værktøjslinjen til at oprette en sammenkædet variant i stedet for at skifte sprog på denne.",
  "inspector.theme.overlay": "Overlejring {pct} %",
  "inspector.theme.overlayLabel": "Overlejring",
  "inspector.theme.removeBackground": "Fjern",
  "inspector.theme.replaceBackground": "Erstat",
  "inspector.theme.showDecimals": "Vis decimaler",
  "inspector.theme.showDecimalsHint": "f.eks. $290.00 vs. $290",
  "inspector.theme.status.draft": "Kladde",
  "inspector.theme.status.live": "Aktiv",
  "inspector.theme.status.overdue": "Forfalden",
  "inspector.theme.status.paid": "Betalt",
  "inspector.theme.status.sent": "Sendt",
  "inspector.theme.statusLabel": "Status",
  "inspector.theme.topic.logistics": "Forsendelse og logistik",
  "inspector.theme.topic.other": "Ikke kategoriseret",
  "inspector.theme.topic.receipts": "Kvitteringer og refusioner",
  "inspector.theme.topic.recurring": "Tilbagevendende",
  "inspector.theme.topic.sales": "Salg og tilbud",
  "inspector.theme.topic.services": "Professionelle ydelser",
  "inspector.theme.topicLabel": "Emne",
  "inspector.theme.uploadBackground": "Upload baggrund",
  "languages.de": "Tysk",
  "languages.en": "Engelsk",
  "languages.es": "Spansk",
  "languages.footnote": "Når du opretter et sprog, laves der en sammenkædet kopi, som grupperes under samme emne.",
  "languages.fr": "Fransk",
  "languages.ja": "Japansk",
  "languages.pt": "Portugisisk",
  "languages.state.create": "Opret",
  "languages.state.editing": "Redigeres nu",
  "languages.state.open": "Åbn",
  "languages.title": "Sprogvarianter",
  "list.actions": "Handlinger",
  "list.name": "Navn",
  "list.status": "Status",
  "list.updated": "Opdateret",
  "manager.group.documents": "{count, plural, one {# dokument} other {# dokumenter}}",
  "manager.group.label": "Gruppér efter",
  "manager.group.language": "Sprog",
  "manager.group.languages": "{count, plural, one {# sprog} other {# sprog}}",
  "manager.group.none": "Ingen",
  "manager.group.topic": "Emne",
  "manager.layout.gallery": "Galleri",
  "manager.layout.label": "Visning",
  "manager.layout.list": "Liste",
  "manager.loadFailed": "Fakturaerne kunne ikke indlæses",
  "manager.search.clear": "Ryd søgning",
  "manager.search.invoices": "Søg i fakturaer…",
  "manager.search.templates": "Søg i skabeloner…",
  "manager.subtitle": "Genbrugelige skabeloner og de fakturaer, du bygger ud fra dem.",
  "manager.tabs.invoices": "Fakturaer",
  "manager.tabs.label": "Type",
  "manager.tabs.templates": "Skabeloner",
  "manager.title": "Fakturaer",
  "manager.untitled": "Uden titel",
  "new.blank": "Tom faktura",
  "new.blankHint": "Start fra bunden",
  "new.category.adjustments": "Reguleringer",
  "new.category.business": "Erhverv",
  "new.category.nonprofit": "Almennyttigt",
  "new.category.payments": "Betalinger",
  "new.category.projects": "Projekter",
  "new.category.recurring": "Tilbagevendende",
  "new.category.sales": "Salg",
  "new.category.services": "Ydelser",
  "new.category.shipping": "Forsendelse",
  "new.failed": "Kunne ikke oprettes",
  "new.invoice": "Ny faktura",
  "new.startersFailed": "Startskabelonerne kunne ikke indlæses. Start fra bunden, eller prøv igen.",
  "new.subtitle": "Start fra et tomt lærred eller en færdig skabelon.",
  "new.template": "Ny skabelon",
  "new.yourTemplates": "Dine skabeloner",
  "optional.approvalShow": "Godkendelse",
  "optional.attachShow": "Bilag",
  "optional.conShow": "Kontakt",
  "optional.delShow": "Leveringsforløb",
  "optional.discShow": "Rabatkoder",
  "optional.lateShow": "Rykkergebyrer",
  "optional.legalShow": "Juridisk sidefod",
  "optional.loyShow": "Loyalitetspoint",
  "optional.mcShow": "Flere valutaer",
  "optional.payhShow": "Betalingshistorik",
  "optional.poShow": "Ordrebetingelser",
  "optional.qrShow": "Betalings-QR",
  "optional.recurShow": "Tilbagevendende",
  "optional.refShow": "Refusionspolitik",
  "optional.shipShow": "Leveres til",
  "optional.sigShow": "Underskrift",
  "optional.taxbShow": "Momsoversigt",
  "optional.termsShow": "Accept af betingelser",
  "section.approval.hint": "Status for godkendelse",
  "section.approval.title": "Godkendelse",
  "section.attachments.hint": "Vedhæftede filer",
  "section.attachments.title": "Bilag",
  "section.branding.hint": "Logo og brandnavn",
  "section.branding.title": "Branding",
  "section.contact.hint": "Supportoplysninger",
  "section.contact.title": "Kontakt",
  "section.custom.hint": "Din egen sektion",
  "section.custom.title": "Egen sektion",
  "section.customer.hint": "Kundeoplysninger",
  "section.customer.title": "Faktureres til",
  "section.delivery.hint": "Ekspeditionsstatus",
  "section.delivery.title": "Leveringsforløb",
  "section.discount.hint": "Anvendte kampagnekoder",
  "section.discount.title": "Rabatkoder",
  "section.from.hint": "Dine virksomhedsoplysninger",
  "section.from.title": "Fra",
  "section.images.hint": "Logo, baggrund, QR og fotos",
  "section.images.title": "Billeder",
  "section.items.hint": "Varer og ydelser",
  "section.items.title": "Fakturalinjer",
  "section.latefees.hint": "Gebyr ved forsinket betaling",
  "section.latefees.title": "Rykkergebyrer",
  "section.legal.hint": "Det med småt",
  "section.legal.title": "Juridisk sidefod",
  "section.loyalty.hint": "Belønningssaldo",
  "section.loyalty.title": "Loyalitetspoint",
  "section.meta.hint": "Nummer, datoer, indkøbsordre og betingelser",
  "section.meta.title": "Fakturaoplysninger",
  "section.multicurrency.hint": "Totaler i andre valutaer",
  "section.multicurrency.title": "Flere valutaer",
  "section.notes.hint": "Tekst i sidefoden",
  "section.notes.title": "Noter",
  "section.payhistory.hint": "Tidligere betalinger",
  "section.payhistory.title": "Betalingshistorik",
  "section.payment.hint": "Sådan betaler du",
  "section.payment.title": "Betaling",
  "section.poterms.hint": "Betingelser for indkøbsordren",
  "section.poterms.title": "Ordrebetingelser",
  "section.qr.hint": "Scan og betal",
  "section.qr.title": "Betalings-QR",
  "section.recurring.hint": "Rytme for opkrævning",
  "section.recurring.title": "Tilbagevendende",
  "section.refund.hint": "Returnering og refusion",
  "section.refund.title": "Refusionspolitik",
  "section.shipto.hint": "Leveringsadresse",
  "section.shipto.title": "Leveres til",
  "section.signature.hint": "Godkendt underskrift",
  "section.signature.title": "Underskrift",
  "section.tax.hint": "Satser og rabatter",
  "section.tax.title": "Moms og totaler",
  "section.taxbreak.hint": "Momskomponenter",
  "section.taxbreak.title": "Momsoversigt",
  "section.terms.hint": "Afkrydsningsfelt til accept",
  "section.terms.title": "Betingelser",
  "section.theme.hint": "Farve, valuta, status",
  "section.theme.title": "Titel og tema",
  "seed.gallery.title": "Billeder",
  "seed.image.caption": "Tilføj en billedtekst",
  "seed.image.title": "Billede",
  "seed.item": "Ny vare",
  "seed.kv.label": "Etiket",
  "seed.kv.row1k": "Omkostningssted",
  "seed.kv.row2k": "Kontrakt",
  "seed.kv.title": "Referenceoplysninger",
  "seed.kv.value": "Værdi",
  "seed.text.body": "Skriv din egen tekst her — omfang, leveringsnoter, betingelser eller en besked til kunden.",
  "seed.text.title": "Yderligere noter",
  "status.draft": "Kladde",
  "status.live": "Aktiv",
  "status.overdue": "Forfalden",
  "status.paid": "Betalt",
  "status.sent": "Sendt",
  "toast.deleteFailed": "Kunne ikke slettes",
  "toast.duplicateFailed": "Kunne ikke duplikeres",
  "toast.duplicated.invoice": "Faktura duplikeret",
  "toast.duplicated.template": "Skabelon duplikeret",
  "toast.imageTooLarge": "Billedet er for stort (maks. {max})",
  "toast.imageUnreadable": "Filen kunne ikke læses",
  "toast.languageFailed": "Sproget kunne ikke tilføjes",
  "toast.notAnImage": "Den fil er ikke et billede",
  "toast.renameFailed": "Kunne ikke omdøbes",
  "topic.logistics": "Forsendelse og logistik",
  "topic.other": "Ikke kategoriseret",
  "topic.receipts": "Kvitteringer og refusioner",
  "topic.recurring": "Tilbagevendende",
  "topic.sales": "Salg og tilbud",
  "topic.services": "Professionelle ydelser"
} as Record<string, string>;
