// SPDX-License-Identifier: AGPL-3.0-only
/** GENERATED — de-DE strings for the invoices page. Do not edit by hand. */
export default {
  "add.allOn": "Alle Standardblöcke sind bereits auf dieser Rechnung.",
  "add.custom": "Selbst gestalten",
  "add.standard": "Standardblöcke",
  "add.subtitle": "Gestalten Sie einen eigenen Abschnitt oder schalten Sie einen der Standardblöcke ein.",
  "add.title": "Abschnitt hinzufügen",
  "canvas.addSection": "Abschnitt hinzufügen",
  "canvas.approval.approved": "Genehmigt",
  "canvas.approval.pending": "Ausstehend",
  "canvas.approval.rejected": "Abgelehnt",
  "canvas.approval.title": "Genehmigung",
  "canvas.attachments": "Anhänge",
  "canvas.blocks.parties": "Absender & Rechnung an",
  "canvas.blocks.paynotes": "Zahlung & Hinweise",
  "canvas.brandName": "Markenname",
  "canvas.brandingHint": "Marke · zum Bearbeiten klicken",
  "canvas.contact": "Fragen? Sprechen Sie uns an",
  "canvas.custom.addRow": "Zeile hinzufügen",
  "canvas.custom.body": "Abschnittstext",
  "canvas.custom.caption": "Bildunterschrift",
  "canvas.custom.clearImage": "Bild entfernen",
  "canvas.custom.clearSlot": "Entfernen",
  "canvas.custom.clearSlotOf": "Bild {n} entfernen",
  "canvas.custom.remove": "Abschnitt entfernen",
  "canvas.custom.removeOf": "Abschnitt entfernen: {title}",
  "canvas.custom.removeRow": "Zeile entfernen",
  "canvas.custom.removeRowOf": "Zeile {n} entfernen",
  "canvas.custom.rowLabel": "Beschriftung von Zeile {n}",
  "canvas.custom.rowValue": "Wert von Zeile {n}",
  "canvas.custom.titleLabel": "Abschnittstitel",
  "canvas.custom.upload": "Zum Hochladen eines Bildes klicken",
  "canvas.custom.uploadSlot": "Bild {n} hochladen",
  "canvas.customerName": "Kundenname",
  "canvas.dateSigned": "Datum der Unterschrift",
  "canvas.delivery.title": "Lieferverlauf",
  "canvas.discount.title": "Rabattcodes",
  "canvas.due": "Fällig",
  "canvas.from": "Absender",
  "canvas.insertAbove": "Abschnitt über {label} einfügen",
  "canvas.insertHere": "Hier einen Abschnitt einfügen",
  "canvas.invoiceTo": "Rechnung an",
  "canvas.issued": "Ausgestellt",
  "canvas.items.add": "Position hinzufügen",
  "canvas.items.amount": "Betrag",
  "canvas.items.description": "Beschreibung",
  "canvas.items.descriptionOf": "Beschreibung von Position {n}",
  "canvas.items.qty": "Menge",
  "canvas.items.qtyOf": "Menge von Position {n}",
  "canvas.items.rate": "Preis",
  "canvas.items.rateOf": "Preis von Position {n}",
  "canvas.items.remove": "Position entfernen: {name}",
  "canvas.items.reorder": "Zum Anordnen ziehen",
  "canvas.items.reorderOf": "Zum Anordnen ziehen: {name}",
  "canvas.items.row": "Position {n}",
  "canvas.latefees.sentence": "Auf Beträge, die mehr als {days} Tage nach dem Fälligkeitsdatum offen sind, fallen monatlich {rate} % Verzugsgebühr an.",
  "canvas.latefees.title": "Verzugsgebühr",
  "canvas.legal": "Rechtliches",
  "canvas.lines.customer": "Kundenzeile {n}",
  "canvas.lines.from": "Absenderzeile {n}",
  "canvas.lines.payment": "Zahlungszeile {n}",
  "canvas.lines.ship": "Lieferzeile {n}",
  "canvas.loyalty.balance": "{balance} Pkt. · {level}",
  "canvas.loyalty.title": "Punktestand",
  "canvas.multicurrency.note": "Umgerechnet aus {total} zu Richtkursen.",
  "canvas.multicurrency.title": "Auch zahlbar in",
  "canvas.notes": "Hinweise",
  "canvas.payhistory.title": "Zahlungsverlauf",
  "canvas.payment": "Zahlung",
  "canvas.poNumber": "Bestellnummer",
  "canvas.poTerms": "Bedingungen der Bestellung",
  "canvas.qr.due": "Fälliger Betrag · {total}",
  "canvas.qr.title": "Per QR-Code zahlen",
  "canvas.recurring.next": "Nächste am {next} · {count}",
  "canvas.recurring.title": "Wiederkehrend — {freq}",
  "canvas.refund": "Rückerstattungsregeln",
  "canvas.reorderSection": "Abschnitt zum Anordnen ziehen",
  "canvas.reorderSectionOf": "Abschnitt zum Anordnen ziehen: {label}",
  "canvas.select": "{label} bearbeiten",
  "canvas.shipName": "Empfängername",
  "canvas.shipTo": "Lieferung an",
  "canvas.sigName": "Name des Unterzeichners",
  "canvas.sigTitle": "Funktion des Unterzeichners",
  "canvas.signature": "Unterschrift",
  "canvas.taxbreak.title": "Steueraufschlüsselung",
  "canvas.terms": "Bedingungen",
  "canvas.termsAccepted": "Bedingungen angenommen",
  "canvas.termsLabel": "Beschriftung der Bedingungen",
  "canvas.totals.discount": "Rabatt ({rate})",
  "canvas.totals.subtotal": "Zwischensumme",
  "canvas.totals.tax": "Steuer ({rate})",
  "canvas.totals.total": "Gesamtbetrag",
  "card.delete": "Löschen",
  "card.duplicate": "Duplizieren",
  "card.edit": "Bearbeiten",
  "card.rename": "Umbenennen",
  "card.renameLabel": "Neuer Name",
  "card.total": "GESAMT",
  "custom.gallery.hint": "Zwei oder drei Bilder nebeneinander",
  "custom.gallery.label": "Bilderreihe",
  "custom.image.hint": "Foto, Zeichnung oder Zertifikat hochladen",
  "custom.image.label": "Bildblock",
  "custom.kv.hint": "Paare aus Beschriftung und Wert",
  "custom.kv.label": "Detailzeilen",
  "custom.text.hint": "Ihr eigener Text — Hinweise, Umfang, Bedingungen",
  "custom.text.label": "Textabschnitt",
  "delete.body.invoice": "Das lässt sich nicht rückgängig machen. Die Rechnung wird dauerhaft entfernt.",
  "delete.body.template": "Das lässt sich nicht rückgängig machen. Die Vorlage wird dauerhaft entfernt.",
  "delete.confirm": "Löschen",
  "delete.title": "{name} löschen?",
  "editor.delete": "Löschen",
  "editor.discard.body": "Ihre Änderungen an {name} gehen verloren.",
  "editor.discard.confirm": "Verwerfen",
  "editor.discard.keep": "Weiter bearbeiten",
  "editor.discard.title": "Nicht gespeicherte Änderungen verwerfen?",
  "editor.duplicate": "Duplizieren",
  "editor.images": "Bilder",
  "editor.kind.invoice": "Rechnung",
  "editor.kind.template": "Vorlage",
  "editor.loadFailed": "Dieses Dokument konnte nicht geladen werden",
  "editor.nameLabel": "Name",
  "editor.redo": "Wiederholen",
  "editor.saveFailed": "Konnte nicht gespeichert werden",
  "editor.saveInvoice": "Rechnung speichern",
  "editor.saveState.dirty": "Nicht gespeicherte Änderungen",
  "editor.saveState.error": "Nicht gespeichert",
  "editor.saveState.saved": "Alle Änderungen gespeichert",
  "editor.saveState.saving": "Wird gespeichert…",
  "editor.saveTemplate": "Vorlage speichern",
  "editor.sendInvoice": "Rechnung senden",
  "editor.shortcutSave": "Dokument speichern",
  "editor.undo": "Rückgängig",
  "empty.invoices.body": "Erstellen Sie Ihre erste Rechnung aus einer Vorlage oder auf leerer Fläche.",
  "empty.invoices.title": "Noch keine Rechnungen",
  "empty.noMatch.body": "Versuchen Sie einen anderen Suchbegriff.",
  "empty.noMatch.invoices": "Keine passenden Rechnungen",
  "empty.noMatch.templates": "Keine passenden Vorlagen",
  "empty.templates.body": "Erstellen Sie eine wiederverwendbare Rechnungsvorlage, aus der Ihr Team arbeiten kann.",
  "empty.templates.title": "Noch keine Vorlagen",
  "inspector.addLine": "Zeile hinzufügen",
  "inspector.approval.name": "Name des Genehmigers",
  "inspector.approval.status.approved": "Genehmigt",
  "inspector.approval.status.pending": "Ausstehend",
  "inspector.approval.status.rejected": "Abgelehnt",
  "inspector.approval.statusLabel": "Status",
  "inspector.approval.title": "Rolle / Funktion",
  "inspector.attachments.add": "Datei hinzufügen",
  "inspector.attachments.files": "Dateien",
  "inspector.attachments.name": "Name von Datei {n}",
  "inspector.attachments.removeRow": "Datei {n} entfernen",
  "inspector.attachments.seedName": "Neue Datei.pdf",
  "inspector.attachments.size": "Größe von Datei {n}",
  "inspector.branding.accentHintAfter": "& Design.",
  "inspector.branding.accentHintBefore": "Ändern Sie die Akzentfarbe im Abschnitt",
  "inspector.branding.accentHintBold": "Titel",
  "inspector.branding.brandName": "Markenname",
  "inspector.branding.logoImage": "Logobild",
  "inspector.branding.logoMark": "Logozeichen",
  "inspector.branding.logoNoteAfter": "in der Symbolleiste.",
  "inspector.branding.logoNoteBefore": "Ein hochgeladenes Logo ersetzt das Zeichen oben. Alle festen Bilder liegen unter",
  "inspector.branding.logoNoteBold": "Bilder",
  "inspector.branding.removeLogo": "Entfernen",
  "inspector.branding.uploadLogo": "Logo hochladen",
  "inspector.contact.email": "E-Mail",
  "inspector.contact.name": "Kontaktname",
  "inspector.contact.phone": "Telefon",
  "inspector.custom.addRow": "Zeile hinzufügen",
  "inspector.custom.body": "Fließtext",
  "inspector.custom.caption": "Bildunterschrift",
  "inspector.custom.galleryHint": "Klicken Sie auf der Rechnung auf jeden Platz, um ein Bild hochzuladen.",
  "inspector.custom.height": "Höhe",
  "inspector.custom.image": "Bild",
  "inspector.custom.remove": "Abschnitt entfernen",
  "inspector.custom.title": "Abschnittstitel",
  "inspector.custom.upload": "Hochladen / ersetzen",
  "inspector.customer.addressContact": "Adresse & Kontakt",
  "inspector.customer.clientName": "Kundenname",
  "inspector.delivery.add": "Schritt hinzufügen",
  "inspector.delivery.cycle": "Status von Schritt {n}: {status}",
  "inspector.delivery.label": "Schritt {n}",
  "inspector.delivery.note": "Tippen Sie auf den Status, um zwischen Ausstehend → In Arbeit → Erledigt zu wechseln.",
  "inspector.delivery.removeRow": "Schritt {n} entfernen",
  "inspector.delivery.seedLabel": "Neuer Schritt",
  "inspector.delivery.status.current": "In Arbeit",
  "inspector.delivery.status.done": "Erledigt",
  "inspector.delivery.status.todo": "Ausstehend",
  "inspector.delivery.steps": "Schritte",
  "inspector.discount.add": "Code hinzufügen",
  "inspector.discount.amount": "Betrag von Code {n}",
  "inspector.discount.code": "Code {n}",
  "inspector.discount.codePlaceholder": "CODE",
  "inspector.discount.codes": "Rabattcodes",
  "inspector.discount.label": "Beschreibung von Code {n}",
  "inspector.discount.labelPlaceholder": "Beschreibung",
  "inspector.discount.removeRow": "Code {n} entfernen",
  "inspector.discount.seedLabel": "Neuer Rabatt",
  "inspector.fallback.title": "Bearbeiten",
  "inspector.from.companyDetails": "Firmendaten",
  "inspector.images.addSection": "Bildabschnitt hinzufügen",
  "inspector.images.background": "Hintergrund",
  "inspector.images.backgroundHint": "Wasserzeichen hinter der Rechnung",
  "inspector.images.intro": "Feste Bilder, die mit der Rechnung mitgehen. Einmal hochladen — jedes Dokument aus dieser Vorlage behält sie.",
  "inspector.images.logo": "Logo",
  "inspector.images.logoHint": "Ersetzt das Logozeichen",
  "inspector.images.qr": "QR-Code",
  "inspector.images.qrHint": "Wird im QR-Zahlungsblock angezeigt",
  "inspector.images.remove": "Entfernen",
  "inspector.images.replace": "Ersetzen",
  "inspector.images.signature": "Unterschrift",
  "inspector.images.signatureHint": "Eingescannte Unterschrift",
  "inspector.images.stamp": "Stempel / Siegel",
  "inspector.images.stampHint": "Stempel für Bezahlt oder Genehmigt",
  "inspector.images.upload": "Hochladen",
  "inspector.images.uploadSlot": "{label} hochladen",
  "inspector.items.add": "Position hinzufügen",
  "inspector.items.count": "Positionen",
  "inspector.items.hint": "Bearbeiten Sie jede Zelle direkt auf der Rechnung oder ziehen Sie am Griff, um die Reihenfolge zu ändern.",
  "inspector.items.subtotal": "Zwischensumme",
  "inspector.latefees.grace": "Karenzzeit",
  "inspector.latefees.graceUnit": "Tage",
  "inspector.latefees.rate": "Gebührensatz",
  "inspector.latefees.rateUnit": "% monatlich",
  "inspector.legal.footer": "Rechtliche Fußzeile",
  "inspector.line": "{label} {n}",
  "inspector.loyalty.balance": "Punktestand",
  "inspector.loyalty.earned": "Erhaltene Punkte",
  "inspector.loyalty.level": "Stufe",
  "inspector.meta.due": "Fälligkeitsdatum",
  "inspector.meta.issued": "Rechnungsdatum",
  "inspector.meta.number": "Rechnungsnummer",
  "inspector.meta.poNumber": "Bestellnummer",
  "inspector.meta.terms": "Zahlungsbedingungen",
  "inspector.multicurrency.add": "Währung hinzufügen",
  "inspector.multicurrency.code": "Code von Währung {n}",
  "inspector.multicurrency.note": "Der Kurs wird mit dem Gesamtbetrag der Rechnung multipliziert. Code, Symbol, dann Kurs.",
  "inspector.multicurrency.rate": "Kurs von Währung {n}",
  "inspector.multicurrency.rates": "Währungen & Kurse",
  "inspector.multicurrency.removeRow": "Währung {n} entfernen",
  "inspector.multicurrency.symbol": "Symbol von Währung {n}",
  "inspector.notes.footerNotes": "Hinweise in der Fußzeile",
  "inspector.notes.hint": "Steht unten auf der Rechnung — Bedingungen, ein Dankeschön oder Rechtstext.",
  "inspector.payhistory.add": "Zahlung hinzufügen",
  "inspector.payhistory.amount": "Betrag von Zahlung {n}",
  "inspector.payhistory.amountPlaceholder": "Betrag",
  "inspector.payhistory.date": "Datum von Zahlung {n}",
  "inspector.payhistory.datePlaceholder": "Datum",
  "inspector.payhistory.method": "Art von Zahlung {n}",
  "inspector.payhistory.methodPlaceholder": "Zahlungsart",
  "inspector.payhistory.payments": "Zahlungen",
  "inspector.payhistory.removeRow": "Zahlung {n} entfernen",
  "inspector.payment.instructions": "Zahlungshinweise",
  "inspector.poterms.terms": "Bedingungen der Bestellung",
  "inspector.qr.caption": "Bildunterschrift",
  "inspector.qr.hint": "Codiert „Fälliger Betrag · {total}“. Angezeigt wird das Bild, das Sie unter „Bilder“ hochladen.",
  "inspector.recurring.annually": "Jährlich",
  "inspector.recurring.frequency": "Häufigkeit",
  "inspector.recurring.monthly": "Monatlich",
  "inspector.recurring.next": "Nächstes Ausgabedatum",
  "inspector.recurring.note": "Hinweis zum Rhythmus",
  "inspector.recurring.quarterly": "Vierteljährlich",
  "inspector.recurring.weekly": "Wöchentlich",
  "inspector.refund.policy": "Rückerstattungsregeln",
  "inspector.removeLine": "{label} {n} entfernen",
  "inspector.removeSection": "Abschnitt entfernen",
  "inspector.shipto.addressLines": "Adresszeilen",
  "inspector.shipto.name": "Name des Empfängers",
  "inspector.signature.hint": "Auf der Rechnung erscheinen eine Unterschriftenlinie und ein Datumsfeld zum Unterschreiben von Hand.",
  "inspector.signature.name": "Name des Unterzeichners",
  "inspector.signature.title": "Funktion / Rolle",
  "inspector.tax.discount": "Rabatt",
  "inspector.tax.discountRow": "Rabatt",
  "inspector.tax.subtotal": "Zwischensumme",
  "inspector.tax.tax": "Steuer",
  "inspector.tax.taxRate": "Steuersatz",
  "inspector.tax.total": "Gesamtbetrag",
  "inspector.taxbreak.add": "Steuerzeile hinzufügen",
  "inspector.taxbreak.components": "Steuerbestandteile",
  "inspector.taxbreak.label": "Beschriftung von Steuerzeile {n}",
  "inspector.taxbreak.note": "Jeder Satz wird auf die Zwischensumme nach Abzug des Rabatts angewendet.",
  "inspector.taxbreak.rate": "Satz von Steuerzeile {n}",
  "inspector.taxbreak.removeRow": "Steuerzeile {n} entfernen",
  "inspector.taxbreak.seedLabel": "Neue Steuer",
  "inspector.terms.checkboxLabel": "Beschriftung des Kästchens",
  "inspector.terms.preChecked": "Vorab angehakt",
  "inspector.terms.preCheckedHint": "Das Kästchen bereits angehakt anzeigen",
  "inspector.theme.accentColour": "Akzentfarbe",
  "inspector.theme.backgroundHint": "Legt einen randlosen Hintergrund hinter die ganze Rechnung — ideal für Briefpapier oder ein Wasserzeichen.",
  "inspector.theme.backgroundImage": "Hintergrundbild",
  "inspector.theme.currency": "Währung",
  "inspector.theme.documentTitle": "Dokumenttitel",
  "inspector.theme.language": "Sprache",
  "inspector.theme.languageNote": "Erstellen Sie mit der Sprachschaltfläche in der Symbolleiste eine verknüpfte Variante, statt diese hier neu auszuzeichnen.",
  "inspector.theme.overlay": "Überlagerung {pct} %",
  "inspector.theme.overlayLabel": "Überlagerung",
  "inspector.theme.removeBackground": "Entfernen",
  "inspector.theme.replaceBackground": "Ersetzen",
  "inspector.theme.showDecimals": "Nachkommastellen anzeigen",
  "inspector.theme.showDecimalsHint": "z. B. 290,00 $ statt 290 $",
  "inspector.theme.status.draft": "Entwurf",
  "inspector.theme.status.live": "Aktiv",
  "inspector.theme.status.overdue": "Überfällig",
  "inspector.theme.status.paid": "Bezahlt",
  "inspector.theme.status.sent": "Gesendet",
  "inspector.theme.statusLabel": "Status",
  "inspector.theme.topic.logistics": "Versand & Logistik",
  "inspector.theme.topic.other": "Ohne Kategorie",
  "inspector.theme.topic.receipts": "Belege & Erstattungen",
  "inspector.theme.topic.recurring": "Wiederkehrend",
  "inspector.theme.topic.sales": "Verkauf & Angebote",
  "inspector.theme.topic.services": "Dienstleistungen",
  "inspector.theme.topicLabel": "Thema",
  "inspector.theme.uploadBackground": "Hintergrund hochladen",
  "languages.de": "Deutsch",
  "languages.en": "Englisch",
  "languages.es": "Spanisch",
  "languages.footnote": "Eine neue Sprache erzeugt eine verknüpfte Kopie, gruppiert unter demselben Thema.",
  "languages.fr": "Französisch",
  "languages.ja": "Japanisch",
  "languages.pt": "Portugiesisch",
  "languages.state.create": "Anlegen",
  "languages.state.editing": "Bearbeiten",
  "languages.state.open": "Öffnen",
  "languages.title": "Sprachvarianten",
  "list.actions": "Aktionen",
  "list.name": "Name",
  "list.status": "Status",
  "list.updated": "Aktualisiert",
  "manager.group.documents": "{count, plural, one {# Dokument} other {# Dokumente}}",
  "manager.group.label": "Gruppierung",
  "manager.group.language": "Sprache",
  "manager.group.languages": "{count, plural, one {# Sprache} other {# Sprachen}}",
  "manager.group.none": "Keine",
  "manager.group.topic": "Thema",
  "manager.layout.gallery": "Galerie",
  "manager.layout.label": "Ansicht",
  "manager.layout.list": "Liste",
  "manager.loadFailed": "Rechnungen konnten nicht geladen werden",
  "manager.search.clear": "Suche löschen",
  "manager.search.invoices": "Rechnungen durchsuchen…",
  "manager.search.templates": "Vorlagen durchsuchen…",
  "manager.subtitle": "Wiederverwendbare Vorlagen und die Rechnungen, die Sie daraus erstellen.",
  "manager.tabs.invoices": "Rechnungen",
  "manager.tabs.label": "Art",
  "manager.tabs.templates": "Vorlagen",
  "manager.title": "Rechnungen",
  "manager.untitled": "Ohne Titel",
  "new.blank": "Leere Rechnung",
  "new.blankHint": "Von Grund auf beginnen",
  "new.category.adjustments": "Korrekturen",
  "new.category.business": "Unternehmen",
  "new.category.nonprofit": "Gemeinnützig",
  "new.category.payments": "Zahlungen",
  "new.category.projects": "Projekte",
  "new.category.recurring": "Wiederkehrend",
  "new.category.sales": "Verkauf",
  "new.category.services": "Dienstleistungen",
  "new.category.shipping": "Versand",
  "new.failed": "Konnte nicht erstellt werden",
  "new.invoice": "Neue Rechnung",
  "new.startersFailed": "Die Startvorlagen konnten nicht geladen werden. Beginnen Sie leer oder versuchen Sie es erneut.",
  "new.subtitle": "Beginnen Sie auf leerer Fläche oder mit einer fertigen Vorlage.",
  "new.template": "Neue Vorlage",
  "new.yourTemplates": "Ihre Vorlagen",
  "optional.approvalShow": "Genehmigung",
  "optional.attachShow": "Anhänge",
  "optional.conShow": "Kontakt",
  "optional.delShow": "Lieferverlauf",
  "optional.discShow": "Rabattcodes",
  "optional.lateShow": "Verzugsgebühren",
  "optional.legalShow": "Rechtliche Fußzeile",
  "optional.loyShow": "Treuepunkte",
  "optional.mcShow": "Mehrere Währungen",
  "optional.payhShow": "Zahlungsverlauf",
  "optional.poShow": "Bestellbedingungen",
  "optional.qrShow": "QR-Zahlung",
  "optional.recurShow": "Wiederkehrend",
  "optional.refShow": "Rückerstattungsregeln",
  "optional.shipShow": "Lieferung an",
  "optional.sigShow": "Unterschrift",
  "optional.taxbShow": "Steueraufschlüsselung",
  "optional.termsShow": "Zustimmung zu den Bedingungen",
  "section.approval.hint": "Stand der Genehmigung",
  "section.approval.title": "Genehmigung",
  "section.attachments.hint": "Angehängte Dateien",
  "section.attachments.title": "Anhänge",
  "section.branding.hint": "Logo & Markenname",
  "section.branding.title": "Marke",
  "section.contact.hint": "Kontaktdaten für den Support",
  "section.contact.title": "Kontakt",
  "section.custom.hint": "Ihr eigener Abschnitt",
  "section.custom.title": "Eigener Abschnitt",
  "section.customer.hint": "Kundendaten",
  "section.customer.title": "Rechnung an",
  "section.delivery.hint": "Stand der Lieferung",
  "section.delivery.title": "Lieferverlauf",
  "section.discount.hint": "Angewendete Aktionscodes",
  "section.discount.title": "Rabattcodes",
  "section.from.hint": "Ihre Firmendaten",
  "section.from.title": "Absender",
  "section.images.hint": "Logo, Hintergrund, QR & Fotos",
  "section.images.title": "Bilder",
  "section.items.hint": "Produkte & Leistungen",
  "section.items.title": "Positionen",
  "section.latefees.hint": "Aufschlag bei Verzug",
  "section.latefees.title": "Verzugsgebühren",
  "section.legal.hint": "Kleingedrucktes",
  "section.legal.title": "Rechtliche Fußzeile",
  "section.loyalty.hint": "Prämienguthaben",
  "section.loyalty.title": "Treuepunkte",
  "section.meta.hint": "Nummer, Daten, Bestellung & Bedingungen",
  "section.meta.title": "Rechnungsdaten",
  "section.multicurrency.hint": "Summen in anderen Währungen",
  "section.multicurrency.title": "Mehrere Währungen",
  "section.notes.hint": "Text in der Fußzeile",
  "section.notes.title": "Hinweise",
  "section.payhistory.hint": "Frühere Zahlungen",
  "section.payhistory.title": "Zahlungsverlauf",
  "section.payment.hint": "Wie bezahlt wird",
  "section.payment.title": "Zahlung",
  "section.poterms.hint": "Bedingungen der Bestellung",
  "section.poterms.title": "Bestellbedingungen",
  "section.qr.hint": "Code zum Scannen und Bezahlen",
  "section.qr.title": "QR-Zahlung",
  "section.recurring.hint": "Rhythmus der Abbuchung",
  "section.recurring.title": "Wiederkehrend",
  "section.refund.hint": "Rückgaben und Erstattungen",
  "section.refund.title": "Rückerstattungsregeln",
  "section.shipto.hint": "Lieferanschrift",
  "section.shipto.title": "Lieferung an",
  "section.signature.hint": "Verbindliche Unterzeichnung",
  "section.signature.title": "Unterschrift",
  "section.tax.hint": "Sätze & Rabatte",
  "section.tax.title": "Steuer & Summen",
  "section.taxbreak.hint": "Steuerbestandteile",
  "section.taxbreak.title": "Steueraufschlüsselung",
  "section.terms.hint": "Kästchen zur Zustimmung",
  "section.terms.title": "Bedingungen",
  "section.theme.hint": "Farbe, Währung, Status",
  "section.theme.title": "Titel & Design",
  "seed.gallery.title": "Bilder",
  "seed.image.caption": "Bildunterschrift hinzufügen",
  "seed.image.title": "Bild",
  "seed.item": "Neuer Eintrag",
  "seed.kv.label": "Beschriftung",
  "seed.kv.row1k": "Kostenstelle",
  "seed.kv.row2k": "Vertrag",
  "seed.kv.title": "Referenzangaben",
  "seed.kv.value": "Wert",
  "seed.text.body": "Fügen Sie hier Ihren eigenen Text ein — Umfang, Lieferhinweise, Bedingungen oder eine Nachricht an Ihre Kundschaft.",
  "seed.text.title": "Weitere Hinweise",
  "status.draft": "Entwurf",
  "status.live": "Aktiv",
  "status.overdue": "Überfällig",
  "status.paid": "Bezahlt",
  "status.sent": "Gesendet",
  "toast.deleteFailed": "Konnte nicht gelöscht werden",
  "toast.duplicateFailed": "Konnte nicht dupliziert werden",
  "toast.duplicated.invoice": "Rechnung dupliziert",
  "toast.duplicated.template": "Vorlage dupliziert",
  "toast.imageTooLarge": "Bild zu groß (max. {max})",
  "toast.imageUnreadable": "Diese Datei konnte nicht gelesen werden",
  "toast.languageFailed": "Diese Sprache konnte nicht hinzugefügt werden",
  "toast.notAnImage": "Diese Datei ist kein Bild",
  "toast.renameFailed": "Konnte nicht umbenannt werden",
  "topic.logistics": "Versand & Logistik",
  "topic.other": "Ohne Kategorie",
  "topic.receipts": "Belege & Erstattungen",
  "topic.recurring": "Wiederkehrend",
  "topic.sales": "Verkauf & Angebote",
  "topic.services": "Dienstleistungen"
} as Record<string, string>;
