// SPDX-License-Identifier: AGPL-3.0-only
/** GENERATED — en-US strings for the invoices page. Do not edit by hand. */
export default {
  "add.allOn": "Every standard block is already on this invoice.",
  "add.custom": "Build your own",
  "add.standard": "Standard blocks",
  "add.subtitle": "Build your own, or switch on one of the standard blocks.",
  "add.title": "Add a section",
  "canvas.addSection": "Add section",
  "canvas.approval.approved": "Approved",
  "canvas.approval.pending": "Pending",
  "canvas.approval.rejected": "Rejected",
  "canvas.approval.title": "Approval",
  "canvas.attachments": "Attachments",
  "canvas.blocks.parties": "From & Invoice to",
  "canvas.blocks.paynotes": "Payment & notes",
  "canvas.brandName": "Brand name",
  "canvas.brandingHint": "Branding · click to edit",
  "canvas.contact": "Questions? Contact us",
  "canvas.custom.addRow": "Add row",
  "canvas.custom.body": "Section body",
  "canvas.custom.caption": "Caption",
  "canvas.custom.clearImage": "Remove image",
  "canvas.custom.clearSlot": "Remove",
  "canvas.custom.clearSlotOf": "Remove image {n}",
  "canvas.custom.remove": "Remove section",
  "canvas.custom.removeOf": "Remove section: {title}",
  "canvas.custom.removeRow": "Remove row",
  "canvas.custom.removeRowOf": "Remove row {n}",
  "canvas.custom.rowLabel": "Label of row {n}",
  "canvas.custom.rowValue": "Value of row {n}",
  "canvas.custom.titleLabel": "Section title",
  "canvas.custom.upload": "Click to upload an image",
  "canvas.custom.uploadSlot": "Upload image {n}",
  "canvas.customerName": "Customer name",
  "canvas.dateSigned": "Date signed",
  "canvas.delivery.title": "Delivery timeline",
  "canvas.discount.title": "Discount codes",
  "canvas.due": "Due",
  "canvas.from": "From",
  "canvas.insertAbove": "Add a section above {label}",
  "canvas.insertHere": "Add a section here",
  "canvas.invoiceTo": "Invoice to",
  "canvas.issued": "Issued",
  "canvas.items.add": "Add line item",
  "canvas.items.amount": "Amount",
  "canvas.items.description": "Description",
  "canvas.items.descriptionOf": "Description of line {n}",
  "canvas.items.qty": "Qty",
  "canvas.items.qtyOf": "Quantity of line {n}",
  "canvas.items.rate": "Rate",
  "canvas.items.rateOf": "Rate of line {n}",
  "canvas.items.remove": "Remove line item: {name}",
  "canvas.items.reorder": "Drag to reorder",
  "canvas.items.reorderOf": "Drag to reorder: {name}",
  "canvas.items.row": "Line item {n}",
  "canvas.latefees.sentence": "A late fee of {rate}% per month applies to balances unpaid more than {days} days past the due date.",
  "canvas.latefees.title": "Late payment fee",
  "canvas.legal": "Legal",
  "canvas.lines.customer": "Customer line {n}",
  "canvas.lines.from": "From line {n}",
  "canvas.lines.payment": "Payment line {n}",
  "canvas.lines.ship": "Shipping line {n}",
  "canvas.loyalty.balance": "{balance} pts · {level}",
  "canvas.loyalty.title": "Loyalty balance",
  "canvas.multicurrency.note": "Converted from {total} at indicative rates.",
  "canvas.multicurrency.title": "Also payable in",
  "canvas.notes": "Notes",
  "canvas.payhistory.title": "Payment history",
  "canvas.payment": "Payment",
  "canvas.poNumber": "PO number",
  "canvas.poTerms": "Purchase order terms",
  "canvas.qr.due": "Amount due · {total}",
  "canvas.qr.title": "Pay by QR",
  "canvas.recurring.next": "Next on {next} · {count}",
  "canvas.recurring.title": "Recurring — {freq}",
  "canvas.refund": "Refund policy",
  "canvas.reorderSection": "Drag to reorder section",
  "canvas.reorderSectionOf": "Drag to reorder section: {label}",
  "canvas.select": "Edit {label}",
  "canvas.shipName": "Shipping name",
  "canvas.shipTo": "Ship to",
  "canvas.sigName": "Signer name",
  "canvas.sigTitle": "Signer title",
  "canvas.signature": "Signature",
  "canvas.taxbreak.title": "Tax breakdown",
  "canvas.terms": "Terms",
  "canvas.termsAccepted": "Terms accepted",
  "canvas.termsLabel": "Terms label",
  "canvas.totals.discount": "Discount ({rate})",
  "canvas.totals.subtotal": "Subtotal",
  "canvas.totals.tax": "Tax ({rate})",
  "canvas.totals.total": "Total",
  "card.delete": "Delete",
  "card.duplicate": "Duplicate",
  "card.edit": "Edit",
  "card.rename": "Rename",
  "card.renameLabel": "New name",
  "card.total": "TOTAL",
  "custom.gallery.hint": "Two or three images side by side",
  "custom.gallery.label": "Image row",
  "custom.image.hint": "Upload a photo, drawing or certificate",
  "custom.image.label": "Image block",
  "custom.kv.hint": "Label / value pairs",
  "custom.kv.label": "Detail rows",
  "custom.text.hint": "Your own copy — notes, scope, conditions",
  "custom.text.label": "Text section",
  "delete.body.invoice": "This can’t be undone. The invoice will be permanently removed.",
  "delete.body.template": "This can’t be undone. The template will be permanently removed.",
  "delete.confirm": "Delete",
  "delete.title": "Delete {name}?",
  "editor.delete": "Delete",
  "editor.discard.body": "Your edits to {name} will be lost.",
  "editor.discard.confirm": "Discard",
  "editor.discard.keep": "Keep editing",
  "editor.discard.title": "Discard unsaved changes?",
  "editor.duplicate": "Duplicate",
  "editor.images": "Images",
  "editor.kind.invoice": "Invoice",
  "editor.kind.template": "Template",
  "editor.loadFailed": "Couldn’t load this document",
  "editor.nameLabel": "Name",
  "editor.redo": "Redo",
  "editor.saveFailed": "Could not save",
  "editor.saveInvoice": "Save invoice",
  "editor.saveState.dirty": "Unsaved changes",
  "editor.saveState.error": "Couldn’t save",
  "editor.saveState.saved": "All changes saved",
  "editor.saveState.saving": "Saving…",
  "editor.saveTemplate": "Save template",
  "editor.sendInvoice": "Send invoice",
  "editor.shortcutSave": "Save the document",
  "editor.undo": "Undo",
  "empty.invoices.body": "Build your first invoice from a template or a blank canvas.",
  "empty.invoices.title": "No invoices yet",
  "empty.noMatch.body": "Try a different search term.",
  "empty.noMatch.invoices": "No invoices match",
  "empty.noMatch.templates": "No templates match",
  "empty.templates.body": "Create a reusable invoice template your team can build from.",
  "empty.templates.title": "No templates yet",
  "inspector.addLine": "Add line",
  "inspector.approval.name": "Approver name",
  "inspector.approval.status.approved": "Approved",
  "inspector.approval.status.pending": "Pending",
  "inspector.approval.status.rejected": "Rejected",
  "inspector.approval.statusLabel": "Status",
  "inspector.approval.title": "Role / title",
  "inspector.attachments.add": "Add file",
  "inspector.attachments.files": "Files",
  "inspector.attachments.name": "File {n} name",
  "inspector.attachments.removeRow": "Remove file {n}",
  "inspector.attachments.seedName": "New file.pdf",
  "inspector.attachments.size": "File {n} size",
  "inspector.branding.accentHintAfter": "section.",
  "inspector.branding.accentHintBefore": "Change the accent colour under the",
  "inspector.branding.accentHintBold": "title",
  "inspector.branding.brandName": "Brand name",
  "inspector.branding.logoImage": "Logo image",
  "inspector.branding.logoMark": "Logo mark",
  "inspector.branding.logoNoteAfter": "in the toolbar.",
  "inspector.branding.logoNoteBefore": "An uploaded logo replaces the mark above. All fixed images live under",
  "inspector.branding.logoNoteBold": "Images",
  "inspector.branding.removeLogo": "Remove",
  "inspector.branding.uploadLogo": "Upload logo",
  "inspector.contact.email": "Email",
  "inspector.contact.name": "Contact name",
  "inspector.contact.phone": "Phone",
  "inspector.custom.addRow": "Add row",
  "inspector.custom.body": "Body copy",
  "inspector.custom.caption": "Caption",
  "inspector.custom.galleryHint": "Click each slot on the invoice to upload an image.",
  "inspector.custom.height": "Height",
  "inspector.custom.image": "Image",
  "inspector.custom.remove": "Remove section",
  "inspector.custom.title": "Section title",
  "inspector.custom.upload": "Upload / replace",
  "inspector.customer.addressContact": "Address & contact",
  "inspector.customer.clientName": "Client name",
  "inspector.delivery.add": "Add step",
  "inspector.delivery.cycle": "Step {n} status: {status}",
  "inspector.delivery.label": "Step {n}",
  "inspector.delivery.note": "Tap the status to cycle Pending → In progress → Done.",
  "inspector.delivery.removeRow": "Remove step {n}",
  "inspector.delivery.seedLabel": "New step",
  "inspector.delivery.status.current": "In progress",
  "inspector.delivery.status.done": "Done",
  "inspector.delivery.status.todo": "Pending",
  "inspector.delivery.steps": "Steps",
  "inspector.discount.add": "Add code",
  "inspector.discount.amount": "Code {n} amount",
  "inspector.discount.code": "Code {n}",
  "inspector.discount.codePlaceholder": "CODE",
  "inspector.discount.codes": "Discount codes",
  "inspector.discount.label": "Code {n} description",
  "inspector.discount.labelPlaceholder": "Description",
  "inspector.discount.removeRow": "Remove code {n}",
  "inspector.discount.seedLabel": "New discount",
  "inspector.fallback.title": "Edit",
  "inspector.from.companyDetails": "Company details",
  "inspector.images.addSection": "Add an image section",
  "inspector.images.background": "Background",
  "inspector.images.backgroundHint": "Watermark behind the invoice",
  "inspector.images.intro": "Fixed images that travel with the invoice. Upload once and every document built from this template keeps them.",
  "inspector.images.logo": "Logo",
  "inspector.images.logoHint": "Replaces the logo mark",
  "inspector.images.qr": "QR code",
  "inspector.images.qrHint": "Shown in the payment QR block",
  "inspector.images.remove": "Remove",
  "inspector.images.replace": "Replace",
  "inspector.images.signature": "Signature",
  "inspector.images.signatureHint": "Scanned signature image",
  "inspector.images.stamp": "Stamp / seal",
  "inspector.images.stampHint": "Paid or approval stamp",
  "inspector.images.upload": "Upload",
  "inspector.images.uploadSlot": "Upload {label}",
  "inspector.items.add": "Add line item",
  "inspector.items.count": "Line items",
  "inspector.items.hint": "Edit any cell directly on the invoice, or drag the handle to reorder.",
  "inspector.items.subtotal": "Subtotal",
  "inspector.latefees.grace": "Grace period",
  "inspector.latefees.graceUnit": "days",
  "inspector.latefees.rate": "Late fee rate",
  "inspector.latefees.rateUnit": "% per month",
  "inspector.legal.footer": "Legal footer",
  "inspector.line": "{label} {n}",
  "inspector.loyalty.balance": "Points balance",
  "inspector.loyalty.earned": "Points earned",
  "inspector.loyalty.level": "Level",
  "inspector.meta.due": "Due date",
  "inspector.meta.issued": "Issue date",
  "inspector.meta.number": "Invoice number",
  "inspector.meta.poNumber": "PO number",
  "inspector.meta.terms": "Payment terms",
  "inspector.multicurrency.add": "Add currency",
  "inspector.multicurrency.code": "Currency {n} code",
  "inspector.multicurrency.note": "Rate is multiplied by the invoice total. Code, symbol, then rate.",
  "inspector.multicurrency.rate": "Currency {n} rate",
  "inspector.multicurrency.rates": "Currencies & rates",
  "inspector.multicurrency.removeRow": "Remove currency {n}",
  "inspector.multicurrency.symbol": "Currency {n} symbol",
  "inspector.notes.footerNotes": "Footer notes",
  "inspector.notes.hint": "Shown at the bottom of the invoice — terms, thank-you note, or legal text.",
  "inspector.payhistory.add": "Add payment",
  "inspector.payhistory.amount": "Payment {n} amount",
  "inspector.payhistory.amountPlaceholder": "Amount",
  "inspector.payhistory.date": "Payment {n} date",
  "inspector.payhistory.datePlaceholder": "Date",
  "inspector.payhistory.method": "Payment {n} method",
  "inspector.payhistory.methodPlaceholder": "Method",
  "inspector.payhistory.payments": "Payments",
  "inspector.payhistory.removeRow": "Remove payment {n}",
  "inspector.payment.instructions": "Payment instructions",
  "inspector.poterms.terms": "Purchase order terms",
  "inspector.qr.caption": "Caption",
  "inspector.qr.hint": "Encodes Amount due · {total}. The code shown is the image you upload under Images.",
  "inspector.recurring.annually": "Annually",
  "inspector.recurring.frequency": "Frequency",
  "inspector.recurring.monthly": "Monthly",
  "inspector.recurring.next": "Next issue date",
  "inspector.recurring.note": "Schedule note",
  "inspector.recurring.quarterly": "Quarterly",
  "inspector.recurring.weekly": "Weekly",
  "inspector.refund.policy": "Refund policy",
  "inspector.removeLine": "Remove {label} {n}",
  "inspector.removeSection": "Remove section",
  "inspector.shipto.addressLines": "Address lines",
  "inspector.shipto.name": "Ship-to name",
  "inspector.signature.hint": "A signature line and date field appear on the invoice for hand-signing.",
  "inspector.signature.name": "Signatory name",
  "inspector.signature.title": "Title / role",
  "inspector.tax.discount": "Discount",
  "inspector.tax.discountRow": "Discount",
  "inspector.tax.subtotal": "Subtotal",
  "inspector.tax.tax": "Tax",
  "inspector.tax.taxRate": "Tax rate",
  "inspector.tax.total": "Total",
  "inspector.taxbreak.add": "Add tax line",
  "inspector.taxbreak.components": "Tax components",
  "inspector.taxbreak.label": "Tax line {n} label",
  "inspector.taxbreak.note": "Each rate is applied to the subtotal after any discount.",
  "inspector.taxbreak.rate": "Tax line {n} rate",
  "inspector.taxbreak.removeRow": "Remove tax line {n}",
  "inspector.taxbreak.seedLabel": "New tax",
  "inspector.terms.checkboxLabel": "Checkbox label",
  "inspector.terms.preChecked": "Pre-checked",
  "inspector.terms.preCheckedHint": "Show the box already ticked",
  "inspector.theme.accentColour": "Accent colour",
  "inspector.theme.backgroundHint": "Adds a full-bleed background behind the whole invoice — great for letterhead or a watermark.",
  "inspector.theme.backgroundImage": "Background image",
  "inspector.theme.currency": "Currency",
  "inspector.theme.documentTitle": "Document title",
  "inspector.theme.language": "Language",
  "inspector.theme.languageNote": "Use the language button in the toolbar to create a linked variation instead of re-tagging this one.",
  "inspector.theme.overlay": "Overlay {pct}%",
  "inspector.theme.overlayLabel": "Overlay",
  "inspector.theme.removeBackground": "Remove",
  "inspector.theme.replaceBackground": "Replace",
  "inspector.theme.showDecimals": "Show decimals",
  "inspector.theme.showDecimalsHint": "e.g. $290.00 vs $290",
  "inspector.theme.status.draft": "Draft",
  "inspector.theme.status.live": "Live",
  "inspector.theme.status.overdue": "Overdue",
  "inspector.theme.status.paid": "Paid",
  "inspector.theme.status.sent": "Sent",
  "inspector.theme.statusLabel": "Status",
  "inspector.theme.topic.logistics": "Shipping & logistics",
  "inspector.theme.topic.other": "Uncategorised",
  "inspector.theme.topic.receipts": "Receipts & refunds",
  "inspector.theme.topic.recurring": "Recurring",
  "inspector.theme.topic.sales": "Sales & quotes",
  "inspector.theme.topic.services": "Professional services",
  "inspector.theme.topicLabel": "Topic",
  "inspector.theme.uploadBackground": "Upload background",
  "languages.de": "German",
  "languages.en": "English",
  "languages.es": "Spanish",
  "languages.footnote": "Creating a language makes a linked copy, grouped under the same topic.",
  "languages.fr": "French",
  "languages.ja": "Japanese",
  "languages.pt": "Portuguese",
  "languages.state.create": "Create",
  "languages.state.editing": "Editing",
  "languages.state.open": "Open",
  "languages.title": "Language variations",
  "list.actions": "Actions",
  "list.name": "Name",
  "list.status": "Status",
  "list.updated": "Updated",
  "manager.group.documents": "{count, plural, one {# document} other {# documents}}",
  "manager.group.label": "Group",
  "manager.group.language": "Language",
  "manager.group.languages": "{count, plural, one {# language} other {# languages}}",
  "manager.group.none": "None",
  "manager.group.topic": "Topic",
  "manager.layout.gallery": "Gallery",
  "manager.layout.label": "Layout",
  "manager.layout.list": "List",
  "manager.loadFailed": "Couldn’t load invoices",
  "manager.search.clear": "Clear search",
  "manager.search.invoices": "Search invoices…",
  "manager.search.templates": "Search templates…",
  "manager.subtitle": "Reusable templates & the invoices you build from them.",
  "manager.tabs.invoices": "Invoices",
  "manager.tabs.label": "Kind",
  "manager.tabs.templates": "Templates",
  "manager.title": "Invoices",
  "manager.untitled": "Untitled",
  "new.blank": "Blank invoice",
  "new.blankHint": "Build from scratch",
  "new.category.adjustments": "Adjustments",
  "new.category.business": "Business",
  "new.category.nonprofit": "Nonprofit",
  "new.category.payments": "Payments",
  "new.category.projects": "Projects",
  "new.category.recurring": "Recurring",
  "new.category.sales": "Sales",
  "new.category.services": "Services",
  "new.category.shipping": "Shipping",
  "new.failed": "Could not create it",
  "new.invoice": "New invoice",
  "new.startersFailed": "The starters could not be loaded. Start blank, or try again.",
  "new.subtitle": "Start from a blank canvas or a ready-made template.",
  "new.template": "New template",
  "new.yourTemplates": "Your templates",
  "optional.approvalShow": "Approval",
  "optional.attachShow": "Attachments",
  "optional.conShow": "Contact",
  "optional.delShow": "Delivery timeline",
  "optional.discShow": "Discount codes",
  "optional.lateShow": "Late fees",
  "optional.legalShow": "Legal footer",
  "optional.loyShow": "Loyalty points",
  "optional.mcShow": "Multi-currency",
  "optional.payhShow": "Payment history",
  "optional.poShow": "PO terms",
  "optional.qrShow": "Payment QR",
  "optional.recurShow": "Recurring",
  "optional.refShow": "Refund policy",
  "optional.shipShow": "Ship to",
  "optional.sigShow": "Signature",
  "optional.taxbShow": "Tax breakdown",
  "optional.termsShow": "Terms acceptance",
  "section.approval.hint": "Sign-off status",
  "section.approval.title": "Approval",
  "section.attachments.hint": "Attached files",
  "section.attachments.title": "Attachments",
  "section.branding.hint": "Logo & brand name",
  "section.branding.title": "Branding",
  "section.contact.hint": "Support details",
  "section.contact.title": "Contact",
  "section.custom.hint": "Your own section",
  "section.custom.title": "Custom section",
  "section.customer.hint": "Client details",
  "section.customer.title": "Invoice to",
  "section.delivery.hint": "Fulfilment status",
  "section.delivery.title": "Delivery timeline",
  "section.discount.hint": "Applied promo codes",
  "section.discount.title": "Discount codes",
  "section.from.hint": "Your company details",
  "section.from.title": "From",
  "section.images.hint": "Logo, background, QR & photos",
  "section.images.title": "Images",
  "section.items.hint": "Products & services",
  "section.items.title": "Line items",
  "section.latefees.hint": "Overdue penalty",
  "section.latefees.title": "Late fees",
  "section.legal.hint": "Fine print",
  "section.legal.title": "Legal footer",
  "section.loyalty.hint": "Rewards balance",
  "section.loyalty.title": "Loyalty points",
  "section.meta.hint": "Number, dates, PO & terms",
  "section.meta.title": "Invoice details",
  "section.multicurrency.hint": "Totals in other currencies",
  "section.multicurrency.title": "Multi-currency",
  "section.notes.hint": "Footer text",
  "section.notes.title": "Notes",
  "section.payhistory.hint": "Past payments",
  "section.payhistory.title": "Payment history",
  "section.payment.hint": "How to pay",
  "section.payment.title": "Payment",
  "section.poterms.hint": "Purchase order terms",
  "section.poterms.title": "PO terms",
  "section.qr.hint": "Scan-to-pay code",
  "section.qr.title": "Payment QR",
  "section.recurring.hint": "Charge schedule",
  "section.recurring.title": "Recurring",
  "section.refund.hint": "Returns & refunds",
  "section.refund.title": "Refund policy",
  "section.shipto.hint": "Delivery address",
  "section.shipto.title": "Ship to",
  "section.signature.hint": "Authorised sign-off",
  "section.signature.title": "Signature",
  "section.tax.hint": "Rates & discounts",
  "section.tax.title": "Tax & totals",
  "section.taxbreak.hint": "Tax components",
  "section.taxbreak.title": "Tax breakdown",
  "section.terms.hint": "Acceptance checkbox",
  "section.terms.title": "Terms",
  "section.theme.hint": "Colour, currency, status",
  "section.theme.title": "Title & theme",
  "seed.gallery.title": "Images",
  "seed.image.caption": "Add a caption",
  "seed.image.title": "Image",
  "seed.item": "New item",
  "seed.kv.label": "Label",
  "seed.kv.row1k": "Cost centre",
  "seed.kv.row2k": "Contract",
  "seed.kv.title": "Reference details",
  "seed.kv.value": "Value",
  "seed.text.body": "Add your own copy here — scope, delivery notes, conditions or a message to the client.",
  "seed.text.title": "Additional notes",
  "status.draft": "Draft",
  "status.live": "Live",
  "status.overdue": "Overdue",
  "status.paid": "Paid",
  "status.sent": "Sent",
  "toast.deleteFailed": "Could not delete it",
  "toast.duplicateFailed": "Could not duplicate it",
  "toast.duplicated.invoice": "Invoice duplicated",
  "toast.duplicated.template": "Template duplicated",
  "toast.imageTooLarge": "Image too large (max {max})",
  "toast.imageUnreadable": "Could not read that file",
  "toast.languageFailed": "Could not add that language",
  "toast.notAnImage": "That file is not an image",
  "toast.renameFailed": "Could not rename it",
  "topic.logistics": "Shipping & logistics",
  "topic.other": "Uncategorised",
  "topic.receipts": "Receipts & refunds",
  "topic.recurring": "Recurring",
  "topic.sales": "Sales & quotes",
  "topic.services": "Professional services"
} as Record<string, string>;
