// SPDX-License-Identifier: AGPL-3.0-only
/** GENERATED — fr-FR strings for the invoices page. Do not edit by hand. */
export default {
  "add.allOn": "Tous les blocs standard figurent déjà sur cette facture.",
  "add.custom": "Créer la vôtre",
  "add.standard": "Blocs standard",
  "add.subtitle": "Créez la vôtre, ou activez l’un des blocs standard.",
  "add.title": "Ajouter une section",
  "canvas.addSection": "Ajouter une section",
  "canvas.approval.approved": "Approuvé",
  "canvas.approval.pending": "En attente",
  "canvas.approval.rejected": "Refusé",
  "canvas.approval.title": "Approbation",
  "canvas.attachments": "Pièces jointes",
  "canvas.blocks.parties": "Émetteur et destinataire",
  "canvas.blocks.paynotes": "Paiement et notes",
  "canvas.brandName": "Nom de la marque",
  "canvas.brandingHint": "Identité visuelle · cliquez pour modifier",
  "canvas.contact": "Des questions ? Contactez-nous",
  "canvas.custom.addRow": "Ajouter une ligne",
  "canvas.custom.body": "Corps de la section",
  "canvas.custom.caption": "Légende",
  "canvas.custom.clearImage": "Supprimer l’image",
  "canvas.custom.clearSlot": "Supprimer",
  "canvas.custom.clearSlotOf": "Supprimer l’image {n}",
  "canvas.custom.remove": "Supprimer la section",
  "canvas.custom.removeOf": "Supprimer la section : {title}",
  "canvas.custom.removeRow": "Supprimer la ligne",
  "canvas.custom.removeRowOf": "Supprimer la ligne {n}",
  "canvas.custom.rowLabel": "Étiquette de la ligne {n}",
  "canvas.custom.rowValue": "Valeur de la ligne {n}",
  "canvas.custom.titleLabel": "Titre de la section",
  "canvas.custom.upload": "Cliquez pour téléverser une image",
  "canvas.custom.uploadSlot": "Téléverser l’image {n}",
  "canvas.customerName": "Nom du client",
  "canvas.dateSigned": "Date de signature",
  "canvas.delivery.title": "Suivi de livraison",
  "canvas.discount.title": "Codes de remise",
  "canvas.due": "Échéance",
  "canvas.from": "Émetteur",
  "canvas.insertAbove": "Ajouter une section au-dessus de {label}",
  "canvas.insertHere": "Ajouter une section ici",
  "canvas.invoiceTo": "Facturer à",
  "canvas.issued": "Émission",
  "canvas.items.add": "Ajouter une ligne",
  "canvas.items.amount": "Montant",
  "canvas.items.description": "Description",
  "canvas.items.descriptionOf": "Description de la ligne {n}",
  "canvas.items.qty": "Qté",
  "canvas.items.qtyOf": "Quantité de la ligne {n}",
  "canvas.items.rate": "P.U.",
  "canvas.items.rateOf": "Prix unitaire de la ligne {n}",
  "canvas.items.remove": "Supprimer la ligne : {name}",
  "canvas.items.reorder": "Faites glisser pour réorganiser",
  "canvas.items.reorderOf": "Faites glisser pour réorganiser : {name}",
  "canvas.items.row": "Ligne de facture {n}",
  "canvas.latefees.sentence": "Des pénalités de retard de {rate} % par mois s’appliquent aux soldes impayés plus de {days} jours après la date d’échéance.",
  "canvas.latefees.title": "Pénalités de retard",
  "canvas.legal": "Mentions légales",
  "canvas.lines.customer": "Ligne client {n}",
  "canvas.lines.from": "Ligne émetteur {n}",
  "canvas.lines.payment": "Ligne paiement {n}",
  "canvas.lines.ship": "Ligne livraison {n}",
  "canvas.loyalty.balance": "{balance} pts · {level}",
  "canvas.loyalty.title": "Solde de fidélité",
  "canvas.multicurrency.note": "Converti depuis {total} à des taux indicatifs.",
  "canvas.multicurrency.title": "Également payable en",
  "canvas.notes": "Notes",
  "canvas.payhistory.title": "Historique des paiements",
  "canvas.payment": "Paiement",
  "canvas.poNumber": "N° de bon de commande",
  "canvas.poTerms": "Conditions du bon de commande",
  "canvas.qr.due": "Montant dû · {total}",
  "canvas.qr.title": "Payer par QR",
  "canvas.recurring.next": "Prochaine le {next} · {count}",
  "canvas.recurring.title": "Récurrent — {freq}",
  "canvas.refund": "Politique de remboursement",
  "canvas.reorderSection": "Faites glisser pour réorganiser la section",
  "canvas.reorderSectionOf": "Faites glisser pour réorganiser la section : {label}",
  "canvas.select": "Modifier {label}",
  "canvas.shipName": "Nom du destinataire",
  "canvas.shipTo": "Livrer à",
  "canvas.sigName": "Nom du signataire",
  "canvas.sigTitle": "Fonction du signataire",
  "canvas.signature": "Signature",
  "canvas.taxbreak.title": "Détail des taxes",
  "canvas.terms": "Conditions",
  "canvas.termsAccepted": "Conditions acceptées",
  "canvas.termsLabel": "Libellé des conditions",
  "canvas.totals.discount": "Remise ({rate})",
  "canvas.totals.subtotal": "Sous-total",
  "canvas.totals.tax": "Taxe ({rate})",
  "canvas.totals.total": "Total",
  "card.delete": "Supprimer",
  "card.duplicate": "Dupliquer",
  "card.edit": "Modifier",
  "card.rename": "Renommer",
  "card.renameLabel": "Nouveau nom",
  "card.total": "TOTAL",
  "custom.gallery.hint": "Deux ou trois images côte à côte",
  "custom.gallery.label": "Rangée d’images",
  "custom.image.hint": "Téléversez une photo, un dessin ou un certificat",
  "custom.image.label": "Bloc image",
  "custom.kv.hint": "Paires étiquette / valeur",
  "custom.kv.label": "Lignes de détail",
  "custom.text.hint": "Votre propre texte — notes, périmètre, conditions",
  "custom.text.label": "Section de texte",
  "delete.body.invoice": "Cette action est irréversible. La facture sera définitivement supprimée.",
  "delete.body.template": "Cette action est irréversible. Le modèle sera définitivement supprimé.",
  "delete.confirm": "Supprimer",
  "delete.title": "Supprimer {name} ?",
  "editor.delete": "Supprimer",
  "editor.discard.body": "Vos modifications de {name} seront perdues.",
  "editor.discard.confirm": "Abandonner",
  "editor.discard.keep": "Continuer l’édition",
  "editor.discard.title": "Abandonner les modifications non enregistrées ?",
  "editor.duplicate": "Dupliquer",
  "editor.images": "Images",
  "editor.kind.invoice": "Facture",
  "editor.kind.template": "Modèle",
  "editor.loadFailed": "Impossible de charger ce document",
  "editor.nameLabel": "Nom",
  "editor.redo": "Rétablir",
  "editor.saveFailed": "Enregistrement impossible",
  "editor.saveInvoice": "Enregistrer la facture",
  "editor.saveState.dirty": "Modifications non enregistrées",
  "editor.saveState.error": "Enregistrement impossible",
  "editor.saveState.saved": "Toutes les modifications sont enregistrées",
  "editor.saveState.saving": "Enregistrement…",
  "editor.saveTemplate": "Enregistrer le modèle",
  "editor.sendInvoice": "Envoyer la facture",
  "editor.shortcutSave": "Enregistrer le document",
  "editor.undo": "Annuler",
  "empty.invoices.body": "Composez votre première facture à partir d’un modèle ou d’une page vierge.",
  "empty.invoices.title": "Aucune facture pour l’instant",
  "empty.noMatch.body": "Essayez un autre terme de recherche.",
  "empty.noMatch.invoices": "Aucune facture ne correspond",
  "empty.noMatch.templates": "Aucun modèle ne correspond",
  "empty.templates.body": "Créez un modèle de facture réutilisable à partir duquel votre équipe peut travailler.",
  "empty.templates.title": "Aucun modèle pour l’instant",
  "inspector.addLine": "Ajouter une ligne",
  "inspector.approval.name": "Nom de l’approbateur",
  "inspector.approval.status.approved": "Approuvé",
  "inspector.approval.status.pending": "En attente",
  "inspector.approval.status.rejected": "Refusé",
  "inspector.approval.statusLabel": "Statut",
  "inspector.approval.title": "Rôle / fonction",
  "inspector.attachments.add": "Ajouter un fichier",
  "inspector.attachments.files": "Fichiers",
  "inspector.attachments.name": "Nom du fichier {n}",
  "inspector.attachments.removeRow": "Supprimer le fichier {n}",
  "inspector.attachments.seedName": "Nouveau fichier.pdf",
  "inspector.attachments.size": "Taille du fichier {n}",
  "inspector.branding.accentHintAfter": "et thème.",
  "inspector.branding.accentHintBefore": "Modifiez la couleur d’accentuation dans la section",
  "inspector.branding.accentHintBold": "Titre",
  "inspector.branding.brandName": "Nom de la marque",
  "inspector.branding.logoImage": "Image du logo",
  "inspector.branding.logoMark": "Monogramme",
  "inspector.branding.logoNoteAfter": "dans la barre d’outils.",
  "inspector.branding.logoNoteBefore": "Un logo téléversé remplace le monogramme ci-dessus. Toutes les images fixes se trouvent sous",
  "inspector.branding.logoNoteBold": "Images",
  "inspector.branding.removeLogo": "Supprimer",
  "inspector.branding.uploadLogo": "Téléverser un logo",
  "inspector.contact.email": "E-mail",
  "inspector.contact.name": "Nom du contact",
  "inspector.contact.phone": "Téléphone",
  "inspector.custom.addRow": "Ajouter une ligne",
  "inspector.custom.body": "Corps du texte",
  "inspector.custom.caption": "Légende",
  "inspector.custom.galleryHint": "Cliquez sur chaque emplacement de la facture pour téléverser une image.",
  "inspector.custom.height": "Hauteur",
  "inspector.custom.image": "Image",
  "inspector.custom.remove": "Supprimer la section",
  "inspector.custom.title": "Titre de la section",
  "inspector.custom.upload": "Téléverser / remplacer",
  "inspector.customer.addressContact": "Adresse et contact",
  "inspector.customer.clientName": "Nom du client",
  "inspector.delivery.add": "Ajouter une étape",
  "inspector.delivery.cycle": "Statut de l’étape {n} : {status}",
  "inspector.delivery.label": "Étape {n}",
  "inspector.delivery.note": "Appuyez sur le statut pour faire défiler En attente → En cours → Terminé.",
  "inspector.delivery.removeRow": "Supprimer l’étape {n}",
  "inspector.delivery.seedLabel": "Nouvelle étape",
  "inspector.delivery.status.current": "En cours",
  "inspector.delivery.status.done": "Terminé",
  "inspector.delivery.status.todo": "En attente",
  "inspector.delivery.steps": "Étapes",
  "inspector.discount.add": "Ajouter un code",
  "inspector.discount.amount": "Montant du code {n}",
  "inspector.discount.code": "Code {n}",
  "inspector.discount.codePlaceholder": "CODE",
  "inspector.discount.codes": "Codes de remise",
  "inspector.discount.label": "Description du code {n}",
  "inspector.discount.labelPlaceholder": "Description",
  "inspector.discount.removeRow": "Supprimer le code {n}",
  "inspector.discount.seedLabel": "Nouvelle remise",
  "inspector.fallback.title": "Modifier",
  "inspector.from.companyDetails": "Coordonnées de l’entreprise",
  "inspector.images.addSection": "Ajouter une section image",
  "inspector.images.background": "Fond",
  "inspector.images.backgroundHint": "Filigrane derrière la facture",
  "inspector.images.intro": "Des images fixes qui accompagnent la facture. Téléversez-les une fois et tous les documents issus de ce modèle les conservent.",
  "inspector.images.logo": "Logo",
  "inspector.images.logoHint": "Remplace le monogramme",
  "inspector.images.qr": "Code QR",
  "inspector.images.qrHint": "Affiché dans le bloc QR de paiement",
  "inspector.images.remove": "Supprimer",
  "inspector.images.replace": "Remplacer",
  "inspector.images.signature": "Signature",
  "inspector.images.signatureHint": "Image de signature numérisée",
  "inspector.images.stamp": "Tampon / sceau",
  "inspector.images.stampHint": "Tampon de paiement ou d’approbation",
  "inspector.images.upload": "Téléverser",
  "inspector.images.uploadSlot": "Téléverser {label}",
  "inspector.items.add": "Ajouter une ligne",
  "inspector.items.count": "Lignes de facture",
  "inspector.items.hint": "Modifiez n’importe quelle cellule directement sur la facture, ou faites glisser la poignée pour réorganiser.",
  "inspector.items.subtotal": "Sous-total",
  "inspector.latefees.grace": "Délai de grâce",
  "inspector.latefees.graceUnit": "jours",
  "inspector.latefees.rate": "Taux de pénalité",
  "inspector.latefees.rateUnit": "% par mois",
  "inspector.legal.footer": "Mentions légales",
  "inspector.line": "{label} {n}",
  "inspector.loyalty.balance": "Solde de points",
  "inspector.loyalty.earned": "Points gagnés",
  "inspector.loyalty.level": "Niveau",
  "inspector.meta.due": "Date d’échéance",
  "inspector.meta.issued": "Date d’émission",
  "inspector.meta.number": "Numéro de facture",
  "inspector.meta.poNumber": "N° de bon de commande",
  "inspector.meta.terms": "Conditions de paiement",
  "inspector.multicurrency.add": "Ajouter une devise",
  "inspector.multicurrency.code": "Code de la devise {n}",
  "inspector.multicurrency.note": "Le taux est multiplié par le total de la facture. Code, symbole, puis taux.",
  "inspector.multicurrency.rate": "Taux de la devise {n}",
  "inspector.multicurrency.rates": "Devises et taux",
  "inspector.multicurrency.removeRow": "Supprimer la devise {n}",
  "inspector.multicurrency.symbol": "Symbole de la devise {n}",
  "inspector.notes.footerNotes": "Notes de bas de page",
  "inspector.notes.hint": "Affichées en bas de la facture — conditions, remerciements ou mentions légales.",
  "inspector.payhistory.add": "Ajouter un paiement",
  "inspector.payhistory.amount": "Montant du paiement {n}",
  "inspector.payhistory.amountPlaceholder": "Montant",
  "inspector.payhistory.date": "Date du paiement {n}",
  "inspector.payhistory.datePlaceholder": "Date",
  "inspector.payhistory.method": "Moyen du paiement {n}",
  "inspector.payhistory.methodPlaceholder": "Moyen",
  "inspector.payhistory.payments": "Paiements",
  "inspector.payhistory.removeRow": "Supprimer le paiement {n}",
  "inspector.payment.instructions": "Instructions de paiement",
  "inspector.poterms.terms": "Conditions du bon de commande",
  "inspector.qr.caption": "Légende",
  "inspector.qr.hint": "Encode Montant dû · {total}. Le code affiché est l’image que vous téléversez sous Images.",
  "inspector.recurring.annually": "Chaque année",
  "inspector.recurring.frequency": "Fréquence",
  "inspector.recurring.monthly": "Chaque mois",
  "inspector.recurring.next": "Prochaine émission",
  "inspector.recurring.note": "Note de récurrence",
  "inspector.recurring.quarterly": "Chaque trimestre",
  "inspector.recurring.weekly": "Chaque semaine",
  "inspector.refund.policy": "Politique de remboursement",
  "inspector.removeLine": "Supprimer {label} {n}",
  "inspector.removeSection": "Supprimer la section",
  "inspector.shipto.addressLines": "Lignes d’adresse",
  "inspector.shipto.name": "Nom du destinataire",
  "inspector.signature.hint": "Une ligne de signature et un champ de date apparaissent sur la facture pour une signature manuscrite.",
  "inspector.signature.name": "Nom du signataire",
  "inspector.signature.title": "Fonction / rôle",
  "inspector.tax.discount": "Remise",
  "inspector.tax.discountRow": "Remise",
  "inspector.tax.subtotal": "Sous-total",
  "inspector.tax.tax": "Taxe",
  "inspector.tax.taxRate": "Taux de taxe",
  "inspector.tax.total": "Total",
  "inspector.taxbreak.add": "Ajouter une ligne de taxe",
  "inspector.taxbreak.components": "Composantes de la taxe",
  "inspector.taxbreak.label": "Libellé de la ligne de taxe {n}",
  "inspector.taxbreak.note": "Chaque taux s’applique au sous-total, après remise éventuelle.",
  "inspector.taxbreak.rate": "Taux de la ligne de taxe {n}",
  "inspector.taxbreak.removeRow": "Supprimer la ligne de taxe {n}",
  "inspector.taxbreak.seedLabel": "Nouvelle taxe",
  "inspector.terms.checkboxLabel": "Libellé de la case",
  "inspector.terms.preChecked": "Cochée par défaut",
  "inspector.terms.preCheckedHint": "Afficher la case déjà cochée",
  "inspector.theme.accentColour": "Couleur d’accentuation",
  "inspector.theme.backgroundHint": "Ajoute une image pleine page derrière toute la facture — idéale pour un papier à en-tête ou un filigrane.",
  "inspector.theme.backgroundImage": "Image de fond",
  "inspector.theme.currency": "Devise",
  "inspector.theme.documentTitle": "Titre du document",
  "inspector.theme.language": "Langue",
  "inspector.theme.languageNote": "Utilisez le bouton de langue de la barre d’outils pour créer une variante liée, au lieu de changer la langue de ce document.",
  "inspector.theme.overlay": "Voile {pct} %",
  "inspector.theme.overlayLabel": "Voile",
  "inspector.theme.removeBackground": "Supprimer",
  "inspector.theme.replaceBackground": "Remplacer",
  "inspector.theme.showDecimals": "Afficher les décimales",
  "inspector.theme.showDecimalsHint": "p. ex. 290,00 $ contre 290 $",
  "inspector.theme.status.draft": "Brouillon",
  "inspector.theme.status.live": "En ligne",
  "inspector.theme.status.overdue": "En retard",
  "inspector.theme.status.paid": "Payée",
  "inspector.theme.status.sent": "Envoyée",
  "inspector.theme.statusLabel": "Statut",
  "inspector.theme.topic.logistics": "Expédition et logistique",
  "inspector.theme.topic.other": "Sans catégorie",
  "inspector.theme.topic.receipts": "Reçus et remboursements",
  "inspector.theme.topic.recurring": "Récurrent",
  "inspector.theme.topic.sales": "Ventes et devis",
  "inspector.theme.topic.services": "Services professionnels",
  "inspector.theme.topicLabel": "Sujet",
  "inspector.theme.uploadBackground": "Téléverser un fond",
  "languages.de": "Allemand",
  "languages.en": "Anglais",
  "languages.es": "Espagnol",
  "languages.footnote": "Créer une langue génère une copie liée, regroupée sous le même sujet.",
  "languages.fr": "Français",
  "languages.ja": "Japonais",
  "languages.pt": "Portugais",
  "languages.state.create": "Créer",
  "languages.state.editing": "En cours d’édition",
  "languages.state.open": "Ouvrir",
  "languages.title": "Variantes linguistiques",
  "list.actions": "Actions",
  "list.name": "Nom",
  "list.status": "Statut",
  "list.updated": "Mis à jour",
  "manager.group.documents": "{count, plural, one {# document} other {# documents}}",
  "manager.group.label": "Grouper par",
  "manager.group.language": "Langue",
  "manager.group.languages": "{count, plural, one {# langue} other {# langues}}",
  "manager.group.none": "Aucun",
  "manager.group.topic": "Sujet",
  "manager.layout.gallery": "Galerie",
  "manager.layout.label": "Affichage",
  "manager.layout.list": "Liste",
  "manager.loadFailed": "Impossible de charger les factures",
  "manager.search.clear": "Effacer la recherche",
  "manager.search.invoices": "Rechercher des factures…",
  "manager.search.templates": "Rechercher des modèles…",
  "manager.subtitle": "Des modèles réutilisables et les factures que vous créez à partir de ceux-ci.",
  "manager.tabs.invoices": "Factures",
  "manager.tabs.label": "Type",
  "manager.tabs.templates": "Modèles",
  "manager.title": "Factures",
  "manager.untitled": "Sans titre",
  "new.blank": "Facture vierge",
  "new.blankHint": "Partir de zéro",
  "new.category.adjustments": "Ajustements",
  "new.category.business": "Entreprise",
  "new.category.nonprofit": "Associations",
  "new.category.payments": "Paiements",
  "new.category.projects": "Projets",
  "new.category.recurring": "Récurrent",
  "new.category.sales": "Ventes",
  "new.category.services": "Services",
  "new.category.shipping": "Expédition",
  "new.failed": "Création impossible",
  "new.invoice": "Nouvelle facture",
  "new.startersFailed": "Les modèles de départ n’ont pas pu être chargés. Partez de zéro ou réessayez.",
  "new.subtitle": "Partez d’une page vierge ou d’un modèle prêt à l’emploi.",
  "new.template": "Nouveau modèle",
  "new.yourTemplates": "Vos modèles",
  "optional.approvalShow": "Approbation",
  "optional.attachShow": "Pièces jointes",
  "optional.conShow": "Contact",
  "optional.delShow": "Suivi de livraison",
  "optional.discShow": "Codes de remise",
  "optional.lateShow": "Pénalités de retard",
  "optional.legalShow": "Mentions légales",
  "optional.loyShow": "Points de fidélité",
  "optional.mcShow": "Multidevise",
  "optional.payhShow": "Historique des paiements",
  "optional.poShow": "Conditions de commande",
  "optional.qrShow": "QR de paiement",
  "optional.recurShow": "Récurrent",
  "optional.refShow": "Politique de remboursement",
  "optional.shipShow": "Livrer à",
  "optional.sigShow": "Signature",
  "optional.taxbShow": "Détail des taxes",
  "optional.termsShow": "Acceptation des conditions",
  "section.approval.hint": "État de la validation",
  "section.approval.title": "Approbation",
  "section.attachments.hint": "Fichiers joints",
  "section.attachments.title": "Pièces jointes",
  "section.branding.hint": "Logo et nom de marque",
  "section.branding.title": "Identité visuelle",
  "section.contact.hint": "Coordonnées d’assistance",
  "section.contact.title": "Contact",
  "section.custom.hint": "Votre propre section",
  "section.custom.title": "Section personnalisée",
  "section.customer.hint": "Coordonnées du client",
  "section.customer.title": "Facturer à",
  "section.delivery.hint": "État de la préparation",
  "section.delivery.title": "Suivi de livraison",
  "section.discount.hint": "Codes promo appliqués",
  "section.discount.title": "Codes de remise",
  "section.from.hint": "Les coordonnées de votre entreprise",
  "section.from.title": "Émetteur",
  "section.images.hint": "Logo, fond, QR et photos",
  "section.images.title": "Images",
  "section.items.hint": "Produits et services",
  "section.items.title": "Lignes de facture",
  "section.latefees.hint": "Pénalité de retard",
  "section.latefees.title": "Pénalités de retard",
  "section.legal.hint": "Petits caractères",
  "section.legal.title": "Mentions légales",
  "section.loyalty.hint": "Solde de récompenses",
  "section.loyalty.title": "Points de fidélité",
  "section.meta.hint": "Numéro, dates, commande et conditions",
  "section.meta.title": "Détails de la facture",
  "section.multicurrency.hint": "Totaux dans d’autres devises",
  "section.multicurrency.title": "Multidevise",
  "section.notes.hint": "Texte de bas de page",
  "section.notes.title": "Notes",
  "section.payhistory.hint": "Paiements passés",
  "section.payhistory.title": "Historique des paiements",
  "section.payment.hint": "Comment payer",
  "section.payment.title": "Paiement",
  "section.poterms.hint": "Conditions du bon de commande",
  "section.poterms.title": "Conditions de commande",
  "section.qr.hint": "Code à scanner pour payer",
  "section.qr.title": "QR de paiement",
  "section.recurring.hint": "Rythme des prélèvements",
  "section.recurring.title": "Récurrent",
  "section.refund.hint": "Retours et remboursements",
  "section.refund.title": "Politique de remboursement",
  "section.shipto.hint": "Adresse de livraison",
  "section.shipto.title": "Livrer à",
  "section.signature.hint": "Validation autorisée",
  "section.signature.title": "Signature",
  "section.tax.hint": "Taux et remises",
  "section.tax.title": "Taxes et totaux",
  "section.taxbreak.hint": "Composantes de la taxe",
  "section.taxbreak.title": "Détail des taxes",
  "section.terms.hint": "Case d’acceptation",
  "section.terms.title": "Conditions",
  "section.theme.hint": "Couleur, devise, statut",
  "section.theme.title": "Titre et thème",
  "seed.gallery.title": "Images",
  "seed.image.caption": "Ajoutez une légende",
  "seed.image.title": "Image",
  "seed.item": "Nouvel article",
  "seed.kv.label": "Étiquette",
  "seed.kv.row1k": "Centre de coûts",
  "seed.kv.row2k": "Contrat",
  "seed.kv.title": "Informations de référence",
  "seed.kv.value": "Valeur",
  "seed.text.body": "Ajoutez ici votre propre texte — périmètre, notes de livraison, conditions ou un message au client.",
  "seed.text.title": "Notes complémentaires",
  "status.draft": "Brouillon",
  "status.live": "En ligne",
  "status.overdue": "En retard",
  "status.paid": "Payée",
  "status.sent": "Envoyée",
  "toast.deleteFailed": "Suppression impossible",
  "toast.duplicateFailed": "Duplication impossible",
  "toast.duplicated.invoice": "Facture dupliquée",
  "toast.duplicated.template": "Modèle dupliqué",
  "toast.imageTooLarge": "Image trop volumineuse (max. {max})",
  "toast.imageUnreadable": "Impossible de lire ce fichier",
  "toast.languageFailed": "Impossible d’ajouter cette langue",
  "toast.notAnImage": "Ce fichier n’est pas une image",
  "toast.renameFailed": "Renommage impossible",
  "topic.logistics": "Expédition et logistique",
  "topic.other": "Sans catégorie",
  "topic.receipts": "Reçus et remboursements",
  "topic.recurring": "Récurrent",
  "topic.sales": "Ventes et devis",
  "topic.services": "Services professionnels"
} as Record<string, string>;
