// SPDX-License-Identifier: AGPL-3.0-only
/** GENERATED — zh-CN strings for the invoices page. Do not edit by hand. */
export default {
  "add.allOn": "所有标准区块都已添加到这张发票上。",
  "add.custom": "自己搭建",
  "add.standard": "标准区块",
  "add.subtitle": "自己搭建，或启用某个标准区块。",
  "add.title": "添加区块",
  "canvas.addSection": "添加区块",
  "canvas.approval.approved": "已批准",
  "canvas.approval.pending": "待审批",
  "canvas.approval.rejected": "已驳回",
  "canvas.approval.title": "审批",
  "canvas.attachments": "附件",
  "canvas.blocks.parties": "开票方与收票方",
  "canvas.blocks.paynotes": "付款与备注",
  "canvas.brandName": "品牌名称",
  "canvas.brandingHint": "品牌信息 · 点击可编辑",
  "canvas.contact": "有疑问？请联系我们",
  "canvas.custom.addRow": "添加行",
  "canvas.custom.body": "区块正文",
  "canvas.custom.caption": "图注",
  "canvas.custom.clearImage": "移除图片",
  "canvas.custom.clearSlot": "移除",
  "canvas.custom.clearSlotOf": "移除图片 {n}",
  "canvas.custom.remove": "移除区块",
  "canvas.custom.removeOf": "移除区块：{title}",
  "canvas.custom.removeRow": "移除行",
  "canvas.custom.removeRowOf": "移除第 {n} 行",
  "canvas.custom.rowLabel": "第 {n} 行的标签",
  "canvas.custom.rowValue": "第 {n} 行的值",
  "canvas.custom.titleLabel": "区块标题",
  "canvas.custom.upload": "点击上传图片",
  "canvas.custom.uploadSlot": "上传图片 {n}",
  "canvas.customerName": "客户名称",
  "canvas.dateSigned": "签署日期",
  "canvas.delivery.title": "配送进度",
  "canvas.discount.title": "折扣码",
  "canvas.due": "到期日",
  "canvas.from": "开票方",
  "canvas.insertAbove": "在{label}上方添加区块",
  "canvas.insertHere": "在此处添加区块",
  "canvas.invoiceTo": "收票方",
  "canvas.issued": "开具日期",
  "canvas.items.add": "添加明细项",
  "canvas.items.amount": "金额",
  "canvas.items.description": "描述",
  "canvas.items.descriptionOf": "第 {n} 行的描述",
  "canvas.items.qty": "数量",
  "canvas.items.qtyOf": "第 {n} 行的数量",
  "canvas.items.rate": "单价",
  "canvas.items.rateOf": "第 {n} 行的单价",
  "canvas.items.remove": "移除明细项：{name}",
  "canvas.items.reorder": "拖动可排序",
  "canvas.items.reorderOf": "拖动可排序：{name}",
  "canvas.items.row": "明细项 {n}",
  "canvas.latefees.sentence": "逾期超过到期日 {days} 天仍未付清的款项，将按每月 {rate}% 收取滞纳金。",
  "canvas.latefees.title": "逾期滞纳金",
  "canvas.legal": "法律条款",
  "canvas.lines.customer": "客户信息第 {n} 行",
  "canvas.lines.from": "开票方第 {n} 行",
  "canvas.lines.payment": "付款信息第 {n} 行",
  "canvas.lines.ship": "收货信息第 {n} 行",
  "canvas.loyalty.balance": "{balance} 分 · {level}",
  "canvas.loyalty.title": "积分余额",
  "canvas.multicurrency.note": "按参考汇率自 {total} 换算。",
  "canvas.multicurrency.title": "也可用以下货币支付",
  "canvas.notes": "备注",
  "canvas.payhistory.title": "付款记录",
  "canvas.payment": "付款",
  "canvas.poNumber": "采购订单号",
  "canvas.poTerms": "采购订单条款",
  "canvas.qr.due": "应付金额 · {total}",
  "canvas.qr.title": "扫码付款",
  "canvas.recurring.next": "下次：{next} · {count}",
  "canvas.recurring.title": "周期性 — {freq}",
  "canvas.refund": "退款政策",
  "canvas.reorderSection": "拖动可调整区块顺序",
  "canvas.reorderSectionOf": "拖动可调整区块顺序：{label}",
  "canvas.select": "编辑{label}",
  "canvas.shipName": "收货人名称",
  "canvas.shipTo": "收货方",
  "canvas.sigName": "签署人姓名",
  "canvas.sigTitle": "签署人职务",
  "canvas.signature": "签名",
  "canvas.taxbreak.title": "税费明细",
  "canvas.terms": "条款",
  "canvas.termsAccepted": "已接受条款",
  "canvas.termsLabel": "条款标签",
  "canvas.totals.discount": "折扣（{rate}）",
  "canvas.totals.subtotal": "小计",
  "canvas.totals.tax": "税额（{rate}）",
  "canvas.totals.total": "总计",
  "card.delete": "删除",
  "card.duplicate": "复制",
  "card.edit": "编辑",
  "card.rename": "重命名",
  "card.renameLabel": "新名称",
  "card.total": "总计",
  "custom.gallery.hint": "两到三张图片并排显示",
  "custom.gallery.label": "图片行",
  "custom.image.hint": "上传照片、图纸或证书",
  "custom.image.label": "图片区块",
  "custom.kv.hint": "标签与值成对显示",
  "custom.kv.label": "信息行",
  "custom.text.hint": "你自己的文字——备注、范围或条件",
  "custom.text.label": "文本区块",
  "delete.body.invoice": "此操作无法撤销。该发票将被永久移除。",
  "delete.body.template": "此操作无法撤销。该模板将被永久移除。",
  "delete.confirm": "删除",
  "delete.title": "删除 {name}？",
  "editor.delete": "删除",
  "editor.discard.body": "你对 {name} 的修改将会丢失。",
  "editor.discard.confirm": "放弃",
  "editor.discard.keep": "继续编辑",
  "editor.discard.title": "放弃未保存的更改？",
  "editor.duplicate": "复制",
  "editor.images": "图片",
  "editor.kind.invoice": "发票",
  "editor.kind.template": "模板",
  "editor.loadFailed": "无法加载该文档",
  "editor.nameLabel": "名称",
  "editor.redo": "重做",
  "editor.saveFailed": "保存失败",
  "editor.saveInvoice": "保存发票",
  "editor.saveState.dirty": "有未保存的更改",
  "editor.saveState.error": "保存失败",
  "editor.saveState.saved": "所有更改已保存",
  "editor.saveState.saving": "保存中…",
  "editor.saveTemplate": "保存模板",
  "editor.sendInvoice": "发送发票",
  "editor.shortcutSave": "保存文档",
  "editor.undo": "撤销",
  "empty.invoices.body": "从模板或空白画布开始，创建你的第一张发票。",
  "empty.invoices.title": "还没有发票",
  "empty.noMatch.body": "换个搜索词试试。",
  "empty.noMatch.invoices": "没有匹配的发票",
  "empty.noMatch.templates": "没有匹配的模板",
  "empty.templates.body": "创建一个可复用的发票模板，供团队在此基础上制作。",
  "empty.templates.title": "还没有模板",
  "inspector.addLine": "添加行",
  "inspector.approval.name": "审批人姓名",
  "inspector.approval.status.approved": "已批准",
  "inspector.approval.status.pending": "待审批",
  "inspector.approval.status.rejected": "已驳回",
  "inspector.approval.statusLabel": "状态",
  "inspector.approval.title": "角色 / 职务",
  "inspector.attachments.add": "添加文件",
  "inspector.attachments.files": "文件",
  "inspector.attachments.name": "第 {n} 个文件的名称",
  "inspector.attachments.removeRow": "移除第 {n} 个文件",
  "inspector.attachments.seedName": "新文件.pdf",
  "inspector.attachments.size": "第 {n} 个文件的大小",
  "inspector.branding.accentHintAfter": "区块下修改强调色。",
  "inspector.branding.accentHintBefore": "可在",
  "inspector.branding.accentHintBold": "标题",
  "inspector.branding.brandName": "品牌名称",
  "inspector.branding.logoImage": "标志图片",
  "inspector.branding.logoMark": "标志图形",
  "inspector.branding.logoNoteAfter": "中。",
  "inspector.branding.logoNoteBefore": "上传标志后会替换上方的图形。所有固定图片都在工具栏的",
  "inspector.branding.logoNoteBold": "图片",
  "inspector.branding.removeLogo": "移除",
  "inspector.branding.uploadLogo": "上传标志",
  "inspector.contact.email": "邮箱",
  "inspector.contact.name": "联系人姓名",
  "inspector.contact.phone": "电话",
  "inspector.custom.addRow": "添加行",
  "inspector.custom.body": "正文",
  "inspector.custom.caption": "图注",
  "inspector.custom.galleryHint": "在发票上点击各个位置即可上传图片。",
  "inspector.custom.height": "高度",
  "inspector.custom.image": "图片",
  "inspector.custom.remove": "移除区块",
  "inspector.custom.title": "区块标题",
  "inspector.custom.upload": "上传 / 替换",
  "inspector.customer.addressContact": "地址与联系方式",
  "inspector.customer.clientName": "客户名称",
  "inspector.delivery.add": "添加步骤",
  "inspector.delivery.cycle": "步骤 {n} 状态：{status}",
  "inspector.delivery.label": "步骤 {n}",
  "inspector.delivery.note": "点击状态可在“待处理 → 进行中 → 已完成”之间切换。",
  "inspector.delivery.removeRow": "移除步骤 {n}",
  "inspector.delivery.seedLabel": "新步骤",
  "inspector.delivery.status.current": "进行中",
  "inspector.delivery.status.done": "已完成",
  "inspector.delivery.status.todo": "待处理",
  "inspector.delivery.steps": "步骤",
  "inspector.discount.add": "添加优惠码",
  "inspector.discount.amount": "优惠码 {n} 的金额",
  "inspector.discount.code": "优惠码 {n}",
  "inspector.discount.codePlaceholder": "CODE",
  "inspector.discount.codes": "折扣码",
  "inspector.discount.label": "优惠码 {n} 的说明",
  "inspector.discount.labelPlaceholder": "说明",
  "inspector.discount.removeRow": "移除优惠码 {n}",
  "inspector.discount.seedLabel": "新折扣",
  "inspector.fallback.title": "编辑",
  "inspector.from.companyDetails": "公司信息",
  "inspector.images.addSection": "添加图片区块",
  "inspector.images.background": "背景",
  "inspector.images.backgroundHint": "衬在发票背后的水印",
  "inspector.images.intro": "随发票一同保存的固定图片。上传一次，基于该模板创建的每个文档都会保留它们。",
  "inspector.images.logo": "标志",
  "inspector.images.logoHint": "会替换标志图形",
  "inspector.images.qr": "二维码",
  "inspector.images.qrHint": "显示在扫码付款区块中",
  "inspector.images.remove": "移除",
  "inspector.images.replace": "替换",
  "inspector.images.signature": "签名",
  "inspector.images.signatureHint": "扫描的签名图片",
  "inspector.images.stamp": "印戳 / 印章",
  "inspector.images.stampHint": "“已付款”或审批印章",
  "inspector.images.upload": "上传",
  "inspector.images.uploadSlot": "上传{label}",
  "inspector.items.add": "添加明细项",
  "inspector.items.count": "明细项",
  "inspector.items.hint": "可直接在发票上编辑任意单元格，或拖动手柄调整顺序。",
  "inspector.items.subtotal": "小计",
  "inspector.latefees.grace": "宽限期",
  "inspector.latefees.graceUnit": "天",
  "inspector.latefees.rate": "滞纳金费率",
  "inspector.latefees.rateUnit": "%/月",
  "inspector.legal.footer": "法律页脚",
  "inspector.line": "{label} {n}",
  "inspector.loyalty.balance": "积分余额",
  "inspector.loyalty.earned": "已获积分",
  "inspector.loyalty.level": "等级",
  "inspector.meta.due": "到期日",
  "inspector.meta.issued": "开具日期",
  "inspector.meta.number": "发票编号",
  "inspector.meta.poNumber": "采购订单号",
  "inspector.meta.terms": "付款条件",
  "inspector.multicurrency.add": "添加货币",
  "inspector.multicurrency.code": "货币 {n} 的代码",
  "inspector.multicurrency.note": "汇率会与发票总计相乘。依次填写代码、符号和汇率。",
  "inspector.multicurrency.rate": "货币 {n} 的汇率",
  "inspector.multicurrency.rates": "货币与汇率",
  "inspector.multicurrency.removeRow": "移除货币 {n}",
  "inspector.multicurrency.symbol": "货币 {n} 的符号",
  "inspector.notes.footerNotes": "页脚备注",
  "inspector.notes.hint": "显示在发票底部——条款、致谢语或法律文本。",
  "inspector.payhistory.add": "添加付款",
  "inspector.payhistory.amount": "第 {n} 笔付款的金额",
  "inspector.payhistory.amountPlaceholder": "金额",
  "inspector.payhistory.date": "第 {n} 笔付款的日期",
  "inspector.payhistory.datePlaceholder": "日期",
  "inspector.payhistory.method": "第 {n} 笔付款的方式",
  "inspector.payhistory.methodPlaceholder": "方式",
  "inspector.payhistory.payments": "付款",
  "inspector.payhistory.removeRow": "移除第 {n} 笔付款",
  "inspector.payment.instructions": "付款说明",
  "inspector.poterms.terms": "采购订单条款",
  "inspector.qr.caption": "图注",
  "inspector.qr.hint": "编码内容为“应付金额 · {total}”。显示的二维码就是你在“图片”中上传的那张图。",
  "inspector.recurring.annually": "每年",
  "inspector.recurring.frequency": "频率",
  "inspector.recurring.monthly": "每月",
  "inspector.recurring.next": "下次开具日期",
  "inspector.recurring.note": "周期说明",
  "inspector.recurring.quarterly": "每季度",
  "inspector.recurring.weekly": "每周",
  "inspector.refund.policy": "退款政策",
  "inspector.removeLine": "移除{label} {n}",
  "inspector.removeSection": "移除区块",
  "inspector.shipto.addressLines": "地址行",
  "inspector.shipto.name": "收货人名称",
  "inspector.signature.hint": "发票上会显示签名栏和日期栏，供手写签署。",
  "inspector.signature.name": "签署人姓名",
  "inspector.signature.title": "职务 / 角色",
  "inspector.tax.discount": "折扣",
  "inspector.tax.discountRow": "折扣",
  "inspector.tax.subtotal": "小计",
  "inspector.tax.tax": "税额",
  "inspector.tax.taxRate": "税率",
  "inspector.tax.total": "总计",
  "inspector.taxbreak.add": "添加税费行",
  "inspector.taxbreak.components": "税费项",
  "inspector.taxbreak.label": "税费行 {n} 的标签",
  "inspector.taxbreak.note": "每个税率都按扣除折扣后的小计计算。",
  "inspector.taxbreak.rate": "税费行 {n} 的税率",
  "inspector.taxbreak.removeRow": "移除税费行 {n}",
  "inspector.taxbreak.seedLabel": "新税费",
  "inspector.terms.checkboxLabel": "复选框标签",
  "inspector.terms.preChecked": "默认勾选",
  "inspector.terms.preCheckedHint": "显示时该复选框已勾选",
  "inspector.theme.accentColour": "强调色",
  "inspector.theme.backgroundHint": "在整张发票背后添加满版背景——很适合信头或水印。",
  "inspector.theme.backgroundImage": "背景图片",
  "inspector.theme.currency": "货币",
  "inspector.theme.documentTitle": "文档标题",
  "inspector.theme.language": "语言",
  "inspector.theme.languageNote": "如需其他语言，请用工具栏中的语言按钮创建关联版本，而不是改这一份的语言标记。",
  "inspector.theme.overlay": "遮罩 {pct}%",
  "inspector.theme.overlayLabel": "遮罩",
  "inspector.theme.removeBackground": "移除",
  "inspector.theme.replaceBackground": "替换",
  "inspector.theme.showDecimals": "显示小数",
  "inspector.theme.showDecimalsHint": "例如 $290.00 与 $290",
  "inspector.theme.status.draft": "草稿",
  "inspector.theme.status.live": "已启用",
  "inspector.theme.status.overdue": "已逾期",
  "inspector.theme.status.paid": "已付款",
  "inspector.theme.status.sent": "已发送",
  "inspector.theme.statusLabel": "状态",
  "inspector.theme.topic.logistics": "物流与配送",
  "inspector.theme.topic.other": "未分类",
  "inspector.theme.topic.receipts": "收据与退款",
  "inspector.theme.topic.recurring": "周期性",
  "inspector.theme.topic.sales": "销售与报价",
  "inspector.theme.topic.services": "专业服务",
  "inspector.theme.topicLabel": "主题",
  "inspector.theme.uploadBackground": "上传背景",
  "languages.de": "德语",
  "languages.en": "英语",
  "languages.es": "西班牙语",
  "languages.footnote": "添加语言会创建一个关联副本，并归在同一主题下。",
  "languages.fr": "法语",
  "languages.ja": "日语",
  "languages.pt": "葡萄牙语",
  "languages.state.create": "创建",
  "languages.state.editing": "正在编辑",
  "languages.state.open": "打开",
  "languages.title": "语言版本",
  "list.actions": "操作",
  "list.name": "名称",
  "list.status": "状态",
  "list.updated": "更新时间",
  "manager.group.documents": "{count, plural, other {# 个文档}}",
  "manager.group.label": "分组",
  "manager.group.language": "语言",
  "manager.group.languages": "{count, plural, other {# 种语言}}",
  "manager.group.none": "不分组",
  "manager.group.topic": "主题",
  "manager.layout.gallery": "画廊",
  "manager.layout.label": "布局",
  "manager.layout.list": "列表",
  "manager.loadFailed": "无法加载发票",
  "manager.search.clear": "清除搜索",
  "manager.search.invoices": "搜索发票…",
  "manager.search.templates": "搜索模板…",
  "manager.subtitle": "可复用的模板，以及基于它们创建的发票。",
  "manager.tabs.invoices": "发票",
  "manager.tabs.label": "类型",
  "manager.tabs.templates": "模板",
  "manager.title": "发票",
  "manager.untitled": "未命名",
  "new.blank": "空白发票",
  "new.blankHint": "从零开始",
  "new.category.adjustments": "调整",
  "new.category.business": "商务",
  "new.category.nonprofit": "非营利",
  "new.category.payments": "付款",
  "new.category.projects": "项目",
  "new.category.recurring": "周期性",
  "new.category.sales": "销售",
  "new.category.services": "服务",
  "new.category.shipping": "配送",
  "new.failed": "创建失败",
  "new.invoice": "新建发票",
  "new.startersFailed": "无法加载起始模板。可以从空白开始，或重试。",
  "new.subtitle": "从空白画布开始，或使用现成的模板。",
  "new.template": "新建模板",
  "new.yourTemplates": "你的模板",
  "optional.approvalShow": "审批",
  "optional.attachShow": "附件",
  "optional.conShow": "联系方式",
  "optional.delShow": "配送进度",
  "optional.discShow": "折扣码",
  "optional.lateShow": "滞纳金",
  "optional.legalShow": "法律页脚",
  "optional.loyShow": "积分",
  "optional.mcShow": "多币种",
  "optional.payhShow": "付款记录",
  "optional.poShow": "订单条款",
  "optional.qrShow": "扫码付款",
  "optional.recurShow": "周期性",
  "optional.refShow": "退款政策",
  "optional.shipShow": "收货方",
  "optional.sigShow": "签名",
  "optional.taxbShow": "税费明细",
  "optional.termsShow": "条款确认",
  "section.approval.hint": "审批状态",
  "section.approval.title": "审批",
  "section.attachments.hint": "随附文件",
  "section.attachments.title": "附件",
  "section.branding.hint": "标志与品牌名称",
  "section.branding.title": "品牌信息",
  "section.contact.hint": "支持联系信息",
  "section.contact.title": "联系方式",
  "section.custom.hint": "你自己的区块",
  "section.custom.title": "自定义区块",
  "section.customer.hint": "客户信息",
  "section.customer.title": "收票方",
  "section.delivery.hint": "履约状态",
  "section.delivery.title": "配送进度",
  "section.discount.hint": "已使用的优惠码",
  "section.discount.title": "折扣码",
  "section.from.hint": "你的公司信息",
  "section.from.title": "开票方",
  "section.images.hint": "标志、背景、二维码与照片",
  "section.images.title": "图片",
  "section.items.hint": "商品与服务",
  "section.items.title": "明细项",
  "section.latefees.hint": "逾期罚金",
  "section.latefees.title": "滞纳金",
  "section.legal.hint": "小字条款",
  "section.legal.title": "法律页脚",
  "section.loyalty.hint": "奖励余额",
  "section.loyalty.title": "积分",
  "section.meta.hint": "编号、日期、采购订单与条款",
  "section.meta.title": "发票信息",
  "section.multicurrency.hint": "其他货币的合计",
  "section.multicurrency.title": "多币种",
  "section.notes.hint": "页脚文本",
  "section.notes.title": "备注",
  "section.payhistory.hint": "过往付款",
  "section.payhistory.title": "付款记录",
  "section.payment.hint": "如何付款",
  "section.payment.title": "付款",
  "section.poterms.hint": "采购订单条款",
  "section.poterms.title": "订单条款",
  "section.qr.hint": "扫码支付用的二维码",
  "section.qr.title": "扫码付款",
  "section.recurring.hint": "收款周期",
  "section.recurring.title": "周期性",
  "section.refund.hint": "退货与退款",
  "section.refund.title": "退款政策",
  "section.shipto.hint": "收货地址",
  "section.shipto.title": "收货方",
  "section.signature.hint": "授权签署",
  "section.signature.title": "签名",
  "section.tax.hint": "税率与折扣",
  "section.tax.title": "税费与合计",
  "section.taxbreak.hint": "税费项",
  "section.taxbreak.title": "税费明细",
  "section.terms.hint": "确认复选框",
  "section.terms.title": "条款",
  "section.theme.hint": "颜色、货币、状态",
  "section.theme.title": "标题与外观",
  "seed.gallery.title": "图片",
  "seed.image.caption": "添加图注",
  "seed.image.title": "图片",
  "seed.item": "新条目",
  "seed.kv.label": "标签",
  "seed.kv.row1k": "成本中心",
  "seed.kv.row2k": "合同",
  "seed.kv.title": "参考信息",
  "seed.kv.value": "值",
  "seed.text.body": "在这里写下你自己的文字——服务范围、交付说明、条件，或给客户的留言。",
  "seed.text.title": "补充说明",
  "status.draft": "草稿",
  "status.live": "已启用",
  "status.overdue": "已逾期",
  "status.paid": "已付款",
  "status.sent": "已发送",
  "toast.deleteFailed": "删除失败",
  "toast.duplicateFailed": "复制失败",
  "toast.duplicated.invoice": "发票已复制",
  "toast.duplicated.template": "模板已复制",
  "toast.imageTooLarge": "图片过大（上限 {max}）",
  "toast.imageUnreadable": "无法读取该文件",
  "toast.languageFailed": "无法添加该语言",
  "toast.notAnImage": "该文件不是图片",
  "toast.renameFailed": "重命名失败",
  "topic.logistics": "物流与配送",
  "topic.other": "未分类",
  "topic.receipts": "收据与退款",
  "topic.recurring": "周期性",
  "topic.sales": "销售与报价",
  "topic.services": "专业服务"
} as Record<string, string>;
