// SPDX-License-Identifier: AGPL-3.0-only
/** GENERATED — zh-TW strings for the invoices page. Do not edit by hand. */
export default {
  "add.allOn": "這張發票已經加入所有標準區塊。",
  "add.custom": "自行建立",
  "add.standard": "標準區塊",
  "add.subtitle": "自行建立，或開啟其中一個標準區塊。",
  "add.title": "新增區段",
  "canvas.addSection": "新增區段",
  "canvas.approval.approved": "已核准",
  "canvas.approval.pending": "待審核",
  "canvas.approval.rejected": "已退回",
  "canvas.approval.title": "簽核",
  "canvas.attachments": "附件",
  "canvas.blocks.parties": "開立方與收票方",
  "canvas.blocks.paynotes": "付款與備註",
  "canvas.brandName": "品牌名稱",
  "canvas.brandingHint": "品牌識別 · 點選即可編輯",
  "canvas.contact": "有問題嗎？聯絡我們",
  "canvas.custom.addRow": "新增列",
  "canvas.custom.body": "區段內文",
  "canvas.custom.caption": "圖說",
  "canvas.custom.clearImage": "移除圖片",
  "canvas.custom.clearSlot": "移除",
  "canvas.custom.clearSlotOf": "移除圖片 {n}",
  "canvas.custom.remove": "移除區段",
  "canvas.custom.removeOf": "移除區段：{title}",
  "canvas.custom.removeRow": "移除列",
  "canvas.custom.removeRowOf": "移除第 {n} 列",
  "canvas.custom.rowLabel": "第 {n} 列的標籤",
  "canvas.custom.rowValue": "第 {n} 列的值",
  "canvas.custom.titleLabel": "區段標題",
  "canvas.custom.upload": "點選以上傳圖片",
  "canvas.custom.uploadSlot": "上傳圖片 {n}",
  "canvas.customerName": "客戶名稱",
  "canvas.dateSigned": "簽署日期",
  "canvas.delivery.title": "配送時程",
  "canvas.discount.title": "折扣碼",
  "canvas.due": "到期日",
  "canvas.from": "開立方",
  "canvas.insertAbove": "在{label}上方新增區段",
  "canvas.insertHere": "在這裡新增區段",
  "canvas.invoiceTo": "收票方",
  "canvas.issued": "開立日期",
  "canvas.items.add": "新增明細項目",
  "canvas.items.amount": "金額",
  "canvas.items.description": "說明",
  "canvas.items.descriptionOf": "第 {n} 列的說明",
  "canvas.items.qty": "數量",
  "canvas.items.qtyOf": "第 {n} 列的數量",
  "canvas.items.rate": "單價",
  "canvas.items.rateOf": "第 {n} 列的單價",
  "canvas.items.remove": "移除明細項目：{name}",
  "canvas.items.reorder": "拖曳可重新排序",
  "canvas.items.reorderOf": "拖曳可重新排序：{name}",
  "canvas.items.row": "明細項目 {n}",
  "canvas.latefees.sentence": "超過到期日 {days} 天仍未付清的餘額，每月加收 {rate}% 的逾期費用。",
  "canvas.latefees.title": "逾期付款費用",
  "canvas.legal": "法律聲明",
  "canvas.lines.customer": "客戶資料第 {n} 行",
  "canvas.lines.from": "開立方資料第 {n} 行",
  "canvas.lines.payment": "付款資訊第 {n} 行",
  "canvas.lines.ship": "送貨資料第 {n} 行",
  "canvas.loyalty.balance": "{balance} 點 · {level}",
  "canvas.loyalty.title": "點數餘額",
  "canvas.multicurrency.note": "依參考匯率自 {total} 換算。",
  "canvas.multicurrency.title": "亦可用以下幣別支付",
  "canvas.notes": "備註",
  "canvas.payhistory.title": "付款紀錄",
  "canvas.payment": "付款",
  "canvas.poNumber": "採購單號",
  "canvas.poTerms": "採購單條款",
  "canvas.qr.due": "應付金額 · {total}",
  "canvas.qr.title": "掃 QR 付款",
  "canvas.recurring.next": "下次：{next} · {count}",
  "canvas.recurring.title": "週期性 — {freq}",
  "canvas.refund": "退款政策",
  "canvas.reorderSection": "拖曳可重新排序區段",
  "canvas.reorderSectionOf": "拖曳可重新排序區段：{label}",
  "canvas.select": "編輯{label}",
  "canvas.shipName": "收貨人姓名",
  "canvas.shipTo": "送貨至",
  "canvas.sigName": "簽署人姓名",
  "canvas.sigTitle": "簽署人職稱",
  "canvas.signature": "簽名",
  "canvas.taxbreak.title": "稅額明細",
  "canvas.terms": "條款",
  "canvas.termsAccepted": "已同意條款",
  "canvas.termsLabel": "條款標籤",
  "canvas.totals.discount": "折扣（{rate}）",
  "canvas.totals.subtotal": "小計",
  "canvas.totals.tax": "稅額（{rate}）",
  "canvas.totals.total": "總計",
  "card.delete": "刪除",
  "card.duplicate": "複製",
  "card.edit": "編輯",
  "card.rename": "重新命名",
  "card.renameLabel": "新名稱",
  "card.total": "總計",
  "custom.gallery.hint": "兩到三張圖片並排",
  "custom.gallery.label": "圖片列",
  "custom.image.hint": "上傳照片、圖稿或證書",
  "custom.image.label": "圖片區塊",
  "custom.kv.hint": "標籤／數值配對",
  "custom.kv.label": "明細列",
  "custom.text.hint": "你自己的文字 — 備註、工作範圍或條件",
  "custom.text.label": "文字區段",
  "delete.body.invoice": "此動作無法復原。發票將被永久移除。",
  "delete.body.template": "此動作無法復原。範本將被永久移除。",
  "delete.confirm": "刪除",
  "delete.title": "刪除 {name}？",
  "editor.delete": "刪除",
  "editor.discard.body": "你對 {name} 的修改將會遺失。",
  "editor.discard.confirm": "捨棄",
  "editor.discard.keep": "繼續編輯",
  "editor.discard.title": "捨棄未儲存的變更？",
  "editor.duplicate": "複製",
  "editor.images": "圖片",
  "editor.kind.invoice": "發票",
  "editor.kind.template": "範本",
  "editor.loadFailed": "無法載入這份文件",
  "editor.nameLabel": "名稱",
  "editor.redo": "重做",
  "editor.saveFailed": "無法儲存",
  "editor.saveInvoice": "儲存發票",
  "editor.saveState.dirty": "尚未儲存的變更",
  "editor.saveState.error": "無法儲存",
  "editor.saveState.saved": "所有變更已儲存",
  "editor.saveState.saving": "儲存中…",
  "editor.saveTemplate": "儲存範本",
  "editor.sendInvoice": "寄送發票",
  "editor.shortcutSave": "儲存文件",
  "editor.undo": "復原",
  "empty.invoices.body": "以範本或空白畫布建立你的第一張發票。",
  "empty.invoices.title": "還沒有發票",
  "empty.noMatch.body": "試試其他搜尋字詞。",
  "empty.noMatch.invoices": "沒有符合的發票",
  "empty.noMatch.templates": "沒有符合的範本",
  "empty.templates.body": "建立一份可重複使用的發票範本，讓團隊可以據以製作。",
  "empty.templates.title": "還沒有範本",
  "inspector.addLine": "新增列",
  "inspector.approval.name": "簽核人姓名",
  "inspector.approval.status.approved": "已核准",
  "inspector.approval.status.pending": "待審核",
  "inspector.approval.status.rejected": "已退回",
  "inspector.approval.statusLabel": "狀態",
  "inspector.approval.title": "角色／職稱",
  "inspector.attachments.add": "新增檔案",
  "inspector.attachments.files": "檔案",
  "inspector.attachments.name": "檔案 {n} 名稱",
  "inspector.attachments.removeRow": "移除檔案 {n}",
  "inspector.attachments.seedName": "新檔案.pdf",
  "inspector.attachments.size": "檔案 {n} 大小",
  "inspector.branding.accentHintAfter": "區段中修改。",
  "inspector.branding.accentHintBefore": "強調色可在",
  "inspector.branding.accentHintBold": "標題",
  "inspector.branding.brandName": "品牌名稱",
  "inspector.branding.logoImage": "標誌圖片",
  "inspector.branding.logoMark": "標誌圖形",
  "inspector.branding.logoNoteAfter": "之中。",
  "inspector.branding.logoNoteBefore": "上傳標誌後會取代上方的圖形。所有固定圖片都收在工具列的",
  "inspector.branding.logoNoteBold": "圖片",
  "inspector.branding.removeLogo": "移除",
  "inspector.branding.uploadLogo": "上傳標誌",
  "inspector.contact.email": "電子郵件",
  "inspector.contact.name": "聯絡人姓名",
  "inspector.contact.phone": "電話",
  "inspector.custom.addRow": "新增列",
  "inspector.custom.body": "內文",
  "inspector.custom.caption": "圖說",
  "inspector.custom.galleryHint": "點選發票上的各個位置即可上傳圖片。",
  "inspector.custom.height": "高度",
  "inspector.custom.image": "圖片",
  "inspector.custom.remove": "移除區段",
  "inspector.custom.title": "區段標題",
  "inspector.custom.upload": "上傳／取代",
  "inspector.customer.addressContact": "地址與聯絡方式",
  "inspector.customer.clientName": "客戶名稱",
  "inspector.delivery.add": "新增步驟",
  "inspector.delivery.cycle": "步驟 {n} 狀態：{status}",
  "inspector.delivery.label": "步驟 {n}",
  "inspector.delivery.note": "點選狀態可依序切換 待處理 → 進行中 → 已完成。",
  "inspector.delivery.removeRow": "移除步驟 {n}",
  "inspector.delivery.seedLabel": "新步驟",
  "inspector.delivery.status.current": "進行中",
  "inspector.delivery.status.done": "已完成",
  "inspector.delivery.status.todo": "待處理",
  "inspector.delivery.steps": "步驟",
  "inspector.discount.add": "新增折扣碼",
  "inspector.discount.amount": "折扣碼 {n} 金額",
  "inspector.discount.code": "折扣碼 {n}",
  "inspector.discount.codePlaceholder": "CODE",
  "inspector.discount.codes": "折扣碼",
  "inspector.discount.label": "折扣碼 {n} 說明",
  "inspector.discount.labelPlaceholder": "說明",
  "inspector.discount.removeRow": "移除折扣碼 {n}",
  "inspector.discount.seedLabel": "新折扣",
  "inspector.fallback.title": "編輯",
  "inspector.from.companyDetails": "公司資料",
  "inspector.images.addSection": "新增圖片區段",
  "inspector.images.background": "背景",
  "inspector.images.backgroundHint": "發票背後的浮水印",
  "inspector.images.intro": "隨發票一起帶著走的固定圖片。上傳一次，之後以此範本製作的每份文件都會保留。",
  "inspector.images.logo": "標誌",
  "inspector.images.logoHint": "會取代標誌圖形",
  "inspector.images.qr": "QR 碼",
  "inspector.images.qrHint": "顯示在 QR 付款區塊中",
  "inspector.images.remove": "移除",
  "inspector.images.replace": "取代",
  "inspector.images.signature": "簽名",
  "inspector.images.signatureHint": "掃描的簽名圖檔",
  "inspector.images.stamp": "印章／戳記",
  "inspector.images.stampHint": "已付款或核准的戳記",
  "inspector.images.upload": "上傳",
  "inspector.images.uploadSlot": "上傳{label}",
  "inspector.items.add": "新增明細項目",
  "inspector.items.count": "明細項目",
  "inspector.items.hint": "可直接在發票上編輯任一欄位，或拖曳握把重新排序。",
  "inspector.items.subtotal": "小計",
  "inspector.latefees.grace": "寬限期",
  "inspector.latefees.graceUnit": "天",
  "inspector.latefees.rate": "逾期費率",
  "inspector.latefees.rateUnit": "%／月",
  "inspector.legal.footer": "法律頁尾",
  "inspector.line": "{label} {n}",
  "inspector.loyalty.balance": "點數餘額",
  "inspector.loyalty.earned": "已獲得點數",
  "inspector.loyalty.level": "等級",
  "inspector.meta.due": "到期日",
  "inspector.meta.issued": "開立日期",
  "inspector.meta.number": "發票號碼",
  "inspector.meta.poNumber": "採購單號",
  "inspector.meta.terms": "付款條件",
  "inspector.multicurrency.add": "新增幣別",
  "inspector.multicurrency.code": "幣別 {n} 代碼",
  "inspector.multicurrency.note": "匯率會乘上發票總計。依序填入代碼、符號與匯率。",
  "inspector.multicurrency.rate": "幣別 {n} 匯率",
  "inspector.multicurrency.rates": "幣別與匯率",
  "inspector.multicurrency.removeRow": "移除幣別 {n}",
  "inspector.multicurrency.symbol": "幣別 {n} 符號",
  "inspector.notes.footerNotes": "頁尾備註",
  "inspector.notes.hint": "顯示在發票底部 — 條款、感謝詞或法律文字。",
  "inspector.payhistory.add": "新增付款",
  "inspector.payhistory.amount": "付款 {n} 金額",
  "inspector.payhistory.amountPlaceholder": "金額",
  "inspector.payhistory.date": "付款 {n} 日期",
  "inspector.payhistory.datePlaceholder": "日期",
  "inspector.payhistory.method": "付款 {n} 方式",
  "inspector.payhistory.methodPlaceholder": "方式",
  "inspector.payhistory.payments": "付款",
  "inspector.payhistory.removeRow": "移除付款 {n}",
  "inspector.payment.instructions": "付款說明",
  "inspector.poterms.terms": "採購單條款",
  "inspector.qr.caption": "圖說",
  "inspector.qr.hint": "編碼內容為「應付金額 · {total}」。畫面上的圖碼就是你在「圖片」中上傳的圖片。",
  "inspector.recurring.annually": "每年",
  "inspector.recurring.frequency": "頻率",
  "inspector.recurring.monthly": "每月",
  "inspector.recurring.next": "下次開立日期",
  "inspector.recurring.note": "週期說明",
  "inspector.recurring.quarterly": "每季",
  "inspector.recurring.weekly": "每週",
  "inspector.refund.policy": "退款政策",
  "inspector.removeLine": "移除{label} {n}",
  "inspector.removeSection": "移除區段",
  "inspector.shipto.addressLines": "地址",
  "inspector.shipto.name": "收貨人姓名",
  "inspector.signature.hint": "發票上會出現簽名欄與日期欄，供親筆簽署。",
  "inspector.signature.name": "簽署人姓名",
  "inspector.signature.title": "職稱／角色",
  "inspector.tax.discount": "折扣",
  "inspector.tax.discountRow": "折扣",
  "inspector.tax.subtotal": "小計",
  "inspector.tax.tax": "稅額",
  "inspector.tax.taxRate": "稅率",
  "inspector.tax.total": "總計",
  "inspector.taxbreak.add": "新增稅額列",
  "inspector.taxbreak.components": "稅額項目",
  "inspector.taxbreak.label": "稅額列 {n} 標籤",
  "inspector.taxbreak.note": "各項稅率都以折扣後的小計計算。",
  "inspector.taxbreak.rate": "稅額列 {n} 稅率",
  "inspector.taxbreak.removeRow": "移除稅額列 {n}",
  "inspector.taxbreak.seedLabel": "新稅額",
  "inspector.terms.checkboxLabel": "核取方塊標籤",
  "inspector.terms.preChecked": "預先勾選",
  "inspector.terms.preCheckedHint": "顯示為已勾選的狀態",
  "inspector.theme.accentColour": "強調色",
  "inspector.theme.backgroundHint": "在整張發票後方加上滿版背景 — 很適合信頭或浮水印。",
  "inspector.theme.backgroundImage": "背景圖片",
  "inspector.theme.currency": "幣別",
  "inspector.theme.documentTitle": "文件標題",
  "inspector.theme.language": "語言",
  "inspector.theme.languageNote": "請用工具列的語言按鈕建立連結的語言版本，而不是改標這一份的語言。",
  "inspector.theme.overlay": "遮罩 {pct}%",
  "inspector.theme.overlayLabel": "遮罩",
  "inspector.theme.removeBackground": "移除",
  "inspector.theme.replaceBackground": "取代",
  "inspector.theme.showDecimals": "顯示小數",
  "inspector.theme.showDecimalsHint": "例如 $290.00 與 $290",
  "inspector.theme.status.draft": "草稿",
  "inspector.theme.status.live": "啟用中",
  "inspector.theme.status.overdue": "已逾期",
  "inspector.theme.status.paid": "已付款",
  "inspector.theme.status.sent": "已寄出",
  "inspector.theme.statusLabel": "狀態",
  "inspector.theme.topic.logistics": "運送與物流",
  "inspector.theme.topic.other": "未分類",
  "inspector.theme.topic.receipts": "收據與退款",
  "inspector.theme.topic.recurring": "週期性",
  "inspector.theme.topic.sales": "銷售與報價",
  "inspector.theme.topic.services": "專業服務",
  "inspector.theme.topicLabel": "主題",
  "inspector.theme.uploadBackground": "上傳背景",
  "languages.de": "德文",
  "languages.en": "英文",
  "languages.es": "西班牙文",
  "languages.footnote": "新增語言會建立一份連結的副本，並歸在同一個主題之下。",
  "languages.fr": "法文",
  "languages.ja": "日文",
  "languages.pt": "葡萄牙文",
  "languages.state.create": "建立",
  "languages.state.editing": "編輯中",
  "languages.state.open": "開啟",
  "languages.title": "語言版本",
  "list.actions": "動作",
  "list.name": "名稱",
  "list.status": "狀態",
  "list.updated": "更新時間",
  "manager.group.documents": "{count, plural, other {# 份文件}}",
  "manager.group.label": "分組",
  "manager.group.language": "語言",
  "manager.group.languages": "{count, plural, other {# 種語言}}",
  "manager.group.none": "不分組",
  "manager.group.topic": "主題",
  "manager.layout.gallery": "圖庫",
  "manager.layout.label": "版面",
  "manager.layout.list": "清單",
  "manager.loadFailed": "無法載入發票",
  "manager.search.clear": "清除搜尋",
  "manager.search.invoices": "搜尋發票…",
  "manager.search.templates": "搜尋範本…",
  "manager.subtitle": "可重複使用的範本，以及以它們製作的發票。",
  "manager.tabs.invoices": "發票",
  "manager.tabs.label": "類型",
  "manager.tabs.templates": "範本",
  "manager.title": "發票",
  "manager.untitled": "未命名",
  "new.blank": "空白發票",
  "new.blankHint": "從零開始",
  "new.category.adjustments": "調整",
  "new.category.business": "商務",
  "new.category.nonprofit": "非營利",
  "new.category.payments": "付款",
  "new.category.projects": "專案",
  "new.category.recurring": "週期性",
  "new.category.sales": "銷售",
  "new.category.services": "服務",
  "new.category.shipping": "運送",
  "new.failed": "無法建立",
  "new.invoice": "新增發票",
  "new.startersFailed": "無法載入起始範本。請從空白開始，或再試一次。",
  "new.subtitle": "從空白畫布開始，或使用現成的範本。",
  "new.template": "新增範本",
  "new.yourTemplates": "你的範本",
  "optional.approvalShow": "簽核",
  "optional.attachShow": "附件",
  "optional.conShow": "聯絡資訊",
  "optional.delShow": "配送時程",
  "optional.discShow": "折扣碼",
  "optional.lateShow": "逾期費用",
  "optional.legalShow": "法律頁尾",
  "optional.loyShow": "會員點數",
  "optional.mcShow": "多幣別",
  "optional.payhShow": "付款紀錄",
  "optional.poShow": "採購單條款",
  "optional.qrShow": "QR 付款",
  "optional.recurShow": "週期性",
  "optional.refShow": "退款政策",
  "optional.shipShow": "送貨至",
  "optional.sigShow": "簽名",
  "optional.taxbShow": "稅額明細",
  "optional.termsShow": "條款同意",
  "section.approval.hint": "簽核狀態",
  "section.approval.title": "簽核",
  "section.attachments.hint": "附加的檔案",
  "section.attachments.title": "附件",
  "section.branding.hint": "標誌與品牌名稱",
  "section.branding.title": "品牌識別",
  "section.contact.hint": "支援聯絡資訊",
  "section.contact.title": "聯絡資訊",
  "section.custom.hint": "你自己的區段",
  "section.custom.title": "自訂區段",
  "section.customer.hint": "客戶資料",
  "section.customer.title": "收票方",
  "section.delivery.hint": "出貨狀態",
  "section.delivery.title": "配送時程",
  "section.discount.hint": "已套用的優惠碼",
  "section.discount.title": "折扣碼",
  "section.from.hint": "你的公司資料",
  "section.from.title": "開立方",
  "section.images.hint": "標誌、背景、QR 碼與照片",
  "section.images.title": "圖片",
  "section.items.hint": "產品與服務",
  "section.items.title": "明細項目",
  "section.latefees.hint": "逾期加收的費用",
  "section.latefees.title": "逾期費用",
  "section.legal.hint": "細則",
  "section.legal.title": "法律頁尾",
  "section.loyalty.hint": "獎勵餘額",
  "section.loyalty.title": "會員點數",
  "section.meta.hint": "號碼、日期、採購單與條件",
  "section.meta.title": "發票資訊",
  "section.multicurrency.hint": "其他幣別的總計",
  "section.multicurrency.title": "多幣別",
  "section.notes.hint": "頁尾文字",
  "section.notes.title": "備註",
  "section.payhistory.hint": "過去的付款",
  "section.payhistory.title": "付款紀錄",
  "section.payment.hint": "付款方式",
  "section.payment.title": "付款",
  "section.poterms.hint": "採購訂單的條款",
  "section.poterms.title": "採購單條款",
  "section.qr.hint": "掃碼付款的圖碼",
  "section.qr.title": "QR 付款",
  "section.recurring.hint": "收費排程",
  "section.recurring.title": "週期性",
  "section.refund.hint": "退貨與退款",
  "section.refund.title": "退款政策",
  "section.shipto.hint": "送貨地址",
  "section.shipto.title": "送貨至",
  "section.signature.hint": "授權簽署",
  "section.signature.title": "簽名",
  "section.tax.hint": "稅率與折扣",
  "section.tax.title": "稅額與總計",
  "section.taxbreak.hint": "稅額項目",
  "section.taxbreak.title": "稅額明細",
  "section.terms.hint": "同意的核取方塊",
  "section.terms.title": "條款",
  "section.theme.hint": "顏色、幣別、狀態",
  "section.theme.title": "標題與外觀",
  "seed.gallery.title": "圖片",
  "seed.image.caption": "加入圖說",
  "seed.image.title": "圖片",
  "seed.item": "新項目",
  "seed.kv.label": "標籤",
  "seed.kv.row1k": "成本中心",
  "seed.kv.row2k": "合約",
  "seed.kv.title": "參考資訊",
  "seed.kv.value": "數值",
  "seed.text.body": "在這裡加入你自己的文字 — 工作範圍、交付說明、條件，或想對客戶說的話。",
  "seed.text.title": "補充備註",
  "status.draft": "草稿",
  "status.live": "啟用中",
  "status.overdue": "已逾期",
  "status.paid": "已付款",
  "status.sent": "已寄出",
  "toast.deleteFailed": "無法刪除",
  "toast.duplicateFailed": "無法複製",
  "toast.duplicated.invoice": "已複製發票",
  "toast.duplicated.template": "已複製範本",
  "toast.imageTooLarge": "圖片太大（上限 {max}）",
  "toast.imageUnreadable": "無法讀取該檔案",
  "toast.languageFailed": "無法新增該語言",
  "toast.notAnImage": "該檔案不是圖片",
  "toast.renameFailed": "無法重新命名",
  "topic.logistics": "運送與物流",
  "topic.other": "未分類",
  "topic.receipts": "收據與退款",
  "topic.recurring": "週期性",
  "topic.sales": "銷售與報價",
  "topic.services": "專業服務"
} as Record<string, string>;
